!RESOURCE "1008_050.csv"

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 457
PUSH INT 1008
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_1
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_1
STATEMENT IF #LABEL_2 #LABEL_3
PUSH INT 0
CALL GetGameFlag
PUSH INT 0
OPERATOR EQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 1
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

#LABEL_2
STATEMENT ELSE
PUSH INT 16
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

#LABEL_3
PUSH INT 1
PUSH INT 3019
PUSH INT 60
PUSH INT 1
PUSH INT 20
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1005
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0001>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 457
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0002>, 0, 1)  ; 「っ！？\nあ…れ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0003>, 1, 1)  ; またしても、顎が頬杖からかくんと外れ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0004>, 2, 1)  ; そして周りの色が一変していることに気づいた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0005>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 458
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0006>, 3, 1)  ; 「冬馬…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 4, 1)  ; 闇に覆われつつある音楽室は、ぼやけた視界とあいまって、\nもう、ほとんど何も見えなくなっていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 5, 1)  ; 外から聞こえてくる同級生たちの喧騒も、\n陽が沈むとともに、少しずつ静まってきてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0009>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 459
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0010>, 6, 1)  ; 「帰っちゃったか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 7, 1)  ; 頭を振りつつ、意識が飛ぶ前の記憶を探る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 8, 1)  ; 俺は確かに冬馬と一緒にいて、\n俺たちのステージに対してのダメ出しと、\n進路の話と、時候の挨拶と…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 9, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 10, 1)  ; もっと踏み込んだ話題があったはずだけど、\n起き抜けの思考が追いついていかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 11, 1)  ; あの時、確かに俺は彼女に…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0016>)  ; ？？？
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 460
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 12, 1)  ; 「おはよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 461
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 13, 1)  ; 「っ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0020>, 14, 1)  ; そんなふうに、惚けたまま、\n自分の言葉を反芻していたら…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 15, 1)  ; 突然、ささやくような、でも艶めかしい声が、\n俺の顔に触る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0022>)  ; ？？？
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 462
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 16, 1)  ; 「おはよ春希くん。\nそして、お疲れさま」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 463
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 17, 1)  ; 「雪菜…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 3000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0026>, 18, 1)  ; …比喩じゃなくて、本当に息が顔に触れた。\nそれほど、至近距離だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 19, 1)  ; 膝立ちで、俺の視線の高さにぴったり合わせ、\n薄暗がりの中、穴が開くほどに俺の顔を見つめてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0028>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 464
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 20, 1)  ; 「え、ええと…クラスの方は？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0030>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 465
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 21, 1)  ; 「とっくに終わったよ。\nもうすぐ６時だもん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0032>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 466
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 22, 1)  ; 「…もうそんな時間なのか。\nだいぶ寝てたなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0034>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 467
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 23, 1)  ; 「そうだね。\nわたしが来てからでも、３０分以上」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0036>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 468
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 24, 1)  ; 「起こしてくれよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 3000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0038>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 469
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 25, 1)  ; 「嫌だよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0040>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 470
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 26, 1)  ; 「そんなに気を使ってくれなくてもいいって。\nだいたい、疲れてるのはお互い…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0042>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 471
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 27, 1)  ; 「そんなことしたら、\n春希くんの寝顔がゆっくり楽しめないよ。\nもったいない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0044>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 472
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 28, 1)  ; 「な…っ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 3000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0046>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 473
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 29, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0048>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 474
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 30, 1)  ; 「…冗談だよな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0050>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 475
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 31, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0052>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 476
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 32, 1)  ; 「冗談だって言ってくれよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0054>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 477
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 33, 1)  ; 「ふふっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0056>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 478
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 34, 1)  ; 「だから！\nからかったって言ってくれっての！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 3000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0058>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 479
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 35, 1)  ; 「あはっ…や～だよ～だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 36, 1)  ; それどころか、俺が目覚めても、\nまだ俺の顔を見つめることをやめてくれないし。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 0
PUSH INT 8166
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0061>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 480
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 37, 1)  ; 「ふあぁぁぁ～…つつつっ！\nあ～、体のあちこちが痛い」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 38, 1)  ; 椅子から立ち上がり、思い切り伸びをする。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 39, 1)  ; もちろん、照れ隠し以外の何物でもない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 3000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0065>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 481
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 40, 1)  ; 「頑張ったもんね今日。\nううん、今日だけじゃなくて、今週ずっと」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0067>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 482
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 41, 1)  ; 「そんなのは雪菜だって…あれ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 42, 1)  ; と、その時になってやっと気づいたのが、\n肩に掛けられている、暖かなコート。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 43, 1)  ; ちょっと軽めで、\n暗がりの中でもわかるくらいの赤系で、\nそして、どう見ても男物じゃなくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0071>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 483
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 44, 1)  ; 「これ…雪菜が？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 204
PUSH INT 3000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0073>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 484
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 45, 1)  ; 「お母さんが持ってきてくれてたんだ。\n昨日、家に帰らなかったから、着替えだって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0075>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 485
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 46, 1)  ; 「………まさに色々とごめん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 47, 1)  ; 俺を気遣ってくれたこととか、\n着替えが必要な原因を作ってしまったこととか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 48, 1)  ; …目の前の雪菜は、やっぱりステージ衣装のままで、\n今の時間だと、見るからに寒そうなこととか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0079>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 486
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 49, 1)  ; 「返すよ。\n…本当に悪い。こういうの男の役目なのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 3000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0081>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 487
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0082>, 50, 1)  ; 「ううん。\n春希くんは、十分男の子の役目、果たしたよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 51, 1)  ; コートを差し出すと、\n雪菜は俺に、無防備に背中をさらす。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0084>, 52, 1)  ; 俺はなんとか理由を聞くことなく、\nその肩に、ゆっくりコートをかけていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0085>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 488
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 53, 1)  ; 「わたしに勇気をくれた。\nあの高い場所で、たくさんの人に向かって、\nそれでも楽しく歌える勇気を」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0087>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 489
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 54, 1)  ; 「そんなこと…ないって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 55, 1)  ; 本当に勇気づけられたのは俺の方だし。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 56, 1)  ; あの絶望的な状況で、\nしかも諦めることが致命的でもない状況で、\nただ俺のワガママだけで突き進んでいた状況で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 57, 1)  ; 一番最初に、俺の理解者になってくれて、\n二番目の理解者を一生懸命引き込んでくれて、\nいつも、俺たちを明るく照らす役目であり続けてくれて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0092>, 58, 1)  ; …時々拗ねたりして完璧じゃないところが、\nまた、俺に強い責任感を与えてくれて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0093>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 490
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 59, 1)  ; 「た～のしかったね～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0095>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 491
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 60, 1)  ; 「めちゃくちゃ、な」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0097>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 492
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 61, 1)  ; 「人前で歌うのって、ものすごく緊張するけど、\n一線を越えちゃったら二度とやめられなくなりそう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 62, 1)  ; そんな雪菜が、俺に背中を向けたまま、\nあの時の余韻を噛みしめるように、暗い天井を見上げる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0100>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 493
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 63, 1)  ; 「うん、今でも覚えてる。\nあのスポットライトに照らされて歌ったんだなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 64, 1)  ; その視線の先に、まばゆいライトが見えるのか、\n暗闇に手をかざし、眩しそうに光をさえぎる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0103>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 494
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0104>, 65, 1)  ; 「…そういえば振りつけとか全然やらなかったね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0105>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 495
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0106>, 66, 1)  ; 「そんなことは些細な問題だ。\n誰も気にしてなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 67, 1)  ; だって、ステージ上の彼女たちは、\n掛け値なしに綺麗だったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 68, 1)  ; 一番至近距離で見てた、\n世界一の贅沢者が言うんだから間違いない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0109>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 496
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 69, 1)  ; 「あ～…歓声が耳に残ってる。\n当分忘れられそうにないな。\n目を閉じると、まだ夢の中にいるみたい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0111>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 497
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 70, 1)  ; 「じゃあ、またやるか？\n俺はともかく、雪菜と冬馬がいれば、\nもっと大きなイベントだって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 71, 1)  ; 冬馬にはけんもほろろに断られたけどな…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0114>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 498
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 72, 1)  ; 「ね、春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0116>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 499
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 73, 1)  ; 「ん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0118>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 500
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 74, 1)  ; 「これからも、ずっと一緒にいてね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0120>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 501
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 75, 1)  ; 「…雪菜さえよければ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 76, 1)  ; そしてやっぱり、\n雪菜の方にも態度を保留された。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 77, 1)  ; そりゃ、楽しさ以上にあれだけ苦労もあれば、か。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0124>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 502
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 78, 1)  ; 「<R峰城大|うえ>、行くんだよね？\n文系だよね？　どこの学部狙い？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0126>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 503
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 79, 1)  ; 「え？　いや、今のところ政経のつもりだけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0128>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 504
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 80, 1)  ; 「むぅ…英文行かない？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0130>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 505
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 81, 1)  ; 「いや俺英語苦手だし。相対的に」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0132>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 506
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 82, 1)  ; 「わたしだって政治も経済も苦手だよ。絶対的に」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 507
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 83, 1)  ; 「無理に学部まで合わせる必要ないだろ。\n今まで通り同じ学校に通うんだから、毎日会えるし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0136>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 508
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0137>, 84, 1)  ; 「毎日も重要だけど、\n一日何時間ってのも重要じゃないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0138>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 509
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 85, 1)  ; 「そもそも教養課程では一緒の講義も多いし。\n何でそんなに選択を急ぐんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0140>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 510
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 86, 1)  ; 「それは…そうなんだけど…ね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0142>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 511
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 87, 1)  ; 「今はそんな先の話より、目先の約束。\n進学しても、また三人で何かやりたいな。\n雪菜と、冬馬と、俺と…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0144>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 512
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 88, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0146>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 513
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 89, 1)  ; 「雪菜？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

@VCALL WN(RES<0148>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 514
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 90, 1)  ; 「一緒にいてね、春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0150>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 515
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 91, 1)  ; 「あ？　ああ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 92, 1)  ; 雪菜が…ちょっと違う？
PUSH INT 1
CALL EndMessage
OPERATOR POP

STATEMENT IF #LABEL_4 #LABEL_5
PUSH INT 0
CALL GetGameFlag
PUSH INT 0
OPERATOR EQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 15
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

#LABEL_4
STATEMENT ELSE
PUSH INT 8
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

#LABEL_5
@VCALL WN(RES<0153>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 516
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 93, 1)  ; 「進学しても、二年になっても、\n三年になって、もしも学部が違っても…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0155>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 517
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 94, 1)  ; 「雪菜？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 95, 1)  ; つい数時間前、\nステージの上で、満員の観衆を翻弄してたときと違う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 210
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0158>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 518
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 96, 1)  ; 「もしもわたしが留年して、\n春希くんの後輩になっちゃったとしても」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0160>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 519
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 97, 1)  ; 「普通にやってれば留年なんかしないって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 98, 1)  ; つい数日前、\n冬馬の家のスタジオで、\n自信に満ち溢れた歌声を響かせていたときとも違う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0163>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 520
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 99, 1)  ; 「もしも、もしも…\nええと、ええとね…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0165>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 521
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 100, 1)  ; 「落ち着けって。\n今、明かりつけるから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 101, 1)  ; 似ているとすれば、昨日の朝。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 102, 1)  ; 雪菜を連れ去りに、３年Ａ組を訪れたときの、\nおどおどして、何だか小さく見えてしまった、あの…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0169>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 522
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0170>, 103, 1)  ; 「駄目！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0171>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 523
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 104, 1)  ; 「っ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 105, 1)  ; あのときの雪菜と同じ雪菜が…\n電灯のスイッチに伸びた、俺の手に絡みつく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 307
PUSH INT 10000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0174>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 524
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 106, 1)  ; 「やめようよ…\n夢が覚めちゃうよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 107, 1)  ; そう、絡みあう。\n俺の右手と、雪菜の左手が…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0177>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 525
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 108, 1)  ; 「ね、春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0179>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 526
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 109, 1)  ; 「雪菜…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 110, 1)  ; 指の一本一本、すべてを重ねあわせ、\nその柔らかい手のひらで、包み込もうとする。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0182>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 527
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0183>, 111, 1)  ; 「今日のわたしは、ずっと夢を見続けてたい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 112, 1)  ; あのときの雪菜と同じに見えて、\nけれど、何か違うものを内に秘めた雪菜が…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0185>, 113, 1)  ; ただ下ろしていただけの、\nもう一つの俺の手にも繋がる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0186>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 528
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 114, 1)  ; 「スポットライトを浴びて、大歓声を受けて、\n大好きな歌を、心から楽しく歌って」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0188>, 115, 1)  ; 絡みあう。\n俺の左手と、雪菜の右手…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0189>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 529
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0190>, 116, 1)  ; 「それで、みんなも喜んでくれて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 117, 1)  ; 暗がりの中…\n届くのは、雪菜の熱い息遣いと、\nわずかな光に照らされて輝く瞳。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0192>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 530
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 118, 1)  ; 「好きな人に、誉められて…\nだから調子に乗って、ごほうびを、ねだって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0194>, 119, 1)  ; そして…\n聞く人によっては、紛らわしいことこの上ない、\n勘違いを誘発する、告白みたいなたとえ話。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0195>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 531
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0196>, 120, 1)  ; 「そしたらその人が、ちょっと苦笑いして、\n甘えん坊のわたしを、やさしく抱きしめて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0197>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 532
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0198>, 121, 1)  ; 「せつ…な…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0199>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 533
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0200>, 122, 1)  ; 「…でも、ちょっと想像してたのと違うね、これ」
PUSH INT 2
PUSH INT 212
PUSH INT 3000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 123, 1)  ; 雪菜の肩から、\n俺がせっかくかけてあげたコートがふわりと落ちる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0202>, 124, 1)  ; それは、雪菜が動いたから。\n繋いだ両手を胸の前に、\n額をこつんと、俺の胸に。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0203>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 534
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0204>, 125, 1)  ; 「こんなふうに、自分の方から迫っちゃうなんて、\n計画のうちにはなかったんだけどな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 126, 1)  ; さっきまで、俺の顔にかかっていた吐息は、\n今は、俺の胸を温かく湿らせる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0206>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 535
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 127, 1)  ; 「あくまでもわたしは受け身で…\nちょっとびっくりしたけど、\nでも、ずっと待ってたんだからいいやって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0208>, 128, 1)  ; 瞳の光は俺の視界から消えたけど、\n今度は雪菜の髪の香りが、俺の五感を刺激する。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0209>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 536
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0210>, 129, 1)  ; 「…そんな感じの、\n都合のいい夢だったんだけどなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 130, 1)  ; 額だけでなく、頬や耳までも俺の胸に埋めてくる。\n…俺の鼓動を聞かれてしまってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 307
PUSH INT 3000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0212>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 537
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 131, 1)  ; 「仕方がないか…\n自分の心を掴みきれてなかった\nわたしが悪いんだもんね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0214>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 538
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 132, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 125
PUSH INT 3000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0216>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 539
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 133, 1)  ; 「ね、春希くん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0218>, 134, 1)  ; もう一度、雪菜が顔を上げる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 135, 1)  ; けれどさっきまでと違うのは、\n俺との身長の差で…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0220>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 540
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 136, 1)  ; 「よけても、いいんだよ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0222>, 137, 1)  ; もう、その瞳と、そして唇は、\n俺の目の前にまで上り詰めてきていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0223>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 541
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 138, 1)  ; 「雪菜…俺…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 124
PUSH INT 3000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0225>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 542
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 139, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0227>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 543
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 140, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0229>, 141, 1)  ; また、雪菜の瞳から光が消える。\nなぜなら、まぶたに遮られてしまったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0230>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 544
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0231>, 142, 1)  ; 「いいの…か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 143, 1)  ; 駄目なのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0233>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 545
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 144, 1)  ; 「本当に俺で…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 145, 1)  ; ずっと今のままは、駄目なのか？\n三人じゃ、駄目なのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0236>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 546
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0237>, 146, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 147, 1)  ; それを、俺に決めろって…\nそんな、重いことを、俺の心だけでって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0239>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 547
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 148, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 149, 1)  ; だったら俺は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0242>, 150, 1)  ; 自分で決断して。自分で動いて。\n自分で結果を受け入れて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 151, 1)  ; まだ、ほんの十数年だけど、\nそれでも、自分の意志を持ってからこれまで、\nずっとそうやって生きてきた俺は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0244>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 2
CALL CRW
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 3000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1005
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

ARRAY_S RES<0245>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 24
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 9900
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 10100
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

@VCALL WN(RES<0246>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 548
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 152, 1)  ; 「ん…ぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0248>, 153, 1)  ; 自分の意志で、雪菜の唇に、\n自分を重ね合わせる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0249>, 154, 1)  ; 雪菜は…抵抗なんかするわけがなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0250>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 549
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 155, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0252>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 550
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 156, 1)  ; 「ん、ん…んぅっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0254>, 157, 1)  ; 雪菜の唇が、俺の唇に、本当に張りついてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 158, 1)  ; 生温かくて、柔らかくて、滑らかで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0256>, 159, 1)  ; 『これが女の子の唇なんだ』なんて、\nとても一般論で片付けられそうになくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0257>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 551
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0258>, 160, 1)  ; 「は、ぁ…んふ、あ、ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 161, 1)  ; ほんのちょっと触れてるだけなのに、\n心をごっそり持っていかれそうなくらいに、\n物凄い感覚で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0260>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 552
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 162, 1)  ; 「は、ぁ…ぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 163, 1)  ; 俺の口から、思わず吐息が漏れる。\nだから雪菜の吐息も俺の顔にかかる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 164, 1)  ; 生温かくて、柔らかくて、滑らかな唇の隙間から、\nやっぱり、生温かくて、柔らかくて、滑らかな吐息。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0264>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 553
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 165, 1)  ; 「ん…ちゅぅ…あ、ふぁ…ぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0266>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 554
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0267>, 166, 1)  ; 「あ、あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0268>, 167, 1)  ; 全身を、電撃が駆け抜けるような痺れが襲う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 168, 1)  ; 体中のどこもかしこも緊張し、\n自分の神経が、ただ一箇所に集中してしまったみたい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 169, 1)  ; そんな、何秒か何年かもわからないくらいの、\n軽くてぎこちなくて、そして熱くて激しいキスが\n俺たち二人の間を通り過ぎ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0271>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 555
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 170, 1)  ; 「はぁ、はぁ、はぁぁ…あ、あは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0273>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 556
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 171, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 172, 1)  ; 俺の腕の力が緩んだ隙に、\nようやく雪菜が唇を離す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 173, 1)  ; …俺の方が雪菜に押しつけていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0277>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 557
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 174, 1)  ; 「はぁぁ…ふぅ、ん。\nあ、あは…あはは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0279>, 175, 1)  ; けれど雪菜は、そんな強引な俺に、\n唇を濡らしたままの笑顔で応えてくれる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0280>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 558
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 176, 1)  ; 「はぁ…あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 177, 1)  ; そして俺の方は…\nあまりにも想像を絶する快感に、\n果ててしまいそうになっていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0283>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 559
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 178, 1)  ; 「ごめん…春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0285>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 560
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 179, 1)  ; 「なんで…謝る？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0287>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 561
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 180, 1)  ; 「だって………ファーストキスなんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0289>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 562
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 181, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0291>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 563
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0292>, 182, 1)  ; 「ごめんね…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0293>, 183, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 184, 1)  ; １１月も終わりに近づいたある土曜日。\n峰城大付属学園祭二日目。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0295>, 185, 1)  ; 俺たち三人が、\nもっとも近くて楽しくて、\nもっとも嬉しかった日。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 186, 1)  ; そして…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 240
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0297>, 187, 1)  ; 俺たち三人が、\n本当に三人でいられた、最後の日。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 240
CALL SetDemoMode
OPERATOR POP

ARRAY_S RES<0298>  ; CATCH
PUSH INT 1
CALL SCall
OPERATOR POP

ARRAY_S RES<0299>  ; 1009
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
