!RESOURCE "1010.csv"

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 1010
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_1
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_1
PUSH INT 17
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1038
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0001>, 0, 1)  ; １２月に、なった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0002>, 1, 1)  ; 街はいよいよ街路樹の葉を落とし、\nその代わり、駅前には特定の日のための大樹が突然生え、\n全体で冬という季節を主張するようになった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0003>, 2, 1)  ; 学園生活最後の煌めきだった学園祭も終わり、\n俺たち三年は、残る灰色だけの四か月に、\n思いを馳せざるを得なくなる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0004>, 3, 1)  ; とはいえ、上に大学のある付属校の強みか弱みか、\nすでにかなりの学生の進路は決まってるから、\n本物の灰色は半分以下。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 4, 1)  ; その中でも、他の大学に推薦の決まった強者や負け組、\n就職を決めた社会人組を除くと、残るは三桁を切る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0006>, 5, 1)  ; これは、そのマイノリティに選ばれてしまった人間の、\n熱く、そして絶望的な戦いの日々…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1044
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 127
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0007>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 6, 1)  ; 「すぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8007
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 16
PUSH INT 15
PUSH INT 0
PUSH INT 32
CALL SetShake
OPERATOR POP

@VCALL WN(RES<0009>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0010>, 7, 1)  ; 「寝るな。\nまだ一問も解いてないぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 212
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0011>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 8, 1)  ; 「ったぁ…\n女の頭を殴るなんて、\nどこまで時代に乗り遅れた団塊世代だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0013>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 9, 1)  ; 「せめて考えるふりくらいしてくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0015>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 10, 1)  ; 「このコタツが悪いんだ。\n足下から、人の思考能力を根こそぎ奪っていく…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0017>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0018>, 11, 1)  ; 「じゃあ、また最初からおさらいするぞ。\n…お前が今勉強しようとしている教科は何だ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 12, 1)  ; 文字通り、絶望的な戦いの日々。\n…主に教える方にとって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0020>, 13, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 14, 1)  ; 改めて…\n１２月に、なった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0022>, 15, 1)  ; かねてからの予告通り、\n明日から期末試験を控え、学園最後の日々は、\n微妙に嫌な方向で慌ただしさを増していく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0023>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0024>, 16, 1)  ; 「地理って、つまらないな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0025>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0026>, 17, 1)  ; 「ならどうして選択した？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0027>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0028>, 18, 1)  ; 「歴史関係と比べて、覚えること少なそうだったから。\n…結局、何も覚えてないから関係なかったけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0029>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0030>, 19, 1)  ; 「…言いたくないが、その選択は正解だった。\nいいか、追試に使うエネルギーを少しでも他に回すため、\n意地でもこいつは本試験で取りに行くぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0031>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 20, 1)  ; 「試験前から追試前提なのか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0033>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 21, 1)  ; 「全教科やってる時間なんかあるわけないだろ。\nもちろん居眠りしてる時間があるなんて思うな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0035>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 22, 1)  ; 「…やっぱ学校やめようかなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0037>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 23, 1)  ; 「確かにお前ん家の財力なら\nニートの一人くらい余裕だろうけど、俺はそんな、\n事情もない社会的弱者を生み出すつもりはないぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0039>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 24, 1)  ; 「勝手に人のこと友達って決めつけておいて、\nなんて言い草だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0041>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0042>, 25, 1)  ; 「友達だから言いたいこと言ってるわけ。\nほら、問一」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0043>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 26, 1)  ; 「うう…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0045>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 27, 1)  ; 「お疲れさま～\nちょっとだけ休憩にしようか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 323
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0047>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 28, 1)  ; 「そうだな、随分としごかれたし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0049>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0050>, 29, 1)  ; 「雪菜…\nすぐそれを持ったままリビングに戻ってくれ。\nこのままじゃ朝になっても終わりそうにない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0051>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0052>, 30, 1)  ; 「あはは…やられてるね、かずさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 31, 1)  ; テーブルの上に、\nコーヒーカップと菓子皿の載ったトレイを置くと、\n雪菜がごそごそと、俺の左隣のスペースに潜り込む。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 203
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0054>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 32, 1)  ; 「雪菜、お前の彼氏は粘着だ。屑だ。\n女の苦しむ顔を見て悦ぶ真性の××野郎だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 33, 1)  ; そのまま、コタツの中で手を探り当て、\nきゅっと握りしめる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0057>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 34, 1)  ; 「言っておくが、俺が『もう勝手にしろ』\nって放り出すかと思ったら大間違いだぞ。\n逆に、怒ってノルマを増やす可能性が高い」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0059>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 35, 1)  ; 「それって多分嘘じゃないよねぇ…経験上」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 36, 1)  ; 指を一本一本絡めて、\n手のひら全体をぴったり合わせ、\nちょっとだけ力を込める。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 203
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0062>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 37, 1)  ; 「とにかくコーヒーはもらう。\n冷めたら逆に申し訳ないだろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 210
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0064>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0065>, 38, 1)  ; 「それはそうとさ…\n本当に、メープルシロップって必要だったの？\nこのドーナツ、生クリーム入ってるんだけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 39, 1)  ; そして…１・２・３って、３秒数えて、\nあとはゆっくりと離し、全て元通り。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0067>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 40, 1)  ; 「カナダじゃ常識だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0069>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 41, 1)  ; 「そ、そうなんだ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0071>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 42, 1)  ; 「クワガタの言うことを信じるな雪菜」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 43, 1)  ; 冬馬の前でいるときは、\n二人きりでいるつもりにならないこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 44, 1)  ; けれど、あまりよそよそしくして、\n冬馬に余計な気を使わせてもいけない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 45, 1)  ; 『かずさ』と『雪菜』の友情のためにって、\n俺たちが話し合って決めた、３秒ルール。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 46, 1)  ; しつこいけど…\n１２月に、なった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 47, 1)  ; 雪菜と俺がつきあい始めて、\n二週間が、経っていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 48, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1044
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0079>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 49, 1)  ; 「ほら、これこれ！\n露天風呂があって一泊二食ついて９５００円！\nしかも冬休み期間中でこの値段だよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0081>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0082>, 50, 1)  ; 「クリスマスに…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0083>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0084>, 51, 1)  ; 「この年代で…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0085>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 52, 1)  ; 「おかしいかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 53, 1)  ; 結局、ろくろく勉強も始まらないまま、\nしっかり始まってしまった休憩時間。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 54, 1)  ; 『雪を見に行こうよ！』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 55, 1)  ; そう言って、雪菜が皆の目の前で開いてみせたのは、\nとある古ぼけた温泉旅館のパンフレット。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0090>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 56, 1)  ; 「お母さんのいとこが経営してるところなんだ。\nクリスマスシーズンでも、今から余裕で取れるって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0092>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 57, 1)  ; 「…それ、逆にまずいんじゃないの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 58, 1)  ; 青森のリンゴ農家に、北関東の山奥の温泉旅館に…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 59, 1)  ; 雪菜の親類縁者は全国津々浦々に根を張ってるようで、\nまぁ、色々とめでたいような気がしないでもない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0096>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 60, 1)  ; 「普通、雪国に行くとしても、せめてスキーだろ。\n白雅温泉って、近くにゲレンデないぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0098>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 61, 1)  ; 「え～、だってわたし滑れないし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0100>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 62, 1)  ; 「滑れないなら、北原に手取り足取り教えてもらうとか…\nそういう若々しい発想はないのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0102>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 63, 1)  ; 「のんびりお風呂入ったり、\n部屋でみんなでお喋りしてたほうが楽しいよ。\nあとは雪だるま作ったり、雪合戦したり…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0104>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 64, 1)  ; 「いいのか北原？\nこいつ、お前の彼女とか以前に学園のアイドルだぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0106>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 65, 1)  ; 「俺に振るなよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 66, 1)  ; そりゃ、確かに問題がないわけじゃないけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 67, 1)  ; でも、雪菜が普通に学園のアイドル然としてたら、\n俺は彼女と接点なんか持てなかっただろうし。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 68, 1)  ; それに、ここまで好きに…なることも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0111>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 69, 1)  ; 「…やってらんない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0113>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 70, 1)  ; 「お、お前も当事者だろうが！\n『３人で遊びに行く』計画なんだぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 71, 1)  ; どうやら色々と顔に出てたらしい。\nそりゃ、やってられないかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 115
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0116>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 72, 1)  ; 「そうだよ、かずさにも絶対に来てもらうからね？\n大体、かずさが来ないとお父さんの許可下りないし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 219
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0118>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 73, 1)  ; 「…あたしが抑止力にでもなると思ってるのか？\n雪菜の父親は？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0120>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 74, 1)  ; 「そもそも抑止力なんか必要ないから。\nいるのは説得力だけだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0122>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 75, 1)  ; 「…大きく出たな、北原。\nいや、この場合は小さく、か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0124>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 76, 1)  ; 「ね、いいよね？\nここにしようよ！\n安いよ？　お得だよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0126>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 77, 1)  ; 「別にお金は気にしてないし。\n足りなければ下ろせば済む話だし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0128>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 78, 1)  ; 「親に言えば欲しい額くれるし。\n普段真面目にやってるから用途なんか聞かれないし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0130>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 79, 1)  ; 「こ、このブルジョワな人たちわ～！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 219
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0132>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 80, 1)  ; 「その代わり家庭崩壊してるけどね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 81, 1)  ; 「別に本人が気にしてないならいいんじゃないか？\n…どこかの家はドロドロしてるみたいだけどな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0136>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0137>, 82, 1)  ; 「…何だよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0138>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 83, 1)  ; 「いや、振ったのそっち…ってか睨むなよ怖い！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 84, 1)  ; この辺は、未だにネタと本気の境界線が曖昧だ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0141>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 85, 1)  ; 「も～、そんなことよりも、行こうね温泉。決まり！\n冬休み入ったらすぐに出発！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0143>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0144>, 86, 1)  ; 「でも今のままだと追試が…\n冬休み前に終わってくれればいいけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 216
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0145>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 87, 1)  ; 「かずさ！　絶対に頑張ろうね！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0147>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 88, 1)  ; 「なんであたし一人が頑張らなくちゃならないんだ？\nなんだか馬鹿馬鹿しい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0149>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0150>, 89, 1)  ; 「お前一人が頑張ってこなかったくせに、\n今さら何を言ってやがる…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 90, 1)  ; 何度も繰り返しになるが、\n期末試験は、明日から始まる…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 91, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1044
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0153>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 92, 1)  ; 「すぐ戻るから…\n雪菜、ちゃんと冬馬が逃げ出さないように見張っててな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0155>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 93, 1)  ; 「了解」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 1000
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 0
PUSH INT 8175
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0157>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 94, 1)  ; 「…なんか囚人みたいな扱いだな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0159>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0160>, 95, 1)  ; 「心配なんだよ春希くん。\n誰よりも、かずさのことが。\k\n
PUSH INT 2
PUSH INT 212
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 2
PUSH INT 8000
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 96, 0)  ; …わたしよりもさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0162>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 97, 1)  ; 「だからってこの扱いは酷すぎるだろ。\n朝から晩まで、食事も休憩もなく…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0164>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 98, 1)  ; 「食事は２回出したし、休憩は３回挟んだような」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0166>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 99, 1)  ; 「…５回も練習問題やらせやがって。\nなんてしつこいんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0168>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 100, 1)  ; 「だってかずさ、\n未だに半分も解けてないじゃない。\n春希くんの方は８割は解けてるよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0170>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 101, 1)  ; 「仕方ないだろ、雪菜たちの言う通り、\nあたしは今までサボってきたんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0172>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 102, 1)  ; 「今日だって、春希くんより一生懸命じゃないよね？\n教わる立場なのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 212
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0174>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 103, 1)  ; 「だから、毎日の積み重ねがある奴とは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0176>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 104, 1)  ; 「彼…社会科の選択は日本史だよ。\n地理なんか今まで全然やってないよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 30
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0178>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 105, 1)  ; 「…は？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0180>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 106, 1)  ; 「選択授業の教室で、\n春希くんを見たことある？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0182>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0183>, 107, 1)  ; 「……いや」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0184>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0185>, 108, 1)  ; 「かずさに教えるために、\n二晩徹夜して予習したんだよ？\nだからここ最近、電話かけてもすぐ切られた…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0186>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 109, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0188>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 110, 1)  ; 「明日、かずさが頑張ってる隣の教室で、\n春希くん、準備不足のツケを払うことになるんだよ？\n…日本史の試験、同じ時間だし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 321
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0190>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 111, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0192>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 112, 1)  ; 「…んふふ～♪」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0194>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 113, 1)  ; 「そんな勝ち誇ったような顔するな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 114, 1)  ; 「だぁってさ…\nかずさ、泣きそうな顔するんだもん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 110
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0198>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 115, 1)  ; 「してない。呆れてただけ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0200>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 116, 1)  ; 「そっかなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0202>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 117, 1)  ; 「そもそも、彼氏の余計なお節介がそんなに嬉しいか？\n自分のためにしてくれてることでもないのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0204>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 118, 1)  ; 「うん、すごく嬉しい。\nわたしのためじゃないけど、わたしたちのためだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0206>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 119, 1)  ; 「あ～そうですかそうですか。\nそりゃ、よかったね～。\n…ホントやってらんない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0208>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 120, 1)  ; 「かずさは、嬉しくない？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0210>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 121, 1)  ; 「無償の親切には慣れてないものでね。\nついつい疑り深くなる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0212>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 122, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0214>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 123, 1)  ; 「なに？\nあたし何か変なこと言った？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0216>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 124, 1)  ; 「最初にそういうことしたのは、\nかずさの方じゃないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0218>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 125, 1)  ; 「え…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0220>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 126, 1)  ; 「春希くんは、かずさに全然恩を返し切れてないって、\nそう、思ってるんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0222>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 127, 1)  ; 「なんの、こと…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0224>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 128, 1)  ; 「同好会を救ってくれたこととか、\nわたしたち三人を形にしてくれたこととか、\nあと、三曲目を作ってくれたこととか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0226>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 129, 1)  ; 「そんなの、雪菜のおかげでもあるだろ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0228>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0229>, 130, 1)  ; 「あと、夏休みのコーチのこととか…\n春希くんは、かずさのこと、神様みたいに思ってる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0230>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0231>, 131, 1)  ; <F14「…そんなことまで喋りやがったのか」>
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0232>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0233>, 132, 1)  ; 「だからさ…いつもみたいに、\n押しつけがましいって思うかもしれないけど、\nそれでも、春希くんの気持ちをさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 110
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0234>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 133, 1)  ; 「恩なんて、あたしはそんなもの売った覚えはない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0236>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0237>, 134, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0238>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0239>, 135, 1)  ; 「恩だなんて…感じて欲しくない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0240>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 136, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0242>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 137, 1)  ; 「あれは全部、自分のためにやったことだ。\nそんなものを勝手に恩に着て、\n勝手に返されても困る」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 323
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0244>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 138, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0246>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 139, 1)  ; 「だいたい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0248>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0249>, 140, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0250>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 141, 1)  ; 「あれは…あたしがしたくて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0252>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 142, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 206
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0254>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 143, 1)  ; 「～っ！　わかったよ！\n有難く受け取ればいいんだろ？\nそんなふうに泣きそうな顔するな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0256>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 144, 1)  ; 「よろしくね、かずさ♪」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0258>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 145, 1)  ; 「………ホントに、お前って奴は」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0260>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0261>, 146, 1)  ; 「悪い、お待た…」
PUSH INT 0
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1
CALL VW
OPERATOR POP

PUSH INT 1
PUSH INT 212
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0262>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 147, 1)  ; 「遅い！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0264>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 148, 1)  ; 「………すまん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0266>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0267>, 149, 1)  ; 「…ふふっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0268>, 150, 1)  ; なんだかよくわからないけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 151, 1)  ; 俺がお手洗いから戻ると、\n冬馬は、まるで親の敵でも討つかのように、\n怖い顔して俺に色々と質問を始めた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 152, 1)  ; …人にモノを教わる態度じゃないと思うんだけどな。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1000
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1042
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0271>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 153, 1)  ; 「悪い。先に行ってる。\nちょっとそこのコンビニに用があるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0273>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 154, 1)  ; 「え？　おい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0275>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 155, 1)  ; 「後からゆっくり来てくれればいい。\n…こっちもゆっくりしてるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 156, 1)  ; 夜も更け、\n小木曽家の常識に照らし合わせた時間をもって、\n俺たちの勉強会はお開きとなった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 157, 1)  ; で、家人に挨拶し、靴を履いて外に出た瞬間、\n冬馬が俺を置いてそそくさと先に行ってしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 2
PUSH INT 216
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0279>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0280>, 158, 1)  ; 「あ～、ちょっと待って！\nお母さんが、二人におミカンどうぞって。\k\n
PUSH INT 2
PUSH INT 113
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 2
PUSH INT 8001
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 159, 0)  ; ………あれ？　かずさは？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0282>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 160, 1)  ; 「………あ～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 161, 1)  ; で、数秒後に俺は、\n冬馬のその行動の意図を知るわけで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0285>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 162, 1)  ; 「春希くん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0287>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 163, 1)  ; 「冬馬ならコンビニに用があるから先に行くって。\n…俺が預かっとくから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0289>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0290>, 164, 1)  ; 「あ、うん。\k\n
PUSH INT 2
PUSH INT 115
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 2
PUSH INT 8002
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 165, 0)  ; ちゃんと二人分あ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0292>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0293>, 166, 1)  ; 「雪菜」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 204
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0294>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0295>, 167, 1)  ; 「………あ～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 168, 1)  ; 二つの紙袋を受け取ると同時に、\n雪菜を俺の胸に納めたとき。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0297>, 169, 1)  ; どうやら雪菜も、\n冬馬の意図に気づいてしまったらしい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 170, 1)  ; ホントにあいつ、\n余計な気、使いやがって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0299>, 171, 1)  ; ここまで配慮してもらっで何もしなかったら、\n雪菜だけでなく、冬馬の顔にまで泥を塗ることになるだろ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0300>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0301>, 172, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0302>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0303>, 173, 1)  ; 「ふふ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 174, 1)  ; 雪菜は、俺の胸に顔を埋めると、\n匂いを嗅いでるのか、匂いを刷り込んでるのか、\nしばらく顔をこすりつけていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0305>, 175, 1)  ; 髪から漂う優しい香りが、俺の鼻腔にふんわり拡がり、\nいつもみたいに、男の欲求を思い切りかきたてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0306>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0307>, 176, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0308>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0309>, 177, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 178, 1)  ; そんな俺の声が、よっぽど切羽詰まってたのか、\n見透かしたように、雪菜が俺を悪戯っぽい瞳で見上げる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 124
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0311>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 179, 1)  ; 「んむっ…♪」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0313>, 180, 1)  ; もちろん…すぐに目をつぶること前提で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0314>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0315>, 181, 1)  ; 「ん、ん、ん…は、あむ…ちゅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0316>, 182, 1)  ; 雪菜の唇が、\n俺の唇の上で、様々に形を変えながら動く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0317>, 183, 1)  ; 強くすぼめて押しつけてきたり、\n軽く開いて覆い被せてみたり、\n閉じたり開いたりして俺の唇を挟んでみたり。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0318>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0319>, 184, 1)  ; 「ふぅ…ん、んむ…あ、あ…は、はぁ、はぁぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0320>, 185, 1)  ; 回を重ねるたびに、\n一度あたりの時間が長くなっていく俺たちのキス。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0321>, 186, 1)  ; もう、３秒なんて、目じゃない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0322>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0323>, 187, 1)  ; 「ふぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 125
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0324>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0325>, 188, 1)  ; 「はぁぁぁぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0326>, 189, 1)  ; 二人の唇が離れ、\n俺に熱い息を吹きかけてくる女の子の綺麗な顔が、\n目の前に広がり。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0327>, 190, 1)  ; で、そんな瞬間、思い知る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0328>, 191, 1)  ; …俺たちは、自他共に認める、\n認められないカップルなんだって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0329>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0330>, 192, 1)  ; 「…おやすみ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0331>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0332>, 193, 1)  ; 「うん、おやすみ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0333>, 194, 1)  ; 俺を形容する言葉の中に、\n雪菜と釣り合うものは、存在しないんだろうなって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0334>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 195, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0336>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0337>, 196, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0338>, 197, 1)  ; でも、ま…\n別に悲観してる訳じゃない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0339>, 198, 1)  ; こうなってしまったからには仕方ない。\n自分が頑張って、雪菜に釣り合う男になるしかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0340>, 199, 1)  ; だって…やっぱり雪菜のこと、好きだし。\nこのキスも、何物にも代え難い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0341>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 140
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0342>, 200, 1)  ; 「ね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0343>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 141
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0344>, 201, 1)  ; 「ん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0345>, 202, 1)  ; 頑張ることには慣れてる。\n成果を上げることだって、コツはわかってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0346>, 203, 1)  ; …ただ、今までと方向性が違うだけで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0347>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 142
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0348>, 204, 1)  ; 「アンコール」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0349>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 143
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0350>, 205, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0351>, 206, 1)  ; 額をくっつけたまま。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0352>, 207, 1)  ; 喋るたびに、唇の先が触れるくらい近づいたまま。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0353>, 208, 1)  ; 俺たちは、言葉を交わし…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 124
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0354>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 144
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0355>, 209, 1)  ; 「んっ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0356>, 210, 1)  ; 俺たちは、キスを交わす。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0357>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 145
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0358>, 211, 1)  ; 「ん、んぅ…はぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0359>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 146
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0360>, 212, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 125
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0361>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 147
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0362>, 213, 1)  ; 「もっかい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0363>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 148
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0364>, 214, 1)  ; 「ああ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 124
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0365>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 149
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0366>, 215, 1)  ; 「ふぅん…ん、んぅぅぅっ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0367>, 216, 1)  ; そして…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0368>, 217, 1)  ; 回を重ねるたびに、\n一度あたりの回数が増えていく、俺たちのキス。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0369>, 218, 1)  ; もう、３回なんて、目じゃない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0370>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 150
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0371>, 219, 1)  ; 「ん、んむぅ…は、ちゅぷ…あ、んっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0372>, 220, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 615
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 15
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 14
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1043
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0373>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 151
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0374>, 221, 1)  ; 「ねぇ、母さん母さん！\n俺、今凄いモノ見ちゃった！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 60
CALL SES
OPERATOR POP

@VCALL WN(RES<0375>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 152
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0376>, 222, 1)  ; 「ああそう。\n先にお風呂入っちゃいなさい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0377>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 153
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0378>, 223, 1)  ; 「いやホント、マジ凄いんだって！\n俺の部屋の窓から門のとこ見えんじゃん。\nそしたら姉ちゃんがさぁ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0379>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 154
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0380>, 224, 1)  ; 「やめときなさい。\n…お父さんそこにいるんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 103
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0381>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 155
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0382>, 225, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 8209
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0383>)  ; 雪菜の父
PUSH INT 13
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 156
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0384>, 226, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1020
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0385>)  ; コンビニ店員
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 157
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0386>, 227, 1)  ; 「いらっしゃいませ～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0387>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 158
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0388>, 228, 1)  ; 「…あれ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0389>, 229, 1)  ; ５分後…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0390>, 230, 1)  ; 俺がコンビニに着いたとき、\n冬馬の姿は、どこにもなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0391>, 231, 1)  ; 駅まで小走りに追いかけたけど、\n結局、追いつくことはできなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 60
CALL SES
OPERATOR POP

@VCALL SetMessageE(RES<0392>, 232, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0393>, 233, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0394>, 234, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0395>  ; CATCH
PUSH INT 100
CALL SCall
OPERATOR POP

PUSH INT 7
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 3006
PUSH INT 120
PUSH INT 1
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 11
PUSH INT 108
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 10
PUSH INT 102
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1011
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0396>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 159
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0397>, 235, 1)  ; 「と、いうわけで、\nあっという間に終わったな～、期末！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0398>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 160
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 236, 1)  ; 「何が『と、いうわけ』なんだか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0400>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 161
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 237, 1)  ; 「めぶい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0402>, 238, 1)  ; 『と、いうわけ』で…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0403>, 239, 1)  ; 激動の試験週間はたちまち過ぎ去り、\n本日土曜日の英語をもって、めでたく終了した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 101
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0404>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 162
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0405>, 240, 1)  ; 「…また随分やり込んだみたいだな春希。\n有終の美で全科目トップでも狙いに行ったか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0406>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 163
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0407>, 241, 1)  ; 「そんなコストパフォーマンスの悪いことできるか…\n全科目平均点狙いに決まってるだろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 108
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0408>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 164
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0409>, 242, 1)  ; 「なんだとっくに寝てたんだ。\nそれにしても自然な寝言」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0410>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 165
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0411>, 243, 1)  ; 「色々事情があったんだよ。\n何しろ卒業がかかってたんでな。\n…あと起きてるから。脳以外は」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0412>, 244, 1)  ; 昨日は、同じ教科だったから、\nまだこっちも試験勉強できる分マシだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0413>, 245, 1)  ; …んだけど、途中で
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0414>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 128
PUSH INT 1044
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0415>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 166
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0416>, 246, 1)  ; 『お前の母ちゃんヨーロッパに住んでんだろ！\nなんで娘がここまで英語からっきしなんだよ！』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0417>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 167
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0418>, 247, 1)  ; 『おあいにくさま。母さんが住んでるのはフランス。\n英語禁止令のおかげで喋ることすら許されない国』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0419>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 168
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0420>, 248, 1)  ; 『かずさ…それはいくらなんでも』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0421>, 249, 1)  ; などという低次元の罵りあいで、\nごっそり体力を奪われたような気がする。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0422>, 250, 1)  ; 今日の試験も、もういっそのこと３０分過ぎた時点で\n隣の席と答案用紙をすり替えるトリックを使おうかと\n本気で悩んだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0423>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 11
PUSH INT 105
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 10
PUSH INT 109
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1011
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL SetMessageE(RES<0424>, 251, 1)  ; …追試…いや追々試に期待だな、今日のは。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0425>, 252, 1)  ; ピアノ関係の外来語はあんなに詳しいのに…\nやっぱドイツ語しか喋れないんだろうか、あいつ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0426>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 169
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0427>, 253, 1)  ; 「で、雪菜ちゃんたちまだ来ないのか？\nそろそろ１時になるけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0428>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 170
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0429>, 254, 1)  ; 「もう来るだろ…\n学割申請用紙取りに行っただけだし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 107
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0430>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 171
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0431>, 255, 1)  ; 「…もしも『誰と旅行に行く』かを\n彼女が誰かにポロリと漏らしたら、\nお前の席に花だけは飾っておいてやるからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 105
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0432>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 172
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0433>, 256, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0434>, 257, 1)  ; 冬休み旅行の計画は、雪菜の中で、\nかなり具体的な青写真が焼き上がってるらしい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0435>, 258, 1)  ; 俺が一緒にいる時点で、あの両親を…というか父親を、\nどうやって理詰めで説得するつもりなのか知らないけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 11
PUSH INT 101
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0436>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 173
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0437>, 259, 1)  ; 「ねぇ、春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0438>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 174
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0439>, 260, 1)  ; 「ん～？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0440>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 175
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0441>, 261, 1)  ; 「どうして…雪菜に告白したんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0442>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 176
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0443>, 262, 1)  ; 「ひくっ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 105
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0444>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 177
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0445>, 263, 1)  ; 「おい、依緒…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0446>, 264, 1)  ; 雪菜と俺のことは、\nもちろん、とっくに武也と依緒には<R公表済み|バレバレ>だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0447>, 265, 1)  ; とはいえ、そういうことを隠せない雪菜だから、\n既に全校生徒の過半数は知ってるんじゃないかって\n気もしてるけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0448>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 178
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0449>, 266, 1)  ; 「もうちょっと待つことできなかったのかな？\n例えば、卒業式の後とかさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0450>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 179
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0451>, 267, 1)  ; 「依緒…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0452>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 180
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0453>, 268, 1)  ; 「雪菜の気持ちは確かめるまでもないし、\nいつ告白したって同じ返事だったに決まってる。\nでも…そこまで焦る必要あったのかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0454>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 181
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0455>, 269, 1)  ; 「あ、いや…え？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0456>, 270, 1)  ; 『お前に雪菜は似合わない』とか、\n『みんなの夢を壊すな』とか、\n『なぁ、もうヤったのか？』とかいう質問は想定してた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0457>, 271, 1)  ; …最後のを聞かれたらブチ切れるけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 101
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0458>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 182
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0459>, 272, 1)  ; 「何言ってんだ依緒？\nいつ告ってもＯＫだってんなら、\nどうして待つ必要があるんだ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0460>, 273, 1)  ; けど、依緒のこの問いかけは、\n完全に予想の外側で、一瞬、質問の意味すら見失った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 110
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0461>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 183
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0462>, 274, 1)  ; 「いや、それは…\k\n
PUSH INT 11
PUSH INT 106
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 11
PUSH INT 8003
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0463>, 275, 0)  ; だって、知り合ってからまだ一月なんだぞ？\nちょっと急ぎすぎじゃないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0464>, 276, 1)  ; 確かに、俺が責められても仕方ないとは思う\nカップリングなんだけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0465>, 277, 1)  ; そういうことよりも、依緒の口調には、\nどこかやり切れなさみたいなものが見え隠れしてて、\nなんだか、心がざわつく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 102
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0466>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 184
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0467>, 278, 1)  ; 「それがどうした？\n俺だったら初対面のその夜に…いや、なんでもない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0468>, 279, 1)  ; ついでに武也も、相手が相手だけに、\n俺の擁護にいつものキレがない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 103
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0469>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 185
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0470>, 280, 1)  ; 「雪菜…本当に今で良かったのかな？\nもう少し時間が欲しかったんじゃないのかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0471>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 186
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0472>, 281, 1)  ; 「なぁ、依緒…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0473>, 282, 1)  ; けど依緒は、一つだけ誤解してる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0474>, 283, 1)  ; あの夜…\n俺たちは確かに、お互いの想いを伝え合い、\nなんというか、その、アレになった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0475>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 187
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0476>, 284, 1)  ; 「確かに、俺が相手じゃ心配なのはわかるし、\n不満なのもありえないのもわかるけどさ。だけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0477>, 285, 1)  ; だけどそれは…どっちにも迷いなんかなくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0478>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 188
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0479>, 286, 1)  ; 「だけ、ど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0480>, 287, 1)  ; 時期だって、相手だって、\n絶対にこうでなくちゃならないって、\n固く信じ合え………て………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0481>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 189
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0482>, 288, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 106
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0483>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 190
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0484>, 289, 1)  ; 「春希？\nほら、春希黙り込んじまったじゃねえか。\n今のは明らかに依緒が空気読めてないぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 110
PUSH INT 1000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0485>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 191
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0486>, 290, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0487>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 192
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0488>, 291, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0489>, 292, 1)  ; 時間が欲しかったのは………誰なんだよ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0490>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 193
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0491>, 293, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0492>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 194
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0493>, 294, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

@VCALL WN(RES<0494>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 195
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0495>, 295, 1)  ; 「いや、だからさ…\n俺が揉め事の間に入るって、立場おかしいだろ？\nお前ら正気に戻ってくれよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 9
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 1000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 10
PUSH INT 105
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 11
PUSH INT 110
PUSH INT 1000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1011
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0496>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 196
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0497>, 296, 1)  ; 「あ～、いたいた。\nみんなお待たせ～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0498>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 197
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0499>, 297, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0500>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 198
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0501>, 298, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0502>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 199
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0503>, 299, 1)  ; 「と、冬馬」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 127
PUSH INT 1000
OPERATOR ADD
PUSH INT 7
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 11
PUSH INT 110
PUSH INT 1000
OPERATOR ADD
PUSH INT 8
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 10
PUSH INT 105
PUSH INT 1000
OPERATOR ADD
PUSH INT 9
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 1000
OPERATOR ADD
PUSH INT 10
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1011
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0504>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 200
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0505>, 300, 1)  ; 「…めぶい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0506>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 201
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0507>, 301, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 1000
OPERATOR ADD
PUSH INT 10
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0508>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 202
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0509>, 302, 1)  ; 「どしたの？　みんな暗い顔して？\n…テスト、そんなに悲惨なことになってる？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0510>, 303, 1)  ; 俺は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0511>, 304, 1)  ; なんだかその時、\n雪菜の顔も、冬馬の顔も、\nどっちも全然見ることができなくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 108
PUSH INT 1000
OPERATOR ADD
PUSH INT 8
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0512>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 203
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0513>, 305, 1)  ; 「もう泣きたい。\n推薦取り消されたらどうしよう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0514>, 306, 1)  ; なんて、依緒が納めてくれた後も。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 1000
OPERATOR ADD
PUSH INT 10
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0515>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 204
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0516>, 307, 1)  ; 「あ、じゃあ、憂さ晴らしにカラオケ行かない？\nせっかくテストから解放されたんだし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0517>, 308, 1)  ; なんて、雪菜がとんでもないことを言い出したときも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 102
PUSH INT 1000
OPERATOR ADD
PUSH INT 9
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0518>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 205
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0519>, 309, 1)  ; 「お、いいねそれ！　雪菜ちゃんの生ボーカルかぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0520>, 310, 1)  ; なんて、何も知らない武也がそれに乗ってしまったときも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 1000
OPERATOR ADD
PUSH INT 7
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0521>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 206
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0522>, 311, 1)  ; 「北原？\nその、もしかして…あたしのせい、か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0523>, 312, 1)  ; 冬馬が、そんな俺を、\nずっと気遣っていてくれていたときも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0524>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 207
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0525>, 313, 1)  ; 「………違うよ。\n冬馬には関係ないことだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 321
PUSH INT 1000
OPERATOR ADD
PUSH INT 7
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0526>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 208
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0527>, 314, 1)  ; 「っ…\nそ、そう、か」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0528>, 315, 1)  ; 俺はずっと、空気の読めないまま暗く沈み、\nもう一度割り切るまでに、それから数時間を要した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0529>, 316, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 3002
PUSH INT 120
PUSH INT 1
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0530>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 209
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0531>, 317, 1)  ; 「お前さ、勘違いも大概にしとけよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0532>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 210
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0533>, 318, 1)  ; 「何がよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0534>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 211
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0535>, 319, 1)  ; 「あいつらさ…俺の見た感じだと、\n告ったの雪菜ちゃんの方からだぜ？　ほぼ間違いなく」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0536>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 212
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0537>, 320, 1)  ; 「…どうしてそんなこと言えるのよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0538>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 213
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0539>, 321, 1)  ; 「だってさ、春希は………なんでもないけどさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0540>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 214
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0541>, 322, 1)  ; 「憶測でモノ言わないでよ。\n雪菜がこんなに早く告白する訳なんてなかったのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0542>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 215
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0543>, 323, 1)  ; 「どうしてそんなこと言えるんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0544>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 216
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0545>, 324, 1)  ; 「だってさ、雪菜は………やっぱ、なんでもないけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0546>, 325, 1)  ; そして…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0547>, 326, 1)  ; その一時間後、\n武也は、雪菜の真の姿を知る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0548>, 327, 1)  ; ちなみに、雪菜と武也以外の三人は、\n最初から曲を入れるそぶりすら見せなかったとか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0549>, 328, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0550>  ; CATCH
PUSH INT 100
CALL SCall
OPERATOR POP

ARRAY_S RES<0551>  ; 1010_020
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
