!RESOURCE "1012_030_2.csv"

#Z10
OPERATOR POP
PUSH INT 2
PUSH INT 9778
PUSH INT 0
PUSH INT 1
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1029
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1028
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1035
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 3104
PUSH INT 30
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1024
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 30
CALL SES
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1025
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1037
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 12
PUSH INT 1046
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1047
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2500
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 45
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2500
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 45
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2500
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1037
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 3104
PUSH INT 30
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1024
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 30
CALL SES
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1039
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 12
PUSH INT 1036
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 60
CALL SES
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 12
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 454
PUSH INT 1012
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT GOTO #LABEL_0
OPERATOR POP

#LABEL_0
PUSH INT 1
PUSH INT 0
CALL EroMode
OPERATOR POP

PUSH INT 0
PUSH INT 8070
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 16
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 10170
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

@VCALL WN(RES<0001>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 454
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0002>, 0, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0003>, 1, 1)  ; もう、問答無用だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0004>, 2, 1)  ; 家に誰がいるかも確かめないまま、\n俺たちは手を繋いだまま堂々と部屋に入り、\nベッドにもつれるように倒れ込んだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 3, 1)  ; 母親は帰ってなかったけれど、\nもし帰っていても、同じ事をしたと思う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 455
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 4, 1)  ; 「んんっ！？\nん、んぅ…あ、は、はぁ、ぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 5, 1)  ; そして、残された時間を、\n一瞬たりとも無駄にしないという決心とともに、\n軽い触れ合いを無視して、深く絡みあう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0009>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 456
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0010>, 6, 1)  ; 「ん、ん、ん～っ、\nは、あ、あむっ、ん、んむ…ぷぁっ、あぁ、あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0011>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 457
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 7, 1)  ; 「あ、んむ…はぁ、ぁぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 8, 1)  ; あの時みたいに、\n彼女は俺の激しさを嫌悪しない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 9, 1)  ; 入ってくる舌を受け入れて、\nおそるおそるだけど、自分の舌で絡ませようとしてくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 10, 1)  ; そんな、健気でたどたどしい努力が、\nその容姿やいつもの態度とは裏腹で、\nそれがまた嬉しくて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0016>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 458
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 11, 1)  ; 「は、あ、あむ…\nん、ん…は、春希、ぃ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 459
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 12, 1)  ; 「う、うん…あ、んむ…冬馬…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 460
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 13, 1)  ; 「～～～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0022>, 14, 1)  ; がりっ
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0023>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 461
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0024>, 15, 1)  ; 「いへぇっ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 16, 1)  ; なんて浸ってたら、\nいきなり強烈なカウンターパンチ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0026>, 17, 1)  ; 差し込んだ舌を、上と下の前歯で挟まれて、\n結構な力を込められた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0027>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 462
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0028>, 18, 1)  ; 「ちょ、ちょ、ちょっと…おい…今のは…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 19, 1)  ; つまり、舌を噛まれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0030>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 463
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 20, 1)  ; 「冬馬って、誰だよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0032>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 464
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 21, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0034>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 465
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 22, 1)  ; 「間違えるな…馬鹿」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 23, 1)  ; 俺から離れた冬馬の…いや、かずさの唇が、\nそんな可愛らしい、女の子みたいな不満を漏らす。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0037>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 466
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 24, 1)  ; 「…ごめん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0039>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 467
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 25, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0041>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 468
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0042>, 26, 1)  ; 「ごめん…かずさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0043>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 469
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 27, 1)  ; 「仕方ない…許す」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 28, 1)  ; 『まだ慣れてない』なんて当然の言い訳を、\n聞き入れてくれるはずもないくらい、\nかずさは、かずさと呼ばれることに飢えていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0046>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 470
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 29, 1)  ; 「ね、春希…\nべ～って、して」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0048>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 471
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 30, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0050>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 472
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 31, 1)  ; 「ほら、早く」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0052>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 473
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 32, 1)  ; 「あ、ああ…？\nほう、は？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0054>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 474
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 33, 1)  ; 「やっぱり…\nちょっとだけ、血、出てるな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 34, 1)  ; それはお前が…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0057>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 475
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 35, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0059>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 476
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 36, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 37, 1)  ; なんて言う前に。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 38, 1)  ; かずさの舌が、俺の舌の一部分を這い、\nちょっとだけ、しみる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0063>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 477
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 39, 1)  ; 「ん…れろ…\nこうしておけば、治る、よ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0065>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 478
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 40, 1)  ; 「あ、んぅ…はぁ、は、ぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0067>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 479
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 41, 1)  ; 「ん、んふ…春希…\nは、あぁ、んむ、ちゅ…ちゅぷ…は、ぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 42, 1)  ; 俺の舌を、ねぶるように舐め回し、\n唇で挟み込み、唾液を飲み込む。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 43, 1)  ; そんな積極的で、俺に奉仕するかずさなんて、\n俺たちの一年間の歴史上に存在しない冬馬かずさで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0071>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 480
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 44, 1)  ; 「はむ…ん、ちゅぷ…ん、ん、んっ…\nふえぇ…ぅぇぇぇぇ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 45, 1)  ; こうして、キスしながら涙を溢れさせるかずさも、\n俺の知っている冬馬かずさとは別人だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0074>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 481
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 46, 1)  ; 「春希、春希…っ、\nずっと、ずっと…くそ、この野郎…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 47, 1)  ; …こんなところだけはいつも通りだけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0077>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 482
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 48, 1)  ; 「ん…んむ…ぷぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0079>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 483
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 49, 1)  ; 「あ、あ、あ…んむぅ、ん～っ、\nんっ、んぅ…あ、あはぁっ…あ、あぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 50, 1)  ; だから俺は、そんな慣れないかずさに慣れようと、\nもっともっと、可愛い反応を引き出そうと、する。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0082>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 484
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 51, 1)  ; 「ぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0084>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 485
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 52, 1)  ; 「触る、ぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 53, 1)  ; ワイシャツのボタンを外すと、\nそこには、俺がずっと想像してた白いふくらみ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 54, 1)  ; ちょっと固めのブラに覆われてるけれど、\nその中の柔らかさを思い描くだけで、もう…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0088>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 486
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 55, 1)  ; 「雪菜のは…触ったか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0090>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 487
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 56, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0092>, 57, 1)  ; 背中に冷水を浴びせられるってのは、\nまさにこのことだって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0093>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 488
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 58, 1)  ; 「直接触るのは、お前が初めてだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0095>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 489
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 59, 1)  ; 「間接的なら…触ったんだ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0097>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 490
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 60, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 61, 1)  ; しかも二度も。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0100>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 491
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 62, 1)  ; 「ごめん…嫉妬深いよな、あたし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0102>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 492
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 63, 1)  ; 「本当だな。\nこんな奴だなんて思わなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0104>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 493
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 64, 1)  ; 「そんな…酷いこと言わないでくれよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0106>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 494
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 65, 1)  ; 「………ごめん。\nそれじゃ、触るから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 66, 1)  ; 『どっちがだよ！？』なんて…\n今は、そんないつもの軽口なんか\n叩ける状況じゃないみたいだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0109>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 495
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 67, 1)  ; 「あぁっ…あ、あ…\nう、うそ…やだ、は、春希、お前…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 68, 1)  ; ブラをちょっと撫でただけで、\nびくんって身体が揺れた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 69, 1)  ; その揺れが手のひらにまで伝わり、\n膨らみが押しつけられ、しっかりと胸の形を伝える。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0113>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 496
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 70, 1)  ; 「ふ、ぅ、あ…ちょっと、おい…あ、やめ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 71, 1)  ; 目をそらして、自分の指を噛みしめて、\n全身に這い回る違和感と戦い続けるかずさ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 72, 1)  ; だけど俺の方は、自分の葛藤と戦うことを放棄して、\n次から次へと手の中に伝わってくる温かさと柔らかさに、\n恍惚となっていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 10170
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

@VCALL WN(RES<0117>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 497
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 73, 1)  ; 「あ、こら…ふぁぁっ、あ、んっ…\nい、いきなり外すなよ…びっくり、するじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0119>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 498
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0120>, 74, 1)  ; 「う、うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0121>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 499
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 75, 1)  ; 「人の話聞けよ春希…んっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 76, 1)  ; ブラを無理やりたくし上げて、\nとうとう、断りもなく、その膨らみに直接触れる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0124>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 500
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 77, 1)  ; 「っ…あ、ああ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0126>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 501
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 78, 1)  ; 「…どうしたんだ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 79, 1)  ; 今度は、俺がびくんって震えたのを、\nかずさが心配そうに上目遣いで見上げる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0129>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 502
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 80, 1)  ; 「すげ…柔らかい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0131>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 503
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 81, 1)  ; 「そういうこと言うな恥ずかしい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 82, 1)  ; けど、俺のそんな、\n若いんだか親父臭いんだかわからない感激に、\n慌てて目をそらして、思いっきり頬を染める。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 504
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 83, 1)  ; 「お前が聞いたんだろ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 84, 1)  ; 可愛い…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0137>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 505
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 85, 1)  ; 「は、あっ、あ…うあ、春希…\nお前、お前、なにしてんだよ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0139>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 506
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 86, 1)  ; 「なにって…触って…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0141>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 507
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 87, 1)  ; 「揉んでるだろ！\n明らかに、手がいやらしく動いてるじゃないかっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 88, 1)  ; 嫌になるくらい、可愛い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0144>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 508
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 89, 1)  ; 「そりゃ…揉むだろ。\nだって、かずさの………お前の身体だぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0146>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 509
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 90, 1)  ; 「っ………そう、か」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 91, 1)  ; 今までの、かずさの厳しい言葉や激しい言動が、\n全てこの日の落差のためにあったんじゃないかって、\nそんな馬鹿なことを思ってしまうくらいに、可愛い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0149>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 510
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0150>, 92, 1)  ; 「な、なぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0151>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 511
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 93, 1)  ; 「な、何だよ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0153>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 512
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 94, 1)  ; 「ここ…キスしても、いいか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0155>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 513
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 95, 1)  ; 「そんなこと聞くなよ。\n…駄目って言いそうになるじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0157>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 514
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 96, 1)  ; 「…悪い」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 97, 1)  ; 右手で寄せた、かずさの左胸の、ピンク色の突起。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0160>, 98, 1)  ; そこに、いやらしく唇を寄せていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0161>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 515
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 99, 1)  ; 「ん…ちゅ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0163>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 516
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 100, 1)  ; 「～～～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0165>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 517
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 101, 1)  ; 「っ…だ、大丈夫、か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 102, 1)  ; 唇で挟んだだけで、\nかずさは三度大きく跳ね上がり、\nベッドのパイプに頭をぶつけた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0168>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 518
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 103, 1)  ; 「ご、ごめん…\n感触よりも、なんか、春希の姿がさ…\nあたしの胸吸ってる、お前の顔が、その…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0170>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 519
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 104, 1)  ; 「俺はもともとこんな顔だよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0172>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 520
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 105, 1)  ; 「違うよ。\nいつもはもっとカッコいいって。\nそんな…怖くないってば…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0174>, 106, 1)  ; カッコいいって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 107, 1)  ; それって、本当にこいつの口から出た言葉なんだろうか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 108, 1)  ; なんで、こんな時に限って、\n迂闊にも口に出してしまうんだろうか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0177>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 521
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 109, 1)  ; 「今の春希…獣みたいだよ。\nお前がそんなふうになるなんて、信じられないよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0179>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 522
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 110, 1)  ; 「当たり前だろ…\nお前のこと、犯してるんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0181>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 523
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 111, 1)  ; 「春希…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0183>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 524
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 112, 1)  ; 「もう、やめないぞ。\n後悔したって、遅いんだぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0185>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 525
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 113, 1)  ; 「………後悔なんて、し飽きた」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0187>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 526
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0188>, 114, 1)  ; 「…そか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 115, 1)  ; 俺には、その言葉の深さは理解できないかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0190>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 527
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 116, 1)  ; 「じゃ、引き続き犯すぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0192>, 117, 1)  ; だから今は、ただ欲望に忠実に。\nかずさを、俺のものに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0193>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 528
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0194>, 118, 1)  ; 「っ…は、ぅぁ、あ、んっ…\nや、い、やぁぁ…んっ、くぅっ、あ、ああ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 119, 1)  ; 白い胸の先端に、今度こそ激しく舌を這わせ、\n両手を使って双丘を揉み上げ、こね回す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 529
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 120, 1)  ; 「あ、ぅぅ…んっ、あ、くぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0198>, 121, 1)  ; 俺の舌や手や指が動くたび、\nかずさは相変わらず、びくんびくんと反応するけど、\nでも、もう、何があっても俺を否定しない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0199>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 530
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0200>, 122, 1)  ; 「はぁ、ぁ、ぁ…春希…春希、\nあたし、あたしさぁ…はぁぁんっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 123, 1)  ; 俺の目の前で、\n唾液にべとべとにされて揺れるかずさの胸が、\n俺の思考をどんどん奪う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0202>, 124, 1)  ; 優等生とか委員長とか堅物とか、\nそんな代名詞が俺から抜けていくのがわかる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 125, 1)  ; 確かに俺、獣になってきてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0204>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 531
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 126, 1)  ; 「う…う～、ぃぅっ、う、ん～っ、\nあ、はぁ、はぁ、はぁぁ…いああんっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0206>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 532
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 127, 1)  ; 「か…かずさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0208>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 533
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 128, 1)  ; 「う、うん…んんっ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0210>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 534
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 129, 1)  ; 「欲しい…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0212>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 535
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 130, 1)  ; 「………わかった、よ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0214>, 131, 1)  ; その証拠に、もう下半身が脈打ってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
PUSH INT 10180
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

@VCALL WN(RES<0215>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 536
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0216>, 132, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0217>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 537
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0218>, 133, 1)  ; 「見るな、よ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0219>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 538
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0220>, 134, 1)  ; 「お前、こそ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0221>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 539
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0222>, 135, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0223>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 540
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 136, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 137, 1)  ; お互いに、下半身を覆う布きれを剥ぎ取ったとき。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 138, 1)  ; お互いの、その先にあるものの正体を目にして、\nそこから視線が動かせなくなってしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0227>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 541
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 139, 1)  ; 「変な形」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0229>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 542
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 140, 1)  ; 「お前だって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0231>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 543
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 141, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0233>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 544
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 142, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 143, 1)  ; 本当は、そこの場所を特定するためにも、\n正しいことをしているはずなんだけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 144, 1)  ; それでも、そんな目的とはかけ離れたところで、\n興奮と、好奇心と、躊躇が入り交じった\n熱いため息を、お互いに吐く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0237>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 545
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 145, 1)  ; 「いい、か」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0239>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 546
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 146, 1)  ; 「う、うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 147, 1)  ; お互い、本当のやり方もわからず、\nけれど、この年代相応の知識は持ち合わせてて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0242>, 148, 1)  ; だから俺は、自分のものを掴み、\nかずさのその部分へと、ゆっくりと押しつけて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0243>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 547
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0244>, 149, 1)  ; 「…春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0245>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 548
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0246>, 150, 1)  ; 「ん…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0247>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 549
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0248>, 151, 1)  ; 「あたしたち…今、最悪のこと、してるな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0249>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 550
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 152, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 153, 1)  ; かずさのその言葉も、\n胸の奥深く、受け入れる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0252>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 551
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 154, 1)  ; 「二度と会えないかもしれないのに、\n今さら気持ちを確かめ合ってどうすんだろうな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0254>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 552
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 155, 1)  ; 「そうだな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0256>, 156, 1)  ; 俺の先端が、かずさの中心に触れた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 157, 1)  ; そこは、少し触っただけでぬめりを感じるほど、\nかずさの他の肌とは全然違う感触に満ちていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0258>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 553
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 158, 1)  ; 「ね、春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0260>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 554
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 159, 1)  ; 「やめるか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0262>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 555
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 160, 1)  ; 「ううん…それは絶対に嫌だ。\nでも、その前にもう一度キス、してよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0264>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 556
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 161, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0266>, 162, 1)  ; そんな臨戦態勢のまま、\nかずさは安心して目を閉じる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0267>, 163, 1)  ; だから俺は、今度こそ、\nかずさが安心できるくらいの優しい優しいキスを…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8193
PUSH INT 0
PUSH INT 1
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0268>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 557
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 164, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0270>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 558
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0271>, 165, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 166, 1)  ; そうやって、\n俺たちがあと１センチにまで迫ったところで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0273>, 167, 1)  ; それが、鳴り響いた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 60
PUSH INT 240
CALL SEV
OPERATOR POP

@VCALL WN(RES<0274>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 559
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 168, 1)  ; 「あ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0276>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 560
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 169, 1)  ; 「は…春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 170, 1)  ; 俺の、脱ぎ捨てたワイシャツのポケット。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0279>, 171, 1)  ; そこから零れる、電子音と光の点滅と振動。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0280>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 561
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 172, 1)  ; 「あ、あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0282>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 562
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 173, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 174, 1)  ; 今の時間、俺のところに電話をかけてくる人間は、\nかなり限られる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 175, 1)  ; いや…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 176, 1)  ; 今年に入ってかかってきた数十件のうち、\nほぼ９５％以上は、同じ人からかかってきてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0287>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 563
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 177, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 178, 1)  ; それは、つまり…\n今日、話の途中でいきなり駆け出してしまったから、\nきっと、ものすごく心配してるはずの…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0290>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 564
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 179, 1)  ; 「～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0292>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 565
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0293>, 180, 1)  ; 「んっ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 181, 1)  ; けれど、俺の手が、\nベッドの下のワイシャツに伸びようとした瞬間。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0295>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 566
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 182, 1)  ; 「ん…んぅ…ちゅぷ…は、あ、あむっ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0297>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 567
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 183, 1)  ; 「か、かず…っ、んんんっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0299>, 184, 1)  ; 俺の背中に、力いっぱい両腕が回されて、\n激しいキスが、出迎えた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0300>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 568
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0301>, 185, 1)  ; 「ん…んむ、は、あ、あぁぁ…んぷ…あ、んむ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0302>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 569
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0303>, 186, 1)  ; 「………んっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 187, 1)  ; かずさの、たどたどしく入ってくる舌を…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0305>, 188, 1)  ; けれど俺は、慣れた仕草で包み込むように受け入れた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0306>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 570
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0307>, 189, 1)  ; 「んっ………ん、んぅ…ん～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0308>, 190, 1)  ; するとかずさは、安心したように、\nゆっくりと攻守交代し、俺の舌に自分の口中を委ねる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0309>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 571
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 191, 1)  ; 「んぅ…は、あ、あぁ…ちゅぷっ…\nは、あ、ぁぁ…春希ぃ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0311>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 572
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 192, 1)  ; 「今度こそ…行くな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0313>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 573
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0314>, 193, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0315>, 194, 1)  ; 唇を、俺の唾液でべたべたにしながら、\nかずさがふっと力を抜いてみせる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0316>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 574
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0317>, 195, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0318>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 575
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0319>, 196, 1)  ; 「んっ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0320>, 197, 1)  ; 聞こえない…\n今の俺たちには、何も聞こえない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0321>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 576
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0322>, 198, 1)  ; 「いぅっ…！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0323>, 199, 1)  ; だってかずさの目が、泣きそうな瞳で訴えてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0324>, 200, 1)  ; 『春希…お前、今はあたしの男だろ？』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0325>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 577
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0326>, 201, 1)  ; 「あ、あ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0327>, 202, 1)  ; だから俺も、瞳でこう答える。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0328>, 203, 1)  ; 『ずっと…かずさのものだ』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
PUSH INT 10190
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

@VCALL WN(RES<0329>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 578
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0330>, 204, 1)  ; 「～～～っ！\nう、あ、あ…いあぁぁぁぁっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0331>, 205, 1)  ; 最後の一線を、超えた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0332>, 206, 1)  ; もの凄い締めつけと、\n全身を走り抜けるぞわぞわした感覚が、\n俺が、かずさを貫いたことを如実に語ってた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0333>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 579
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0334>, 207, 1)  ; 「い、痛っ…痛い、痛いっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 208, 1)  ; それと、かずさの大きな悲鳴が。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0336>, 209, 1)  ; 俺たちの耳に届く雑音をかき消そうとしてるのか、\nそれとも本当に苦しいのかよくわからないけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0337>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 580
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0338>, 210, 1)  ; 「痛いって、このヘタクソ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0339>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 581
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0340>, 211, 1)  ; 「ご、ごめん…くっ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0341>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 582
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0342>, 212, 1)  ; 「キスはあんなに上手かったのに…お前…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0343>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 583
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0344>, 213, 1)  ; 「ごめん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0345>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 584
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0346>, 214, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0347>, 215, 1)  ; 半分まで入ったところで、\nかずさの身体を気づかって止める。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0348>, 216, 1)  ; けど、止めたからって大丈夫かどうかなんて、\n経験のない俺にわかるわけなんかなくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0349>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 585
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0350>, 217, 1)  ; 「痛いよ、春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0351>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 586
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0352>, 218, 1)  ; 「…気をつける」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0353>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 587
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0354>, 219, 1)  ; 「春希のが入ってる…痛いよぉ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0355>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 588
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0356>, 220, 1)  ; 「駄々、こねるなよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0357>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 589
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0358>, 221, 1)  ; 「ん…んぅ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0359>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 590
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0360>, 222, 1)  ; 「んむ…は、ぁぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0361>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 591
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0362>, 223, 1)  ; 「んんっ、あ、ちゅ…は、んむ…ふ、ぁぁ、ん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SES
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0363>, 224, 1)  ; 涙をぽろぽろ流して俺に痛みを訴えるかずさを、\nまたキスで癒しながら、少しずつ潜り込んでいく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0364>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 592
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0365>, 225, 1)  ; 「ん、ん…んぅっ…\nあ、はぁ、はぁ、はぁぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0366>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 593
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0367>, 226, 1)  ; 「まだ、痛いか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0368>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 594
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0369>, 227, 1)  ; 「当たり前だ…\n一生分の痛みを使い果たしたくらい、痛かった…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0370>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 595
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0371>, 228, 1)  ; 「悪い。慣れてなくて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0372>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 596
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0373>, 229, 1)  ; 「お前…あたしを疵モノにしたな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0374>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 597
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0375>, 230, 1)  ; 「ああ、した」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0376>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 598
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0377>, 231, 1)  ; 「馬鹿野郎…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0378>, 232, 1)  ; 泣きそうな顔で泣いていたかずさが、\nふっと微笑んで、そして泣いた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0379>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 599
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0380>, 233, 1)  ; 「かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0381>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 600
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0382>, 234, 1)  ; 「んっ…いい、よ。\n動け、よ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0383>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 601
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0384>, 235, 1)  ; 「うん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0385>, 236, 1)  ; 唇、頬、額、まぶた…\n軽いキスの雨を降らせて、かずさを愛する。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0386>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 602
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0387>, 237, 1)  ; 「あたしの奥に、お前を刻んでくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0388>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 603
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0389>, 238, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0390>, 239, 1)  ; 下半身に少し力を入れて、\nほんの少しずつ、奥へと進んでいく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0391>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 604
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0392>, 240, 1)  ; 「一生消えない傷を、残してくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0393>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 605
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0394>, 241, 1)  ; 「うん……」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0395>, 242, 1)  ; かずさの身体が硬直しても、\nもう、止めない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0396>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 606
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0397>, 243, 1)  ; 「だってお前はさ…\nあたしのたった一人の、弟子なんだから、な？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0398>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 607
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 244, 1)  ; 「ああ…\n俺の師匠は、後にも先にも、かずさだけだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0400>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 608
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 245, 1)  ; 「大切な、大切な…あたしだけの…っ、\nあっ、あ～っ、あぁぁぁぁぁ～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0402>, 246, 1)  ; その瞬間…\nとうとう、奥までかずさを貫いた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0403>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 609
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0404>, 247, 1)  ; 「～っ、く、ぅ、ぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0405>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 610
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0406>, 248, 1)  ; 「あっ、あっ、あっ…い、あ、うあぁぁっ、\nや、やめ…いい、あぅっ、う、う～っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0407>, 249, 1)  ; かずさの苦鳴が、部屋中に響き渡る。\n下手をすると、隣の家に聞こえてるかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0408>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 611
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0409>, 250, 1)  ; 「あっ、う、うく、あぁぁぁ…あんっ、\nい、いたっ、あ、ぅ、ぅぁぁぁぁっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0410>, 251, 1)  ; それでも俺は、かずさを気遣わず、\nただ、自分を押し進め、そして引き抜く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0411>, 252, 1)  ; 違う…ただ、気遣えないだけ。\n初めてのことで、自分すら制御できないだけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0412>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 612
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0413>, 253, 1)  ; 「い、い～っ、あ、あうっ、は、は、はぁっ…\nは、は…春希…春希、ぃ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0414>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 613
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0415>, 254, 1)  ; 「かず、さ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0416>, 255, 1)  ; 俺の体の下で、かずさが痛みと苦しみで悶える。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0417>, 256, 1)  ; だけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0418>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 614
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0419>, 257, 1)  ; 「はぁっ、は、あっ、ああんっ、ひぅっ…\nう、う、う…ふぇぇぇぇ…えぅっ、う、う～っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0420>, 258, 1)  ; その表情は、\nなんだか痛々しいくらいに幸せそうで、\n俺の胸を締めつける。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0421>, 259, 1)  ; これが最後…\nもう、かずさに会えなくなる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0422>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 615
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0423>, 260, 1)  ; 「あぁぁっ、あっ、春希…\nあ、あたし、あたし…痛いけど…でも、痛くない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0424>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 616
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0425>, 261, 1)  ; 「う、ん…あぁぁっ、かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0426>, 262, 1)  ; 怒鳴られることも、罵られることも、\n嘲笑われることも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0427>, 263, 1)  ; お節介を焼くことも、面倒を見てもらうことも、\n感謝して照れられることも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0428>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 617
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0429>, 264, 1)  ; 「あ、は、あぁぁ…んっ…く…ぁ…\nあ、あ…あたし…言えばよかった…\nカッコなんか、つけなきゃよかった…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0430>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 618
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0431>, 265, 1)  ; 「ごめん…言えなくて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0432>, 266, 1)  ; その綺麗な横顔に見とれることも、\n時折、意味もなくじっと見つめられることも、\nそして、意味もなくシカトされることも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0433>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 619
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0434>, 267, 1)  ; 「馬鹿だ、あたし、馬鹿だ…ん、く、ぅぁ…\nああああんっ、あっ、あ～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0435>, 268, 1)  ; 気持ちをぶつけることも、\n気持ちを受け止めることも、\n同じ気持ちを持つ証として抱きあうことも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0436>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 620
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0437>, 269, 1)  ; 「かずさ…ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0438>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 621
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0439>, 270, 1)  ; 「ん、んぷ…ん…っ、\nは、はぁ、はぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0440>, 271, 1)  ; かずさの、痛々しい告白を唇で塞ぐ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0441>, 272, 1)  ; 彼女が後悔すればするほど、\n俺の罪をあぶり出してしまうから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0442>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 622
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0443>, 273, 1)  ; 「あぁぁっ、んっ、んぅ…ぷぁっ…\nあ、春希…お前…くそぅ…好きだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0444>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 623
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0445>, 274, 1)  ; 「俺、だって…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0446>, 275, 1)  ; 二人の女の子を心の底から悲しませた、\n俺の愚鈍な人格が晒されてしまうから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0447>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 624
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0448>, 276, 1)  ; 「好きだ…好きだ好きだ好きだっ、\n悔しい、悔しいよ…なんで、なんでぇっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0449>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 625
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0450>, 277, 1)  ; 「いてくれよ、かずさ…\nずっと俺の側に、俺の隣にさぁっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0451>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 626
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0452>, 278, 1)  ; 「無理だよ…無理なんだよ。\nもう、あたし、うあぁぁぁっ、あ～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0453>, 279, 1)  ; キスが途絶えたら、額をぶつけあう。\n目尻の涙を舌ですくう。\nそして、またキスを重ねる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0454>, 280, 1)  ; かずさの身体と、絶え間なく絡みあい、\nお互い初めて同士のセックスは、\nお互いに全然余裕を持たないまま…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0455>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 627
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0456>, 281, 1)  ; 「あっ…あぁ…だ…も、もう…\nかずさ…ああ、俺、俺…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0457>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 628
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0458>, 282, 1)  ; 「っ、ぅ…ぁ…さよなら、春希。\n忘れない…忘れないからっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0459>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 629
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0460>, 283, 1)  ; 「駄目だ…行ったら駄目だ。\n嫌だ、嫌だよ、俺…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0461>, 284, 1)  ; かずさが、遠くへ行ってしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0462>, 285, 1)  ; この逢瀬が終わったら、\n遠くの空へ、旅立ってしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0463>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 630
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0464>, 286, 1)  ; 「ありがと…春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0465>, 287, 1)  ; なのに俺は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0466>, 288, 1)  ; かずさの中に迸っていく、\nこの快感を止められない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0467>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 631
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0468>, 289, 1)  ; 「っ…\nあ、あ、あ、あ、あ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0469>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 632
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0470>, 290, 1)  ; 「あっ、あっ、あっ…うん、いいよ…\nあたしの中に…お前を、残して」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0471>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 633
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0472>, 291, 1)  ; 「っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0473>, 292, 1)  ; そして、その言葉が…\n直接の、引き金になった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 15
PUSH INT 255
PUSH INT 255
PUSH INT 255
CALL F
OPERATOR POP

PUSH INT 0
PUSH INT 15
PUSH INT 255
PUSH INT 255
PUSH INT 255
CALL F
OPERATOR POP

PUSH INT 1
PUSH INT 10190
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 0
PUSH INT 60
PUSH INT 255
PUSH INT 255
PUSH INT 255
CALL F
OPERATOR POP

@VCALL WN(RES<0474>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 634
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0475>, 293, 1)  ; 「あ…あああ…っ、\nあ、ああっ、あああああっ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0476>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 635
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0477>, 294, 1)  ; 「あ～っ、ああぁぁぁ～っ、\nあ、あ、あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0478>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 636
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0479>, 295, 1)  ; 「はぁっ、はぁっ、はぁっ…\nあ、くる…あ、んっ…熱…ぅ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0480>, 296, 1)  ; 頭が弾けるんじゃないかっていう、\nたった一度の大きな鼓動の後…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0481>, 297, 1)  ; かずさの一番奥に届いたまま、\n俺は、思い切り放出していた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0482>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 637
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0483>, 298, 1)  ; 「あ、あ…はっ…\nは、春希、春希…ぃ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0484>, 299, 1)  ; 何度も、何度も…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0485>, 300, 1)  ; 俺の心臓が、どくん、どくんと動くたび、\nかずさの胎内に、流れ込んでいく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0486>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 638
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0487>, 301, 1)  ; 「ん、あぁ…\nこれが、お前の…かぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0488>, 302, 1)  ; ずっと俺にのしかかられ、組み敷かれていたかずさが、\nそれでもなお、俺の頭に手を回し、そっと抱きしめる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0489>, 303, 1)  ; 繋がったまま、両足を絡めて、\nまるで二人が溶け合うのを願うかのように。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0490>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 639
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0491>, 304, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0492>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 640
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0493>, 305, 1)  ; 「ありがと、春希。\n…すごく、痛かったよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0494>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 641
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0495>, 306, 1)  ; 「っ…ぅ、ぃ、ぅぅ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0496>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 642
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0497>, 307, 1)  ; 「………泣くなよ。\n捨てた女の目の前でさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0498>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 643
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0499>, 308, 1)  ; 「言うな…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0500>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 644
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0501>, 309, 1)  ; 「そんなことされたらさ…心配になっちゃうだろ。\n側に、いたくなっちゃうじゃないかよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0502>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 645
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0503>, 310, 1)  ; 「いてくれよ…\nだからさぁ…何で駄目なんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0504>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 646
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0505>, 311, 1)  ; 「なんでだろうなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0506>, 312, 1)  ; 抱きあって、絡みあって、睦みあって、\nそして泣きあって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0507>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 647
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0508>, 313, 1)  ; 「なんで、こうなっちゃったんだろうなぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0509>, 314, 1)  ; 俺たちは、最後の夜を…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0510>, 315, 1)  ; 絶対にしないって誓った後悔にまみれて、\nそして、お互いの肌のぬくもりを感じながら、眠った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 360
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 360
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0511>, 316, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0512>, 317, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0513>, 318, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0514>, 319, 1)  ; そして、俺が本当に眠ってしまった、\nほんの少しの隙を縫って…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0515>, 320, 1)  ; かずさは、俺の部屋から、消えてしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0516>, 321, 1)  ; 残っていたのは、彼女の残り香と、\n俺の背中に刻まれた、何本もの爪痕と、\nシーツに染み付いていた、初めての証。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0517>, 322, 1)  ; そして、なくなったものは…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0518>, 323, 1)  ; 俺の制服から引きちぎられていた、ボタン二つ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 60
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL EroMode
OPERATOR POP

STATEMENT IF _ #LABEL_2
CALL GetReplayMode
STATEMENT JMP_IF
OPERATOR POP
CALL GoTitle
OPERATOR POP

#LABEL_2
PUSH INT 80
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

ARRAY_S RES<0519>  ; CATCH
PUSH INT 1
CALL SCall
OPERATOR POP

ARRAY_S RES<0520>  ; 1013
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
