!RESOURCE "1013.csv"

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 1013
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_1
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_1
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 2502
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL SetMessageE(RES<0001>, 0, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1055
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 2502
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL SetMessageE(RES<0002>, 1, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 2502
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0003>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0004>, 2, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 3, 1)  ; 昨夜の雪は、朝には止み、\n道を覆っていた分も、ほとんど解けていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0006>, 4, 1)  ; けれど空は、昨夜の白い街をいつ再現してもいいように、\n今にも泣き出しそうな分厚い雲に覆われていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 4002
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8247
PUSH INT 0
PUSH INT 0
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 5, 1)  ; 強い風が窓を揺らす。\n音だけで寒さが伝わってくるような、嫌な風。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 6, 1)  ; 春の訪れは、まだ遠い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 2
PUSH INT 307
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1055
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0009>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0010>, 7, 1)  ; 「春希くん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0011>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 8, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 9, 1)  ; 見上げるとそこには、今、一番会わなくちゃならないひと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 10, 1)  ; 今、一番会いたくないひとが、いた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0015>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 11, 1)  ; 「ごめんなさい…\n電話、繋がらないし、鍵、開いてたし、\nもしかして、この前みたいに倒れてるんじゃって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 12, 1)  ; ああ…そういえば、さっきからチャイム鳴ってたっけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0018>, 13, 1)  ; 携帯…朝から何度も鳴ってたっけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0019>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0020>, 14, 1)  ; 「大丈夫。この通りなんともない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0021>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0022>, 15, 1)  ; 「この通りって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0023>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0024>, 16, 1)  ; 「…おかしいかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 210
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0025>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0026>, 17, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 18, 1)  ; 雪菜からの呼びかけを無視し続け、\nベッドに背をもたれ、膝を抱え、縮こまっている俺は、\nどうやら心配を抱かせるに十分な状態だったらしい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0028>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 19, 1)  ; 「本当に大丈夫だって。\nありがと、心配してくれて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0030>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0031>, 20, 1)  ; 「心配するのは当たり前だよ。\k\n
PUSH INT 2
PUSH INT 210
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 2
PUSH INT 8000
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 21, 0)  ; だって、わたしは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0033>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 22, 1)  ; 「で、どうしたの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0035>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 23, 1)  ; 「う、うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 24, 1)  ; 『だって、わたしは』の後に続く言葉を、\n今、聞いてしまう訳にはいかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 25, 1)  ; 自分が踏みにじってしまったものを、\n今さら臆面もなく受け取る訳にはいかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0039>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0040>, 26, 1)  ; 「本当は昨日言えればよかったんだけど、\k\n
PUSH INT 2
PUSH INT 311
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 2
PUSH INT 8001
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 27, 0)  ; でも、ごめん、色々あって言い忘れちゃって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0042>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 28, 1)  ; 「うん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 29, 1)  ; その雪菜の態度だけで、\nどうして昨日言わなかったのか…\nいや、言えなかったのか、わかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0045>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 30, 1)  ; 「かずさのことなんだけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 31, 1)  ; つまり、かずさからの手紙に書いてあったことだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 32, 1)  ; 俺が、雪菜の話を最後まで聞かずに、\n学校を飛び出してしまったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 33, 1)  ; …あの時、雪菜からの電話に、出なかった、から。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0050>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 34, 1)  ; 「今日、午後２時の飛行機で…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0052>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 35, 1)  ; 「そっか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0054>, 36, 1)  ; だから昨夜だったのか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 37, 1)  ; あの時のかずさの電話は、\n本気で最後のお別れのつもりだったんだな。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 38, 1)  ; 俺が、台無しにしてしまったけれど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0057>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 39, 1)  ; 「…驚かないんだね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0059>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 40, 1)  ; 「まぁ…\nここ数日ってのは、最初からわかってたことだし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 41, 1)  ; また嘘をついた。\n雪菜を騙した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 42, 1)  ; なのにもう、違和感も気持ち悪さも感じない。\n俺の中の何かが麻痺してる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0063>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 43, 1)  ; 「行こうよ、春希くん。\n今からなら十分間に合うよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0065>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 44, 1)  ; 「いいよ俺は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0067>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0068>, 45, 1)  ; 「どうして？\k\n
PUSH INT 2
PUSH INT 118
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 2
PUSH INT 8002
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 46, 0)  ; 次に会えるの、いつになるかわからないんだよ？\nわたしたちの、親友なんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0070>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 47, 1)  ; 「もう、いいんだよ、俺は」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0072>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 48, 1)  ; 「春希くん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 49, 1)  ; だってもう、何度もさよならを言った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 50, 1)  ; 別れても、ずっと好きだって、誓った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 51, 1)  ; 雪菜を………本気で裏切った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0077>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 52, 1)  ; 「雪菜」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0079>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 53, 1)  ; 「なに？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0081>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0082>, 54, 1)  ; 「それよりも、話があるんだ。\n聞いてくれないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0083>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0084>, 55, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 56, 1)  ; なんの話かも伝えていないのに、\n一瞬、雪菜の瞳が揺れた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 57, 1)  ; そりゃ、今の俺の立ち振る舞いじゃ、\nただならぬものを感じるのも無理はない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0087>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 58, 1)  ; 「あのさ、俺、本当は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 222
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0089>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 59, 1)  ; 「聞けないよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 60, 1)  ; けれど、それ以上に…\n雪菜の目には、怯えみたいな光が宿っていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0092>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 61, 1)  ; 「大事な話なんだ。\nこれ以上、先延ばしにする訳にはいかないんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 62, 1)  ; それでも続ける。\n雪菜に、残酷な俺の気持ちを告げる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 63, 1)  ; だってこれ以上、\n雪菜を裏切り続ける訳にはいかないから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 64, 1)  ; 武也の言う偽善が、たとえ皆を救うんだとしても、\nそんなのは本当の救いじゃない。本物の幸せじゃない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 65, 1)  ; …はずなのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0098>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 66, 1)  ; 「わたしにだって大事な用があるんだよ。\nかずさに会わなくちゃならないんだよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 67, 1)  ; だけど、雪菜は譲らない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0101>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 68, 1)  ; 「だから…空港への、電車の中で聞く。\nそうじゃなきゃ、絶対に聞かない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 69, 1)  ; 俺たちが、初めて名前で呼び合った、あの日みたいに、\n必死に、子供みたいな駄々をこねる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0104>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 70, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0106>, 71, 1)  ; 俺が空港に行ってしまえば、\nもう一度、かずさに会ってしまえば、\n余計、酷い別れになってしまうかもしれないのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 72, 1)  ; そして、今の雪菜は、もしかしたら、\nそのことに気づいているかもしれないのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0108>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 73, 1)  ; 「行こう、春希くん。\nまだ、終わってないんだよ、わたしたち」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 74, 1)  ; それでも雪菜は、\n俺に、その白くて細い手を差し伸べた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 75, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3104
PUSH INT 60
PUSH INT 1
PUSH INT 200
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 210
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1027
PUSH INT 1
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0112>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 76, 1)  ; 「また、降りそうだね、雪」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0114>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 77, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 204
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0116>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 78, 1)  ; 「たくさん、降らないかな？\n飛行機、止まらないかな？\n全便欠航にならないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0118>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 79, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 307
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0120>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 80, 1)  ; 「かずさ…行くのやめてくれないかな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 81, 1)  ; 空港へと向かう電車の中、\n平日の昼間のせいか、車内に人はまばらだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 82, 1)  ; 雪菜はさっきから窓の外を見上げ、\n今にも白い涙をこぼしそうな灰色の空に、\n一縷の望みをかける。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0124>, 83, 1)  ; それが、実現不可能な願いだと知っていて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0125>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0126>, 84, 1)  ; 「どうして…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0127>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 85, 1)  ; 「ん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0129>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 86, 1)  ; 「どうして…俺を責めないんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0131>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 87, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 60
PUSH INT 360
CALL SEV
OPERATOR POP

PUSH INT 24
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 88, 1)  ; もう、全部話した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0134>, 89, 1)  ; 雪菜とつきあうって約束しておいて、\n実際、それらしい態度を取っておいて、\nなのに、雪菜と違うひとを好きになってしまったこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 90, 1)  ; 誕生日パーティの、あの日のこと。\n初めての、裏切りの日のこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 91, 1)  ; かずさと呼んだ日のこと。\n雪菜との絆を、完全に断ち切ってしまった日のこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0137>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 92, 1)  ; 「こんな酷いことされて…どうして何も言わないんだよ。\nお人好しにも程があるだろ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 93, 1)  ; 本当に、全部話したんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 94, 1)  ; 雪菜と出会う前から、\nかずさに惹かれていたことも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 95, 1)  ; 雪菜とつきあうと決めたとき、\nかずさのことが頭をよぎったことも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 96, 1)  ; 雪菜とつきあい始めてからも、\nかずさをずっと気にしていたことも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 97, 1)  ; かずさを忘れるために、\n雪菜との距離を急いで縮めようとしたことも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0144>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 98, 1)  ; 「なんとか言ってくれよ。\n俺のこと殴るとか、罵るとか、\n許さないって、態度で示してくれよ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 99, 1)  ; 優しすぎることが…\n何も責めたりしないことが…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 100, 1)  ; 何よりも、心をえぐるから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 127
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0148>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 101, 1)  ; 「怒ろうにも…\nほとんど、予想の範囲内だったし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0150>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 102, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0152>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 103, 1)  ; 「春希くんの気持ちは知ってたし。\nかずさの気持ちも知ってたし。\n全部知ってて、後から割り込んだわけだし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0154>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0155>, 104, 1)  ; 「～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0156>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 105, 1)  ; 「ただ、予想できなかったことと言えば、\n二人が…悲しいくらいに真剣だったってことかな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 106, 1)  ; 見透かされてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 107, 1)  ; 俺の、単純で、移り気で、自分勝手で、\n心の底では全然他人を思いやれない性格なんて、\n全部、雪菜は最初から受け止めてくれていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 127
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0160>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 108, 1)  ; 「そこだけは、完全にわたしの計算違い。\nそのせいで、みんなバラバラになっちゃった。\n…ごめんね、春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0162>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 109, 1)  ; 「なんで雪菜が謝るんだよ…\nおかしいだろそんなの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0164>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 110, 1)  ; 「ううん、おかしくないよ。だって…\nわたしも春希くんのこと、裏切ってたんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 111, 1)  ; やめろよ雪菜…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0167>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 112, 1)  ; 「わたしが春希くんに告白したのはね、\nどうしてもあなたと恋人同士になりたかったから。\n………じゃ、ないんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 113, 1)  ; 無理して、俺なんか庇おうとしないでくれよ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0170>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 114, 1)  ; 「ただ、ずっと三人でいたかったから。\nわたしを仲間外れにして欲しくなかったから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 115, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0173>  ; sepia.amp
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 128
PUSH INT 1054
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0174>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 116, 1)  ; 「あの、馬鹿みたいに楽しかった三人でのお祭りを、\nずっと続けていたかったから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0176>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 117, 1)  ; 「ただ、そのためだけに、\nあなたの恋人に立候補したんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0178>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 118, 1)  ; 「だって、わたしが割り込まないと、\n春希くんとかずさはどんどん近づいてく。\nわたしの目の前で、恋人同士になっていく」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 128
PUSH INT 10050
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

@VCALL WN(RES<0180>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 119, 1)  ; 「そして、いつか二人は、\nわたしと少しだけ距離を置くようになる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0182>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0183>, 120, 1)  ; 「一度開いた距離は、どんどん離れてく。\n気づいたときには、二人とひとりになってる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0184>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0185>, 121, 1)  ; 「わたしは、ひとりになるのがどうしても嫌だった。\nだから、バランスを取った」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0186>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 122, 1)  ; 「春希くんの気持ちをわたしに向けさせることで、\nずっと三人でいられるよう、バランスを取ったの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 323
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 128
PUSH INT 1053
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0188>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 123, 1)  ; 「かずさには、春希くんしかいない。\n春希くんも、かずさのことを想ってる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0190>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 124, 1)  ; 「だから、わたしが春希くんの隣にいる限り、\nかずさも、わたしたちから離れていかない。\n…ほら、三人のできあがりだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 128
PUSH INT 10100
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

@VCALL WN(RES<0192>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 125, 1)  ; 「わたしは知ってたんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0194>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 126, 1)  ; 「あの時、わたしがあなたに告白したら、\nあなたは絶対に受け入れてくれるって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 127, 1)  ; 「かずさがあなたに気持ちを伝える前なら、\n絶対に勝てるって、知ってたんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 128
PUSH INT 1028
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0198>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 128, 1)  ; 「だって知ってたんだ。\n春希くんの責任感の強さ。面倒見の良さ。\n頼み事を絶対に断れない、優しさも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0200>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 129, 1)  ; 「あなたのことが好きだって、\nあなたのことが必要だって言う人のこと、\n突き放せるわけがないって、知ってたんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 128
PUSH INT 10140
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 10140
PUSH INT 0
PUSH INT 1
CALL V_Flag
OPERATOR POP

PUSH INT 10140
PUSH INT 1
PUSH INT 0
CALL V_Flag
OPERATOR POP

PUSH INT 3
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 20
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 60
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 1
CALL ChangeWeather
OPERATOR POP

@VCALL WN(RES<0202>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 130, 1)  ; 「かずさも、春希くんも傷つくって知ってて、\nそれでもわたし一人だけのために、そうしたんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0204>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 131, 1)  ; 「だから春希くんは、わたしを裏切ってないんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0206>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 132, 1)  ; 「三人でいたいって、わたしの願いを叶えるために、\n苦しんで、もがいて、我慢して…潰れちゃっただけ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0208>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 0
PUSH INT 3104
PUSH INT 60
PUSH INT 1
PUSH INT 60
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1027
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0209>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0210>, 133, 1)  ; 「だから、わたしには怒る資格なんかない。\n悲しむなんて許されない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0211>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0212>, 134, 1)  ; 「もう、いいよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 307
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0213>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0214>, 135, 1)  ; 「ごめんね…春希くんのこと、好きだけど。\nでも、かずさほど…真剣じゃ、なかったよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0215>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0216>, 136, 1)  ; 「もう、いいんだって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 137, 1)  ; まるで、雪菜が俺に一方的な別れを告げているような…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0218>, 138, 1)  ; そんな、とってつけたような自己不当化。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 323
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0219>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0220>, 139, 1)  ; 「だから、ね、気にしないで？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 140, 1)  ; ただ、俺の罪を軽くするためだけの、\n不器用にも程がある加害者の論理。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 141, 1)  ; 「春希くんが、わたしのことを許せないって言うなら、\nもう、あなたのこと追いかけたりしないから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0224>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 142, 1)  ; 「そんなこと…そんなこと言ってないっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 143, 1)  ; 許されないのは俺の方なのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 210
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0227>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 144, 1)  ; 「けれどもし、あなたがかずさを失って寂しかったり、\nわたしのこと、まだ少しでも好きでいてくれるなら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0229>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 145, 1)  ; 「やめろ雪菜、やめ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 222
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0231>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 146, 1)  ; 「わたしを、かずさの代わりにしてもいいんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0233>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 147, 1)  ; 「っ………やめろ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 148, 1)  ; 同じ車両にいた数少ない乗客たちが、\n一斉に俺たちの方を向く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 149, 1)  ; こんな公共の場所で、\n女の子相手にみっともなく怒鳴る男を、\n奇異の視線で一瞥して、すぐに目をそらす。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0237>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 150, 1)  ; 「そんなの違う…ただの現実逃避だろ。\nまたいつか壊れる。お互い、もっと深く傷つくよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0239>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 151, 1)  ; 「ううん、わたしは傷つかない。\n…違うな、傷ついても仕方ないんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 152, 1)  ; きっと、他愛のないカップルの言い争いだと思ってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0242>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 153, 1)  ; 「だってわたしが壊したんだから。\n三人でいたくて、全部バラバラにしてしまったんだから。\nだから、わたしが春希くんを慰めてあげる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0244>, 154, 1)  ; 電車を降りてしばらくしたら、すぐに仲直りして、\nまた傍目を気にせずに、今度はじゃれ合うんだろうって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 155, 1)  ; …そんなくだらない喧嘩だったら、\nどれだけ良かっただろうか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0246>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 156, 1)  ; 「もう駄目かな？\n春希くん、わたしのこと、軽蔑しちゃったかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0248>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0249>, 157, 1)  ; 「いい加減にしてくれ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 158, 1)  ; まるで噛みあわない会話。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 159, 1)  ; 雪菜は、何があっても俺の罪を認めない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0252>, 160, 1)  ; 俺が、あるはずのない雪菜の罪なんか認めないように。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0253>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0254>, 161, 1)  ; 「…やっぱり駄目かぁ。\n許してくれないんだね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 162, 1)  ; そうさ、許さない。\n雪菜が俺を許すことを、許さない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0256>, 163, 1)  ; だって、雪菜が許してしまったら、\n俺はいつまで経っても最低な人間のままだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 164, 1)  ; 二度と恋なんかできない。\n二度と人のことを好きになれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0258>, 165, 1)  ; 今、俺の目の前にいる大好きなひとでさえも、\n二度と愛することができなくなってしまうから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0259>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0260>, 166, 1)  ; 「ね、春希くん…\nわたしたち、どうすればよかったのかな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 167, 1)  ; どうして俺になんか関わっちゃったんだよ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0262>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 168, 1)  ; 「告白しなければ良かった？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0264>, 169, 1)  ; そうだよ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 170, 1)  ; ずっと告白される側だったんだろ。\n今まで全部断り続けてたって言ってたじゃないか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0266>, 171, 1)  ; どうして俺も、そいつらと同じように、\n歯牙にもかけずにいてくれなかったんだよ？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0267>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0268>, 172, 1)  ; 「学園祭に出るなんて言わなければ良かった？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 173, 1)  ; …そうだよ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 174, 1)  ; バイトが忙しかったじゃないか。\n目立つこと、したくなかったはずだろ？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0271>, 175, 1)  ; どうして俺の理不尽なワガママを、\n苦笑一つで受け入れちゃったんだよ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0272>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0273>, 176, 1)  ; 「あの夕暮れの屋上で…\n春希くんに出逢わなければよかったのかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0274>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 177, 1)  ; 「………嫌だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 178, 1)  ; そんなの、嫌だ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 179, 1)  ; あのとき、雪菜と出逢えなくて、\n雪菜の本当の姿を知ることもなくて、\n俺の学生生活に、雪菜がかすりもしないなんて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 127
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0278>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0279>, 180, 1)  ; 「うん…わたしも絶対に嫌。\nよかった、そこだけは譲れなかったんだ。\n…ありがとうね、春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0280>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 181, 1)  ; 「っ…ぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 182, 1)  ; 同じ車両にいた数少ない乗客たちが、\nまた、ちらちらと俺の方を見る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 183, 1)  ; 情けなくて、カッコ悪くて…\nけれど、そんなことがどうでも良くなるくらい悲しくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0284>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 184, 1)  ; 「…雪、降りそうだね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 185, 1)  ; 俺の表情も、空の雲と同じように、\n今にも降り出しそうに、歪んでいく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 180
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 8248
PUSH INT 60
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 300
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0287>, 186, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 187, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 188, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 60
CALL SES
OPERATOR POP

PUSH INT 60
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1023
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 1
PUSH INT 9777
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0290>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 189, 1)  ; 「ウィーンって直通便あるのかな？\nないとしたら、目的地どこだろう？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0292>, 190, 1)  ; そして…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0293>, 191, 1)  ; とうとう、ここまでやって来てしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0294>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0295>, 192, 1)  ; 「ごめんね、どの便かまでは知らないんだ。\nかずさ、時間しか教えてくれなかったから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 193, 1)  ; 俺の、すくむ足を励まし、かじかむ手を取って、\n雪菜が空港内を駆け回る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0297>, 194, 1)  ; 数日前、ここに来たときには、\n今とは逆に、あいつのこと出迎えたんだっけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 195, 1)  ; 俺たちの崩壊は、あの日から始まったんだっけ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0299>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0300>, 196, 1)  ; 「とにかく、２時にヨーロッパ方面行く便の、\n全部のゲートを回るしか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0301>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 197, 1)  ; 「もういいよ、雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 321
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0303>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 198, 1)  ; 「駄目だよ。\nもう一度ちゃんと会わないと、駄目なんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0305>, 199, 1)  ; 雪菜は、俺の泣き言を許さない。\nそして、自分も泣き言を言わない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0306>, 200, 1)  ; あれだけ酷い事実を告げられてもなお、\n俺を引きずり、かずさを探し、奔走する。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0307>, 201, 1)  ; 彼女に別れを言うためだけじゃなく、\n俺と彼女を、もう一度引き合わせるために。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0308>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0309>, 202, 1)  ; 「１４番、１７番…\nロンドン…じゃないよね、きっと。\nドイツかイタリアくらいかなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0310>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0311>, 203, 1)  ; 「無駄だよ…\nもうすぐ搭乗時刻だ。\nもうゲートの向こうかも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 204, 1)  ; 一生懸命にかずさを探す雪菜を、\n俺は、なんとか引き留めようとする。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0313>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0314>, 205, 1)  ; 「諦めちゃ駄目だってばぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0315>, 206, 1)  ; だって俺には、嫌な予感があったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0316>, 207, 1)  ; 俺の方が、先にかずさのことを見つけてしまいそうな…\nそんな、破滅の予感が、胸に突き刺さっていたから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0317>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessage(RES<0318>, 208, 1)  ; 「こっちにはいないみたい…\k\n
PUSH INT 2
PUSH INT 101
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 2
PUSH INT 8003
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0319>, 209, 0)  ; ね、次は９０番ゲートの方行ってみよう？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0320>, 210, 1)  ; 今すぐここから立ち去りたいのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0321>, 211, 1)  ; もう一度、部屋のベッドに潜り込み、\n午後２時を過ぎた後の現実から目を背けたいのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0322>, 212, 1)  ; それでも、必死で探す雪菜よりも先に、\nあいつと目が合ってしまいそうな、\nそんな気がしてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0323>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0324>, 213, 1)  ; 「こんな広いとこで、\nしかもゲートも出発便もわからない。\n最初から、無理があったんだって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0325>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0326>, 214, 1)  ; 「春希くん…頑張ろうよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 60
CALL SES
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0327>, 215, 1)  ; 例えばさ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0328>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 128
PUSH INT 1008
PUSH INT 2
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0329>, 216, 1)  ; 授業中、俺がふと隣を振り向くと、\nさっきまで、机に突っ伏して寝ていたはずのあいつが、\n不機嫌そうにぷいっと前を向くことがあったんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

ARRAY_S RES<0330>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1023
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0331>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0332>, 217, 1)  ; 「ね、あっち行こう？\n今度こそ、絶対にかずさ見つかるよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0333>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 128
PUSH INT 10010
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0334>, 218, 1)  ; けどそれって、今から考えてみれば…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 219, 1)  ; ずっとこっちを見てたからこそ、\n目をそらすことができたんじゃないのかって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 3009
PUSH INT 60
PUSH INT 1
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

ARRAY_S RES<0336>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 128
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 2000
OPERATOR ADD
PUSH INT 100000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 128
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 168
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0337>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0338>, 220, 1)  ; 「…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 25
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 9900
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
PUSH INT 1023
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0339>, 221, 1)  ; <S0ほら見ろ…>
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0340>, 222, 1)  ; 俺が振り向いた途端、\nあいつはやっぱり目をそらしたじゃないか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0341>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0342>, 223, 1)  ; 「春希くん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0343>, 224, 1)  ; 見つけるんだよ…\nあいつは、簡単に俺を見つけるんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0344>, 225, 1)  ; けれどそのことを、俺に気取られるのが嫌だから、\n絶対に、すぐに目をそらして知らんぷり…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0345>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0346>, 226, 1)  ; 「どうしたの？\n向こうはもう、さっき見てきて………あ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0347>, 227, 1)  ; 俺の視線の先を、雪菜が辿り、真実に行き着いた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0348>, 228, 1)  ; 俺の視線の先に、あいつがいる。\n何食わぬ顔をして、搭乗ゲートへと向かってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0349>, 229, 1)  ; でもその足取りは、明らかに動揺してて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0350>, 230, 1)  ; 自分の荷物を取り落としたまま、\nでも、拾いに戻ることもできなくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0351>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0352>, 231, 1)  ; 「かず…さ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0353>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0354>, 232, 1)  ; 「冬馬ぁぁぁっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 115
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0355>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0356>, 233, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 12
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0357>, 234, 1)  ; 昨夜と同じ、致命的な呼び間違え。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0358>, 235, 1)  ; けれど今は、何も考えることのできないまま、\n慣れ親しんだ苗字を叫び、必死であいつの元へ駆け寄る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0359>, 236, 1)  ; だから、駄目だったのに。\n見つけちゃいけなかったのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0360>, 237, 1)  ; また、雪菜を裏切る。\n最低で最悪の展開を自分で呼び込む。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0361>, 238, 1)  ; それでも俺の駆け出した足は止まらず、\nそしてあいつの足は、完全に止まってしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0362>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0363>, 239, 1)  ; 「やめろ…春希。\n雪菜が…雪菜が…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 10200
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0364>, 240, 1)  ; あいつの目は、俺と、その後ろを見つめてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0365>, 241, 1)  ; 泣きそうな、嬉しそうな、辛そうな、幸せそうな、\nそんな混ぜこぜの表情が、俺と雪菜に注がれてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0366>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0367>, 242, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0368>, 243, 1)  ; なのに俺は、そんなこいつの迷いを無視して、\n強引に、必死に、力いっぱい胸に抱く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0369>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0370>, 244, 1)  ; 「冬馬…冬馬っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0371>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0372>, 245, 1)  ; 「ごめん…\nごめん、雪菜っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 10200
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

@VCALL WN(RES<0373>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0374>, 246, 1)  ; 「ん…んぅ…あぁ…んっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0375>, 247, 1)  ; 舌は、噛まれなかった。\nただ、激しく絡みあっただけだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0376>, 248, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 60
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 128
PUSH INT 60
CALL MV
OPERATOR POP

CALL run
OPERATOR POP

ARRAY_S RES<0377>  ; mv07
PUSH INT 207
CALL SetMovie
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 10220
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 1
PUSH INT 10220
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 1
PUSH INT 10220
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 1
PUSH INT 10220
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 1
PUSH INT 10220
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT 800
CALL MS
OPERATOR POP

PUSH INT 128
PUSH INT 1013
CALL VI
OPERATOR POP

PUSH INT 500
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 8160
PUSH INT 120
PUSH INT 1
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 128
PUSH INT 1060
PUSH INT 1
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 8159
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 4
PUSH INT 10
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

@VCALL WN(RES<0378>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0379>, 249, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 27
PUSH INT 2
OPERATOR NEGATE
PUSH INT 1
PUSH INT 200
CALL M
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0380>, 250, 1)  ; とうとう、降ってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 198
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 1022
PUSH INT 1
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 3
PUSH INT 10
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 30
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 1
CALL ChangeWeather
OPERATOR POP

@VCALL SetMessageE(RES<0381>, 251, 1)  ; <R空港|ここ>に着いたときから、\nいつ泣き出すかもしれなかった空は、\nちょっとだけ意地を張り、その涙を冷たい風で凍らせた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0382>, 252, 1)  ; 耳をつんざくジェットエンジンの音が、\nゆっくりと遠ざっていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0383>, 253, 1)  ; その騒がしさをかき消すように、\n空から降りてくる粉雪は、\nますますその数を増やしていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 4
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 10
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 60
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 1
CALL ChangeWeather
OPERATOR POP

@VCALL SetMessageE(RES<0384>, 254, 1)  ; 俺は、そんな白さの源を探すため、\n真上にある空を見上げる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0385>, 255, 1)  ; いや、そんなのは言い訳で、\n本当は、目の前の現実から目をそらすために。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0386>, 256, 1)  ; …具体的には、今飛び立っていくあの飛行機を、\n絶対に視界に収めないために。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0387>, 257, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0388>, 258, 1)  ; とうとう、降ってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0389>, 259, 1)  ; ずっと三人でいることを誓い合った日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0390>, 260, 1)  ; 三人から二人が抜け出してしまった日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 2
PUSH INT 222
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1022
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 3
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 10
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 60
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 1
CALL ChangeWeather
OPERATOR POP

@VCALL WN(RES<0391>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0392>, 261, 1)  ; 「春希…くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0393>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0394>, 262, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0395>, 263, 1)  ; そして今日…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0396>, 264, 1)  ; 二人から一人が去り、\n一人と一人が残されてしまった日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0397>, 265, 1)  ; いつも、俺たちの分岐点に現れて、\n辛いこと、哀しいことを覆い隠すように、\n雪が、降り積もる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0398>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 266, 1)  ; 「帰ろう…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0400>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 267, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0402>, 268, 1)  ; かずさは去った。\nそして、俺と雪菜だけが残った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0403>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0404>, 269, 1)  ; 「帰ろうよ…\nもう、ここには何もないよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0405>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0406>, 270, 1)  ; 「………だな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0407>, 271, 1)  ; 言葉とは裏腹に、足は一歩も動かない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0408>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0409>, 272, 1)  ; 「せめて、空港の中に戻ろう？\nあったかいコーヒーでも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0410>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0411>, 273, 1)  ; 「うん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0412>, 274, 1)  ; 空を見上げた視線を、\n声の主に戻すことすらしない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0413>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0414>, 275, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0415>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0416>, 276, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0417>, 277, 1)  ; そして、そんな突き放した態度を、\n謝ることすらしない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0418>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0419>, 278, 1)  ; 「春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0420>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 140
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0421>, 279, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0422>, 280, 1)  ; 一度、最低の裏切りをしてしまった相手だから。\nもう、ずっと最低を貫かなくちゃならないから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0423>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 141
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0424>, 281, 1)  ; 「どうしても、わたしの願いを聞いてはくれないの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0425>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 142
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0426>, 282, 1)  ; 「別に…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0427>, 283, 1)  ; だから、俺なんかに優しい言葉をかけないで欲しい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0428>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 143
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0429>, 284, 1)  ; 「あなたがずっとここから動かないって言うんなら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0430>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 144
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0431>, 285, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
ARRAY_S RES<0432>  ; v103200_bg.tga
PUSH INT 3
PUSH INT 2
ARRAY_S RES<0433>
PUSH INT 256
ARRAY_S RES<0434>  ; grp
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 1
ARRAY_S RES<0435>  ; v103200_fence.tga
PUSH INT 4
PUSH INT 2
ARRAY_S RES<0436>
PUSH INT 256
ARRAY_S RES<0437>  ; grp
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 2
ARRAY_S RES<0438>  ; v103200_chr.tga
PUSH INT 5
PUSH INT 2
ARRAY_S RES<0439>
PUSH INT 256
ARRAY_S RES<0440>  ; grp
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

PUSH INT 2
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

PUSH INT 60
PUSH INT 255
PUSH INT 255
PUSH INT 255
CALL FB
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

PUSH INT 2
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
PUSH INT 360
OPERATOR MOV
OPERATOR POP
STATEMENT FOR #LABEL_2 #LABEL_3 #LABEL_4 #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
OPERATOR MOV
OPERATOR POP

#LABEL_3
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR LEQ
STATEMENT JMP_FOR

#LABEL_4
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR INC
OPERATOR POP
STATEMENT GOTO #LABEL_3

#LABEL_5
OPERATOR POP
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
PUSH FLOAT 90
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
CALL sin
OPERATOR MUL
OPERATOR MOV
OPERATOR POP
ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
PUSH INT 1280
PUSH INT 1280
PUSH FLOAT 5
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
OPERATOR SUB
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
OPERATOR ADD
OPERATOR MOV
OPERATOR POP
ARRAY_L 33
PUSH INT 0
OPERATOR INDEX
PUSH INT 720
PUSH INT 720
PUSH FLOAT 5
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
OPERATOR SUB
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
OPERATOR ADD
OPERATOR MOV
OPERATOR POP
ARRAY_L 49
PUSH INT 0
OPERATOR INDEX
ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
PUSH INT 1280
OPERATOR SUB
OPERATOR NEGATE
PUSH INT 2
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
ARRAY_L 50
PUSH INT 0
OPERATOR INDEX
ARRAY_L 33
PUSH INT 0
OPERATOR INDEX
PUSH INT 720
OPERATOR SUB
OPERATOR NEGATE
PUSH INT 2
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
ARRAY_L 50
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
OPERATOR MOV
OPERATOR POP
PUSH INT 0
ARRAY_L 49
PUSH INT 0
OPERATOR INDEX
ARRAY_L 50
PUSH INT 0
OPERATOR INDEX
ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
ARRAY_L 33
PUSH INT 0
OPERATOR INDEX
CALL SetBmpZoom
OPERATOR POP

ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
PUSH INT 1280
PUSH INT 1280
PUSH FLOAT 3
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
OPERATOR SUB
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
OPERATOR ADD
OPERATOR MOV
OPERATOR POP
ARRAY_L 33
PUSH INT 0
OPERATOR INDEX
PUSH INT 720
PUSH INT 720
PUSH FLOAT 3
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
OPERATOR SUB
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
OPERATOR ADD
OPERATOR MOV
OPERATOR POP
ARRAY_L 49
PUSH INT 0
OPERATOR INDEX
ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
PUSH FLOAT 1280
OPERATOR SUB
OPERATOR NEGATE
PUSH INT 2
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
ARRAY_L 50
PUSH INT 0
OPERATOR INDEX
PUSH FLOAT 720
PUSH INT 0
OPERATOR MUL
PUSH FLOAT 720
PUSH INT 0
OPERATOR MUL
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 1
ARRAY_L 49
PUSH INT 0
OPERATOR INDEX
ARRAY_L 50
PUSH INT 0
OPERATOR INDEX
ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
ARRAY_L 33
PUSH INT 0
OPERATOR INDEX
CALL SetBmpZoom
OPERATOR POP

ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
PUSH INT 1280
PUSH INT 1280
PUSH FLOAT 2
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
OPERATOR SUB
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
OPERATOR ADD
OPERATOR MOV
OPERATOR POP
ARRAY_L 33
PUSH INT 0
OPERATOR INDEX
PUSH INT 720
PUSH INT 720
PUSH FLOAT 2
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
OPERATOR SUB
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
OPERATOR ADD
OPERATOR MOV
OPERATOR POP
ARRAY_L 49
PUSH INT 0
OPERATOR INDEX
ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
PUSH FLOAT 1280
OPERATOR SUB
OPERATOR NEGATE
PUSH INT 2
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
ARRAY_L 50
PUSH INT 0
OPERATOR INDEX
PUSH FLOAT 720
PUSH INT 2
OPERATOR MUL
PUSH FLOAT 720
PUSH INT 2
OPERATOR MUL
ARRAY_L 43
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 2
ARRAY_L 49
PUSH INT 0
OPERATOR INDEX
ARRAY_L 50
PUSH INT 0
OPERATOR INDEX
ARRAY_L 48
PUSH INT 0
OPERATOR INDEX
ARRAY_L 33
PUSH INT 0
OPERATOR INDEX
CALL SetBmpZoom
OPERATOR POP

ARRAY_L 26
PUSH INT 0
OPERATOR INDEX
PUSH FLOAT 255
PUSH FLOAT 127
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_L 19
PUSH INT 0
OPERATOR INDEX
PUSH INT 2
OPERATOR DIV
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_6
ARRAY_L 26
PUSH INT 0
OPERATOR INDEX
PUSH INT 128
OPERATOR LT
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 26
PUSH INT 0
OPERATOR INDEX
PUSH INT 128
OPERATOR MOV
OPERATOR POP

#LABEL_6
OPERATOR POP
PUSH INT 0
ARRAY_L 26
PUSH INT 0
OPERATOR INDEX
ARRAY_L 26
PUSH INT 0
OPERATOR INDEX
ARRAY_L 26
PUSH INT 0
OPERATOR INDEX
CALL FB
OPERATOR POP

STATEMENT GOTO #LABEL_4

#LABEL_2
PUSH INT 0
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT 4
ARRAY_S RES<0441>  ; v103201.tga
PUSH INT 7
PUSH INT 2
ARRAY_S RES<0442>
PUSH INT 256
ARRAY_S RES<0443>  ; grp
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 4
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

PUSH INT 4
PUSH INT 1
PUSH INT 255
PUSH INT 60
CALL SetBmpParam
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

PUSH INT 1
CALL ReleaseBmp
OPERATOR POP

PUSH INT 2
CALL ReleaseBmp
OPERATOR POP

PUSH INT 1
PUSH INT 10320
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 10320
PUSH INT 0
PUSH INT 1
CALL V_Flag
OPERATOR POP

PUSH INT 10320
PUSH INT 1
PUSH INT 0
CALL V_Flag
OPERATOR POP

PUSH INT 4
CALL ReleaseBmp
OPERATOR POP

@VCALL WN(RES<0444>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 145
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0445>, 286, 1)  ; 「わたし、こうしてる。\nあなたが冷えてしまわないように、\nずっとこうしてるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0446>)  ; 春希
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 146
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0447>, 287, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0448>, 288, 1)  ; 背中に感じる柔らかさと温かさ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0449>, 289, 1)  ; 俺の胸に回され、しっかりと握りしめられた両手の強さ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0450>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 147
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0451>, 290, 1)  ; 「こうされることが嫌なら…\nかずさを裏切ってしまうって、辛く感じるなら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0452>, 291, 1)  ; そして、心を締めつける重さ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0453>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 148
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0454>, 292, 1)  ; 「早く、ここを動いて。\nわたしを、振りほどいて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0455>, 293, 1)  ; そんな、背中から伝わる温かさに、凍りつく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0456>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 149
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0457>, 294, 1)  ; 「ね、春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0458>, 295, 1)  ; 雪菜が純粋であればあるほど、\n自分の罪深さに押し潰される。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0459>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 150
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0460>, 296, 1)  ; 「これ以上、ここから動こうとしないなら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0461>, 297, 1)  ; こんなに優しくしてくれて…\n精一杯、我慢して背伸びして許して、\n自分の中のしこりを、俺のために全部抑え込んで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0462>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 151
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0463>, 298, 1)  ; 「勘違い、するよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0464>, 299, 1)  ; なのに…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0465>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 152
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0466>, 300, 1)  ; 「悲しさのあまり、あなたがわたしを受け入れてるって、\n最低の思い込み、しちゃうよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0467>, 301, 1)  ; そんな瞬間も、俺の頭の中を占めているのが、\nかずさのことしかないって事実に。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0468>, 302, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 198
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 4
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 10
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 60
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 1
CALL ChangeWeather
OPERATOR POP

@VCALL SetMessageE(RES<0469>, 303, 1)  ; とうとう、降ってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0470>, 304, 1)  ; 一番大切なものを失った日にも、\nやっぱり、俺の前にその白い姿を見せてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0471>, 305, 1)  ; 雪は、覆い隠してくれる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0472>, 306, 1)  ; 辛いこと、哀しいこと。\nそして、見たくもない真実を。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0473>, 307, 1)  ; ただ白く、綺麗なだけの世界を目の前に広げ、\n俺たちを、そこに置き去りにしてくれる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0474>, 308, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 10320
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 10320
PUSH INT 0
PUSH INT 1
CALL V_Flag
OPERATOR POP

PUSH INT 10320
PUSH INT 1
PUSH INT 0
CALL V_Flag
OPERATOR POP

PUSH INT 3
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 10
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 60
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

@VCALL SetMessageE(RES<0475>, 309, 1)  ; けれど、所詮雪は雪であり。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0476>, 310, 1)  ; 一度解けたら、そうやって隠していた事実を、\n忘れていた想いを、もう一度白日の下にさらす。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0477>, 311, 1)  ; 黒く汚れ、ぐちゃぐちゃに踏み潰された泥のように。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 60
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 180
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 180
CALL SES
OPERATOR POP

PUSH INT 320
CALL MS
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 198
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

CALL ResetWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
CALL SetDemoMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0478>  ; sepia.amp
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 3000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 198
PUSH INT 1064
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL WN(RES<0479>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 153
CALL VV
OPERATOR POP

@VCALL SetMessage2(RES<0480>, 312, 1)  ; 「次が…最後の曲です」
PUSH INT 3000
CALL WaitTimer
OPERATOR POP

PUSH INT 0
PUSH INT 8255
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

CALL WaitMessage2
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 155
PUSH INT -1
CALL VI
OPERATOR POP

@VCALL WN(RES<0481>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 155
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0482>, 313, 1)  ; 「この曲は…\n多分、皆さん知らないんじゃないかと思います」<w360>
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0483>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 156
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0484>, 314, 1)  ; 「…多分もなにもないですね。\n昨日完成したばかりの、わたしたちのオリジナルです」<w420>
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0485>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 157
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0486>, 315, 1)  ; 「一日しか練習してないので、\nうまくできるかどうかわかりませんけど…」<w420>
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0487>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 158
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0488>, 316, 1)  ; 「最後の最後まで、\n心の底から楽しんで歌います。\n皆さん聴いてください」<w420>
PUSH INT 1
CALL EndMessage
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL WN(RES<0489>)  ; 雪菜
PUSH INT 2
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 159
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0490>, 317, 1)  ; 「タイトルは…<w300>『届かない恋』です」<w300>
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetDemoMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0491>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 21
PUSH INT 2
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
CALL M
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 22
PUSH INT 2
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
CALL M
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

CALL run
OPERATOR POP

ARRAY_S RES<0492>  ; mv08
PUSH INT 208
CALL SetMovie
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

CALL run
OPERATOR POP

CALL run
OPERATOR POP

ARRAY_S RES<0493>  ; mv09
PUSH INT 209
CALL SetMovie
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

ARRAY_S RES<0494>  ; 2001
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
