!RESOURCE "2020.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 2020
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2010
PUSH INT 12
PUSH INT 26
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8193
PUSH INT 0
PUSH INT 1
PUSH INT 50
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0004>, 0, 1)  ; クリスマスイブを過ぎたクリスマスの日は、\n基本的には、ただの冬の一日に過ぎなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 1, 1)  ; 明け方にやんでしまった雪は、\n道行く人にただ寒さと歩きにくさを与えるだけで、\n昼を過ぎた頃にはすっかり黒く土に溶け込んでいた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0006>, 2, 1)  ; …そんな皮肉めいた見方しかできないのは、\n自分の精神状態のせいという可能性も\n否定できなかったけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 15
CALL SES
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 168
PUSH INT 2135
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 42
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0007>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 3, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 4, 1)  ; そして、今はもうクリスマスでもない、\nただの冬の一日。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0010>, 5, 1)  ; 部屋に帰り着いてから、２４時間以上が過ぎた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 6, 1)  ; 窓の外の黒い空が白く薄曇っていくのを\nリアルタイムで全て視界に収め\n明けない夜が本当にないということを痛感した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 7, 1)  ; そして厚い雲に覆われた空は、\nそのまままたリアルタイムで黒く染まっていき、\n暮れない昼が本当にないということまで思い出させた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 8, 1)  ; それからは地獄の責め苦のように、\n冬特有の長い夜を、灯りをつけないまま、\nまんじりともせずに過ごし。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 9, 1)  ; そして、やっと訪れた二度目の日の出は、\n今度こそ明るい<R朝陽|あさひ>を俺の目に焼きつけた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2201
PUSH INT 0
PUSH INT 1
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 10, 1)  ; そんなに時間が経過したというのに、\n俺はまだ、あれから一睡もできてない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 11, 1)  ; 疲れと眠気に苛まれているはずの頭は、\nそれでもただ一人の記憶を追い出すことができなくて、\n割れんばかりの痛みばかりを俺にもたらす。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 12, 1)  ; このまま部屋に一人で居続けたら、\n頭がどうにかなってしまいそうだったけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0018>, 13, 1)  ; 結局、どこにも逃げ出す場所なんかなくて。\n誰も逃げ場になってくれる人なんかいなくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 14, 1)  ; 俺はまだ、出口さえ見えない暗闇の中をさまよう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8194
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0020>)  ; 留守電アナウンス
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 15, 1)  ; 「ただ今留守にしております。\nご用の方は発信音の後にメッセージをお願いします」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 0
CALL VS
OPERATOR POP

PUSH INT 0
PUSH INT 8206
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0022>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 16, 1)  ; 「…本当に出かけてんのかよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 17, 1)  ; 「おい春希、この前の件だけどな、\n帰ってきたらちゃんと話しようぜ？\n…これ聞いたらすぐに連絡してくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0026>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 18, 1)  ; 「携帯とこっち、両方に入れとくから、\nシカトすんじゃねえぞ？　じゃあな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2205
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0028>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 19, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0030>, 20, 1)  ; さっきの携帯も武也からだった。\nこれでもう、二日で九度目の居留守になる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 21, 1)  ; 最初は、いつまでも電話の通じない俺に対する\n揶揄みたいな響きが含まれてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 22, 1)  ; それは、俺がまだ雪菜と一緒にいるんじゃないかって、\nそんな下世話で温かい期待だったんだと思う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 23, 1)  ; けれど、昨日の夜中…\n依緒からの連絡が来て以降、雲行きが怪しくなる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 24, 1)  ; 彼女の口調は妙に切羽詰まってて、\nけれど内容は、俺の予測を少しも外れはしなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 25, 1)  ; 雪菜と会ったこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 26, 1)  ; 何もなかったって雪菜が言ったこと。\n笑ってたこと、泣いてなかったこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 27, 1)  ; …嘘を、ついてるってわかってしまったこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 28, 1)  ; 数年来の親友だからこそわかる些細な変化。\n無理な明るさ、滲み出る虚しさ、隠せない痛み。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 29, 1)  ; それらの様々な負の感情が雪菜を蝕んでいるって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 30, 1)  ; …その電話があってから後、\n朝まで、依緒と武也からのコールが\n一時間おきくらいに数件続いてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 31, 1)  ; 自分たちが仕掛人だからってだけじゃない。\n純粋に俺たちを心配してるって口調から、\nあいつらの焦燥感が伝わってくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8193
PUSH INT 0
PUSH INT 1
PUSH INT 100
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL SetMessageE(RES<0042>, 32, 1)  ; なのに俺は、\nまるであいつらの慌てぶりを他人事のように俯瞰して、\nスルーを繰り返す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 33, 1)  ; だって、何と答えたらいいのかわからない。\n近すぎるからこそ、何も話せない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 34, 1)  ; あいつらの反応がわかってるからこそ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 35, 1)  ; その反応が、俺にとって痛くて、\nけれど俺を楽にしてしまうからこそ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 36, 1)  ; あいつらは、きっと俺に罰を与える。\n怒り、嘆き、叱責して、必死に俺たちに干渉し、\nなんとか解決策を探そうとするだろう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 37, 1)  ; そして俺は、そのあいつらの干渉に対して、\n罰を受けた気になり、自らの思考を止めてしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 38, 1)  ; そんな自己満足の停滞なんて意味がない。\n解決していないのに、\n解決した気になることほど最悪の事態はない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 39, 1)  ; 痛みを正面から受け止めたって、\n先に進めないなら無駄だ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0050>, 40, 1)  ; だって、俺が楽になった瞬間も、\n雪菜にとっては何も解決してない、救われてない。\nだったら俺一人が楽になることは、何ももたらさない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 41, 1)  ; だから俺は…結局、動けない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0052>, 42, 1)  ; この優しい陽射しに包まれた空が、\nリアルタイムに赤く、そして黒く染まっていくのを\nただ眺める。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 43, 1)  ; 次の夜が明けたら、\n少しは前に進む気になれるんだろうかって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0054>, 44, 1)  ; そんな、初歩も初歩の自問自答を繰り返しつつ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0055>  ; CATCH2
PUSH INT 100
CALL SCall
OPERATOR POP

STATEMENT IF #LABEL_13 #LABEL_14
ARRAY_G 10
PUSH INT 1
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
ARRAY_S RES<0056>  ; 2021
PUSH INT 0
CALL SLoad
OPERATOR POP

#LABEL_13
STATEMENT ELSE
ARRAY_S RES<0057>  ; 2025
PUSH INT 0
CALL SLoad
OPERATOR POP

#LABEL_14
STATEMENT HALT
