!RESOURCE "2021.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 2021
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2010
PUSH INT 12
PUSH INT 28
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 8193
PUSH INT 0
PUSH INT 1
PUSH INT 100
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0004>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 2, 1)  ; 音源との距離感を掴めないまま、\n薄暗がりの中、闇雲に手を伸ばす。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 3, 1)  ; やっと指先に触れた固い物体は規則的に震え、\nそれが俺の探していたものだと教えてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0010>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 4, 1)  ; 「はい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 5
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0012>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 5, 1)  ; 「あ、北原か？\n私、風岡」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0014>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 6, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 7, 1)  ; 何気なく電話に出てから気がついた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 8, 1)  ; 人と会話するのが、数日ぶりだってことに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 9, 1)  ; 「…あれ？　起きてる？\n昼過ぎだから大丈夫だと思ったんだけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 10, 1)  ; 「ああ、えっと…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0022>, 11, 1)  ; 久々の会話に、頭がついていかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 12, 1)  ; しかも寝起きであることが、\n反応の鈍さに拍車をかける。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 13, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0026>, 14, 1)  ; と、その『寝起き』という事実に行き着き、\n余計に妙な反応を返してしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0027>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0028>, 15, 1)  ; 「…済まない。\nどうやら本当に寝てたみたいだな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0029>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0030>, 16, 1)  ; 「いえ、そんな…問題ないです。\nちょっとうたた寝しちゃってただけで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 17, 1)  ; 眠ってたんだ、俺…\nとうとう、眠れたんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0032>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 18, 1)  ; 「ということは、今は家？\n大丈夫？　ちょっとだけでも話せる？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0034>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 19, 1)  ; 「…今、何日の何時ですか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0036>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 20, 1)  ; 「…北原、お前一体何日間寝てたんだよ？\n２８日の１３時半だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 1
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1017
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0038>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 21, 1)  ; 「っ…\nそう、ですか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 22, 1)  ; ２４時間以上ぶりにカーテンを開けると、\n冬の柔らかい陽射しでさえ眩しくて目がくらむ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 23, 1)  ; 時計が１２時を指していた記憶は残ってる。\nてことは、眠れたのは１時間程度か。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0042>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 24, 1)  ; 「…なんか大丈夫じゃなさそうだな。\n明日にでもかけ直そうか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0044>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 25, 1)  ; 「ああ、いや、大丈夫ですから。\nなんでした？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 26, 1)  ; 本当は、頭も体もちっとも休まっていない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 27, 1)  ; 相変わらず頭はぼうっとしたまま。\nもやもやした気分は引きずったまま。\n中途半端な睡眠が、余計に体を疲れさせた気もする。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 28, 1)  ; それでも、この睡眠には大きな意味があった。\n何より、人と話せるきっかけをもたらした。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 29, 1)  ; ずっと逃げていたはずの、人からの接触に、\n無意識のおかげで応えることができたんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0050>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 30, 1)  ; 「いや、大した話じゃないんだけど…\n最近、バイトの方顔出してないから。\nその、元気でやってるか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0052>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 31, 1)  ; 「………元気ですよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0054>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 32, 1)  ; 「その声で言われてもなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0056>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 33, 1)  ; 「寝起きですから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 34, 1)  ; その、久々の人とのコミュニケーションで、\n早速嘘をつくことになるのは、少し気が引けるけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0059>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 35, 1)  ; 「ま、いいや。\nそれで、今度はいつ来てくれる？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0061>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 36, 1)  ; 「ええと、それは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0063>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 37, 1)  ; 「年末進行終わったからって、暇な訳じゃないんだ。\nみんなお前の手を借りたがってる。\n時間があれば手伝いに来てくれないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0065>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 38, 1)  ; 「…ありがとう、ございます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0067>, 39, 1)  ; その言葉は、今のこんな俺にとってでも、\n迷惑とも、お節介とも感じられなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 40, 1)  ; 図らずとも世界と隔絶されてしまった時にこそ、\nその世界に必要とされてるって伝えてくれる言葉は、\nそれだけで嬉しくなる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0069>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 41, 1)  ; 「あ、けれど私の方は、今年中はもう来ないんだ。\n今日から取材でアメリカ。で、今成田」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0071>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 42, 1)  ; 「へぇ…年末なのに？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0073>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 43, 1)  ; 「ニューヨークとかロスとか色々回って、\n帰りがけにグァムで友達と合流してそこからバカンス。\nこっちに帰ってくるのは来年の５日くらい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0075>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 44, 1)  ; 「そうですか…\nお疲れさまです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

CALL IfSkip
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 45, 1)  ; そっか、そのことを伝えに…\nたかがバイトの部下に対して、相変わらず律儀な…
PUSH INT 1
CALL EndMessage
OPERATOR POP

STATEMENT IF _ #LABEL_13
ARRAY_G 16
PUSH INT 1
OPERATOR EQ
STATEMENT JMP_IF
OPERATOR POP
@VCALL WN(RES<0078>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 46, 1)  ; 「…あ、友達って男じゃないぞ？\n北原も会ったよな？　ほら、雨宮佐和子。\n毎年恒例のまるっきり男っ気のない女の二人旅で…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0080>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 47, 1)  ; 「は、はぁ…そうですか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0082>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 48, 1)  ; 「………いや、そんなこと北原に言っても仕方ないな。\n済まなかった、今のは忘れてくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0084>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 49, 1)  ; 「？　わかりました。\n佐和子さんにもよろしく伝えてください。\n楽しんできてくださいって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0086>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 50, 1)  ; 「いいよ別にあいつはどうでも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

CALL IfSkip
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 51, 1)  ; 麻理さんの、その妙に言い訳がましい態度の意味は、\n今の俺には、よく意味がわからなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

#LABEL_13
@VCALL WN(RES<0089>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 52, 1)  ; 「あ、それで、ここからが一応の本題。\n北原の住所に郵便物送っといたから。\nこっちにも昨日届いたばかりで直接渡す時間がなくて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0091>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0092>, 53, 1)  ; 「俺に？\n一体なんです？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0093>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 54, 1)  ; 「それがね…\n冬馬曜子のニューイヤーコンサートのチケット」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0095>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 55, 1)  ; 「え…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0097>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 56, 1)  ; 「冬馬曜子の事務所から、\n直接アンサンブルの編集部に送られてきたんだって。\n…あの記事を書いたライターにって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0099>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 57, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 58, 1)  ; やっと普通に声が出るようになってきたところに、\nまた頭を真っ白にしてくれる名字がこぼれ出た…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0102>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 59, 1)  ; 「凄いな北原。\n初めての記事でここまで取材元に気に入られるなんて\n普通はないぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0104>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 60, 1)  ; 「い、いや…\nそれは相手が特殊なだけで…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0106>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 61, 1)  ; 「せっかくだから楽屋に顔出してみたらどうだ？\nきっとアンサンブルの名前を出せば会ってくれるぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0108>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 62, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0110>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 63, 1)  ; 「ウチの業界は人脈が特に大事だからな。\n会っておいて損なことは一つもないぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 64, 1)  ; 事情も知らずに軽く言ってくれる麻理さんに、\n俺はますます言葉を詰まらせていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 65, 1)  ; もし、俺が冬馬曜子に会いに行ったら、\n向こうは二度も驚くことになるだろう。\nあの記事を書いたのが娘の…だったって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 66, 1)  ; …いや、覚えてる方がおかしいか。\n三年前に一度会ったきりだし。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0115>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 67, 1)  ; 「あの、麻理さん。\nありがたい話ですけど、俺は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0117>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 68, 1)  ; 「もしかしたら…\n冬馬かずさと会わせてくれるかもしれないだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0119>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0120>, 69, 1)  ; 「………ぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0121>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 70, 1)  ; 「会いたいんじゃないのか？　本当は」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 71, 1)  ; 『事情も知らずに』なんて…\n麻理さんを甘く見てたとしか言いようがない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0124>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 72, 1)  ; 「なん、で…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0126>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 73, 1)  ; 「あの記事が世に出てから、北原来なくなったからさ…\nもしかして、昔を思い出して\n落ち込んでるんじゃないかって思って」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0128>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 74, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 75, 1)  ; いや、本当の事情を知るはずがない。\nそんな深くまで喋った記憶なんかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0131>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 76, 1)  ; 「…そこで笑い飛ばしてくれたら\n私も安心できたんだがな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0133>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0134>, 77, 1)  ; 「すいません…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 78, 1)  ; それはただ、純粋に麻理さんの洞察力の賜物であり。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 79, 1)  ; そしてそれは、俺をそこまで心配してくれているという\n動かぬ証拠でもあった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0137>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 80, 1)  ; 「北原って結構ナイーブだよな。\n傷つきやすくて、自分で自分を責めてばかりで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0139>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 81, 1)  ; 「そう…でしょうか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0141>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 82, 1)  ; 「そうだよ。それに辛いことがあると、\n仕事や勉強に逃げようとするから、\nすぐにそういうのわかるし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 83, 1)  ; 本当に、俺のこと見ててくれるんだな、この人。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0144>, 84, 1)  ; それでも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0145>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 85, 1)  ; 「傷ついてるからって理由で、\n俺が被害者だって言うのは、違うと思います」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0147>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 86, 1)  ; 「ん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0149>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0150>, 87, 1)  ; 「だって…\n相手につけた傷の深さに比べたら、\n俺のかすり傷なんて、笑ってしまうくらいの軽さで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0151>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 88, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 89, 1)  ; それでもやっぱり、\n自分の部下に対する贔屓目が抜けてないのは、\n好ましくて、そして間違ってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0154>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0155>, 90, 1)  ; 「そんな俺が、こうして麻理さんに慰めてもらうなんて、\nおこがましいにも程があると思うんですよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0156>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 91, 1)  ; 「だから余計落ち込むのか？\n誰も、自分を叱ってくれないから。\n…叱った後、許してくれないから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0158>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 92, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0160>, 93, 1)  ; 麻理さんの指摘は、\n俺が昨日まで考えてたこととほとんど一緒だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3105
PUSH INT 60
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 5
PUSH INT 16
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1023
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 0
PUSH INT 210
CALL SES
OPERATOR POP

@VCALL WN(RES<0161>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 94, 1)  ; 「じゃあ…私はお前を責めないよ。\nだから、許しもしない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0163>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 95, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0165>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 96, 1)  ; 「北原が話すだけ。それを私が聞くだけ。\n誰もお前を許しはしないけど、\nそれでもお前は少しだけ楽になる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0167>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 97, 1)  ; 「けど…俺一人が楽になったって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 1
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0169>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0170>, 98, 1)  ; 「自分が楽になれば、\n相手に償おうって気も起きるんじゃないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0171>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 99, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0173>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0174>, 100, 1)  ; 「ま、話したくないなら別にいいけど。\n完全にお前のプライベートだし、\n私はバイト先の上司でしかないし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2906
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0175>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 101, 1)  ; 「聞いて…くれるんですか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 98
PUSH INT 9000
PUSH INT -1
PUSH INT 128
PUSH INT 0
PUSH INT 1
CALL VX
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 5
PUSH INT 12
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0177>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 102, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0179>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 103, 1)  ; 「麻理さん…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 16
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0181>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 104, 1)  ; 「………聞くよ。\nそして何もアドバイスはしない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0183>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 105, 1)  ; 「ありがとう…ございます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 16
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0185>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 106, 1)  ; 「それで？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0187>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0188>, 107, 1)  ; 「俺、冬馬かずさのこと、今でも好きだったんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 12
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0189>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0190>, 108, 1)  ; 「そ、そうか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0191>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0192>, 109, 1)  ; 「まだ、忘れてなかったんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0193>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0194>, 110, 1)  ; 「ま、まぁ…そんな感じはしてたよな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0195>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0196>, 111, 1)  ; 「そのせいで、傷つけてしまった相手がいるんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 13
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0197>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0198>, 112, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 1
CALL VS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 113, 1)  ; 呆れるくらい赤裸々に喋ってしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0200>, 114, 1)  ; 俺が最初にユニットに引き入れたのは、\nこともあろうにミス峰城付属の女の子だったこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 115, 1)  ; その人気と注目度の高さとは裏腹に、\nありえないほど気さくな彼女と、\nあっという間に馴染んでいったこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0202>, 116, 1)  ; 学園祭のステージが終わった夜…\n俺が気持ちを確かめ合ったのは、\nかずさじゃなく、彼女だったこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 117, 1)  ; その頃、周囲に公認だったのは、\nかずさと俺じゃなく、彼女と俺だったことも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0204>, 118, 1)  ; かずさとのことで彼女を裏切り、\nそれからも、ずっと沢山のことを抱え、\nお互い引きずったままだってこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 119, 1)  ; そして、クリスマスの夜…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0206>, 120, 1)  ; かずさとのことで、また彼女を裏切り、\nお互いがまだ引きずっているって再認識してしまったこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0207>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0208>, 121, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 122, 1)  ; 麻理さんは公約通り、ただ黙って聞いてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0210>, 123, 1)  ; 時々、俺の話の時系列が飛んでしまった時に、\nほんの少し補足を挟む以外は、\n本当に俺の喋るままにしてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 124, 1)  ; だから俺は最後まで、\n本当に、肝心なところまで喋って…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0212>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 125, 1)  ; 「…すいません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0214>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 126, 1)  ; 「なんで謝るんだ？\n私は“聞く”って言ったぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0216>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 127, 1)  ; 「それでも、話し過ぎたかなって。\n酒の席でもないのに。\nそれどころか、面と向かってもいないのに…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0218>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 128, 1)  ; 「面と向かってないからこそ話せたんだろ？\nこれだと、相手の反応が見えないもんな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0220>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 129, 1)  ; 「そう…なんでしょうか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 130, 1)  ; 「それに、しばらく顔合わせないからこそ話せたんだろ？\n次に顔を合わせるときは、\nもうお互い忘れてるかもしれないもんな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0224>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 131, 1)  ; 「かも、しれませんね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 132, 1)  ; 次に会ったときだって、\nきっとお互い覚えてるってのはわかってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 133, 1)  ; それでも、時間さえ経っていれば、\n忘れた“ふりをする”のがそれだけ簡単になる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 134, 1)  ; そこまで配慮して、\nわざと電話越しに話を聞いてくれた。\n…ってのは、さすがに考えすぎだろうか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0229>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 135, 1)  ; 「にしても、若いな北原は。\nたまにこういう青い話を聞くとほっとする」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0231>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 136, 1)  ; 「俺…普段、そんなに年寄り臭いですか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0233>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 137, 1)  ; 「ま、悪い意味じゃないよ。\n落ち着きすぎてるって言うか、\n理屈っぽいって言うか、醒めてるって言うか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0235>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 138, 1)  ; 「悪い意味じゃないんですかそれ全部…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 5
PUSH INT 12
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1023
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0237>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 139, 1)  ; 「あのさ…\n最初に約束した通り、私は責めも許しもしない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0239>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 140, 1)  ; 「はい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0241>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0242>, 141, 1)  ; 「だから、北原の話を聞きながら、\n私ならどうするかって考えてたんだけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0243>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0244>, 142, 1)  ; 「麻理さんなら…どうしますか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0245>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0246>, 143, 1)  ; 「正直、わからないよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0247>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0248>, 144, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0249>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 145, 1)  ; 「お前が選んだ選択が…\nお前のしたことが正しいのか、\n私にはわからなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0251>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0252>, 146, 1)  ; 「そう、ですか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0253>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0254>, 147, 1)  ; 「『そうか、大変だな』とも言えないし、\n『私にもわかるよ』とも言えない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0255>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0256>, 148, 1)  ; 「麻理さん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 7
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0257>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0258>, 149, 1)  ; 「だからやっぱり『お前は間違ってる』とも言えない。\n…いや、まぁ、元から言わない約束だけどな、それは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0259>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0260>, 150, 1)  ; 「はい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 16
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0261>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 151, 1)  ; 「すまないな…\n私、どうやら本当の役立たずみたいだ。\nこういう話は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0263>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0264>, 152, 1)  ; 「ありがとうございます。\nそれで十分です」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 4
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0265>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0266>, 153, 1)  ; 「なんでだ？\n私、フォローも何もしてないぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0267>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0268>, 154, 1)  ; 「俺…自分だけが間違ってるんじゃないかって…\n自分だけが、何もわかってないんじゃないかって、\nそう思ってたんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 12
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0269>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 155, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0271>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 156, 1)  ; 「けど、そんな訳でもないんだって…\nあ、やっぱり俺だけ少し救われたみたいだ。\nよくないな、これって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 19
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0273>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 157, 1)  ; 「北原…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0275>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 158, 1)  ; 「さてと…\nＰＤＣＡのＣのフェーズはこのくらいかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0277>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 159, 1)  ; 「ＰＤＣＡって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0279>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 160, 1)  ; 「あとは自分の力でＡのフェーズに移行しろ。\n…北原なら、できるよな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 161, 1)  ; ＰＬＡＮ（計画）、ＤＯ（実行）、\nＣＨＥＣＫ（点検）、ＡＣＴ（改善）…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 162, 1)  ; 元々は製造業の管理サイクルだけど、\n今は一般的な仕事の進め方についても適用される手法。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 163, 1)  ; …バイトを始めて一週間で、\n徹底的に叩き込まれたっけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0284>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 164, 1)  ; 「それじゃ、そろそろ行く。\n…私が日本に戻ったら、\nまた大量の仕事を回してやるからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 165, 1)  ; 半分くらいは照れ隠しだと思うけど、\nそれでも残り半分には、真理が含まれてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0287>, 166, 1)  ; 改善、しろって。\n頑張れって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0288>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 167, 1)  ; 「じゃあ…行ってきます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0290>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 168, 1)  ; 「ありがとう…麻理さん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0292>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0293>, 169, 1)  ; 「ありがとうございます…だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 90
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 2205
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 170, 1)  ; そして、多分これはほとんどが照れ隠し。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0295>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 171, 1)  ; 「ありがとう…ございます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0297>, 172, 1)  ; それでも俺にとって、\nそのことを看破したからと言って、\n彼女の指示に従わない選択肢はなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 173, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8159
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 5
PUSH INT 4
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1023
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0299>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0300>, 174, 1)  ; 「さてと…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 10
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0301>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 175, 1)  ; 「あ～あ、置いてかれちゃった…\nニューヨーク行きってまだあるのかな？　今日」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0303>  ; CATCH2
PUSH INT 100
CALL SCall
OPERATOR POP

STATEMENT IF _ #LABEL_14
ARRAY_G 9
PUSH INT 1
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
STATEMENT IF _ #LABEL_14
ARRAY_G 12
PUSH INT 1
OPERATOR EQ
STATEMENT JMP_IF
OPERATOR POP
ARRAY_S RES<0304>  ; 2022
PUSH INT 0
CALL SLoad
OPERATOR POP

#LABEL_14
ARRAY_S RES<0305>  ; 2025
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
