!RESOURCE "2032.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 2032
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2011
PUSH INT 2
PUSH INT 28
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2501
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1042
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 2205
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 20
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SES
OPERATOR POP

PUSH INT 7
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0004>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「春希くん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「遅くなってごめん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 2, 1)  ; ２月２８日。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 3, 1)  ; 日中から夜にかけて、寒気が太平洋側までせり出し、\n関東地方は厳しい寒さが予想される夜。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0010>, 4, 1)  ; というか、今にも雪が降りそうなくらい、\n厚い雲に覆われた、既にかなり寒い夜。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0011>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 5, 1)  ; 「ううん、開始３０分前。\n余裕でセーフだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0013>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 6, 1)  ; 「…うん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 7, 1)  ; そんな寒空の中、\n小木曽家のインターフォンから聞こえてきた声は、\n俺の全身をじわりと温めてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 8, 1)  ; …まぁ、最近は毎日電話で温めてもらってるけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0017>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0018>, 9, 1)  ; 「ちょっと待っててね。\n今すぐに…あ、ちょっと！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 19
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0019>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0020>, 10, 1)  ; 「いらっしゃいませ～。\nご新規様一名ご案内いたします～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0021>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0022>, 11, 1)  ; 「………は？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 12, 1)  ; ええと、改めて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0024>, 13, 1)  ; ２月２８日。\n２月最後の、寒い夜。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 14, 1)  ; 今日は、二週間遅れの…\n雪菜の、誕生パーティ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0026>, 15, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1043
PUSH INT 1
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0027>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0028>, 16, 1)  ; 「お、やっと全員揃った～。\n遅いよ北原さん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0029>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0030>, 17, 1)  ; 「あ、いや、ごめん…でも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 18, 1)  ; ほぼ二週間ぶりに上がらせてもらった\n小木曽家のリビングは、\n予想以上の人で溢れかえっていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 19, 1)  ; おかげで外との気温差が違いすぎて、\nとてもコートなんか着てられる状態では…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 216
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0033>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 20, 1)  ; 「ごめんね春希くん。\nびっくりしたでしょ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 21, 1)  ; と、キッチンに立っていた雪菜が、\nすぐに俺に寄り添いコートを取ってくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0036>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 22, 1)  ; 「…仲直りしたんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0038>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 23, 1)  ; 「してないよぅ！\nなんでかわからないけど、\n来ちゃってたんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 24, 1)  ; けれど今は二人とも、\nお互いの顔を見つめ合ってたりはしない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 25, 1)  ; 何しろ、そんなことより…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 19
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 14
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0042>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 26, 1)  ; 「あ～、なるほどぉ。\n蒸して脂を落としちゃう訳だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 14
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0044>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 27, 1)  ; 「こうして下ごしらえしてからの方が美味しくなるし、\nカロリーを気にしてるならこれで一石二鳥」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0046>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 28, 1)  ; 「や～、すっごいおばさん！\nホントありがと。今度やってみるね！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0048>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 29, 1)  ; 「あ～、もう、朋ちゃんって素直でいいコねぇ…\n雪菜なんかわたしがいくら言っても、\n『そんなのわかってるよ、うるさいなぁ！』なんて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0050>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 30, 1)  ; 「また教えてもらいに来ちゃおっかな～。\nあ、もちろん迷惑じゃなければ、だけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0052>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 31, 1)  ; 「迷惑だなんてとんでもない！　いつでもいらっしゃい。\n素直だし、家庭的だし、何より雪菜よりよっぽど可愛いし。\nあ～あ、わたしは産む子を間違えたわねぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0054>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 32, 1)  ; 「やだも～。\nわたしなんかせっちゃんに叶う訳ないじゃないですか～。\nいちお～去年のミス峰城ではありますけど～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0056>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 33, 1)  ; 「これからも雪菜と仲良くしてあげてね？\nあの子、ああ見えて友達少なくて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0058>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 34, 1)  ; 「まっかせといてくださいって！\nあ、それでこれの味付けなんですけど～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0060>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 35, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0062>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 36, 1)  ; 「…コート、置いてくるね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 37, 1)  ; あまりの展開に胸焼けしまくってそうな雪菜が、\nもはや呆れも通り越しつつ、奥の部屋へと消えていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0065>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 38, 1)  ; 「それにしても、誰が…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 107
PUSH INT 13000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 10
PUSH INT 103
PUSH INT 13000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0067>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 39, 1)  ; 「いや、ま～。\n今日のことをリークしたのはあたしらだけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0069>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 40, 1)  ; 「…何のつもりだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 103
PUSH INT 13000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0071>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 41, 1)  ; 「…色々あったんだよ。\nそりゃもう、逆の意味で誰も信じられなくなるような、\n衝撃的な出来事とかな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 108
PUSH INT 13000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0073>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 42, 1)  ; 「やめときな武也…\nあの現場を見てなくて、\n真実にたどり着ける奴なんかいないよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0075>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 43, 1)  ; 「む、むぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 44, 1)  ; 本当に何があったんだこいつら…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 45, 1)  ; 依緒なんて、前に彼女と話したときは、\n掴みかからんばかりの勢いだったってのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 104
PUSH INT 13000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0079>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 46, 1)  ; 「ま、それよりもさ、\n春希、満喫してるか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0081>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0082>, 47, 1)  ; 「来たばっかだし始まってもいないだろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 104
PUSH INT 13000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0083>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0084>, 48, 1)  ; 「今日のことなんか誰も話してないって、\n勘のいいあんたなら気づいてるよねぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0085>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 49, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0087>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 50, 1)  ; 「コンサート終わっても二日間手放さなかったんだって？\nや～もう、俺ですら恥ずかしくなるくらい\nらぶらぶだねぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0089>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 51, 1)  ; 「聞かせてよ聞かせてよ！\nあんたたちの４８時間。\n別に４８時間かけてもいいからさぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0091>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0092>, 52, 1)  ; 「黙れ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 53, 1)  ; 『色々世話になった。もう心配ない。ありがとう』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 54, 1)  ; …と、本来なら、\n照れつつも真摯に感謝の意を表すところなんだろうけど、\nこいつらはそういう素直な気持ちにさせない天才だな。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 106
PUSH INT 13000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0095>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 55, 1)  ; 「どうだろうねぇこの態度？\nもし俺たちがいなかったらお前らどうなってたか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 107
PUSH INT 13000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0097>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 56, 1)  ; 「ま、あたしたちは\n春希の恩知らずっぷりをよく知ってるからいいけどさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0099>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 57, 1)  ; 「俺もう今日は二度とお前らと話さん。\nついでに雪菜にも口止めしとくからな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 109
PUSH INT 13000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0101>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 58, 1)  ; 「俺たちはそれでいいけどさ、\n一応、関係各所にはそれなりに挨拶しといた方が\nいいんじゃないのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0103>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0104>, 59, 1)  ; 「関係各所って、他に誰が…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 3
PUSH INT 1
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0105>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0106>, 60, 1)  ; 「色々とおめでとうございます。\n…ここに来てるってことは、そういうことですよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0107>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 61, 1)  ; 「………で、なんで君らまでいるんだ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 62, 1)  ; 最初にリビングに来たときから、\n身長的な関係で他の出席者に隠れてしまいつつも、\nぴょこぴょこ跳ねてるポニーテールだけは目に入ってた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0110>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 63, 1)  ; 「安心してください。美穂子は来てません。\n…さすがにまだ気持ちの整理がついてないみたいで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0112>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 64, 1)  ; 「い、いや、別に俺はそんなこと気にしてないぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 65, 1)  ; 雪菜とは接点のないはずの、\n俺のバイト先の後輩にして、\nほんのちょっとだけ、関係各所のうちの一つ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0115>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 66, 1)  ; 「一応、わたしたちの卒業祝いと進学祝いも\n同時開催ってことになってるんですよ。\n明日だと湿っぽくなるから前日にやっちゃおうって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 67, 1)  ; ついでに、孝宏君の<R関係各所|クラスメイト>…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0118>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 68, 1)  ; 「そっか…卒業式、明日だったっけ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 8
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0120>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 69, 1)  ; 「小木曽の合格発表は来週ですけどね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0122>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 70, 1)  ; 「…相変わらず楽天家だなぁ、孝宏君」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 12
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0124>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 71, 1)  ; 「わたしもそう思うんですよねぇ…\n予備校探すとか二次募集探すとか\nいろいろ考えることもあると思うんですけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0126>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 72, 1)  ; 「そして杉浦は相変わらず悲観的なお節介だな。\n合格するって可能性を少しは考えてあげても…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 24
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0128>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 73, 1)  ; 「わたし、勉強でもスポーツでもその他でも、\n頑張った人が報われるって信じたいんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0130>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 74, 1)  ; 「…少しは頑張ってただろ、彼も」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 2
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0132>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 75, 1)  ; 「先輩も頑張ってましたよね。\nコンサート、行きました。\n…素敵でした」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 76, 1)  ; 「っ…あ………りがと。\nその…色々世話になった。もう心配ない。ありがとう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 77, 1)  ; その、突然俺に向けて放たれた真っ直ぐな牽制球に、\n俺は照れつつも真摯に感謝の意を表してしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 6
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0137>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 78, 1)  ; 「みんな、小木曽先輩ばかり注目してて、\nずっと先輩ばかり見てたのは、\n多分、美穂子とわたしくらいだけど………あ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0139>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 79, 1)  ; 「そ、そういえば杉浦、\n君ら、卒業旅行が…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 80, 1)  ; とはいえ、その話題で引き続き勝負するには\n分が悪すぎるので、俺は必死に話題を転換しようと…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 12
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0142>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 81, 1)  ; 「先輩…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0144>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 82, 1)  ; 「な、なに？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0146>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 83, 1)  ; 「…なんか雲行きが怪しいです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0148>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 84, 1)  ; 「だって、今日はこれから雪だろ。\n天気予報でも…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0150>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 85, 1)  ; 「わたし、さっきから小木曽先輩に\nものすごい勢いで睨まれてるんですけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0152>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 86, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 87, 1)  ; ちょっと、忘れてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0155>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 88, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 89, 1)  ; 小春の視線の方に振り返ると、\nそこにはあまりにも大人げない視線を突き刺しつつ、\n頬を思いっきり膨らませた、不謹慎ながら随分と可愛い…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0158>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 90, 1)  ; 「っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0160>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 91, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 2
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 0
PUSH INT 615
PUSH INT 0
PUSH INT 0
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 10
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 1000
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 92, 1)  ; なんて、やっぱりその不謹慎に勘付かれたか、\n大きな足音を立てて二階へ上がってしまった\n雪菜が…つまりさっきまでそこにいた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 12
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0163>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 93, 1)  ; 「追いかけた方がいいんじゃ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0165>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 94, 1)  ; 「いや、あれは別にそう言うことじゃなくて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 16
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0167>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 95, 1)  ; 「今さら照れることでも\n隠すことでもないと思うんですけど？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0169>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0170>, 96, 1)  ; 「………皆に余計なこと言うんじゃないぞ。\nじゃ、ちょっと俺…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 8
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0171>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 97, 1)  ; 「ごゆっくり…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 617
PUSH INT 0
PUSH INT 0
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 30
CALL SES
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 98, 1)  ; まったく雪菜は…\nこんなとこで見境なくしてどうすんだ。\n三つも下の杉浦の方がよっぽど大人の対応じゃないか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0174>, 99, 1)  ; …ま、その分可愛げに満ち溢れてきたけれど。\n最近の雪菜は。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 3
PUSH INT 8
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 23
PUSH INT 7
PUSH INT 1000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 24
PUSH INT 4
PUSH INT 1000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1043
PUSH INT 1
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0175>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 100, 1)  ; 「ふぅ………あ～、もう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 23
PUSH INT 9
PUSH INT 1000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0177>)  ; 早百合
PUSH INT 23
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 101, 1)  ; 「ね、ねぇねぇ小春！\nあれってギターの人だよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 16
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0179>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 102, 1)  ; 「…それが？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 24
PUSH INT 3
PUSH INT 1000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0181>)  ; 亜子
PUSH INT 24
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 103, 1)  ; 「に、二階に上がってったよね？\nしかも小木曽先輩と一緒に！\nあ、あの二人ってもしかして、もしかしてっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 21
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0183>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 104, 1)  ; 「………わたしにそれを聞かないで。\n知るわけないでしょそんなことっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 24
PUSH INT 2
PUSH INT 1000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0185>)  ; 亜子
PUSH INT 24
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 105, 1)  ; 「そんな大人げない目で睨まなくても…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 106, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2139
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 41
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0188>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 107, 1)  ; 「ん、んむ…ちゅ、んく、は、あ、あむ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0190>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 108, 1)  ; 「ん、んぅ…あ、はぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0192>, 109, 1)  ; 結局、雪菜がむくれていたのは\n最初の三秒だけだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0193>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0194>, 110, 1)  ; 「は、あ、ぁ…ん、ちゅぷ…んぷぁ…ぁ…\nは、春希…く…んぅっ、ん、ん…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 111, 1)  ; ドアを閉めた途端、強引に抱きしめ唇を重ねると、\nあっという間に甘い吐息とともに目を閉じて、\nゆっくりと俺に身を委ねてきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 112, 1)  ; 「ん、は、はぁ…あ、ああ…ん…ちゅ…ぅぅ…\nは、はぁ、はぁぁ…ふぅ、ん…\nあ～、一週間ぶり…ほんと、待ち遠しかったよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0198>, 113, 1)  ; 先週一週間、雪菜は外出禁止令を食らってた…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0199>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0200>, 114, 1)  ; 「けど…\nこの中座の仕方はあからさますぎないか？\n俺たち、絶対なんか勘繰られてるぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0201>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0202>, 115, 1)  ; 「勘繰られてても別にいいじゃない。\nどうせ想像通りのことしてるんだから、\n誤解、されてないでしょ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0203>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0204>, 116, 1)  ; 「…お父さんはいい気しないと思うけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 210
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1044
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0205>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0206>, 117, 1)  ; 「今日は出ないよ。書斎に引きこもってる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0207>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0208>, 118, 1)  ; 「それはつまり…俺に会いたくないと…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 119, 1)  ; 雪菜が最初に与えられたペナルティは、\n５日間の外泊と、無断でのコンサート出場に対しての、\n春休み中の外泊禁止令だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0210>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 120, 1)  ; 「いいんだよ春希くんが気を使わなくたって！\nあんな酷いお父さんなんか！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0212>, 121, 1)  ; お父さんとしては、『もう大学生にもなった娘』に対して、\n苦悩の末、十分過ぎるほど譲歩した上での\n処分だったと思う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0213>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0214>, 122, 1)  ; 「いや…俺の目から見ても、\n随分と遠慮してたように思ったけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0215>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0216>, 123, 1)  ; 「どうして？\n外出禁止なんて酷いよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0217>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0218>, 124, 1)  ; 「それは雪菜が言いつけを破るから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0219>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0220>, 125, 1)  ; 「わたしだけが悪いって言うの？\n春希くんだって…ちゃんと、したくせに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 126, 1)  ; ところが先週末、\n雪菜は朝から俺の部屋に来て三食振舞ってくれた挙げ句、\n帰るよう諭す俺の前で『夜モード』になってしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 127, 1)  ; 「するに決まってるだろ。\n俺にそこまで高潔な自制心はない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 128, 1)  ; その結果、とうとう堪忍袋の緒が切れたお父さんは、\n雪菜が反省するまでという条件で、\n外出禁止令を発令してしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0225>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 129, 1)  ; 「…というわけで、\n今夜、春希くんの部屋に行くね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0227>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 130, 1)  ; 「いや、けどパーティ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0229>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 131, 1)  ; 「そこが狙い目なんだよ。\n解散したときに、みんなを送るからって外に出て、\nそのまま抜け出しちゃうの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0231>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 132, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0233>, 133, 1)  ; 雪菜は…別の意味でも強くなってしまったかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 134, 1)  ; とにかく一度お父さんと直接ゆっくり話さないと。\n誤解…はないけど理解だけはしてもらわないと…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 115
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0235>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 135, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0237>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 136, 1)  ; 「なに？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0239>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 137, 1)  ; 「口の端っこ、濡れてる…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0241>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0242>, 138, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 139, 1)  ; それはもちろん、さっきまで唇を重ねていた痕跡で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 204
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0244>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 140, 1)  ; 「わたし、ぬぐってあげる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0246>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 141, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0248>, 142, 1)  ; そんなものは、ハンカチか指先でちょっと拭けば、\nすぐに元通りになる類のものなのに…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 124
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0249>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 143, 1)  ; 「れろ…ん、ちゅ…ちゅぷ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0251>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0252>, 144, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 145, 1)  ; 雪菜が取り出したのは、\nハンカチでもティッシュでもなく…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 125
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0254>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 146, 1)  ; 「あれ…また濡れちゃった。\nおっかしいなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0256>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 147, 1)  ; 「あ、あのな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 2139
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0258>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 148, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0260>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 149, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0262>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 150, 1)  ; 「んんんんっ、ん、ん～っ！\nん、んぷ…は、はぁ、はぁぁ…あむっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0264>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 151, 1)  ; 「ん…ん、んぅ…ちゅ…は、あむ…れろ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0266>, 152, 1)  ; 悪戯っぽくぺろりと出した舌がたまらなく、\nついついもう一度、それを求めて唇を重ねてしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0267>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0268>, 153, 1)  ; 「ん…んぷ…ちゅぷ、あ、あ…はぁぁんっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 154, 1)  ; やっぱり、雪菜は変わった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 155, 1)  ; 弱いようで強く、\n優しいようで意地悪で、\n控えめなようでワガママになった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0271>, 156, 1)  ; ただ、その変わった姿がすごく付属時代っぽいのが、\n俺には、とてもとてもとても、嬉しい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0272>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0273>, 157, 1)  ; 「ん、んぅ、雪菜…ぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0274>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 158, 1)  ; 「はるき…くぅんっ…ん、んむ…ん～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 159, 1)  ; ………そういうの、お父さんは理解してくれるだろうか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 160, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 161, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2139
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 42
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0279>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 162, 1)  ; 「さてと、それじゃ打ち合わせも済んだし、\nいい加減、下に戻らないとね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 163, 1)  ; 脱走計画の打ち合わせが１０秒で、\nそれ以外の『突き合わせ』が１０分以上だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 164, 1)  ; いくらなんでも、そろそろ下の連中も、\n俺たちの目的を間違える方が難しくなってる頃だろう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1044
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0283>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 165, 1)  ; 「じゃ、行こうか春希くん。\n今日のローストビーフはね、結構自信作…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0285>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 166, 1)  ; 「あ、その前に…プレゼント」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0287>, 167, 1)  ; それでもあと１分だけは…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0288>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 168, 1)  ; 「あ、ありがと…\nでもプレゼントはみんなの前で渡すことになってて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0290>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 169, 1)  ; 「駄目なんだ、これ…\n色んな意味で他人には見せられないって言うか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0292>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0293>, 170, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 171, 1)  ; 俺の差し出した小箱を前に、雪菜が固まる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0295>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 172, 1)  ; 「結構、やっちゃった感があると言うか、\nちょっとでも退かれたらおしまいと言うか、\nかなり痛いって言うか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0297>, 173, 1)  ; いや、たぶん正確には、\n俺の言葉と、急に吹き出してきた額の汗に。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0298>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0299>, 174, 1)  ; 「………開けてもいい？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0300>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0301>, 175, 1)  ; 「…うん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 176, 1)  ; 雪菜がその包みを開いた瞬間…\n買ったときの、あの緊張が蘇ってくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8196
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL SetMessageE(RES<0303>, 177, 1)  ; もう、三年も前になる、あの時の…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 15
CALL SES
OPERATOR POP

PUSH INT 2
PUSH INT 115
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0304>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0305>, 178, 1)  ; 「あ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0306>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0307>, 179, 1)  ; 「その…実は結構古くて、しかも安物だけど、\n一応綺麗にしたから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0308>, 180, 1)  ; 買ったときの値段とクリーニング代が、\n実はほとんど変わらなかった…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0309>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 181, 1)  ; 「人には、見せられないんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0311>, 182, 1)  ; 安いものだから。\n古いものだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 183, 1)  ; そして………深い意味のある、ものだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0313>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0314>, 184, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0315>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0316>, 185, 1)  ; 「その…\n一応、それが気に入らなかったときのために、\nちゃんと抑えも用意してる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0317>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0318>, 186, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0319>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0320>, 187, 1)  ; 「や、やっぱこっちの方がいいかな？\n同じ店でさっき買ったんだけど、\nそれよりも高いし、何より…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0321>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0322>, 188, 1)  ; 「………嬉しい、よ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0323>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0324>, 189, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0325>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0326>, 190, 1)  ; 「わたし、これがいい。\nこれでなくちゃ、駄目」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0327>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0328>, 191, 1)  ; 「………ありがとう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0329>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0330>, 192, 1)  ; 「プレゼントした方がありがとうって…\n日本語の使い方、おかしいよ。\nおかしいよ、春希くん………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0331>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0332>, 193, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0333>, 194, 1)  ; それは、満面の笑顔、だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0334>, 195, 1)  ; この際、目の色とか、そこに溜まってるものとか、\nそんなことはどうでもいいんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 196, 1)  ; だって、戻ってきたんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0336>, 197, 1)  ; 三年前の、あの誕生日に戻ってきたんだから…俺たち。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0337>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0338>, 198, 1)  ; 「それじゃあ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0339>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0340>, 199, 1)  ; 「ん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0341>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0342>, 200, 1)  ; 「春希くんが…つけてくれる？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0343>, 201, 1)  ; そう言って、雪菜が…\n『片方の手』を差し出した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 43
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL SetMessageE(RES<0344>, 202, 1)  ; これが、俺たちの終章。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0345>, 203, 1)  ; 激しかった三年間を締めくくるには、\nあまりにも穏やかで、尻すぼみの物語。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0346>, 204, 1)  ; だけどこれが、\nこれこそが…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0347>, 205, 1)  ; 俺たちの、最高のエンディングなんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0348>, 206, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 13000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 15
PUSH INT 101
PUSH INT 13000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1043
PUSH INT 1
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0349>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0350>, 207, 1)  ; 「あ、姉ちゃんどこ行ってたんだよ？\nもうとっくに準備できてるんだぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0351>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0352>, 208, 1)  ; 「ごめんごめん。\nちょっと目にゴミが入っちゃって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0353>, 209, 1)  ; それは、目が赤いことに対しての、\n上手くて、けれどバレバレな言い訳だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0354>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 140
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0355>, 210, 1)  ; 「それじゃ始めよっか。\nみんな～、飲み物注いで～。\n…ねぇ母さん、今日は俺ワインいいよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 19
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0356>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 141
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0357>, 211, 1)  ; 「ほらせっちゃん。\nグラスグラス」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 13000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0358>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 142
CALL VV
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessage(RES<0359>, 212, 1)  ; 「だからせっちゃんは
ARRAY_G 1
PUSH INT 2100
OPERATOR MOV
OPERATOR POP
PUSH INT 9999
CALL call
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 13000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL SetMessageE(RES<0360>, 213, 0)  ; ………もう、なんだかなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 24
PUSH INT 3
PUSH INT 1000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0361>)  ; 亜子
PUSH INT 24
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 143
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0362>, 214, 1)  ; 「あ、あの、お姉さん、初めまして！\nわたし、小木曽君のクラスメイトで…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 24
PUSH INT 4
PUSH INT 1000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 23
PUSH INT 6
PUSH INT 1000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0363>)  ; 早百合
PUSH INT 23
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 144
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0364>, 215, 1)  ; 「清水早百合です！\nあ、あの、コンサート見ましたっ。\nあたし、すっごい感動しちゃって！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0365>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 145
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0366>, 216, 1)  ; 「ありがとう。\nね、二人とも来年は<R峰城大|うち>に来るのかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 23
PUSH INT 1
PUSH INT 1000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0367>)  ; 早百合
PUSH INT 23
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 146
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0368>, 217, 1)  ; 「は、はいっ、\nあたし外語で、このコが教育…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0369>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 147
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0370>, 218, 1)  ; 「そっかぁ…学部違うんだ、残念。\nでも、大学で見かけたら声かけてね？\nあ、そうだ、今度キャンパス案内しようか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 23
PUSH INT 9
PUSH INT 1000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0371>)  ; 早百合
PUSH INT 23
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 148
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0372>, 219, 1)  ; 「えええっ、マジですか！？\n本気にしちゃいますよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 24
PUSH INT 4
PUSH INT 1000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0373>)  ; 亜子
PUSH INT 24
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 149
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0374>, 220, 1)  ; 「も、もう早百合…\nわたしにも挨拶させてよっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0375>, 221, 1)  ; 雪菜が、輪の中心へと戻っていくと、\n途端に場がぱっと華やぐ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0376>, 222, 1)  ; 見た目的にはあんなに派手で、\nいつも皆の注目を集めてる…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0377>, 223, 1)  ; なのに性格的にも男の趣味的にもあんなに地味な、\nこれほどまでにアンバランスな女の子なんて、\n他のどこにもいやしない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0378>, 224, 1)  ; 他の誰でもない、\n俺の、俺だけの…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 11
PUSH INT 102
PUSH INT 13000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 10
PUSH INT 101
PUSH INT 13000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0379>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 150
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0380>, 225, 1)  ; 「このこの～。\nなんだよあの薬指は～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 101
PUSH INT 13000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0381>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 151
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0382>, 226, 1)  ; 「三年待たせた分、飛ばしすぎてんな。\n今のお前、かなり恥ずかしいぜ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0383>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 152
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0384>, 227, 1)  ; 「………今日はお前らとは話さんって言っただろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0385>, 228, 1)  ; 目ざとく雪菜の『左手』に気づいた奴らが、\n俺の脇腹を肘で………かなり手加減無しでこづく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 1043
PUSH INT 1
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 15
PUSH INT 101
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0386>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 153
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0387>, 229, 1)  ; 「さてと、それじゃ乾杯の…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 19
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0388>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 154
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0389>, 230, 1)  ; 「わ、雪！　雪降ってきたよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1042
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 3
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 5
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 90
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0390>)  ; 早百合
PUSH INT 23
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 155
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0391>, 231, 1)  ; 「え、どれどれ？　本当だ～！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0392>, 232, 1)  ; ようやく始まるかと思われた誕生パーティは、\n予想された突然の乱入者に中断を余儀なくされる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0393>)  ; 亜子
PUSH INT 24
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 156
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0394>, 233, 1)  ; 「うわぁ…すごい勢い…真っ白」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0395>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 157
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0396>, 234, 1)  ; 「積もるね、これは絶対」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0397>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 158
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0398>, 235, 1)  ; 「乾杯の…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 236, 1)  ; 皆の歓声に応えるように、\n窓の外の白い粒は、\n自らの存在を誇示するように、強く、激しく舞う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 13000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1043
PUSH INT 1
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0400>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 159
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 237, 1)  ; 「ね、春希くんも…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0402>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 160
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0403>, 238, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0404>, 239, 1)  ; 窓の外を見上げてた雪菜が、\n少しだけ銀色に光る左手を、俺に差し出す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0405>, 240, 1)  ; だから俺は…\n当然のように空いていた雪菜の隣に、\nぴったりと寄り添うように立つ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 6
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 3
PUSH INT 7
PUSH INT 90
PUSH INT 2
PUSH INT 1
PUSH INT 5
CALL SetWeather2
OPERATOR POP

PUSH INT 90
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0406>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 161
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0407>, 241, 1)  ; 「綺麗、だね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0408>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 162
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0409>, 242, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0410>, 243, 1)  ; 明日から三月。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0411>, 244, 1)  ; 三月の月間予報によれば、今回の低気圧が過ぎた後は\n急激に気温も高く、春めいた陽気になっていくらしい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0412>, 245, 1)  ; だとしたらこれは、\n多分、今シーズン最後の雪。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 20180
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1.03
PUSH FLOAT 1.03
PUSH INT 0
PUSH INT 0
CALL V2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 210
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 270
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0413>, 246, 1)  ; 冬が、終わる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0414>, 247, 1)  ; 三人の季節が、終わる。\n『ＷＨＩＴＥ　ＡＬＢＵＭ』の季節が、終わる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0415>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 1
PUSH INT 20180
PUSH INT 1
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0416>, 248, 1)  ; そして、俺たちの…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0417>, 249, 1)  ; 二人だけの季節が、始まるんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 360
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 360
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 100
PUSH INT 62
OPERATOR ADD
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

CALL run
OPERATOR POP

ARRAY_S RES<0418>  ; mv11
PUSH INT 212
CALL SetMovie
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0419>  ; 2033
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
