!RESOURCE "2311.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 2311
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2011
PUSH INT 1
PUSH INT 31
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2900
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1013
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 150
OPERATOR NEGATE
PUSH INT 50
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 50
PUSH INT 50
PUSH INT 2000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 13
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0004>)  ; テニス部員１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「ね～ね～聞いた聞いた？\n副キャプテンの噂！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; テニス部員２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「元副キャプテンね。\n今の副はあたし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0008>)  ; テニス部員３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「あれでしょあれ？\n友達の男を…ってやつ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0010>)  ; テニス部員２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「あの杉浦さんがねぇ…\nなんか信じらんないけどな。\n超がつくくらい真面目な先輩だったのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0012>)  ; テニス部員１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「厳しかったもんね～。\nわたしなんて何度泣かされたことか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0014>)  ; テニス部員２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 5, 1)  ; 「それはあんたがサボってばっかりだったから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0016>)  ; テニス部員３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 6, 1)  ; 「噂が本当なら、人変わっちゃってるよね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; テニス部員１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 7, 1)  ; 「部活引退して、打ち込むものがなくなったから、\n男漁りにハマっちゃったとかそういう感じ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; テニス部員３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 8, 1)  ; 「今までが今までだったから、\n一度男知っちゃって歯止めが利かなくなったのかもね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0022>)  ; テニス部員２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 9, 1)  ; 「あんたたちねぇ…\n二年間世話になりっぱなしだった先輩に対して\nなんてこと言うのよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; テニス部員１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 10, 1)  ; 「ウチらなんかまだマシな方だよ～。\nほら、去年、急に規律が厳しくなったからって\n集団で辞めてった連中いたじゃん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0026>)  ; テニス部員３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 11, 1)  ; 「あ～、松井たち？\nそういえばあなた同じクラスだったっけ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0028>)  ; テニス部員１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 12, 1)  ; 「あいつらなんか大喜びでさ…\n交流試合やってた他校の連中にまでメール流してんの。\n副キャプテン、あっちの男子にも人気あったし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0030>)  ; テニス部員２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 13, 1)  ; 「そんな…\nただの噂なんでしょ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0032>)  ; テニス部員３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 14, 1)  ; 「にしては、メールの内容具体的すぎるのよねぇ。\nそっちにも届いたでしょ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0034>)  ; テニス部員１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 15, 1)  ; 「一年部員もみんな知ってるって言ってたよ？\n男子もだって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0036>)  ; テニス部員２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 16, 1)  ; 「ちょっと酷くない？　それ。\nなんでそんな身内の間のプライベートな話が\nそこまで広まっちゃうのよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0038>)  ; テニス部員３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 17, 1)  ; 「やっぱ、人に厳しいところあったし、\n先生の受けは抜群だったし、\nやっかみも混ざってんじゃない？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0040>)  ; テニス部員１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 18, 1)  ; 「いい人だとは思うんだけどねぇ…\nあ、でも今はアレなのかぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0042>)  ; テニス部員２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 19, 1)  ; 「…そろそろ練習始めるよ。\nそれと、その話はあまり他でしないように。\n噂だけで人を判断するの、よくないって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0044>)  ; テニス部員３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 20, 1)  ; 「今さら遅いと思う…\n多分、全校の半分以上に流れてるから、もう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 21, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1007
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 150
PUSH INT 50
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 0
PUSH INT 50
PUSH INT 2000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0047>)  ; 男子生徒２
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 22, 1)  ; 「あの杉浦がねぇ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0049>)  ; 男子生徒３
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0050>, 23, 1)  ; 「大学生とやりまくりとはね…あ～あ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0051>)  ; 男子生徒２
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0052>, 24, 1)  ; 「くっそ～、俺も大学生だったら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0053>)  ; 男子生徒３
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0054>, 25, 1)  ; 「いやお前それ前提おかしいから。\n大学生だったら誰でもいいって訳じゃ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0055>)  ; 男子生徒２
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 26, 1)  ; 「杉浦の友達とつきあってないと駄目ってこと？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0057>)  ; 男子生徒３
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 27, 1)  ; 「その辺はどうなのかわかんないけどさ…\nでもお前、狙ってたの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0059>)  ; 男子生徒２
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 28, 1)  ; 「そういうコだって最初からわかってりゃなぁ…\n駄目元で一度お願いしてみたかった…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0061>)  ; 男子生徒３
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 29, 1)  ; 「確かに顔抜群だけど、\n色々とサイズが小さくないか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0063>)  ; 男子生徒２
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 30, 1)  ; 「でもあの身体で大学生と毎日…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0065>)  ; 男子生徒３
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 31, 1)  ; 「相手の男、そういう趣味なんかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0067>)  ; 男子生徒２
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 32, 1)  ; 「あ～、ますますヤバい！\nお前それ駄目だって言っちゃ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 1011
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 1007
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0069>)  ; 男子生徒３
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 33, 1)  ; 「やべ俺今想像したらすっげ～興奮してきた！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8250
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0071>)  ; 男子生徒２
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 34, 1)  ; 「聞こえるって！\n聞こえるっつ～の！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 99
PUSH INT 9000
PUSH INT -1
PUSH INT 128
PUSH INT 0
PUSH INT 1
CALL VX
OPERATOR POP

PUSH INT 3
PUSH INT 21
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0073>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 35, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 60
PUSH INT 1
CALL VS
OPERATOR POP

PUSH INT 0
PUSH INT 624
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 36, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 30
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 30
CALL SES
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 15
PUSH INT 104
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1008
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0076>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 37, 1)  ; 「あいつら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0078>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 38, 1)  ; 「人のこと気にしてる場合じゃないんだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0080>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 39, 1)  ; 「ああそうだよその通りだよ悪かったなぁ！\nだからこうして放課後まで頑張ってるじゃねえか！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0082>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 40, 1)  ; 「いよいよ再来週か…入試」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0084>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 41, 1)  ; 「だからこんな時期になってクラスでモメないでくれ…\n少しは委員長の受験を応援してくれよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0086>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 42, 1)  ; 「モメちゃいないけどな。\nただの一方的な袋叩きだし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0088>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 43, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0090>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 44, 1)  ; 「校内で結構有名なのが余計にマズかった。\n杉浦、今年の入学式で新入生歓迎挨拶とかやったじゃん。\n…噂じゃ、諏訪が無理やりねじ込んだって話だったけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0092>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 45, 1)  ; 「ほんと、ロクなことしねぇなウチの担任は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0094>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 46, 1)  ; 「にしても意外だよなぁ。\n今年のミス付属候補のうち、\n杉浦だけはそういう話と無縁だと思ってたのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0096>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 47, 1)  ; 「そもそもあいつはエントリー拒否してただろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0098>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 48, 1)  ; 「…そいやお前の姉ちゃんは\n三年連続優勝だったんだっけ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0100>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 49, 1)  ; 「そっちはどうでもいいから。\nそれより、お前は信じてんのか？\nあんなメチャクチャな噂」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0102>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 50, 1)  ; 「さあ？　でも本当の方が面白いと言えば面白い。\nあの杉浦が陰では性悪ヤリマン女だったなんて、\nある意味、すげぇ意外な展開だよな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0104>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 51, 1)  ; 「…お前なぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0106>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 52, 1)  ; 「いいじゃん、まだ幸運だったって杉浦は」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0108>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 53, 1)  ; 「どこがだよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0110>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 54, 1)  ; 「だってさ、あと一月もすれば卒業だぜ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0112>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 55, 1)  ; 「わかってんのかよお前…\nそれがどういうことなのか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0114>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 56, 1)  ; 「来月には人間関係リセットってことじゃん。\n改めて大学で新しい友達作りゃいいんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0116>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 57, 1)  ; 「それってなぁ…\n今まで積み上げてきた思い出が、たった一月で\n全部なかったことになっちまうってことだぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 58, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 59, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0120>, 60, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0121>  ; CATCH2
PUSH INT 100
CALL SCall
OPERATOR POP

PUSH INT 2011
PUSH INT 2
PUSH INT 1
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 42
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0122>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 61, 1)  ; 「で、どうですかテストの方は？\n進級できそうです？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0124>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 62, 1)  ; 「まだ二日目だぞ？\n三科目しか終わってない段階でそんなことわかるか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0126>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 63, 1)  ; 「二日で三科目しかないんですか？\n大学の試験って随分楽な日程なんですね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0128>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 64, 1)  ; 「…その分試験範囲が広かったり\nレベルが高かったりするの。\n付属の頃と違って科目ごとの参考書もないし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0130>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 65, 1)  ; 「あははっ、わかってますよ先輩。\nだからみんな、試験前は一生懸命走り回るんですよね。\n…コピー機の空いてるコンビニを探して」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0132>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 66, 1)  ; 「言っておくがな…\n俺はいつでもノートを提供する側だったぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 67, 1)  ; 「わたしもですよ。\n試験前になると急に友達が増えるんです。\n…わたしってこんなに人気者だったんだなぁって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 68, 1)  ; 午前０時１５分。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0137>, 69, 1)  ; 試験勉強の合間の小春からの電話は、\n先週からちらほら始まり、\nそろそろ定番の様相を呈してきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 70, 1)  ; さすがに試験本番になってからは\n長電話は控えるようになったけど、\nその分頻度が上がってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 71, 1)  ; 要するに、毎日３０分。\n必ず日付が変わる時間に掛かってくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 72, 1)  ; だから俺は、その時間の５分前に一度勉強をやめ、\nコーヒーを淹れてゆっくり味わいながら、\n携帯が鳴るのを待つようになった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0141>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 73, 1)  ; 「あ、そういえば言い忘れてたけど、\n日曜はごめんな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0143>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0144>, 74, 1)  ; 「謝られることなんて、何もされてませんよ？\n…嬉しいことならいっぱいしてもらったけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0145>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 75, 1)  ; 「違う違う違う！\nそういう話じゃなくて、武也と依緒のこと！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0147>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 76, 1)  ; 「あ…あ～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 77, 1)  ; 向こうの電話口では、\n真っ赤になって照れてるか、不満そうにぶーたれてるか、\nどっちの顔をしてるだろう…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0150>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 78, 1)  ; 「あいつら、なんかこの前は妙にぶしつけだったろ。\nそれで小春が気を悪くしてるんじゃないかって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0152>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 79, 1)  ; 「そんなこと…全然ありませんよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0154>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0155>, 80, 1)  ; 「普段はあんな奴らじゃ…なんだけど、\nでも悪い奴らじゃないんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0156>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 81, 1)  ; 「いい人たちですよね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0158>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 82, 1)  ; 「あいつらがいるから今の俺がいる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0160>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 83, 1)  ; 「…はい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 84, 1)  ; 小春は、俺がこうして太鼓判を押す前から、\n俺を救うためにあいつらを頼ってた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 85, 1)  ; 俺に対する甘すぎる評価はともかくとして、\n小春の人を見る目は確かなのかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0164>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 86, 1)  ; 「…今は『小春がいるから』も付け加えないとな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0166>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 87, 1)  ; 「っ………お互いさまです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0168>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 88, 1)  ; 「でも俺、今のところは頼るばっかりで…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0170>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 89, 1)  ; 「そういうこと、不意打ちで言ってくれるから…\nだから、お互いさまなんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0172>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 90, 1)  ; 「…ごめん、言ってる意味よくわからない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0174>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 91, 1)  ; 「とにかく…\n大切にしてくださいね、友達」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0176>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 92, 1)  ; 「ああ、わかってる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0178>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 93, 1)  ; 「わたしは…\nあの人たちとは、多分友達になれないけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0180>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 94, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 95, 1)  ; その一言に、どれだけの情報と暗喩と、\nそして想いが込められているのか…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0183>, 96, 1)  ; 想像はできるけど、多分、\n本当の正解は、きっとわかってない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0184>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0185>, 97, 1)  ; 「でも先輩は…友達続けてくださいね？\n無理してわたしを優先させることないですからね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0186>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 98, 1)  ; 「小春…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0188>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 99, 1)  ; 「わたしの…勝手なわがままですけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0190>, 100, 1)  ; 先週、あいつらを優先した後の、\n駅前でのあのむくれようは何だったんだよ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 101, 1)  ; でも、そのあからさまな強がりも、\n今はいとおしく感じてしまう俺は、\n小春以上に『何だったんだよ』なのかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0192>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 102, 1)  ; 「なら、小春も約束してくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0194>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 103, 1)  ; 「何をですか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 104, 1)  ; 「矢田さんと友達続けるって。\n無理して俺を優先させることないからな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0198>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 105, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0200>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 106, 1)  ; 「仲違いしたの、俺のせいだってわかってるけど。\nなのに俺、なにもできないけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0202>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 107, 1)  ; 「先輩…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0204>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 108, 1)  ; 「すぐにとは言わない。\nいつかでいいから、矢田さんに謝らせて欲しいな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0206>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 109, 1)  ; 「…心配しなくても大丈夫ですよ。\n美穂子、本当にいい子なんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0208>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 110, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0210>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 111, 1)  ; 「時間は掛かるかもしれないけど、\nいつか必ず三人みんな仲直りさせてみせます。\n大丈夫！　わたし、しつっこいんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0212>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 112, 1)  ; 「うん………信用してるよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0214>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 113, 1)  ; 「だから先輩は、それまではそうやって、\nわたしを元気づけていて下さいね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0216>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 114, 1)  ; 「約束する。\n今はそれしかできないから。\n…絶対に、それだけは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0218>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 115, 1)  ; 「信用、してます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0220>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 116, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 117, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 118, 1)  ; 試験勉強の合間の小春からの電話は…\n毎日、こんなふうに会話が途切れる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 119, 1)  ; <R昔の長電話|さんねんまえ>みたいに自然と言葉が湧いてくることのない、\n一字一句、互いに噛みしめながら紡いでいく不器用な会話。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 120, 1)  ; 立場から性格から…\nそして、自らが招いた立場すら似たもの同士の俺たちの、\n互いの傷をなめ合う、自分に厳しくも相手に優しい誓い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 121, 1)  ; そんなの、お互いに空手形だってわかってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 122, 1)  ; その誓いは、守ろうとすればするほど、\n周りの正常な組織をも巻き込んで壊死させてしまう、\nあまりにも副作用の強い劇薬だから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0229>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 123, 1)  ; 「それじゃ…おやすみなさい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0231>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 124, 1)  ; 「うん…また明日」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0233>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 125, 1)  ; 「………っ、はい！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 2205
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 126, 1)  ; それでも、使わずにはいられない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 127, 1)  ; ほんの一瞬だけでも、小春の元気な声が聞きたいから。\n…嬉しそうな吐息を、感じたいから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL SetMessageE(RES<0237>, 128, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8296
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0238>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0239>, 129, 1)  ; 「………っ、\nぅ、ぅぅ…ぅぃっ…く…ぅ、ぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0240>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 130, 1)  ; 「ぅ、ぅぅ…ぃ、ぅ…\nおやすみ…なさぁい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0242>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 131, 1)  ; 「先輩…わたし…わたし…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0244>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 132, 1)  ; 「全然、平気だよぉ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0246>, 133, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 134, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 210
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0248>  ; CATCH2
PUSH INT 100
CALL SCall
OPERATOR POP

PUSH INT 2011
PUSH INT 2
PUSH INT 3
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 0
PUSH INT 2900
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1007
PUSH INT 2
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 90
CALL SES
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 40
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 3019
PUSH INT 60
PUSH INT 1
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 3
PUSH INT 15
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1008
PUSH INT 2
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0249>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 135, 1)  ; 「………ぇ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 18
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0251>)  ; 諏訪先生
PUSH INT 18
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0252>, 136, 1)  ; 「…というわけだ。\nついては段取りについて来週打ち合わせがあるから、\n追って連絡を待つように」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 150
PUSH INT 120
CALL SEV
OPERATOR POP

PUSH INT 18
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 3
PUSH INT 15
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0253>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0254>, 137, 1)  ; 「ちょ、ちょっと待って…\n待ってください」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 18
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0255>)  ; 諏訪先生
PUSH INT 18
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0256>, 138, 1)  ; 「滅多にないことなんだぞ？\n生徒会経験者でもない人間が選ばれるというのは。\n名誉なことじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 18
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 3
PUSH INT 15
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0257>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0258>, 139, 1)  ; 「そ、そんな、わたし、そんなこと…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 200
PUSH INT 120
CALL SEV
OPERATOR POP

PUSH INT 3
PUSH INT 14
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0259>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0260>, 140, 1)  ; 「答辞、なんて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0261>)  ; 女子生徒１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 141, 1)  ; 「うわ何それ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0263>)  ; 女子生徒２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0264>, 142, 1)  ; 「さすが諏訪。\n最高のネタ師…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0265>)  ; 女子生徒３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0266>, 143, 1)  ; 「ぷ、くく…あはははは…っ、\n駄目、もう駄目…お腹痛い」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 25
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0267>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0268>, 144, 1)  ; 「できません！\nそんな、わたしなんか…無理です」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 18
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0269>)  ; 諏訪先生
PUSH INT 18
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 145, 1)  ; 「…どういう意味だ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 18
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 3
PUSH INT 14
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0271>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 146, 1)  ; 「それは…\n前期生徒会長の堀田さんが適任だと思うから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 18
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0273>)  ; 諏訪先生
PUSH INT 18
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 147, 1)  ; 「職員会議でもう決まったことだ。\nそれを断るというのはどういう意味だと聞いている！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 18
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 15
PUSH INT 104
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0275>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 148, 1)  ; 「どういう意味だって…\nお前の方が意味不明じゃねえか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0277>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 149, 1)  ; 「やっぱあれだろ…\nまた諏訪が無理やりねじ込んできたとしか。\n堀田のクラスの担任、二年目の友松だし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0279>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 150, 1)  ; 「空気読め諏訪…アホかあいつはっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0281>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 151, 1)  ; 「マズい時にえこひいきされたよなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 18
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0283>)  ; 諏訪先生
PUSH INT 18
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 152, 1)  ; 「とにかく、ちゃんとした理由がないと認められない。\n一体どういうことだ？　言ってみろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 18
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 3
PUSH INT 12
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0285>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 153, 1)  ; 「そ、それ、は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 18
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0287>)  ; 諏訪先生
PUSH INT 18
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 154, 1)  ; 「…大した理由がないのなら却下だ。\n何しろ全会一致で決まったんだぞ。\n今さら覆せるか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 18
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 3
PUSH INT 32
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0289>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 155, 1)  ; 「諏訪先生…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 18
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0291>)  ; 諏訪先生
PUSH INT 18
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0292>, 156, 1)  ; 「なぁに、そんなに遠慮することはない。\nもっと堂々と構えてればいいんだ。\n何しろクラスの、いや卒業生全員の代表なんだからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 18
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

@VCALL WN(RES<0293>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 157, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0295>)  ; 女子生徒１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 158, 1)  ; 「凄ぇ…あれが代表だってさぁ。\n一体何のよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0297>)  ; 女子生徒２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 159, 1)  ; 「そこまでして目立ちたいかねぇ…\nあのコのやることマジ訳わかんない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0299>)  ; 女子生徒３
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0300>, 160, 1)  ; 「優等生演じるってのも大変だよねぇ。\n…全っ然同情しないけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0301>)  ; 女子生徒１
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 161, 1)  ; 「なに聞かしてくれるんだろ。\n三年間でぶち壊したカップルの数とか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0303>)  ; 女子生徒２
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 162, 1)  ; 「やってくんないかなぁ…\nそれ、ある意味すっごい楽しみ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 18
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0305>)  ; 諏訪先生
PUSH INT 18
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0306>, 163, 1)  ; 「おい静かにしろ！\n全く朝から落ち着きがないな…\nもうすぐ卒業なんだぞお前らは！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 18
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 15
PUSH INT 104
PUSH INT 1000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0307>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0308>, 164, 1)  ; 「誰のせいだっちゅ～ねん…\nあ～、もう、ふざけんな馬鹿…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0309>)  ; 男子生徒１
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 165, 1)  ; 「抑えろ、抑えろって孝宏。\nお前、今モメていいことなんか何もないぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0311>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 166, 1)  ; 「………は、はは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0313>  ; CATCH2
PUSH INT 100
CALL SCall
OPERATOR POP

ARRAY_S RES<0314>  ; 2312
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
