!RESOURCE "2412.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 2412
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
ARRAY_G 4
PUSH INT 3
OPERATOR MOV
OPERATOR POP
PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2045
PUSH INT 0
PUSH INT 150
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8111
PUSH INT 30
PUSH INT 1
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0004>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「………ん～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 100
PUSH INT 60
CALL SEV
OPERATOR POP

@VCALL WN(RES<0006>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「んふぅぅぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 180
PUSH INT 60
CALL SEV
OPERATOR POP

@VCALL WN(RES<0008>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「す～…んくぅぅぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0010>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「起きろぉぉぉ～！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 8070
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0012>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「ぃぅっ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 100
PUSH INT 10
CALL SEV
OPERATOR POP

@VCALL WN(RES<0014>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 5, 1)  ; 「いつまで寝てんだ！\n今日のゼミ発表会、司会お前だろ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 150
OPERATOR NEGATE
PUSH INT 60
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
PUSH INT 60
PUSH INT 5000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0016>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 6, 1)  ; 「ちょっ、や、や～！\nそ、掃除機でなんて～！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 7, 1)  ; 「だったら早く起きろ！\nその後シャワー浴びて朝飯食って大学だ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 8, 1)  ; 「だ、だめ、だめだって…\nそんなに吸われたらキスマークできちゃうってぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0022>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 9, 1)  ; 「だ、だから早く起きろって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 10, 1)  ; 「ん、あ、や…そ、そこじゃない…\nもっと、下ぁ…あ、ぁぁ…ぅんっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2905
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0026>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 11, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0028>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 12, 1)  ; 「はぁ、はぁ、はぁぁ…ぇ、もう終わり？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0030>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 13, 1)  ; 「…ちょっと自分の行為の変態性に危機感を持ってな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 14, 1)  ; このまま放っておくと、\n色んな場所を掃除機で責めてしまいそうだった。\n…嗜虐心に満ちた笑顔とともに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0033>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 15, 1)  ; 「や、やだ、こんなの中途半端だよぅ…\n朝からスイッチ入っちゃったよぅ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0035>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 16, 1)  ; 「早く服着てシャワー浴びて飯食え」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0037>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 17, 1)  ; 「その順番ってどうなの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0039>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 18, 1)  ; 「やかましい！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8111
PUSH INT 30
PUSH INT 1
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0041>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0042>, 19, 1)  ; 「ほんっと夜が明けると\n常識人に早変わりなんだもんなこのヴァンパイヤは～。\n昨夜はさんざん乙女の色んなとこ吸いまくったくせに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0043>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 20, 1)  ; 「ヴァンパイヤは処女の生き血にしか興味ない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0045>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 21, 1)  ; 「自分で眷属にしといてよく言うよ～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0047>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 22, 1)  ; 「そういうエロ話はもういいから。\nそれよりお前、今年も出席日数ヤバいんだからさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0049>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0050>, 23, 1)  ; 「卒業はしなくても別にいいんだって。\nあたしの進む道に大卒の肩書きは必要ないんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0051>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0052>, 24, 1)  ; 「またそれだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 25, 1)  ; ここに一緒に住むようになって半年…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0054>, 26, 1)  ; 恥ずかしながら、\n俺はまだこいつの人格改造を成し遂げられていない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 27, 1)  ; ゼミの出席日数もレポート提出率もギリギリ。\n部屋ではいつも寝てばかり。家事は全部俺任せ。\nすぐに俺の膝や胸に顔を埋めたがる野性を失った野良猫。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0056>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 28, 1)  ; 「いつか有名になって、\n春希を楽させてあげるからね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0058>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 29, 1)  ; 「そんなヒモの世迷い言を信じるほど、\n俺は夢見がちな行き遅れじゃないの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 30, 1)  ; ウァトスの方も、最近はあまり活動してない。\nその代わり、メジャー劇団のオーディションを\n受けまくってるようだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0061>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 31, 1)  ; 「どうせ有名になったら面倒見てくれた男はポイだろ。\nで、二枚目俳優とかと週刊誌で噂になってさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0063>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 32, 1)  ; 「何言ってんの～。\nあたし、春希に面倒見てもらわなきゃ\nろくろく生きてけないんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0065>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 33, 1)  ; 「もっと自立しろ。\nお前、最近本気で\nパラサイトが板についてきてんじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0067>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 34, 1)  ; 「だからぁ、\nあと三年の辛抱だって。\nそしたら今度はあたしが春希を依存させたげるからね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0069>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 35, 1)  ; 「俺はそんなあやふやな夢になんか頼らないの。\nちゃんと就職も決まったし、自活もできるし、\n何があっても一人で生きていけるように…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0071>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 36, 1)  ; 「あ～そこ、とりあえず二人分頼みます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0073>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 37, 1)  ; 「お前もそうやって夢ばっかり追ってないで\nもうちょっと現実的な生きる道をだなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0075>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 38, 1)  ; 「この前のオーディション、最終選考に残ったよ？\n１００人受けたうちの２人」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0077>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 39, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2905
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 40, 1)  ; こいつの場合、この才能が厄介なんだ。\n俺の常識論を軽く吹き飛ばしてしまうから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0080>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 41, 1)  ; 「だから、ごほうびっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0082>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 42, 1)  ; 「…わかったよ、ほれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0084>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 43, 1)  ; 「んっ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 44, 1)  ; 頭突きのようにぶっきらぼうに突き出す唇を、\nそれでも千晶は嬉しそうについばむ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0087>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 45, 1)  ; 「ね、春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0089>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 46, 1)  ; 「何だよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 47, 1)  ; そして、そのまま俺の胸に顔を埋める。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0092>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 48, 1)  ; 「…あたしのこと、愛してるよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0094>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 49, 1)  ; 「…今のところはな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 50, 1)  ; …開いた両手を一緒に押しつけながら。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 51, 1)  ; そんな“約束”をされたから、\n俺は誤魔化すことすらできなくなる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0098>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 52, 1)  ; 「三年後も…愛してるよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0100>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 53, 1)  ; 「そんなのはお前の心がけ次第だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 54, 1)  ; 一日に一度だけって制限を付けたけど。\n自分だけじゃなく、相手の両手でもＯＫという\n規制解除も増えたけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 55, 1)  ; それでも、俺たちの“約束”は、ずっと続いてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0104>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 56, 1)  ; 「じゃあ、そういうお前はさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0106>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 57, 1)  ; 「あたし？　昨夜正直に言ったじゃん。\n春希が背中越しに両手でおっぱい揉みまくってた時にさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0108>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 58, 1)  ; 「………おい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0110>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 59, 1)  ; 「あれが約束通り、あたしの心からの真実だよ？\nや～、恥ずかしかったな～、も～♪」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0112>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 60, 1)  ; 「そんなの手のひらの感覚に夢中で覚えてる訳ないだろ！\nなんて言ったんだ？　もう一度言ってみろよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0114>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 61, 1)  ; 「だったら…同じコトしてみたら～？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0116>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 62, 1)  ; 「こ、この…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
PUSH INT 60
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 150
OPERATOR NEGATE
PUSH INT 60
PUSH INT 4000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 63, 1)  ; でも、結局“あの日”以来、\nすっかり千晶の方の必殺技に成り下がってしまっていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 64, 1)  ; なぜならこの手の駆け引きで\n俺がこいつに勝てる訳なんかなく…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0120>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 65, 1)  ; 「ね、春希…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0122>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 66, 1)  ; 「なんだよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0124>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 67, 1)  ; 「あたしがあんたを幸せにしてあげる。\nいつか必ず、『お前と一緒にいて良かった』って、\n心から言わせてみせるからね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0126>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 68, 1)  ; 「そんなあやふやな空手形は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 69, 1)  ; それにそんな台詞、\nただ口に出してないだけで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0129>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 70, 1)  ; 「だから、そんなに頑張らなくていい。\n一人で、苦しまなくていい。\n壊れるまで、悩まなくていい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0131>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 71, 1)  ; 「………千晶」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 72, 1)  ; だから、もう自分は捨てられないと悟った飼い猫は、\nそんなふうに、突然自分をさらけ出す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 73, 1)  ; 「時間をかけて、春希を染め上げてあげるからね。\n…思い出の傷、塞がるまで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 74, 1)  ; かつて、そこにあった傷口の血の味が忘れられず、\n食いちぎって傷を拡げた野獣が…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0137>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 75, 1)  ; 「…いいんだよ、塞がなくて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0139>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 76, 1)  ; 「でも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 77, 1)  ; 心の中で、胸の傷をぺろぺろ舐めている千晶の頭を撫で、\nその上目遣いの瞳に、優しく微笑みかける。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0142>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 78, 1)  ; 「俺はずっと、この傷と一緒に生きていくんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0144>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 79, 1)  ; 「じゃあさ…\nあたしは、春希にその傷を付けたナイフを\nこれからもずっと持ち続ける」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0146>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 80, 1)  ; 「千晶…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 81, 1)  ; でも猫の方は、どうやら人間のつもりらしかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0149>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0150>, 82, 1)  ; 「あたしが憧れた三人。\nあたしがぶち壊した三人を忘れないために。\n…二度とこのナイフを使わないために」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0151>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 83, 1)  ; 「…また、いい台詞が思いついたとか、\nほくそ笑んでるんだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0153>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 84, 1)  ; 「久々にウァトスに顔出してみよっかな～。\nな～んかいいプロットが浮かんできたみたい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0155>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 85, 1)  ; 「いつか絶対に治してやる。\nそのねじ曲がった性格を」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0157>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 86, 1)  ; 「あはは…頑張ってねぇ、春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0159>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0160>, 87, 1)  ; 「っ！　はよシャワー浴びてこい！\nこっちはその間に掃除して洗濯して飯作って…\nああ忙しい！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8111
PUSH INT 60
PUSH INT 1
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 88, 1)  ; そして、結局いつもの朝の光景。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 89, 1)  ; それはつまり、いつもの昼の光景であり、\nいつもの夜の光景。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 90, 1)  ; 俺がどれだけ怒っても、説教しても、\nからからと適当なこと言って笑う千晶に、\n結局うやむやにされて、はいおしまい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 91, 1)  ; それだけじゃない。\nこいつはどんなときでも、\nふざけた道化師をやめようとしない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 92, 1)  ; 俺が落ち込んでも、悩んでも、苦しんでても…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 93, 1)  ; いつも脳天気で無責任な笑顔で救ってしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 94, 1)  ; だからこそ俺はまた、\nあの、一人で膝を抱えて震えていた自分を思い出し、\n不安に陥ることがある。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 95, 1)  ; 結局俺たちの関係は、\n千晶に嘘の癒しを与えてもらってたあの日まで\n戻ってしまっているのかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 96, 1)  ; それでも俺は、\nもう、この詐欺師から離れることなんかできない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0170>, 97, 1)  ; だから俺は、千晶を叱り、説教して、抱きしめて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 98, 1)  ; 何だかんだで見捨てられない“演技”をして、\nこの、ものぐさ女を俺に依存させ続ける。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 99, 1)  ; ずっと、俺がこいつの側にいられるように。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 210
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 210
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 210
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 43
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 20480
PUSH INT 0
PUSH INT 150
PUSH INT 0
PUSH INT 10
OPERATOR NEGATE
PUSH INT 5
PUSH FLOAT 1.05
PUSH FLOAT 1.05
PUSH INT 0
PUSH INT 0
CALL V2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 500
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 500
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 300
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SetDemoMode
OPERATOR POP

CALL StartTimer
OPERATOR POP

PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 100, 1)  ; 『ね、<W100>春<W10>希』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0174>, 101, 1)  ; 『本<W10>当<W10>は<W10>ね、<W150>とっ<W10>く<W10>に<W10>治っ<W10>て<W10>る<W10>ん<W10>だ<W10>よ、<W70>あ<W10>た<W10>し。<W200>\nあ<W10>ん<W10>た<W10>へ<W10>の<W10>気<W10>持<W10>ち<W10>だ<W10>け、<W150>ね<W10>じ<W10>曲<W10>がっ<W10>て<W10>な<W10>い<W10>ん<W10>だ<W10>よ』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 12000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 102, 1)  ; 『だ<W10>け<W10>ど、<W150>こ<W10>れ<W10>か<W10>ら<W10>も<W10>演<W10>技<W10>を<W10>続<W10>け<W10>る。<W220>\nあ<W10>た<W10>し<W10>は<W10>ちっ<W10>と<W10>も<W10>変<W10>わっ<W10>て<W10>な<W10>いっ<W10>て、<W130>\nずっ<W20>と<W30>春<W15>希<W15>を<W20>嘆<W12>か<W12>せ<W12>て<W12>や<W10>る<W10>か<W10>ら』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 12000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 103, 1)  ; 『こ<W10>れ<W10>か<W10>ら<W10>も<W150>ずっ<W20>と<W30>あ<W10>ん<W10>た<W10>の<W10>側<W10>に<W12>い<W12>る<W12>た<W12>め<W12>に』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 7000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 104, 1)  ; 『あ<W10>ん<W10>た<W10>の<W12>傷<W12>の<W12>痛<W12>み<W12>を<W20>忘<W12>れ<W12>さ<W12>せ<W12>る、<W120>\nピ<W12>エ<W12>ロ<W12>で<W12>い<W12>る<W12>か<W12>ら<W12>ね？』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 7000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 105, 1)  ; 『だ<W10>か<W10>ら<W10>春<W10>希<W10>…』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 106, 1)  ; 『ずっ<W20>と<W30>あ<W10>た<W10>し<W10>を<W10>叱<W10>る<W10>た<W10>め<W10>に、<W200>\nずっ<W20>と<W180>あ<W12>た<W12>し<W12>と<W12>一<W12>緒<W12>に<W12>い<W12>て<W12>ね』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 9000
CALL WaitTimer
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 360
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 360
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetDemoMode
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_G 4
PUSH INT 0
OPERATOR MOV
OPERATOR POP
PUSH INT 3
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

PUSH INT 23
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

CALL GoTitle
OPERATOR POP

STATEMENT HALT
