!RESOURCE "3011.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3011
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2013
PUSH INT 1
PUSH INT 15
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 0
PUSH INT 4300
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2045
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 7
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
PUSH INT 3906
PUSH INT 60
PUSH INT 1
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2136
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2901
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 120
PUSH INT 120
CALL SEV
OPERATOR POP

@VCALL WN(RES<0004>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「ほら、パン焼けたぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 100
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2048
PUSH INT 1
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0006>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0008>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「ふぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 130
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0010>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「寝不足か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0012>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「ちょっとな…\nさっきまでメール処理してたから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 5, 1)  ; 公約通り、浜田さんはしっかり雑務をｚｉｐでくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0015>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 6, 1)  ; 「家に仕事持ち帰ってんのかよ…\n典型的な日本のサラリーマンだなお前。\nいつか過労死するぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0017>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0018>, 7, 1)  ; 「…否定はしないけどな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 8, 1)  ; 解凍した後のファイル数を見て、\n軽くめまいに襲われた時に眠っておけばよかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 9, 1)  ; 「そうやって身を粉にして働いて、\n家族養うだけで自分を犠牲にする人生か。\n生きてて何が楽しいんだか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0022>, 10, 1)  ; けど、こいつに言われたくないって気持ちはある。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 11, 1)  ; 何しろ俺が真夜中に仕事に手をつけるほど\n眠れなくなってしまった原因は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 12, 1)  ; 「家族が本当に大切だったら、\nそのために頑張れるのは楽しいことだと思うぞ。\nまだ経験で語れないけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 60
CALL SES
OPERATOR POP

@VCALL WN(RES<0026>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 13, 1)  ; 「あ～、そりゃそうだろうな。\n何しろお前の家族になってやろうって相手は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0028>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 14, 1)  ; 「………ほら、目玉焼き」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 100
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0030>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 15, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 16, 1)  ; かずさの方も、俺が言葉を遮った意図を理解したのか、\nそれ以上は嫌味ったらしく踏み込んでこなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0033>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 17, 1)  ; 「塩コショウ？　ソース？　醤油？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 320
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0035>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 18, 1)  ; 「ケチャップ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0037>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 19, 1)  ; 「調味料まで甘めのものを…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 110
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0039>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 20, 1)  ; 「あたしの勝手だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 21, 1)  ; 鍋、フライパン、皿、スプーン、ナイフとフォーク、箸。\nオーブントースターにパンに卵に生野菜に調味料。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0042>, 22, 1)  ; たった一日で、\nかずさの部屋には結構な家財道具が入り込んだ。\n…とはいえ全部俺の部屋からの輸入品だけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0043>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 23, 1)  ; 「さてと、それじゃいただきます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 100
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0045>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 24, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0047>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 25, 1)  ; 「………（じろり）」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0049>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0050>, 26, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0051>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0052>, 27, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 111
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0053>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0054>, 28, 1)  ; 「…いただきます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0055>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 29, 1)  ; 「食べてよし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0057>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 30, 1)  ; 「っとに、鬱陶しい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 31, 1)  ; 昨日もしつこく言い聞かせたのに…\nって、絶対にわざと反抗してるよな、こいつ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0060>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 32, 1)  ; 「って、お前そんなにジャム塗るな。\nまた一瓶空けるつもりか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0062>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 33, 1)  ; 「朝に甘いものは重要だろ。\n糖分取らないと頭働かないぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0064>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0065>, 34, 1)  ; 「それにしても限度が…って、紅茶にも入れるのかよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0066>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0067>, 35, 1)  ; 「ロシアンティーも知らないのか日本人は」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 36, 1)  ; …まぁ、こっちのパラノイア的甘党に関しては、\nわざとでも何でもないことは歴史が証明済みだけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 37, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2048
PUSH INT 1
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0070>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 38, 1)  ; 「へぇ、しばらくは出張扱いなのか。\n思ったより気楽なんだな、お前の仕事も」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0072>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 39, 1)  ; 「言っておくが仕事量は減ってないからな。\nむしろこの取材分だけ増えてる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 40, 1)  ; かずさは味がわかってるのか怪しいくらい\n素早く朝食を平らげ、\n今は二杯目のロシアンティーを喉に流し込んでいる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 41, 1)  ; 今日もまた新品のジャムが一瓶消えた。\n…駄目だこいつ。早く食生活改善させないと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0076>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 42, 1)  ; 「そっちはどうなんだ？\n今日は練習か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 100
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0078>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 43, 1)  ; 「毎日練習だ、朝の１０時から」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0080>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 44, 1)  ; 「こっちでも一日十時間なのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0082>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 45, 1)  ; 「お前のせいでな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0084>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 46, 1)  ; 「そっか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 47, 1)  ; その決めつけは、そりゃ嬉しいけど、\n結構苦しくもあるんだけどな。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 100
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0087>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 48, 1)  ; 「で、これがコンサートやコンクールの直前だと、\n寝て食べる以外の時間は全部弾いてる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0089>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 49, 1)  ; 「…人間のやることじゃないよな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0091>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0092>, 50, 1)  ; 「演奏家なんてみんなそんなもんだ。\nあたしだけ特別こんなことやってる訳じゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0093>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 51, 1)  ; 「大変なんだな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0095>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 52, 1)  ; 「そうだよ。だから家事とか私生活のことなんか\n何もできなくて当然なんだ。\nする暇がないからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0097>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 53, 1)  ; 「お前は単に物臭なだけだろ。\nピアノやってなかった頃だって全然…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0099>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 54, 1)  ; 「うるさいな。\nあの頃のあたしは親に反抗してたからだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0101>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 55, 1)  ; 「カッコ悪かったもんなぁ、あの頃のお前…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 109
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0103>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0104>, 56, 1)  ; 「お前は今もカッコ悪いけどな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0105>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0106>, 57, 1)  ; 「まぁな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 58, 1)  ; それでもその立ち振る舞いが、\n憧れてしまうくらいカッコ良かったのが、\nまたタチが悪かったんだけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 130
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0108>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 59, 1)  ; 「さてと、それじゃ練習に行くか。\nお前はどうするんだ？\nあたしにしつこく付きまとうのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 60, 1)  ; そして今、親への反抗をやめて、\nストイックな音楽家になった冬馬かずさは、\n結局、何をしてもカッコ良いってことを証明した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 61, 1)  ; 俺の作った食事を感謝もせず食べてても、\n俺が世話を焼くのを当然のように受け止めてても、\n俺にどれだけ悪態をついてても…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0112>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 62, 1)  ; 「なぁ、かずさ。\n今日の練習、昼からにできないか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0114>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 63, 1)  ; 「…なんでだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0116>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 64, 1)  ; 「午前中、俺に付き合ってくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0118>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 65, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0120>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 66, 1)  ; 「駄目か…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0122>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 67, 1)  ; 「お、お前、何言ってんだよ。\nそんなこと、今さら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0124>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 68, 1)  ; 「けどお前、家財道具揃えないと。\n空っぽの部屋のまま、一月過ごすつもりなのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0126>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 69, 1)  ; 「………あ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0128>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 70, 1)  ; 「プリンもアイスクリームも、\n今のままじゃ食べたいときに食べられないぞ。\nそれでもいいんだな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 142
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0130>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 71, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 72, 1)  ; だから、自分の照れ隠しのために、\nかずさのカッコ良さを崩そうと躍起になり。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 73, 1)  ; …そのせいで、\nかずさが普段見せない一面を引き出してしまい、\n余計にヤバい気持ちになってしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0134>, 74, 1)  ; またしても悪循環。\nほんと、学習しないな、俺も。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 75, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8205
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
PUSH INT 8203
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 127
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1024
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 240
CALL SES
OPERATOR POP

PUSH INT 0
PUSH INT 3104
PUSH INT 240
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0136>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0137>, 76, 1)  ; 「ふぅ、間に合った」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0138>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 77, 1)  ; 「一本遅らせてもいいから全力で走るな。\nまたヒール折るぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0140>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 78, 1)  ; 「…嫌なことを思い出させるな春希は。\nあの時は雪だったから仕方ないんだって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0142>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 79, 1)  ; 「とにかく、お前は今怪我していい訳ないんだから、\nもうちょっと慎重にだな………あ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0144>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 80, 1)  ; 「だから、そんなヘマなんかしないって言ってるだろ。\nコンサートが近づくと、集中力が増してくるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0146>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 81, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 109
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0148>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 82, 1)  ; 「これが三日前くらいになると、\n自分で言うのもなんだけど凄いぞ。\n１００メートル先で誰かが石を蹴った音が聞こえたり…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0150>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 83, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 130
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0152>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 84, 1)  ; 「…春希？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 85, 1)  ; なんて、こった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0155>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 86, 1)  ; 「かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0157>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 87, 1)  ; 「え、なに………きゃっ！？\nお、お、おい…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 88, 1)  ; かずさの肩に手を置くと、\n力を込めてくるりと半回転。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0160>, 89, 1)  ; そのままドアの方を向かせ、\n背中から抱きしめるように身体を重ねる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0161>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 90, 1)  ; 「は、春希…\nいきなり、なにすんだよお前…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 91, 1)  ; 俺の、そんな強引にも程がある行為に、\nかずさが全身を思いっきり強ばらせる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0164>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 92, 1)  ; 「あんま喋るな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0166>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 93, 1)  ; 「なんで、なんで…\nお前、こんなことしたらどうなるか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0168>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 94, 1)  ; 「頼む、目立たないでくれ…\n昨日言ったことがもう現実になってる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0170>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 95, 1)  ; 「…何のことだ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0172>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 96, 1)  ; 「広告にお前の写真が…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0174>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 97, 1)  ; 「…んだってぇ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 98, 1)  ; かずさに説教を垂れつつふと見上げた先の、\nお馴染みの写真週刊誌の中吊り広告。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 99, 1)  ; 前から三番目の記事紹介に\n『冬馬かずさ』の文字と顔写真を見た瞬間、\n俺の心拍数は一気に３０近く上がった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0178>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 100, 1)  ; 「とにかく下りるまでずっと外見てろ。\n絶対こっち向くなよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0180>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 101, 1)  ; 「けど、どんなこと書いてあるか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0182>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0183>, 102, 1)  ; 「見るな。\nデタラメばっかりだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0184>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0185>, 103, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 104, 1)  ; その一言で、\nかずさにはその記事の内容が、\nもしかしたら伝わってしまったかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 105, 1)  ; けど、やっぱ駄目だ。\nこんな…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0188>, 106, 1)  ; 『取材拒否　暴言乱発　ファンの声援も無視』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 107, 1)  ; 『初来日・天才二世ピアニスト冬馬かずさ\n母親譲りの唯我独尊』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0190>, 108, 1)  ; “これぞ三流週刊誌”という表現が\n気持ちいいくらいぴったりハマる、\nお馴染みの見出し。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0191>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0192>, 109, 1)  ; 「考え過ぎかもしれないけど、\n誰かがお前の正体に気づくかもしれない。\n…そんなことになったらヤだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0193>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0194>, 110, 1)  ; 「春希…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 111, 1)  ; 本当は『気づかれたくない』より\n『見せたくない』気持ちの方が強かったけど、\nいちいちそんな心情を説明する必要なんかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0196>, 112, 1)  ; ただ、俺がこうしないと。\nかずさと日本との間の、緩衝材にならないと…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0197>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0198>, 113, 1)  ; 「だから、悪い。\nちょっと窮屈かもしれないけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 104
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0199>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0200>, 114, 1)  ; 「窮屈だ。悪い。最悪だ。\nお前は本当に厚かましい奴だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0201>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0202>, 115, 1)  ; 「ごめんな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0203>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0204>, 116, 1)  ; 「謝れば済むと思ってやがる。\nあたしなら、許すだろうって思ってやがる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0205>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0206>, 117, 1)  ; 「そんなことは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0207>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0208>, 118, 1)  ; 「………ふざけるな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 119, 1)  ; 口からの罵詈雑言はそのままだったけど、\nそれでも俺は、かずさが落ち着いたことを知り、\n少しだけ胸をなで下ろした。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0210>, 120, 1)  ; だって、全身の緊張が解けたから。\n少しだけ、俺の体が触れるのを許し始めたから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0211>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0212>, 121, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0213>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0214>, 122, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 123, 1)  ; 車内は、いつも通りだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0216>, 124, 1)  ; 皆、目の前の写真に写ってる女性と、\nドアに不自然にへばりついてる女性との\n相関関係には気づいていなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 125, 1)  ; その事実に俺の判断が効いたのかどうかは\n正直よくわからなかったけど、\nでも、今後もこういう判断が発生することだけは実感した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0218>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 126, 1)  ; 「はぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 206
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0220>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 127, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL SEV
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0222>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 16
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0223>)  ; 曜子
PUSH INT 16
PUSH INT 9000
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 128, 1)  ; 『このままじゃ、多分そのうちボロボロになる』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0225>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 0
PUSH INT 255
PUSH INT 60
CALL SEV
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 206
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1024
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 129, 1)  ; 曜子さんの言ってたことは杞憂だと思ってたけど、\n実はあまりそうでないのかも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 130, 1)  ; やっぱり…俺が守らなくちゃならないのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 131, 1)  ; 俺のささやかな未来のためには、\n一番遠ざけなくちゃならないこの女を…？
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 142
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0229>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 132, 1)  ; 「…なぁ、春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0231>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 133, 1)  ; 「…なんだよ、かずさ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0233>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 134, 1)  ; 「さっきからなんか当たってるぞ？\n…あたしのお尻に」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0235>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 135, 1)  ; 「カメラだよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0237>, 136, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 41
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0238>)  ; 店員
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0239>, 137, 1)  ; 「ほら…\nこんな感じですけど、いかがでしょう？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0240>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 138, 1)  ; 「へぇ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0242>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 139, 1)  ; 「へ、へぇじゃない！\n鏡、鏡はどこだ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0244>)  ; 店員
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 140, 1)  ; 「大丈夫ですよ。\nほんとお似合いです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0246>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 141, 1)  ; 「そんな感想はいいから、早く！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0248>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0249>, 142, 1)  ; 「慌てるなよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0250>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 143, 1)  ; 「慌てるに決まってるだろ！\nこんな、こんな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 20620
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL V
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0252>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 144, 1)  ; 「な…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0254>)  ; 店員
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 145, 1)  ; 「彼女、髪長くて綺麗だから、\nちょっと勿体ないかなって気もしたけど、\nこっちもいけますね～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0256>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 146, 1)  ; 「本当だ…全然ＯＫですね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0258>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 147, 1)  ; 「な、な、な…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0260>, 148, 1)  ; 電車から降りて俺たちが最初に目指したのは、\n家電量販店でも家具店でもなく、\nアクセサリショップだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 149, 1)  ; そこで、結構お馴染みになった店員に相談し、\n『素顔が気取られないグッズ』という、\nあまりに怪しい条件で見繕ってもらったのがこれ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 150, 1)  ; コームの髪飾りで髪をサイドアップにまとめ、\n伊達眼鏡で目を隠し…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 151, 1)  ; これで『ただ今話題沸騰のピアニスト冬馬かずさ』改め、\n『その辺にいる眼鏡の綺麗なお姉さん』の出来上がり。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0264>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 152, 1)  ; 「…何だこれは？\n馬鹿にしてるのかお前」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0266>)  ; 店員
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0267>, 153, 1)  ; 「え～？\nすごく似合ってますよねぇ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0268>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 154, 1)  ; 「ねぇ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 155, 1)  ; ………出来上がり、だよな？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0271>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 156, 1)  ; 「女の髪や顔を勝手にいじるなんて、\nお前もえらくなったもんだよなぁ…\n五年前は岩石よりも堅い委員長だったのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0273>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 157, 1)  ; 「仕方ないだろ。\n素のままで歩けなくなったお前が悪い」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0275>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 158, 1)  ; 「っ、あたしのせいじゃない！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0277>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 159, 1)  ; 「うん、お前の責任じゃなくてお前の実力だよ。\n…別に卑下することなんかない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0279>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 160, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 161, 1)  ; 俺がこんな手を思いついたヒントは、\n付属時代、俺と知り合う前の、放課後の雪菜だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 162, 1)  ; 眼鏡をかけて三つ編みにして、わざと野暮ったい服を着て、\n学園のアイドルという自分を、学園近くのスーパーで、\n二年半も隠蔽し続けた嘘つきな女の子。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 163, 1)  ; …その手法をあろうことか、かずさに施すって、\n俺って結構酷い奴なのかもしれないけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 164, 1)  ; でも今は、背に腹を替えられない。\n普段のかずさを世間の目から逸らすことが何よりも先決だ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0285>)  ; 店員
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 165, 1)  ; 「どうします？\n別の持ってきましょうか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0287>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 166, 1)  ; 「だとさ。\nどうする？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0289>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 167, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0291>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0292>, 168, 1)  ; 「…会計お願いします。\n両方とも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0293>)  ; 店員
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 169, 1)  ; 「はい、お買いあげありがとうございます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0295>, 170, 1)  ; そのふてくされた沈黙は、\n『どれでも同じだ馬鹿野郎』という台詞を、\nしっかりと表情で語っていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 171, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3003
PUSH INT 60
PUSH INT 1
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1062
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0297>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 172, 1)  ; 「言っておくけど、\nこんなもの買ったって明日から使わないぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0299>, 173, 1)  ; その後、追加でマフラーと帽子も揃え、\n『その辺にいる眼鏡の綺麗なお姉さん』から、\n『その辺にいる重装備の綺麗なお姉さん』に早変わり。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0300>, 174, 1)  ; …なんか違うような気もするけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0301>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 175, 1)  ; 「何でそんなに嫌がるんだよ？\nそりゃ、少し窮屈かもしれないけど、\n街でいきなり正体バレするよりは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0303>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 176, 1)  ; 「あたし、髪結べないんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0305>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0306>, 177, 1)  ; 「…はぁ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0307>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0308>, 178, 1)  ; 「絶対にグシャグシャになるんだ。\n…前に一度試して、母さんに呆れられたんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0309>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 179, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0311>, 180, 1)  ; こいつが昔からずっとストレートロングのままなのは…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0312>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0313>, 181, 1)  ; 「だから、その…\n眼鏡は使うけど、コームの方は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0314>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0315>, 182, 1)  ; 「俺が結べばいいんだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0316>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0317>, 183, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0318>, 184, 1)  ; 髪をひっつめることすら満足にできない、\n天才的に手先が器用なはずのピアニスト。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0319>, 185, 1)  ; それは多分、生来のめんどくさがりな性格が\n多分に影響してるとは思うけれど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0320>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0321>, 186, 1)  ; 「このまとめ方なら、さっきのやり方見てたから、\nちゃんと再現できると思う」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0322>, 187, 1)  ; 髪をまとめるのと、\n綺麗なストレートのままにしておくのと、\nどっちが大変なんだよと思わないでもないけれど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0323>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0324>, 188, 1)  ; 「けどそれって、毎朝…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0325>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0326>, 189, 1)  ; 「迷惑か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0327>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0328>, 190, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0329>, 191, 1)  ; でも、こいつができないって言うならしょうがない。\n独占取材の邪魔になりそうな要素は、\n担当の俺が極力排除するしかないから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0330>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0331>, 192, 1)  ; 「こっちの仕事の都合もあるから、\n朝早くでないと無理な日もあると思う。\nだから、できれば生活リズムを合わせてくれると…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0332>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0333>, 193, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0334>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 194, 1)  ; 「やっぱ、駄目か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 111
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0336>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0337>, 195, 1)  ; 「知るか。\n勝手にしろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 20
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8238
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 90
CALL SES
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0338>, 196, 1)  ; なんて、いつも通り悪態をつきながら、\n『勝手にしろ』というお墨付きとともに、\nその意を悟られまいと、さっさと先に歩き出す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0339>, 197, 1)  ; 結局、かずさは散々文句を垂れまくっても、\n何だかんだでこっちの主張を受け入れてくれる、\n最後の砦的な優しさを失いはしない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0340>, 198, 1)  ; 俺の前では、いつもいつもふてくされてて、\n俺の干渉をとても迷惑そうに受け流して、\nけれど気がつくと隣にいたりして…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0341>, 199, 1)  ; 今のかずさは、\nまるで俺と雪菜が出逢う前の…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 1062
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0342>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0343>, 200, 1)  ; 「そうだ…\nかずさ、ちょっと待ってくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 104
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0344>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0345>, 201, 1)  ; 「なんでだよ？\n早いところ他の買い物も済ませないと、\n練習時間がどんどん削られて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0346>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0347>, 202, 1)  ; 「一枚だけ、一枚！\nほら、そこに立って」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0348>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0349>, 203, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0350>, 204, 1)  ; 言いながら、俺がカメラをケースから取り出すと、\n眼鏡越しのかずさの瞳が、ちょっと揺らぐ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0351>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0352>, 205, 1)  ; 「ほら、笑って…\nって、普段通りの方がいいか。\nほらかずさ、しかめっ面頼む」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0353>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 140
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0354>, 206, 1)  ; 「…やっぱりあたしを馬鹿にしてるだろ、お前」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0355>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 141
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0356>, 207, 1)  ; 「そう、そんな感じ…\n行きます、はい…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2912
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 9900
PUSH INT 0
PUSH INT 10
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 20630
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1.05
PUSH FLOAT 1.05
PUSH INT 0
PUSH INT 0
CALL V2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 180
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 270
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0357>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 142
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0358>, 208, 1)  ; 「っ…あ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0359>, 209, 1)  ; けど、そんなちょっと戸惑い気味の表情は、\nまんまとデジカメのデータに変換されてしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0360>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 143
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0361>, 210, 1)  ; 「お疲れさまでした。\nじゃ次、家電コーナー行くぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0362>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 144
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0363>, 211, 1)  ; 「初めての一枚が変装姿かよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0364>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 145
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0365>, 212, 1)  ; 「だって、これはこれで…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0366>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 146
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0367>, 213, 1)  ; 「…本当に、馬鹿にしやがって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0368>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 147
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0369>, 214, 1)  ; 「別に馬鹿になんかしてないって。\n本当に似合って…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0370>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 148
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0371>, 215, 1)  ; 「あ…そうだ。\nレシート」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0372>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 149
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0373>, 216, 1)  ; 「え？　何の？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0374>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 150
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0375>, 217, 1)  ; 「変装道具一式のだよ。\nお前、全部現金で払ってたよな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0376>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 151
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0377>, 218, 1)  ; 「あ、あ～………そっか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0378>, 219, 1)  ; ちぇっ、気づかれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0379>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 152
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0380>, 220, 1)  ; 「後でまとめて精算するから、\nとりあえず渡しておいて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0381>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 153
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0382>, 221, 1)  ; 「いるかそんなの。\n俺のニーズで買ったんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0383>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 154
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0384>, 222, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0385>, 223, 1)  ; 俺が払うためにわざと現金払いにしたのに、\nなんて空気を読まない奴だ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0386>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 155
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0387>, 224, 1)  ; 「その代わり、これから買う家電とか家具は別だぞ？\n今の買い物と比べて金額の桁が違うしな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0388>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 156
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0389>, 225, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0390>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 157
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0391>, 226, 1)  ; 「聞いてるのか？\nちゃんと払えよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0392>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 158
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0393>, 227, 1)  ; 「あ、ああ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0394>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 159
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0395>, 228, 1)  ; 「それならいいんだよ。\nさ、今度こそ行くぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0396>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 160
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0397>, 229, 1)  ; 「…春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0398>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 161
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 230, 1)  ; 「あ、それと櫛は後でちゃんと踏んでおけよ？\nそうしないと<R苦|９>しんで<R死|４>ぬことになるからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0400>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 162
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 231, 1)  ; 「現実的なくせに迷信深いなお前は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0402>, 232, 1)  ; こうして、『冬馬かずさ独占取材』の初日は、\n何の計画性もなく、唐突にスタートを切った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0403>, 233, 1)  ; かずさは、やっぱり悪態をつきながらも、\n今度は先に歩き出す俺の後ろを、\n三歩離れてしっかりついてきてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

@VCALL SetMessageE(RES<0404>, 234, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0405>, 235, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0406>, 236, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2061
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0407>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 163
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0408>, 237, 1)  ; 「よし、これでなんとか一通り揃えたかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0409>, 238, 1)  ; 冷蔵庫、テーブル、ベッド、その他諸々。\n家電売り場と家具売り場を縦横無尽に走り回り、\nたった数時間で１０万以上も散財してしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0410>, 239, 1)  ; まぁ、冬馬家にしてみれば、\nこの程度の出費、痛くも痒くもないんだろうけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0411>, 240, 1)  ; …なにしろたった一月程度の滞在のために、\n敷金礼金合わせて三か月分を払う気前のいい一家だ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0412>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 164
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0413>, 241, 1)  ; 「うわ…もう２時だぞ。\nどれだけあたしを引きずり回せば気が済むんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0414>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 165
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0415>, 242, 1)  ; 「…文句言うだけの奴は楽でいいよなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0416>, 243, 1)  ; 結局、店員との交渉は全て俺任せ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0417>, 244, 1)  ; かずさは暇そうに店内の商品を見て回り、\n最終的な俺の選択にケチをつけるだけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0418>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 166
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0419>, 245, 1)  ; 「もうちょっとデザインも考慮に入れろ。\n春希、お前機能とコストパフォーマンスしか\n見てないじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0420>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 167
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0421>, 246, 1)  ; 「生活必需品選びにそれ以外の観点があるか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0422>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 168
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0423>, 247, 1)  ; 「だからお前の生活には潤いが足りないんだ。\nもうちょっとゆとりを持って生きろよこの働き蟻」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0424>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 169
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0425>, 248, 1)  ; 「お前、自分がキリギリスだって自覚してるだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0426>, 249, 1)  ; けれど『じゃあどれならいいんだよ？』という\n俺の質問に、『そんなの知るか』で返してくるから、\n結局最初に選んだのに決まるという展開の繰り返し。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0427>, 250, 1)  ; かずさがいちいち文句さえつけなきゃ、\n余裕で１時に間に合ってたんだけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 130
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0428>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 170
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0429>, 251, 1)  ; 「とにかく用事はこれで終わりなんだな？\nあたしはもう練習に向かっていいんだな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0430>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 171
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0431>, 252, 1)  ; 「ああ、お疲れさま」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0432>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 172
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0433>, 253, 1)  ; 「本当に疲れるのはこれからだ…\n今から十時間だからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0434>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 173
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0435>, 254, 1)  ; 「…今日もやるのか？\n随分と遅くから始めるのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0436>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 174
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0437>, 255, 1)  ; 「ん…日課だからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0438>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 175
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0439>, 256, 1)  ; 「そっか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0440>, 257, 1)  ; なんて、これからの地獄の特訓に\n思いを馳せてるはずなのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0441>, 258, 1)  ; かずさの表情は昨夜からだんだん…\nいや、先週末からどんどん穏やかになってきてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 100
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0442>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 176
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0443>, 259, 1)  ; 「それじゃ、春希…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0444>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 177
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0445>, 260, 1)  ; 「あ、あのさ…\nできれば弾いてるところも撮らせてくれないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0446>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 178
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0447>, 261, 1)  ; 「悪い…練習だけは見せたくないんだ。\nまだ仕上がってないから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0448>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 179
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0449>, 262, 1)  ; 「最初の数分だけでいいんだけどな。\nその、弾いてるふりしてくれれば」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0450>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 180
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0451>, 263, 1)  ; 「コンサートの後にしてくれ。\n今は集中したいんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0452>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 181
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0453>, 264, 1)  ; 「そっか…ごめん、無理言って」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0454>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 182
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0455>, 265, 1)  ; 「いや…あたしの方こそ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0456>, 266, 1)  ; その証拠に、\n以前なら怒鳴られてもおかしくないやり取りも、\nこうしてお互い譲歩しあうことができる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0457>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 183
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0458>, 267, 1)  ; 「じゃ、頑張ってな。\nそうだ、晩飯はどうする？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0459>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 184
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0460>, 268, 1)  ; 「なんでもいい。\nどうせ何作っても大して美味くないだろ、お前」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0461>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 185
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0462>, 269, 1)  ; 「………わかったよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0463>, 270, 1)  ; そのかずさの答えを受けた俺の苦笑いは、\nとっくに背中を向けたかずさには\n届いていなかったかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

CALL IfSkip
OPERATOR POP

@VCALL SetMessageE(RES<0464>, 271, 1)  ; 本当は『外で済ませてくるか家で食うか』を\n聞いたつもりだったんだけどな…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_13
PUSH INT 4
CALL GetGameFlag
PUSH INT 1
OPERATOR EQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 210
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0465>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 186
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0466>, 272, 1)  ; 「今は無理に決まってるだろ、春希…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0467>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 187
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0468>, 273, 1)  ; 「だってさ…\nお前に最高の冬馬かずさを見せるためだけに、\nあたしは日本まで来たんだぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

#LABEL_13
PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0469>  ; CATCH3
PUSH INT 100
CALL SCall
OPERATOR POP

ARRAY_S RES<0470>  ; 3012
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
