!RESOURCE "3023.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3023
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2013
PUSH INT 2
PUSH INT 9
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 40
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2085
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0004>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「ここで会うのは一週間ぶりかしらね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 2, 1)  ; 激動の一日だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 3, 1)  ; 早朝からずっと曜子さんの携帯は繋がらず、\n工藤さんや浜田さんにまで何度も問い合わせて、\nあの親子の行方を捜し求めた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0010>, 4, 1)  ; やっと曜子さんから連絡が返ってきたのが１７時。\nけれどその時彼女がいた場所は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0011>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 5, 1)  ; 「それで、何から話せばいいかしら」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0013>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 6, 1)  ; 「まずは…あなたの今の状態を」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 7, 1)  ; そこは、一週間前に会った病室。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 8, 1)  ; 午前中に連絡したときはいないって話だったのに、\nその後で救急病院から転院してきたんだとか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 9, 1)  ; つまり、俺たちの状況はふりだしに戻った。\n…いや、実質的には後退してた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0018>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 10, 1)  ; 「あら、この期に及んでも\nわたしのことを優先してくれるの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 11, 1)  ; 「当たり前です。辛くないですか？\nこうして俺と話してて大丈夫なんですか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0022>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 12, 1)  ; 「…別に悪くなってないわよ。\n一進一退といったところ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 13, 1)  ; 「…今すぐどうこうってことはないんですね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0026>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 14, 1)  ; 「ええ、ちょっと貧血気味なだけよ。\nベッドで休んで点滴受けたから今は平気」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0028>, 15, 1)  ; 俺に軽口が通用しないことを思い出したか、\n曜子さんは、はぐらかすのをやめてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0029>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0030>, 16, 1)  ; 「ただ、大したことないのに救急車呼んじゃったから、\nしばらくはこうしてなきゃいけないけどね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0031>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 17, 1)  ; 「それって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0033>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 18, 1)  ; 「何しろかずさは、\nわたしがこうなるのを初めて見たから、\nパニックになっちゃってね…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0035>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 19, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0037>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 20, 1)  ; 「ごめん、ギター君。\nわたし、あの子の目の前で倒れちゃった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 21, 1)  ; かずさは、俺に傷つけられ続ける今の生活に耐え切れず、\n俺の監視を振り切って、曜子さんの元に向かった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 22, 1)  ; それは、曜子さんが薬で眠っている早朝…\n予期せぬ事態で自分の体調も整えられない、\n虚勢を張る余裕もない時間帯で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0041>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0042>, 23, 1)  ; 「せっかくあなたが頑張って\n隠し通そうとしてくれたのに、\nどうやら台無しにしてしまったみたいね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0043>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 24, 1)  ; 「…俺のせいです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 25, 1)  ; そんな時、防波堤になると誓ったはずの俺は、\nかずさを落ち着かせられたと甘く考えて、\n迂闊にも眠ってしまっていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 26, 1)  ; それどころか、かずさの感情を強く刺激して、\n自ら防波堤を決壊させる方向へ波を追い込んだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 27, 1)  ; こんな大事なときに限って…\nもう、自分を責める言葉しか思い浮かばない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0048>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 28, 1)  ; 「罰、かしらね。\n自分の娘を騙そうとした」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0050>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 29, 1)  ; 「それも俺のせいです。\nあいつを騙そうって考えたのも、\n曜子さんにそうさせたのも…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 108
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0052>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 30, 1)  ; 「あなた、ちょっと自分で背負い込もうとしすぎよ。\nたかが昔の男が、親よりもしゃしゃり出てくるのは\nどうなのよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0054>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 31, 1)  ; 「…すいません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0056>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 32, 1)  ; 「…そこで謝るのも確信犯よね。\nわたしが巻き込んだことに文句一つ言わずに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0058>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 33, 1)  ; 「…そこまで言うなら、お互い様ってことで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0060>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 34, 1)  ; 「そうね。\n落としどころはその辺にしておきましょうか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 35, 1)  ; 曜子さんが、自分の娘を騙そうとした罰を受けるのなら、\n俺は、自分の大切な人を傷つけた罰を受けるべきだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0063>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 36, 1)  ; 「それで、かずさは…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0065>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 37, 1)  ; 「どこに行ったかは知らない。\nでも多分、前よりも簡単に見つかると思うわ。\n…しばらくは立ち上がる気力も失ってたもの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0067>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 38, 1)  ; 「っ…曜子さん。\n俺は、どうすればいいんですか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0069>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 39, 1)  ; 「わたしがどうすればいいか教えてくれたら、\nその質問に答えてあげるわ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 40, 1)  ; 罰を受けるべきとか、そういう話じゃない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 41, 1)  ; ただ、かずさが心に深い傷を負ったことが、\n俺の心にまで、深い傷を刻み込んだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 42, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0074>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 36
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2085
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0075>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 43, 1)  ; 「…とりあえず、前回と同じ薬を投与しといて。\nで、目覚めたら僕に直接連絡して」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0077>)  ; 看護師
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 44, 1)  ; 「精密検査の方は？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0079>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 45, 1)  ; 「あ～、それも僕が診断してからにする。\nとにかく今日はずっとこっちに詰めてるから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 203
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0081>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0082>, 46, 1)  ; 「ちょっと待ってくれよ…\nこれ、一体どういうことなんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 36
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0083>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0084>, 47, 1)  ; 「あ～、大丈夫大丈夫、\nお母さん、少し安静にしてたらすぐ退院できるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0085>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 48, 1)  ; 「なんでみんな、\nこんなに『わかってる』んだよ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0087>)  ; 看護師
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 49, 1)  ; 「病室で騒がないでください。\n患者さんが起きてしまいますから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0089>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 50, 1)  ; 「まぁ落ち着いて。\nこういうのは大袈裟に見えるけど\nよくあることなんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0091>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0092>, 51, 1)  ; 「よくあるってどういうことだよ？\n母さん、何度もこうなったことあるのか！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0093>)  ; 看護師
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 52, 1)  ; 「お静かに！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0095>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 53, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 36
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0097>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 54, 1)  ; 「ええと、かずさちゃん、だっけ？\nちょっと喫茶室でお茶でもしようか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0099>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 55, 1)  ; 「母さんは…母さんは平気だよな？\nただの貧血なんだよな…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 36
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0101>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 56, 1)  ; 「…とにかく落ち着こう。\n今はお母さんを休ませてあげようね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0103>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0104>, 57, 1)  ; 「で、でも…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 36
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0105>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0106>, 58, 1)  ; 「今は眠ってるだけだ、平気だよ。\nささ、僕と一緒に…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0107>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 59, 1)  ; 「…自分の孫と同じくらいの娘を引っかけようとするな。\n相変わらずあんたは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0109>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 60, 1)  ; 「っ…母さん！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 36
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0111>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 61, 1)  ; 「…曜子ちゃん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 8246
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 15
CALL SES
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0113>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 62, 1)  ; 「…何だか、またいらぬ世話をかけたみたいね。\nでももう大丈夫だから。ありがとうノリ君」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0115>)  ; 高柳
PUSH INT 36
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 63, 1)  ; 「しかし、君の体のことは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0117>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 64, 1)  ; 「娘と二人きりにして頂戴。\n…わたしから話すから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0119>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0120>, 65, 1)  ; 「…母、さん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 66, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 67, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 68, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 24
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2085
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0124>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 69, 1)  ; 「…と、まぁそんなところ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 308
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0126>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 70, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0128>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 71, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0130>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 72, 1)  ; 「は、はは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0132>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 73, 1)  ; 「かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 74, 1)  ; 「冗談だろ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0136>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0137>, 75, 1)  ; 「ええ、超悪質な冗談よ。\n…と言えば、今からでもあなたは信じてくれる？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 30
CALL CR
OPERATOR POP

PUSH INT 20
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8440
PUSH INT 0
PUSH INT 0
PUSH INT 200
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0138>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 76, 1)  ; 「っ…ぁ、ぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0140>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 77, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0142>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 78, 1)  ; 「そ、んな…なんで…\nなんで今、なんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 104
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0144>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 79, 1)  ; 「本人よりショック受けられても困るのよね。\nあくまでも症状が出たのはわたしの方なんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 212
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0146>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 80, 1)  ; 「あんた約束したよなぁ！\n娘より先に死なないって言ったよなぁ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0148>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 81, 1)  ; 「人生、基本的には先送りよ。\nそんなことを本気で信じてる方が痛いんじゃない？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0150>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 82, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0152>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 83, 1)  ; 「人間、死ぬときはあっけないもんよ。\nわたしだって今まで何度もそういうの見てきたし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 131
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0154>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0155>, 84, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0156>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 85, 1)  ; 「そりゃ、まぁ…病気になったのも、\nそれをあなたに知られたのも不本意ではあるけれど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0158>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 86, 1)  ; 「………………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0160>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 87, 1)  ; 「でも、知られてしまった以上は、\n少しでも前向きに捉えないとね。\nあなたもいざって時のこと、覚悟しておいた方が…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 125
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0162>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 88, 1)  ; 「………………………ぅぇっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 105
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0164>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 89, 1)  ; 「う…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0166>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 90, 1)  ; 「う、うぅ…ひぅっ、ひっく…う、うぇ、うぇぇ…っ、\nそ、んな…そんな、そんな、そんな…嘘、だぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0168>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 91, 1)  ; 「あ、あ、あ…ちょっと、かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0170>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 92, 1)  ; 「母さん…母さん母さん母さん…っ、\n嫌だ、嫌だぁ…死ぬな、死んじゃ駄目だぁぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0172>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 93, 1)  ; 「あなたは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0174>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 94, 1)  ; 「長生きするって、言ったじゃないか…\nあたしのために、体に気をつけるって…\nなのに、なのに…ぅ、ぅぇ…ぇぇぅっ、う、うあぁぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0176>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 95, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0178>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 96, 1)  ; 「どうしたら…あたしどうしたらいいんだよ…\n何もなくなっちゃったじゃないか…\nすがるもの、一日で全部なくしちゃったじゃないかぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 103
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0180>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 97, 1)  ; 「…あ～、ごめんごめん、よしよし！\nほら、こっちおいで！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2085
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 100
OPERATOR NEGATE
PUSH INT 80
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 150
PUSH INT 80
PUSH INT 5000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0182>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0183>, 98, 1)  ; 「う、うあぁぁぁぁぁぁっ！\nか、母さん…ふぇ、うえぇぇぇぇぇぇっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0184>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0185>, 99, 1)  ; 「まったく…\nあなたが赤ん坊の時だって、\nこんなことしなかったわよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0186>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 100, 1)  ; 「う、うぇっ、えぐっ、う、うあぁぁ…\nや、やだ…あたし、あたし…ぃ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0188>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 101, 1)  ; 「…ま、しなかったからこそ、\nこんな子に育っちゃったんだけどね。\nごめん、かずさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0190>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 102, 1)  ; 「ふぇぇぅっ、う、うぐ…う、う…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0192>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 103, 1)  ; 「このまますぐ死んだら確かに早すぎるけど…\n安心なさい。そんなに簡単にはくたばらないから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0194>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 104, 1)  ; 「…本当？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 105, 1)  ; 「一応、これでも１００まで生きるつもりだしね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0198>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 106, 1)  ; 「ま、また、裏切ったりしないよな？\nそんなこと信じるのは痛いとか言わないよなぁ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0200>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 107, 1)  ; 「…あ～、さっきは言いすぎたわ、ごめん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0202>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 108, 1)  ; 「一緒に…いてくれるよな？\n母さんだけは、ずっと、ずっと一緒に…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0204>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 109, 1)  ; 「かずさ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0206>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 110, 1)  ; 「帰ろう…\nコンサート終わらせて、早くウィーンに帰ろうよ。\n家でゆっくり寝てれば、すぐに治るよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0208>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 111, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0210>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 112, 1)  ; 「そして治ったら、またピアノ弾こう？\nあたし、これからは母さんの面倒も見るからさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0212>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 113, 1)  ; 「そうだ、一緒にコンサート開くなんてのもいいな。\n連弾とかしたことないよな、あたしたち」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0214>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 114, 1)  ; 「あたしも、母さんの添え物って言われないように、\nもっと腕を上げないとな。\nこれからはコンサートもコンクールも、もっと沢山出て…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0216>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 115, 1)  ; 「かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0218>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 116, 1)  ; 「頑張って、頑張って、\nいつかあんたと並び立つくらいに…\nいや、超えてみせるからさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0220>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 117, 1)  ; 「だから、だから…\nずっと、あたしの…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 118, 1)  ; 「あたしの、ものすごく高い目標で…\n呆れるくらい強い敵で…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0224>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 119, 1)  ; 「かずさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0226>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 120, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0228>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0229>, 121, 1)  ; 「もう、隠しごとはしないわ。\nあなたをこれ以上、欺きたくないから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0230>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0231>, 122, 1)  ; 「母さん…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0232>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0233>, 123, 1)  ; 「ごめんなさい、かずさ…でも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0234>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 124, 1)  ; 「やめろ…やめて…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0236>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0237>, 125, 1)  ; 「………わたしの冒険は、ここまでよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

ARRAY_S RES<0238>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

@VCALL WN(RES<0239>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 126, 1)  ; 「やめろぉぉぉぉぉっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 127, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0242>, 128, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 129, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 210
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 4002
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2006
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 9
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0244>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 130, 1)  ; 「寒…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0246>, 131, 1)  ; 夜間通用口から外に出たとき、\nすでに日はとっぷりと暮れ、\n真冬の冷たい風が容赦なく顔を打ちつけた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 132, 1)  ; 時計を見ると、午後十時をとっくに過ぎている。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0248>, 133, 1)  ; よく考えたら面会時間はとっくに過ぎていたはずなのに、\n病院側も、色々と特例扱いにしてくれたみたいだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0249>, 134, 1)  ; 病院の敷地を抜け、足を踏み入れた峰城大キャンパスは、\n試験期間中の夜ということもあり、人影は見当たらない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 135, 1)  ; それでも、学部棟の窓からいくつか明かりが漏れていて、\n試験だけでなく、卒論発表や修論発表も\n間近に迫っていることを伺わせる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 136, 1)  ; 俺もあの明かりの下で、何度も夜を明かしてたっけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0252>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 4
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2001
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0253>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0254>, 137, 1)  ; 『んじゃさ、朝ご飯食べに行くときに起こして。\nおやすみ～』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0255>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2006
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0256>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 138, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0258>, 139, 1)  ; なんか、いつも妙な芋虫が\n足元に転がってた気がするけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 140, 1)  ; 論文も書かないくせに、\n寝袋持参で研究室に入り浸ってた同期生。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0260>, 141, 1)  ; 四年に進級できたはずなのに、\nそこから徐々に顔を見せなくなり、\n結局、卒業式で顔を合わせることはなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 142, 1)  ; そういえば、就職してから一度だけ、\n偶然、街中で再会したっけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 143, 1)  ; 久しぶりに見たあいつは驚くほど綺麗になっていた…\nいや、多分元から素材は抜群だったんだろう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 144, 1)  ; 近況を聞こうとする俺をはぐらかすかのように、\nいきなり俺の耳をぺろりと舐めて、\nけらけら笑いながら雑踏に消えていきやがった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0264>, 145, 1)  ; そしていつの間にか、ポケットには芝居の券が２枚。\nそれも、俺でも知っている有名劇団のプラチナチケット。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 146, 1)  ; 何を伝えたかったのかもさっぱりわからなかったけど、\nそれも含めて、ちっとも変わってなかったな、あいつ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0266>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 4
PUSH INT 1
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2043
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0267>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0268>, 147, 1)  ; 『………ね、春希？』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4
PUSH INT 22
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0269>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 148, 1)  ; 『あたしはね、\n本当はあんたの想いの深さを知ってるよ？』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0271>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 149, 1)  ; 『物語にしても遜色のない、\nあんたたちの綺麗な想いを知ってるよ？』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4
PUSH INT 8
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0273>)  ; 千晶
PUSH INT 4
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 150, 1)  ; 『ここまで引っ張ったんだ…\nどうせなら、最後まで突っ走って\n綺麗な物語を綺麗なまま完結させて欲しいな』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0275>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2006
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 151, 1)  ; 女であることを感じさせない、\nあの頃の俺にとっては貴重な女友達。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 152, 1)  ; 時々、妙に鋭いことを言いやがって、\n『本当はこいつ、俺のこと何でも知ってるんじゃないか』\nなんて思ったこともあったっけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 153, 1)  ; 和泉…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0279>, 154, 1)  ; 俺は今、お前の言う『想いの深さ』とやらに、\nのたうち回ってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 155, 1)  ; そしてお前の言うように、\n『綺麗な物語を綺麗なまま完結させる』\nなんてことはできそうにない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 156, 1)  ; なぁ、和泉…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 157, 1)  ; あの頃お前は、俺の何を知ってた？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 158, 1)  ; そして今のお前は、\nこれから俺がどうすればいいか、知ってるか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 159, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2008
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 160, 1)  ; 時計を見ると、そろそろ十一時。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 161, 1)  ; 随分ゆっくりと歩いていたせいで、\n…ついでに、懐かしい思い出に浸っていたせいで、\n大学から出るだけで３０分以上もかかってしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 4002
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0287>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 162, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 163, 1)  ; 冷たい風は、相変わらず体を芯から冷やし、\nこの場に立ち止まるのを厭わせる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 164, 1)  ; …けれど、ならどこへ移動しようかとなると、\n途端に自分の思考が鈍っていくのがわかる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 165, 1)  ; 曜子さんは、<R天岩戸の|かずさのいる>場所に心当たりがあると言った。\nそして、そこは俺も十分に予想できる場所だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0292>, 166, 1)  ; けれど、今そこに行く決心はつかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0293>, 167, 1)  ; だって俺はまだ、天照大神の出てきた後の世界を\n自分の中にイメージできていない。\nだから今、その扉の前で踊る訳には行かない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 168, 1)  ; 次にあいつに会うときは、\n全てを決めた後でないとならない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0295>, 169, 1)  ; 二週間の予定だけじゃない。\n日本公演が終わるまでだけじゃない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 170, 1)  ; これからのかずさの人生と、俺の人生…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0297>, 171, 1)  ; どこで生きていくか、誰と生きていくか…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 172, 1)  ; 全て、決心してからでないと、\n会いに行くわけにはいかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0299>, 173, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1036
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0300>, 174, 1)  ; 冬馬曜子の『ピアニストとしての死』は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0301>, 175, 1)  ; 彼女に憧れ、彼女を敵視していたかずさにとって、\n到底受け入れられる事実じゃなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 176, 1)  ; だってあいつは、そこしか見ていなかったはずなんだ。\n冬馬曜子が全盛期のうちに彼女を超える日を。\n直接対決で叩き潰して乗り越える日を。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0303>, 177, 1)  ; 自分の母親を嘲笑い、憎まれ口を叩きあい、\nお互いを称えあい、抱きあって、泣きあう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 178, 1)  ; もしかしたら、その日がピアニストとしての\n最終到達点となっても構わないほどに、\nそこだけ目指してたんだと思う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0305>, 179, 1)  ; けれど、今日…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0306>, 180, 1)  ; かずさの目指した頂は、唐突に消えた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0307>, 181, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2032
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0308>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0309>, 182, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 183, 1)  ; もう、閉店してる。\n相変わらず夜に稼ぐ気のない店だ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0311>, 184, 1)  ; …なんて愚痴をこぼす必要は、本当は全然ない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 185, 1)  ; だって俺は、別に腹が減ってた訳じゃない。\nそれに帰り道の途中だから、無駄足だった訳でもない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0313>, 186, 1)  ; ただ、もしかしたら…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0314>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 3
PUSH INT 21
PUSH INT 18000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2032
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0315>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0316>, 187, 1)  ; 『お店の前で陰気な顔して突っ立ってないでください。\n他のお客さんが逃げちゃいます。\nそんな顔はキッチンの中でしててください…たまには』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0317>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2032
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0318>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0319>, 188, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0320>, 189, 1)  ; なんとなく、誰かが元気づけてくれるんじゃないかって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0321>, 190, 1)  ; 理由もなく、そんな都合のいいことを考えていたのかも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0322>, 191, 1)  ; 友達との卒業旅行の資金稼ぎのため、\n『仕方なく』この店でバイトを始めた後輩。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0323>, 192, 1)  ; 生来の生真面目さと処理能力の高さと物怖じしない態度で、\nいつしか店内の実権を握り、\nなくてはならない存在になるまでに、たったの三か月。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0324>, 193, 1)  ; 結局、大学に進学してからも泣きつかれるまま\nバイトを続け、いつの間にやら数十人の常連を生み出す\n看板娘になっていたっけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0325>, 194, 1)  ; 就職してから二、三度顔を出したことがあるけれど、\n昔と変わらぬ不機嫌な表情でいつもくどくど説教された。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0326>, 195, 1)  ; そういえば、一緒にいた雪菜が、\n一度だけ、帰り際にぽつりとつぶやいた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0327>)  ; 雪菜
PUSH INT 2
PUSH INT 9000
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0328>, 196, 1)  ; 『あの子、まだ春希くんのこと好きだよ、きっと』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2032
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0329>, 197, 1)  ; けれどそれは、見込み違いもいいところで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0330>, 198, 1)  ; ただ俺は、彼女にとって駄目な男だっただけで。\nけどだからこそ、彼女は俺を、絶対に放っておけなくて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0331>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 3
PUSH INT 21
PUSH INT 14000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2057
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0332>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0333>, 199, 1)  ; 『先輩のことを知るためです。\n自分にとって、わからない人でいて欲しくないから』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0334>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 200, 1)  ; 『わたしの近くにいる以上、\nそういう態度は改めてもらわないと困ります』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0336>)  ; 小春
PUSH INT 3
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0337>, 201, 1)  ; 『気になるからです。\n先輩に興味を持ってしまうからです！』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0338>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2032
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0339>, 202, 1)  ; そんな、誰彼構わぬ…\nいや、相手が弱っていればいるほど、\n深く介入していこうとする、困った後輩。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0340>, 203, 1)  ; …あいつなら、\n目の前にかずさがいたらどうするだろうか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0341>, 204, 1)  ; 何もかも信じられずに、\n大切なものを失ってしまった人を目の前にして、\n赤の他人とはいえ、果たして放っておけるだろうか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0342>, 205, 1)  ; 杉浦小春…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0343>, 206, 1)  ; 君なら、今のかずさと出会ったら、何を思う？\n俺に似ているって、自他共に認める君だったら…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0344>, 207, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0345>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2085
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0346>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0347>, 208, 1)  ; 「あの子は、ピアノを愛してる。\nけど、わたしみたいに人生そのものじゃなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0348>, 209, 1)  ; 曜子さんに言わせれば…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0349>, 210, 1)  ; あいつは、ピアノがあれば生きていけるような、\n純粋な音楽家じゃなかったらしかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0350>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0351>, 211, 1)  ; 「あの子は、ピアノを愛してる。\nだって、弾いている間だけは、\n愛する人と触れ合えたから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0352>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0353>, 212, 1)  ; 「それって…曜子さんの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 105
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0354>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0355>, 213, 1)  ; 「ま、確かにわたしも、\nあの子の世界の中の数少ない住人ではあったでしょうね。\nけど…もちろん今の喩えはわたしのことじゃないわよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0356>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0357>, 214, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0358>, 215, 1)  ; 現実は、どこまでもシビアで、\nそして、俺に甘すぎて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0359>, 216, 1)  ; だから、おれの煮え切らない態度に、\n曜子さんは苛立ちを隠さなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0360>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0361>, 217, 1)  ; 「そうやって、\nピアノを弾いている間だけ触れ合える人たちがいたから、\nあの子は毎日、飽きもせずに弾きつづけていただけ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0362>, 218, 1)  ; 現実に存在するけど、空想でしか会えない人。\nそして、自分の側にいて、自分を導いてくれる人。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0363>, 219, 1)  ; …空想と現実を含めても、ほんの数人だけが、\nあいつの世界の全てだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0364>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0365>, 220, 1)  ; 「けど厄介なことに、\nあの子はわたしほどピアノが好きじゃないくせに、\nわたしより才能だけはありやがったのよね…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0366>, 221, 1)  ; そんな、たった数人と触れ合うためだけに\n毎日休まず弾いていたピアノは…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0367>, 222, 1)  ; 皮肉にも、あいつの類稀なる血と才能のせいで\n世界にまで花開いてしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0368>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0369>, 223, 1)  ; 「そんなあの子が、\n自分の道を、自分で見つけられるか…\n実はわたしにも、自信がないのよね…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0370>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0371>, 224, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0372>, 225, 1)  ; だから、だから…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0373>, 226, 1)  ; あいつの手元に、ピアノ“だけ”が残ったとしても…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0374>, 227, 1)  ; その音の先に、触れ合う相手がいなければ、\nそれはもしかして、何の意義ももたらさないのかも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

ARRAY_S RES<0375>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

@VCALL SetMessageE(RES<0376>, 228, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2057
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0377>)  ; 駅アナウンス
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0378>, 229, 1)  ; 「二番線、本日最終電車になります。\nお乗り遅れのないようお願いします」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2306
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0379>)  ; 駅アナウンス
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0380>, 230, 1)  ; 「ドアが閉まります。ご注意下さい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 8205
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 2
PUSH INT 8186
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2145
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 2500
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0381>, 231, 1)  ; かずさは、これからどうなるんだろう…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0382>, 232, 1)  ; あいつのことを、\n『冬馬曜子の娘で世界に通用する若手ピアニスト』\nとしか知らない人たちは、多分あいつにこう言うだろう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0383>, 233, 1)  ; 『母の進んできた道を引き継げ』と。\n『母と同じように、世界へと羽ばたけ』と。\n『母はもう、頑張りたくても頑張れないんだぞ』と。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0384>, 234, 1)  ; そして、そういう人たちに対して俺は、\n『あいつのこと何も知らないくせに勝手なこと言うな』と\n激昂してしまうに違いない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0385>, 235, 1)  ; そんな簡単な話じゃない。\nあいつがそんな決断、できるわけないじゃないか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0386>, 236, 1)  ; だってあいつは、実はすごく弱い奴で、\nとんでもない甘ちゃんで、何の覚悟もなくて、\n普通の人の普通の現実を生きてない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0387>, 237, 1)  ; しかも、そんな普通じゃない現実の中ですら、その才能と、\n夢想混じりの苦しみを伴わない努力だけで上がってきた、\n正真正銘、純粋培養の天才なんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 60
CALL SES
OPERATOR POP

@VCALL WN(RES<0388>)  ; 駅アナウンス
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0389>, 238, 1)  ; 「まもなく、一番線御宿行きが参ります。\n白線の内側までお下がりください」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8192
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0390>, 239, 1)  ; そして今…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0391>, 240, 1)  ; あいつは、積み上げてきたものを全て失って、\n根元からぽきりと折れてしまったんだから。\n…誰でもない、俺のせいで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0392>, 241, 1)  ; それでも、決断しろって言うのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0393>, 242, 1)  ; コンサートを予定通り開催するかしないのか。\nこの先、どうやって生きていくつもりなのか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0394>, 243, 1)  ; 曜子さんの望むまま日本で一緒に暮らすのか、\n曜子さんを説得して元通りウィーンで一緒に暮らすのか。\nそれとも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0395>, 244, 1)  ; 曜子さんの進むはずだった道を引き継いで、\nたくさんの人たちの上に立ち、一緒に世界に挑むのか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0396>, 245, 1)  ; 曜子さんの進むはずだった道を引き継いで、\nけれど誰の力も借りず、たった一人で世界に挑むのか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0397>, 246, 1)  ; それとも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 8204
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 8606
PUSH INT 30
PUSH INT 1
PUSH INT 50
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0398>, 247, 1)  ; そして、諦めろって言うのか…？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 248, 1)  ; お前のことが好きだった…\nお前が好きでいてくれた俺は、\nもう、今の時間にはいないんだって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0400>, 249, 1)  ; 想いが叶わなかったという現実と、\nそろそろ、向かい合おうって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 250, 1)  ; お互いに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 60
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 2057
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2306
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0402>)  ; 駅アナウンス
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0403>, 251, 1)  ; 「二番線、発車いたします。\nドアが閉まります。ご注意下さい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 8205
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 8203
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1024
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 30
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 30
PUSH INT 10
PUSH INT 1000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 240
CALL SES
OPERATOR POP

PUSH INT 0
PUSH INT 3104
PUSH INT 240
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0404>, 252, 1)  ; それとも、それともさ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0405>, 253, 1)  ; これは本当に、\n最悪のたとえ話なんだけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0406>, 254, 1)  ; あいつが、母親も捨て、ピアノも捨て。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0407>, 255, 1)  ; 今まで生きてきた世界に背を向けて、\n自分の望む、小さな、新しい世界に包まれて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0408>, 256, 1)  ; そうして、周囲の期待や家族の思いを全て捨て去り、\n弱い心のまま、強い力を振り回し、\n普通の世界を壊してしまうという未来は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0409>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0410>, 257, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0411>, 258, 1)  ; なんて、馬鹿馬鹿しい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0412>, 259, 1)  ; できるわけがない。\nそんな恐ろしい選択肢、あいつは絶対選べない。\n泣きながら、その場に立ち尽くしてしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0413>, 260, 1)  ; だから、そんなたとえ話、あり得ない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0414>, 261, 1)  ; つまりそれは、あいつ一人じゃ為し得ない、\nあいつには、物理的に選べない未来。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0415>, 262, 1)  ; …誰かの、本気の後押しがない限り。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0416>, 263, 1)  ; だったら…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0417>, 264, 1)  ; あいつが決められないのなら、\nその誰かが、あいつの人生を決めるのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0418>, 265, 1)  ; 誰かが、あいつに『～を選べ』って言うのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0419>, 266, 1)  ; でもそれって、\nそいつ自身の人生を決断するってことでも…\nあるんじゃないのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0420>, 267, 1)  ; それは僭越なのかもしれない。\n人の人生を弄ぶ、悪魔の所業なのかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0421>, 268, 1)  ; じゃあ、だからって、\nその誰かは、何もしなくていいのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0422>, 269, 1)  ; かずさを…\n守らなくても、いいって言うのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0423>, 270, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3012
PUSH INT 90
PUSH INT 1
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2026
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2013
PUSH INT 2
PUSH INT 10
PUSH INT -1
PUSH INT 0
CALL Calender
OPERATOR POP

@VCALL SetMessageE(RES<0424>, 271, 1)  ; いつの間にか、日付が変わってた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0425>, 272, 1)  ; それでも編集部の窓からは、\n相変わらず明かりが煌々と漏れている。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0426>, 273, 1)  ; けれどそこに、\n俺が今、一番頼りたいと思ってる人はいない。\n…もう、二年も前から。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0427>, 274, 1)  ; 俺が社会に出る前に、そこで生きていくことの何たるかを\n徹底的に叩き込んでくれた、社会人としての俺の大恩人。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 90
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0428>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 5
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2027
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0429>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0430>, 275, 1)  ; 『私に任せておけ。\n編集長が総没と言ったって、\n発売日にはお前の記事がちゃんと載ってるはずだ』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0431>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2026
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0432>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0433>, 276, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0434>, 277, 1)  ; 麻理さん…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0435>, 278, 1)  ; 俺、頑張ってきたんです。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0436>, 279, 1)  ; 少しでもあなたに追いつきたくて一生懸命働いてきました。\nまだ一年目だけど、ほんのちょっとだけ自信もつきました。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0437>, 280, 1)  ; おかげで、人との嬉しい繋がりが…\n社会との大切なしがらみが、たくさん作れました。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0438>, 281, 1)  ; 麻理さん…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0439>, 282, 1)  ; そんなあなたなら、今、何を選びますか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0440>, 283, 1)  ; それでも仕事ですか？\n人との繋がりですか？\n社会とのしがらみですか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0441>, 284, 1)  ; 俺には、わからなくなってきてしまいました。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0442>, 285, 1)  ; だから、帰ってきてくれませんか？\nまた、俺の上司に戻ってきてくれませんか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0443>, 286, 1)  ; そしてまた、俺を導いてくれませんか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0444>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 5
PUSH INT 1
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1023
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0445>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0446>, 287, 1)  ; 『北原って結構ナイーブだよな。\n傷つきやすくて、自分で自分を責めてばかりで』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5
PUSH INT 4
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0447>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0448>, 288, 1)  ; 『だから余計落ち込むのか？\n誰も、自分を叱ってくれないから。\n…叱った後、許してくれないから』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0449>)  ; 麻理
PUSH INT 5
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 140
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0450>, 289, 1)  ; 『じゃあ…私はお前を責めないよ。\nだから、許しもしない』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0451>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2026
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0452>, 290, 1)  ; …そうでしたね。\nあの時、約束したんですよね。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0453>, 291, 1)  ; 自分で決めるって。人に委ねないって。\n人の意見におもねることもしないって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0454>, 292, 1)  ; …そして、許しを請わないって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0455>, 293, 1)  ; たとえあなたの…\n俺の周りの、誰の意にすら添わない結果になったとしても。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0456>, 294, 1)  ; 俺が決断するんだって。\n俺が全ての責任を負うんだって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0457>, 295, 1)  ; 俺が、その“誰か”になるんだって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0458>, 296, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2911
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1033
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0459>, 297, 1)  ; 終電もなくなった御宿の街。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0460>, 298, 1)  ; 俺は、温かい場所を探すこともなく、\nあてもなく道端のガードレールに腰掛けた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0461>, 299, 1)  ; 冷たい風に晒されて、暖房は缶コーヒーだけ。\n空を見上げても、分厚い雲は星一つ見せてくれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0462>, 300, 1)  ; そんな、人が佇むには辛すぎる夜…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0463>, 301, 1)  ; なのに俺の脳裏には、\n今まで触れあってきた沢山の人たちの暖かい表情が、\n浮かんでは消えていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0464>, 302, 1)  ; 武也、依緒、柳原さん…\n大学時代から、付属時代から続いている\n数多くの同級生、先輩、後輩。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0465>, 303, 1)  ; 浜田さん、木崎さん、鈴木さん、松岡さん、\nそれとデスクに編集長。\n今、俺がいるべき場所の先輩、上司たち。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0466>, 304, 1)  ; それ以外にも、様々な仕事で関わった人たち、\nプライベートで知り合った人たち、\n年齢も性別も様々な、俺が名前を知っている人たち。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0467>, 305, 1)  ; そして…\n今の俺にとって、本当の家族よりも家族同然の人たち。\n小木曽のお父さん、お母さん、孝宏君。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0468>, 306, 1)  ; それから…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8061
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL SetMessageE(RES<0469>, 307, 1)  ; 今まで生きてきた人生で、俺が一番大切にして、\n俺を一番大切にしてくれたひと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0470>, 308, 1)  ; トラブルを起こすことも、\n相手の態度に腹を立てることも、\n自分が相手を怒らせることももちろんあったけれど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0471>, 309, 1)  ; 全てが全てというわけには流石にいかないけど、\n話し合い、本音をぶつけあい、やがて仲直りして、\nいつしかまた、もとの暖かい表情に戻っていった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 2143
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 100
PUSH INT 0
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
OPERATOR NEGATE
PUSH INT 0
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0472>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 141
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0473>, 310, 1)  ; 「…ぬる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0474>, 311, 1)  ; だから、あいつも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0475>, 312, 1)  ; いつか、そんな皆と同じように、\nごく自然に他人に暖かい顔を見せられるようになる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0476>, 313, 1)  ; たとえ辛くても、やせ我慢でも、\nきっと笑って生きていけるようになる。\n必ず…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0477>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 142
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0478>, 314, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0479>, 315, 1)  ; 必ずって何％だ？\n１００％か？\n絶対か？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0480>, 316, 1)  ; あいつが、たくさんの人と繋がって、\nたくさんの人に笑顔を振りまいて、\nたくさんの人を幸せにして…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0481>, 317, 1)  ; その結果、たくさんの人に幸せにしてもらう？\n…それってどんなファンタジーだよ？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0482>, 318, 1)  ; 俺は、そんな夢物語を信じられるのか？\n信じ込むことが許されるのか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0483>, 319, 1)  ; 俺には、数え切れない人たちとの思い出がある。\n無数の、社会との繋がりがある。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0484>, 320, 1)  ; それらは過去だけじゃなく、\n今だって毎日新しい出会いを繰り返し、\nその出会いがまた新しい社会との繋がりを生み出している。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0485>, 321, 1)  ; かずさのそれとは似ても似つかない小さな世界だけど、\nその世界の隅々まで繋がろうと手を伸ばしてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0486>, 322, 1)  ; それは、かずさのそれとは似ても似つかない、\n外に向かって開かれた世界。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0487>, 323, 1)  ; そんな、全然違う世界に住む俺が、\n『あいつはきっと大丈夫だ』なんて…\nそんなふうに、わかったように言えるはずが…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0488>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 143
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0489>, 324, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 6
PUSH INT 3
PUSH INT 7
PUSH INT 32
PUSH INT 2
PUSH INT 1
PUSH INT 5
CALL SetWeather2
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 15
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0490>, 325, 1)  ; そうやって、いつまでも堂々巡りを繰り返し、\n今日という日をやり過ごそうとしていた俺を…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0491>, 326, 1)  ; 神様は、許してはくれなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 7
PUSH INT 96
PUSH INT -1000
PUSH INT -1000
CALL ChangeWeather
OPERATOR POP

@VCALL SetMessageE(RES<0492>, 327, 1)  ; とうとう、降ってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0493>, 328, 1)  ; ずっと三人でいることを誓い合った日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0494>, 329, 1)  ; 三人から二人が抜け出してしまった日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0495>, 330, 1)  ; 二人から一人が去り、\n一人と一人が残されてしまった日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0496>, 331, 1)  ; 一人と一人が、もう一度二人になろうとして、\nけれどどうしても許しあうことができなかった日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0497>, 332, 1)  ; 一人と一人が、何度もお互いを傷つけあった末に、\n今度こそ、心の底から二人になろうと誓った日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0498>, 333, 1)  ; ………二人が、再び三人になった日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0499>, 334, 1)  ; そして今日…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0500>, 335, 1)  ; ああ、そうなんだ。\nやっぱり、今日なんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0501>, 336, 1)  ; 今日が、俺の人生の…\nそして、三人の分岐点なんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0502>, 337, 1)  ; 今日、俺がする決断は、\n俺の周りの沢山の人を巻き込むことになるんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0503>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 1
PUSH INT 125
PUSH INT 4000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1033
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0504>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 144
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0505>, 338, 1)  ; 『あたしの前から先に消えたのはお前だろ！？\n勝手に手の届かないとこに行ったのはお前だろ！』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0506>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 145
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0507>, 339, 1)  ; 『あたしがつまらない男を好きになって何が悪い！』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0508>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0509>, 340, 1)  ; だって、あの時からずっと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0510>, 341, 1)  ; 俺の運命が転がり始めるのは、必ず冬だった。\nその日には、雪が降っていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0511>, 342, 1)  ; いつも、降っていたんだ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0512>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 146
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0513>, 343, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 6
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 3
PUSH INT 7
PUSH INT 120
PUSH INT 2
PUSH INT 1
PUSH INT 5
CALL SetWeather2
OPERATOR POP

PUSH INT 120
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0514>, 344, 1)  ; 胸が、痛い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0515>, 345, 1)  ; 全身に染み入る冬の寒さよりも、雪の冷たさよりも、\nもっと辛く苦しいものが、濁流のように押し寄せてくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0516>, 346, 1)  ; もう、逃げられないって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0517>, 347, 1)  ; 二つのうちの一つを選ぶしかないって。\n…それも、一度選んだはずの選択肢を、もう一度。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0518>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 147
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0519>, 348, 1)  ; 「っ…ぅ、く…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0520>, 349, 1)  ; 雪が、滲む。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0521>, 350, 1)  ; 体も心も掻き毟らんばかりの痛みが、\n俺の目頭までも襲ってきたから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0522>, 351, 1)  ; どうして…\nどうして、かつて結論を出したはずのことで、\nこんなに迷わなければならないんだよ、俺は。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0523>, 352, 1)  ; 何が正しいのか、わかってる。\n正しくて、尊くて、嬉しいってわかってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0524>, 353, 1)  ; それなのに俺は、迷う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0525>, 354, 1)  ; だって、これが最後の決断だから…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0526>, 355, 1)  ; かずさは決められないから、\nだから、俺が決める。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0527>, 356, 1)  ; ただ一つだけの、俺の気持ちに従う。\n…世界で一番大切な人を、選ぶ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0528>, 357, 1)  ; 俺は、誰を幸せにしたいんだろう。\n誰となら、間違えても後悔しないんだろう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0529>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 148
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0530>, 358, 1)  ; 「～～～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0531>, 359, 1)  ; これが最後…\nもう二度と引き返せない、最後の決断。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0532>, 360, 1)  ; 考えよう…\nこの雪が、終わるまで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0533>, 361, 1)  ; だから、できれば…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0534>, 362, 1)  ; せめて、朝まで降り続いてくれ、雪よ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 300
CALL MS
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 300
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 210
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0535>  ; CATCH3
PUSH INT 1
CALL SCall
OPERATOR POP

STATEMENT IF #LABEL_13 #LABEL_14
ARRAY_G 27
PUSH INT 1
OPERATOR EQ
STATEMENT JMP_IF
OPERATOR POP
ARRAY_S RES<0536>  ; 3201
PUSH INT 0
CALL SLoad
OPERATOR POP

#LABEL_13
STATEMENT ELSE
ARRAY_S RES<0537>  ; 3101
PUSH INT 0
CALL SLoad
OPERATOR POP

#LABEL_14
STATEMENT HALT
