!RESOURCE "3101.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3101
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2013
PUSH INT 2
PUSH INT 9
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 0
PUSH INT 8401
PUSH INT 0
PUSH INT 0
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 0
PUSH INT 8402
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 13
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2110
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0004>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「…本当にそんな電話があったんですね？\nこちらの部屋のお客様から」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「だからこんなに急いでるんじゃないですか。\n一刻を争うんです！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0008>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「しかし…\nあなたがお客様の関係者であるということが\nはっきり証明できた訳ではないので…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0010>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「事務所に確認してくれって言ったでしょ。\nそれで連絡はついたんですか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0012>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「いえ、そういうわけにも…\n何しろもう、午前二時を過ぎてますし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0014>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 5, 1)  ; 「一刻を争うって言ってるじゃないですか！\n電話の内容話したでしょ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0016>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 6, 1)  ; 「事実なら確かに大事ですが…\nしかし先日も新聞社の方が関係者を騙って、\nこちらのお部屋まで乗り込んできたことがありまして」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 7, 1)  ; 「ああもう…いいです、俺が勝手にやります！\nあなたは警察でも何でも呼んでてください。\nもし嘘だったらそのまま俺を突き出せばいいでしょ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 8, 1)  ; 「っ…わかりました。\nしかし、まずは私どもの方でお伺いさせていただきます。\nそれでよろしいですね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0022>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 9, 1)  ; 「お願いします。\nかずさを…彼女を助けてください！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1900
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0024>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 10, 1)  ; 「…冬馬様。\n夜分遅く申し訳ありません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0026>, 11, 1)  ; 俺のあまりの剣幕に、\nやっと事の重大さを悟り始めた客室係が、\n一つ咳払いをすると、ドアを軽く叩く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1900
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0027>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0028>, 12, 1)  ; 「冬馬様、冬馬様…\nもしお目覚めになられましたら、大変お手数ですが、\nこちらをお開けいただけないでしょうか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0029>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0030>, 13, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 14, 1)  ; けれど、彼のノックも声も、\nスイートルームの分厚いドアを超えて部屋に響くには、\nいささか以上に頼りない音量のままで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0032>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 15, 1)  ; 「………お休みのようですね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0034>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 16, 1)  ; 「だから反応がないって言ってるでしょ！\nフロントからの電話だって\n繋がらなかったじゃないですか！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0036>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 17, 1)  ; 「そ、それは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0038>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 18, 1)  ; 「かずさ！　かずさ！\nお願いだから返事してくれ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0040>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 19, 1)  ; 「ちょ、ちょっと、おやめください。\n他のお客様の迷惑になります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0042>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 20, 1)  ; 「そんなこと言ってる場合じゃないんだ！\nあいつに何かあったらどうしてくれるんですか！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0044>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 21, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 22, 1)  ; 深夜のフロントに飛び込んできた俺を、\n最初、ホテルの従業員たちは\n強い警戒とともに出迎えた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 23, 1)  ; 俺が冬馬かずさの関係者であることを告げ、\nすぐに彼女の滞在する部屋の鍵を開けるよう迫ると、\nその警戒レベルはますます上がっていった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0048>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 24, 1)  ; 「かずさ！　無事か？\nいるんだろ？　おい、しっかりしてくれ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0050>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 25, 1)  ; 「ほ、本当に、その…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0052>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 26, 1)  ; 「もし取り返しのつかないことになったら、\n俺、絶対に許さないからな…\nあんたらの規則ごと呪ってやる！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 15
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1012
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0054>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 27, 1)  ; 「………っ、\n冬馬様、冬馬様！\nご無事ですか！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 28, 1)  ; 規則を盾に、電話取り次ぎ以上をしてくれないフロントと\n不毛な交渉をすること十数分…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 29, 1)  ; 彼女が俺の留守電に『さよなら』とメッセージを残した後、\n一切の連絡を絶ったことを告げると、\nようやく渋々と協力を申し出てくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 30, 1)  ; それでもまだ、９対１くらいで疑惑の方が強かった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0059>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 31, 1)  ; 「くそ…くそっ！\nどうすればいい…どうすりゃいいんだよっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0061>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 32, 1)  ; 「おかしい…ですね。\nこれだけ騒いでいて反応がないというのは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0063>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 33, 1)  ; 「だからさっきから言ってんじゃん！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0065>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 34, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0067>, 35, 1)  ; 彼らは、部屋の前までついてきてはくれたものの、\n実力行使に出ることはなく、あくまでも規則通り、\nお客様がドアを開けてくれるのを待っている…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 36, 1)  ; けど、それも当然だ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 37, 1)  ; 彼らにとって大事なのは、宿泊客の安全と快適であって、\nこんな、どこの馬の骨ともわからない男の\n言いがかりじみた懇願なんて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0070>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 38, 1)  ; 「くそ…やっぱり警察だ。いや救急車！\nすいません、フロントから１１９に…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0072>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 39, 1)  ; 「………その前にドアを開けてみましょう。\nこうなったら仕方ありません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0074>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 40, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 41, 1)  ; さっきまで、規則と宿泊客しかなかったホテルマンの瞳に、\n俺の必死の形相が映り込んでいた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0077>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 42, 1)  ; 「但し、まずは私が中に入らせていただきます。\nお客様は、許可なしに勝手に入ってきたりしないように」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0079>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 43, 1)  ; 「あ、あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0081>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0082>, 44, 1)  ; 「それが守れないようでしたら、\nこちらも規則を守らせていただきますが…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 45, 1)  ; 彼にも、俺と同じ緊張がうつってしまっていたけれど、\nけれどその表情からは、さっきまでの疑惑の色は消え、\nほんの少しだけど、俺に対する前向きな色が見て取れた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0084>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 46, 1)  ; 「お願いします…っ、\nかずさのこと！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 47, 1)  ; ようやく、俺の悲痛な叫びが、\n彼の『公』以外の部分にも届いたのかもしれなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0087>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0088>, 48, 1)  ; 「それでは…\n冬馬様、大変申し訳ありませんが、\n緊急事態につき、失礼させていただきます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0089>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 49, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 50, 1)  ; と、彼のポケットから部屋のキーが取り出され、\nそして、かずさの部屋のドアの鍵穴へと…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

@VCALL WN(RES<0092>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 51, 1)  ; 「え…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 52, 1)  ; 差し込まれる直前、\nその鍵穴が、ゆっくりと鍵を避けるように、\n奥へとずれていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 53, 1)  ; いや、正確には…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0096>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 54, 1)  ; 「ご愁傷様…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 55, 1)  ; 扉が、開かれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0099>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 56, 1)  ; 「そいつ、真に迫ってただろ？\nけど…大嘘つきのマスコミなんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0101>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 57, 1)  ; 「え………？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0103>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0104>, 58, 1)  ; 「かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 59, 1)  ; そして、その扉の奥からは、\n一日ぶりの、懐かしい顔…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0106>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 60, 1)  ; 「慌ててる振りしてるけど、\n全部計算尽くなんだ。\n最初から、あんたを利用する気だったんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0108>)  ; 客室係
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 61, 1)  ; 「え…ええ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0110>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 62, 1)  ; 「本当に心配してたんだよ…\n良かった、かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 63, 1)  ; ただ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 64, 1)  ; 『さよなら』なんて意味深な電話は、\nもちろん、かかってきてないけどな。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 65, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 4002
PUSH INT 30
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 2000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2071
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0115>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 66, 1)  ; 「さむ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 67, 1)  ; 雪は、既にやんでいた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 68, 1)  ; 積もることもなく、道路をほんの少しだけ濡らし、\nそして、風だけは強烈に冷やしつつ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 69, 1)  ; 空は、少しだけ雲が切れてきていて、\n夜が明ければきっと、まぶしい朝陽が照らし…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0120>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 70, 1)  ; 「なんで来たんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0122>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 71, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0124>, 72, 1)  ; 手の中に吹き込んだ息が白く滞り、\nけれどすぐに夜の闇に消えていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0125>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0126>, 73, 1)  ; 「こんな時間に、あんな大騒ぎしやがって…\n本当に警察に連れて行かれても文句言えないぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 74, 1)  ; あの後、ホテルのスタッフは、\n俺の深夜の非常識を厳しく追及しようにも、\nかずさの手前、顔を真っ赤にして困惑していた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0128>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 75, 1)  ; 「すぐに会いたかったから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 76, 1)  ; 結局、ホテル側が最終的に矛を収めたのは、\n『こいつ、あたしの連れだから』という、\nかずさのつまらなそうな一言で…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0131>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 77, 1)  ; 「っ…出てってからまる一日経ってる。\nちっともすぐじゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 78, 1)  ; 完全にとばっちりを受けた件の客室係は、\nよくある男女の痴話喧嘩に巻き込まれたと、\n今ごろフロントでため息をついているに違いない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 79, 1)  ; 「そうだな…\nごめん、遅くなって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 111
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0136>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0137>, 80, 1)  ; 「馬鹿野郎…っ、\n誰も待ってなんか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 81, 1)  ; …問題は、\nその認識があながち間違いじゃないってことで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 82, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 8244
PUSH INT 90
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 10
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8249
PUSH INT 90
PUSH INT 1
PUSH INT 60
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 90
PUSH INT 0
PUSH INT 10
PUSH INT 30
OPERATOR NEGATE
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 10
PUSH INT 20
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 4002
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0140>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 83, 1)  ; 「どこ、行くんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0142>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 84, 1)  ; 「別に…行くあてなんか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0144>, 85, 1)  ; 冷たい風の吹く深夜の街を、\nかずさは俺について歩く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0145>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 86, 1)  ; 「何だよ、それ…\nこんな寒空の中、人を連れ回しておいて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 87, 1)  ; 夜中に呼び出されて不機嫌なはずなのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 88, 1)  ; あまりにも色々なことがあり過ぎて、\n心が掻き乱されているはずなのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0149>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0150>, 89, 1)  ; 「なら、ファミレスにでも入るか？\nそこで話そうか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0151>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 90, 1)  ; 「別に…話すことなんかない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0153>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 91, 1)  ; 「そう、か…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0155>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 92, 1)  ; 「…だから、もっとゆっくり歩け。\nついていく方の身にもなれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0157>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 93, 1)  ; 「………すまん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 94, 1)  ; それでもかずさは、俺の後をついてくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0160>, 95, 1)  ; 離れないよう、追い越さないよう、\n必死で歩調を合わせて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0161>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 96, 1)  ; 「でも寒い…\nやっぱり、寒い」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0163>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 97, 1)  ; 「こっち、来い。\n少しでも風除けになるだろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0165>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 98, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 99, 1)  ; ついには、俺の隣にぴったりと身体を寄せて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0168>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 100, 1)  ; 「さっきまで雪だったんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0170>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 101, 1)  ; 「ん…ホテルの窓から見てた」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0172>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 102, 1)  ; 「やっぱ起きてたんじゃないかよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0174>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 103, 1)  ; 「それが…どうしたってんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 104, 1)  ; だって今のかずさには、俺しかいないから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 105, 1)  ; どれだけ憎まれ口を叩いたって、\nどれだけ突き放そうとしたって、\n心の底から俺のことを求めてしまっているから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 106, 1)  ; そんな痛い決め付けが\nもしも単なる俺の思い上がりだったなら、\nどれだけ、お互いにとって幸せだったことか…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 60
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 60
CALL SES
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3012
PUSH INT 60
PUSH INT 1
PUSH INT 100
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2061
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0179>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 107, 1)  ; 「いつから知ってたんだ？\n母さんのこと」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0181>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 108, 1)  ; 「ほんの最近だよ…一週間前」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0183>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 109, 1)  ; 「どうして母さんはお前に話したんだよ。\nあたしにも秘密にしてたことを、何で？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0185>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 110, 1)  ; 「それは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0187>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0188>, 111, 1)  ; 「お前の方があたしより信じられるってのか？\nあたしよりも、頼りになるっていうのか…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0189>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0190>, 112, 1)  ; 「俺が強引に聞き出したんだよ。\nさっきみたいに、無茶な手を使って押しかけて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0191>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0192>, 113, 1)  ; 「だったら、どうしてお前は黙ってた…\n母さんから聞いたことを秘密にしてたんだよ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0193>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0194>, 114, 1)  ; 「お前がこうなるってわかってたからだよ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0195>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0196>, 115, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 116, 1)  ; だから案の定、\nかずさはその俺の指摘に、俯いて黙り込んでしまう。\n無言のまま、はっきり肯定してしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0198>, 117, 1)  ; 曜子さんにすがることができなくなってしまった今、\nもう、自分で解決法を見出せずにいることを。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 118, 1)  ; すがりつこうと伸ばした手を宙に浮かせたまま、\nずっと道に迷って泣いていることを。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0200>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 119, 1)  ; 「だから…\nだからここ最近、ずっと優しかったんだな。\nあんなに、わざとらしさ丸出しで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0202>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 120, 1)  ; 「嫌だったか、そういうの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0204>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 121, 1)  ; 「そんなことあるわけないだろ…\nお前に優しくされて、嬉しくないあたしなんかいない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0206>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 122, 1)  ; 「それもなんだかな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0208>, 123, 1)  ; …伸ばした手が、ずっと俺を捜していることを。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0209>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0210>, 124, 1)  ; 「けれど、もっと自然にして欲しかった。\n裏があるって気づかせて欲しくなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0211>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0212>, 125, 1)  ; 「お前の求める俺は難しいな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 126, 1)  ; 俺はもう、かずさのことで、\n自分に都合のいい妄想に浸れなくなってしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0214>, 127, 1)  ; 『かずさが五年前からずっと本気で俺のことを想ってる』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 128, 1)  ; そんな、俺にとって夢みたいな、\n一番ありえないはずの妄想が…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0216>, 129, 1)  ; あろうことか当の本人に、\nありえないくらい強く肯定されてしまったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 110
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0217>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0218>, 130, 1)  ; 「本当はあたしのこと\n鬱陶しくてしょうがなかったんだろ？\nでも母さんのこと隠すためには一緒にいるしかなくて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0219>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0220>, 131, 1)  ; 「だから、そんな訳ないって何度言わせれば…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0221>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0222>, 132, 1)  ; 「本当のこと知ったら、\nあたしが自殺でもするんじゃないかって、\nそんなこと、考えてたんだろ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0223>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 133, 1)  ; 「思ってない。\nお前はそこまで他人を思いやれない奴じゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0225>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 134, 1)  ; 「ぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0227>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 135, 1)  ; 「…でも、自分一人で立ち直れるとも思ってない。\nお前、そんな勇気ないもんな。\nそこまで強くないもんな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0229>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 136, 1)  ; 「な、んだよ、それはぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0231>, 137, 1)  ; まさに今のかずさは、\n俺の想像通りの迷い子だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 138, 1)  ; 前に進むのも、諦めるのも怖くて、\nずっとその場に立ち止まってて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0233>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 139, 1)  ; 「…随分とわかったようなこと言うじゃないか。\nまるであたしの保護者気取りだな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0235>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 140, 1)  ; 「………ああ、気取ってるよ。\n俺、お前を護りたいって思ってる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 203
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0237>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 141, 1)  ; 「そんな…そんな義務感はごめんだ！\n愛してもくれない男に護られるなんて…っ、\nそんなの、いくらあたしだってプライドが許さない！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0239>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 142, 1)  ; 「ならしゃんとしろよ！\n一人でも生きていけるって、\n俺や曜子さんに証明してみせろよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0241>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0242>, 143, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0243>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0244>, 144, 1)  ; 「できないだろお前？\nそういうの全然できないんだろ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0245>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0246>, 145, 1)  ; 「そ…んなことない…\nだってあたし、一人だった…\n五年前までは、ずっと一人で生きてきた…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0247>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0248>, 146, 1)  ; 「あんなの一人でもなんでもない。\nお前が勝手にそう思い込んでただけだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0249>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 147, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0251>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0252>, 148, 1)  ; 「曜子さんのお金と、曜子さんの心遣いで護られて、\n好き勝手にすくすく育ってきたんじゃないか。\n…逆恨みしながら」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 104
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0253>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0254>, 149, 1)  ; 「それが…それがなんだっていうんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 150, 1)  ; もしもこのまま誰も手を差し伸べなかったら、\n立ち止まったまま、ゆっくりと朽ちていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0256>, 151, 1)  ; 自分で自分に手を下すことはなくても、\n結果として、そうなってしまってもおかしくない、\nそんな、弱すぎる奴。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3012
PUSH INT 60
PUSH INT 1
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1033
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0257>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0258>, 152, 1)  ; 「お前は昔からそうだ。\nわがままで、だらしなくて、人として間違ってて…\n見てて、イライラする」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0259>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0260>, 153, 1)  ; 「春希…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0261>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 154, 1)  ; 「しかも悪い女だ。性格も、態度も、そして諦めも。\nお前のいいところなんて\n見た目とピアノの腕だけじゃないか！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 131
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0263>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0264>, 155, 1)  ; 「そんな…春希ぃ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 156, 1)  ; だから、俺がほんの少し突き放しただけで、\nあっという間に俯き、声を震わせる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0266>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0267>, 157, 1)  ; 「お前、見た目キンキラキンだけど中身は腐ってる。\nいくら才能だけ認められても、社会人としては失格だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0268>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 158, 1)  ; 「やめろよ…\nやめてよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 159, 1)  ; さっきまでの弱々しい虚栄すらもう張れず、\nショックも涙も隠すことができず。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0271>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 160, 1)  ; 「そんな最低なくせに、\n俺なんかを好きだなんて最低の上塗りだよ。\nそのせいでどれだけ俺が苦しめられたかわかってんのか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0273>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 161, 1)  ; 「そんな酷いこと言わないでくれ…\nあたしだって…そんなことわかってるよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 162, 1)  ; それどころか、その涙をいっぱいに溜めた瞳で、\n捨て犬のように、すがるように俺を見上げてくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0276>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 163, 1)  ; 「だから、お前みたいな奴は世界に弾かれて当然なんだ。\n才能の上にあぐらをかいて、社会と馴染もうとしない、\n人としては、本当に未熟な奴だから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0278>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0279>, 164, 1)  ; 「なんで今になって、\nそんなわかりきったこと、言い出すんだよぉ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 165, 1)  ; 本当に、弱すぎる奴。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 2143
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 100
PUSH INT 0
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
OPERATOR NEGATE
PUSH INT 0
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0281>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 166, 1)  ; 「かずさ…お前は本当に駄目な奴だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0283>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 167, 1)  ; 「言うな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 168, 1)  ; 孤高だって、格好いいって、狼のように気高い奴だって…\nそんなふうに憧れてた昔が、馬鹿馬鹿しく崩れ去る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0286>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0287>, 169, 1)  ; 「誰かに支えられてなくちゃ生きていけないくせに、\n頼ろうとする相手を選り好みしすぎて自滅して…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0288>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 170, 1)  ; 「やめろって言ってるだろ！\nもう黙れ…黙ってくれよぉ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 171, 1)  ; 狼の皮を被った兎…\n孤高を気取り、けれど寂しければ死んでしまう、\nそんな、絶滅するしかない歪な種。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0291>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0292>, 172, 1)  ; 「俺と曜子さんの両方ともいなくなったら、\nどうやって生きていくつもりだったんだよ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0293>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 173, 1)  ; 「そんなの知るか！\nそんなあり得ないこと考えてたまるか！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0295>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 174, 1)  ; 「お前がこんなにも駄目な奴だから、\nどうしようもない弱い奴だから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0297>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 175, 1)  ; 「春希ぃっ！\nお前はぁっ…！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0299>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0300>, 176, 1)  ; 「だから………俺がなんとかするしかないだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

@VCALL WN(RES<0301>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 177, 1)  ; 「………………ぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0303>, 178, 1)  ; …そんなどうしようもない奴、\n放っておける訳なんかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 179, 1)  ; 曜子さんがなれないというのなら、\n俺が『手を差し伸べるべき誰か』になるしかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1033
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 23
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0305>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0306>, 180, 1)  ; 「俺、さ…\nそんな最低なお前が好きだ。\n…世界で、一番好きだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0307>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0308>, 181, 1)  ; 「………………ぇ、えっ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0309>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 182, 1)  ; 「お前が幸せに生きてくれないと嫌なんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0311>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 183, 1)  ; 「………………………春希？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0313>, 184, 1)  ; いや………なりたいんだ。\nかずさの、『手を差し伸べるべき誰か』に。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0314>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0315>, 185, 1)  ; 「お前が幸せになるために…\nいや、お前が生きていくために、\n俺が必要だって言うのなら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1.3
PUSH FLOAT 1.3
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 1800
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0316>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0317>, 186, 1)  ; 「俺は、お前の側にいる。\n…たとえ、全てを捨てることになっても」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 360
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0318>  ; CATCH3
PUSH INT 100
CALL SCall
OPERATOR POP

ARRAY_S RES<0319>  ; 3102
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
