!RESOURCE "3104.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3104
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2013
PUSH INT 2
PUSH INT 17
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 4300
PUSH INT 90
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 15
PUSH INT 106
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1043
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0004>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「ふあぁぁ～～～ぁれ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 30000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 15
PUSH INT 106
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1043
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0006>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「あ、おはよ孝宏。\n春休み入ったのに早いじゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 101
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0008>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「姉ちゃんこそ…\n日曜の朝見かけるなんて珍しいじゃん。\n大抵は寝坊してるか外泊してるかのどっちかだし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 30000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0010>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「そうかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0012>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「で、なにしてんの？　弁当？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 30000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0014>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 5, 1)  ; 「うん、まぁね。\nよし、完成！\nね、ね、我ながらいい色合いだと思わない？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 102
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0016>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 6, 1)  ; 「昨日デートしたばっかじゃん。\n相変わらずらぶらぶだねぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 100
PUSH INT 30000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0018>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 7, 1)  ; 「そういうんじゃないよぉ。\nただ春希くん最近忙しくて、\nちゃんとしたもの食べれてないって言うから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 8, 1)  ; 「それがらぶらぶでなくてなんだっつ～の。\nこりゃ、マジで秒読みかな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 30000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0022>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 9, 1)  ; 「喜んでくれるかな…くれるよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 101
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0024>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 10, 1)  ; 「今日はどこ行くの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 30000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0026>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 11, 1)  ; 「え、別に。\n何も決めてないけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 104
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0028>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 12, 1)  ; 「なんだよ、ノープランか。\nだったら部屋でメシ作ってあげりゃ良かったじゃん。\n今までそうしてなかったっけ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 30000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0030>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 13, 1)  ; 「………うるさいなぁ、どうだっていいでしょ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 103
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0032>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 14, 1)  ; 「…姉ちゃん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 30000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0034>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 15, 1)  ; 「…出かけてくる。\nそれじゃ、行ってきます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

@VCALL WN(RES<0036>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 16, 1)  ; 「あ、ああ…って、姉ちゃん後片づけ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 615
PUSH INT 0
PUSH INT 0
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 10
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 1000
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0038>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 17, 1)  ; 「………行ってらっしゃい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 14
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0040>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 18, 1)  ; 「あら、孝宏、\n春休み入ったのに早いじゃない。デート？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 103
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0042>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 19, 1)  ; 「それは姉ちゃんだろ。\n…浮かれすぎて後片づけも忘れてるし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0044>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 20, 1)  ; 「…いいのよ。\nわたしがやっておくから。\nついでにあんたの朝ご飯も用意するわね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 101
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0046>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 21, 1)  ; 「あ、別にいいよ。\n俺、この弁当の残り物で…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 14
PUSH INT 103
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0048>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 22, 1)  ; 「やめときなさい、それは。\nちゃんとしたもの作るから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 103
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0050>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 23, 1)  ; 「え、けど…もったいないじゃん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0052>)  ; 雪菜の母
PUSH INT 14
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 24, 1)  ; 「いいから。\nあなたは食べたら駄目。\n…余計な心配することになるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0054>)  ; 孝宏
PUSH INT 15
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 25, 1)  ; 「…母さん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2201
PUSH INT 0
PUSH INT 1
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 26, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8403
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 5
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2044
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0057>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 27, 1)  ; 「それじゃあ…な」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 28, 1)  ; 休日の朝…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 29, 1)  ; 少し日が高くなった頃に起き出して、\nちょっと遅めの朝食を済ませた頃には、\nもう曜子さんの言う『午後から』に近づいていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0061>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 30, 1)  ; 「今日は、帰るのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0063>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 31, 1)  ; 「母さんにスタジオを追い出されたらな。\nだから、食事の用意とかはいいよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0065>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 32, 1)  ; 「そっか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0067>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 33, 1)  ; 「帰ってこなくても、待ってなくていい。\nそれよりも早く寝ろ。\n昨夜、一睡もしてなかったろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 34, 1)  ; そのことがわかるとしたら、\n一睡もしてない奴しかいないはずなんだけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 320
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0070>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 35, 1)  ; 「その代わり…\n目覚めたとき、隣に変なのが寝てても気にしないでくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0072>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 36, 1)  ; 「………ああ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 37, 1)  ; それでも、かずさの微かな笑顔と、\nほんの少し悪戯っぽい言葉に、\n俺は、心配するのをやめた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0075>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 38, 1)  ; 「行って、きます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0077>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 39, 1)  ; 「うん…行ってこい。\n頑張ってな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0079>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 40, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 20
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8234
PUSH INT 0
PUSH INT 0
PUSH INT 100
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 41, 1)  ; だって、かずさは無理してなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0082>, 42, 1)  ; 追加公演まで残り二週間…\n体力的には、これから相当追い込むだろうけど、\n少なくとも精神的にはリラックスしてるみたいだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 43, 1)  ; もし、昨夜の俺が少しでもかずさを満たしたのなら、\nそれに勝る喜びはない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0084>, 44, 1)  ; 俺が、かずさの帰るべき場所でいられるのなら。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 45, 1)  ; 今も、そして、これからも、ずっと…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 8404
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2045
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0086>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 46, 1)  ; 「昨日のおかずがたくさん余っちゃって…\n捨てるのももったいなかったから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0088>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 47, 1)  ; 「別に、無理に食べろって言ってないよ。\nお腹空いてなかったら、捨てちゃっていいんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0090>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 48, 1)  ; 「…駄目だ。\n押しつけがましすぎるよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0092>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 49, 1)  ; 「えっと、えっと…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0094>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 50, 1)  ; 「違うんだよ。\n別に、大した意味はないんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0096>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 51, 1)  ; 「ただ、そのね…\nその…えっと…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0098>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 52, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0100>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 53, 1)  ; 「お母さんが！\nそう、お母さんが、持って行けって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0102>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 54, 1)  ; 「春希くん、最近忙しそうだったから。\nきちんとした食事してないだろうからって。\nわ、わたしは、そんなつもりなかったんだけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 118
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0104>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 55, 1)  ; 「………うん、これで行こう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0106>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 56, 1)  ; 「ごめんね、お母さん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8401
PUSH INT 0
PUSH INT 0
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 57, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 716
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8060
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0109>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 58, 1)  ; 「ふぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 59, 1)  ; かずさを送り出し、洗い物を済ませると、\n時計はちょうど１２時を指していた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 60, 1)  ; かずさの言う通り、昨夜から寝てなかったけれど、\nまだ、ベッドに横になる気は起きなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 61, 1)  ; 休日のうちに、やっておくべきことが山ほどある。\nというか、これから数日はもう暇なんかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 62, 1)  ; それにきっと…\nベッドで目を閉じても、眠ることなんかできない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2043
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8403
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0115>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 63, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 64, 1)  ; 靴を履き、ドアを開け、\nふと部屋の中を振り返ったとき、\n一瞬、俺の中の時間が止まった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 150
OPERATOR NEGATE
PUSH INT 60
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
PUSH INT 60
PUSH INT 3500
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 65, 1)  ; シンプルな、飾りっ気のない部屋が目に映る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 66, 1)  ; ベッド、クローゼット、本棚、\nテレビ、冷蔵庫、炊飯器、電子レンジ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0120>, 67, 1)  ; 最低限の家具と家電。\n持ってる服は、大半が仕事用のスーツやワイシャツ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 68, 1)  ; …けれど、こんな面白みのない部屋に時々鎮座する、\nミキサー、ホットプレート、圧力鍋に泡立て器。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 69, 1)  ; ………俺以外の、『二人目の住人』が持ち込んだもの。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0123>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0124>, 70, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 71, 1)  ; 懐かしさを感じるには、まだ実感が湧いてこない。\n悲しさを感じるには、まだ決心が追いついてこない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0126>, 72, 1)  ; つい数日前まで、\nここは俺たちの“巣”だと言っても間違いじゃなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 73, 1)  ; そこにあるものは、何もかも自然にそこにあって。\nシンプルとファンシーが変な具合に融合したところが\nちょっとした味わいで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 74, 1)  ; けれど、もう、\nこの景色をそう感じられるのも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8404
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 75, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 40
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 19
PUSH INT 1
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 1039
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0130>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 76, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 115
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 19
PUSH INT 1
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0132>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 77, 1)  ; 「っ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0134>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 78, 1)  ; 「久しぶり…って、誕生日パーティ以来か。\n探したよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 216
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0136>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0137>, 79, 1)  ; 「と、朋…どうして？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0138>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 80, 1)  ; 「昨日からずっと携帯に出ないから、\nさっき家にかけたんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0140>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 81, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0142>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 82, 1)  ; 「お弁当作って、\n北原さんのところに出かけたって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0144>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 83, 1)  ; 「そうだよ。\n春希くんの所に行くんだ。\nだからごめん、今日はちょっと…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 10
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0146>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 84, 1)  ; 「じゃあ、何でこんなところにいるの？\n北原さんのマンション、すぐそこじゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0148>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 85, 1)  ; 「それは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0150>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 86, 1)  ; 「…何が、あったの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0152>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 87, 1)  ; 「な、何って…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0154>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0155>, 88, 1)  ; 「それ、北原さんへのお弁当だよね？\nどうしてここで開けてるの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0156>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 89, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0158>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 90, 1)  ; 「北原さん、いなかったの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0160>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 91, 1)  ; 「………（ふるふる）」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0162>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 92, 1)  ; 「来客中だったとか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0164>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 93, 1)  ; 「………（ふるふる）」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0166>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 94, 1)  ; 「それじゃ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0168>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 95, 1)  ; 「行かなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 12
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0170>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 96, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0172>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 97, 1)  ; 「…ううん、マンションに入ろうとしたところで、\n足が動かなくなっちゃった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 10
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0174>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 98, 1)  ; 「どうして…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0176>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 99, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 14
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0178>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 100, 1)  ; 「………正直に話して。\nわたし、雪菜の味方だから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0180>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 101, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0182>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0183>, 102, 1)  ; 「この間わたし、言ったよね？\n彼が冬馬かずさと会ってるかもしれないって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0184>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0185>, 103, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 10
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0186>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 104, 1)  ; 「まさかとは思うけど…\n雪菜、昨日彼と…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0188>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 105, 1)  ; 「おかしいの…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 12
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0190>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 106, 1)  ; 「…何が？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0192>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 107, 1)  ; 「このお弁当…\n味見してみたら………まずいの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 10
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0194>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 108, 1)  ; 「お弁当？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 109, 1)  ; 「食べられないくらい、酷いの。\nこんな料理を、わたしが作ったの…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 12
PUSH INT 31000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0198>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 110, 1)  ; 「せ、雪菜…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0200>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 111, 1)  ; 「なんなのこれ…\nどうやって作ったのか全然覚えてない…\nわたし、どうしちゃったの…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0202>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 112, 1)  ; 「ちょっと…しっかりしてよ…\n何言ってるのよあなた…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 130
PUSH INT 31000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0204>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 113, 1)  ; 「わ、わたし…わたし…っ、\nあ、あ、あ…あぁぁぁぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0206>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 114, 1)  ; 「雪菜…？\n雪菜！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0208>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 115, 1)  ; 「あああああああ…\nうああああぁぁぁぁぁ～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0210>, 116, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1036
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0211>)  ; 不動産屋
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0212>, 117, 1)  ; 「それじゃ、本当によろしいんですね？\n次回の更新はしないということで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0213>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0214>, 118, 1)  ; 「ええ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0215>)  ; 不動産屋
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0216>, 119, 1)  ; 「今の契約期限が３末までですから、\n来月末には引き払っていただくことになりますが」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0217>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0218>, 120, 1)  ; 「十分です。\nそれまでには引き払っておきますから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0219>)  ; 不動産屋
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0220>, 121, 1)  ; 「海外赴任ですかぁ…どちらへ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0221>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0222>, 122, 1)  ; 「ええ、ヨーロッパ…オーストリアの方へ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 123, 1)  ; 五年かかって築き上げた思い出も、\nあの部屋の、味わいのある光景も…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 124, 1)  ; 数日後には、もうそこに存在しなくなる。\n跡形もなく消え去ってしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0225>  ; CATCH3
PUSH INT 100
CALL SCall
OPERATOR POP

ARRAY_S RES<0226>  ; 3105
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
