!RESOURCE "3105.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3105
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2013
PUSH INT 2
PUSH INT 18
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 8260
PUSH INT 60
PUSH INT 1
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2027
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 1908
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0004>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「北原ぁ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「…はい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 2, 1)  ; 月曜日…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 3, 1)  ; 日が暮れてからが勝負とばかり、\n編集部に更なる活気が出てきた頃…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0010>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 4, 1)  ; 「北原…\nお前、お前………なんでだよっ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 5, 1)  ; 浜田さんの怒声がその喧噪に割り込んだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0013>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 6, 1)  ; 「これからだろ…\nお前、まだ何も返しちゃいないだろ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0015>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 7, 1)  ; 「…すいません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0017>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0018>, 8, 1)  ; 「っ…こ、こ、こ…\nとにかく会議室まで来い！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 0
PUSH INT 1908
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0019>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0020>, 9, 1)  ; 「………はい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 8263
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 10, 1)  ; 意外と…早かったな、伝わるの。\nもう少しくらいは気軽に過ごしたかったけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 32
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0022>)  ; 木崎
PUSH INT 32
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 11, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 32
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 31
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0024>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 12, 1)  ; 「…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 33
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0026>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 13, 1)  ; 「っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2029
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0028>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 14, 1)  ; 「どういうことだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0030>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 15, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 16, 1)  ; 会議室に呼び出した後も、\nしばらく浜田さんは呼吸を落ち着かせるだけで、\nなかなか本題に切り出さなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 17, 1)  ; 奥さんに言われてやめていたはずのタバコを一本取り出し、\nけど会議室がもう禁煙になっていることを思い出し、\n余計イライラを募らせて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 10
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0034>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 18, 1)  ; 「編集長に辞表出したって…どういうことだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 19, 1)  ; 仕方なしみたいに、やっと本題に入った。\nまるで、本当はこんな話したくないみたいな態度だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0037>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 20, 1)  ; 「一身上の都合で…\n辞めさせていただきます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 5
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0039>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 21, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 22, 1)  ; …俺と同じように視線を泳がせていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 33
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 32
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 31
PUSH INT 6
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2028
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0042>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 23, 1)  ; 「…聞いた？\n今の、聞こえた？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 32
PUSH INT 4
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0044>)  ; 木崎
PUSH INT 32
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 24, 1)  ; 「ああ…\n鈴木の顔見て聞き違いじゃないってわかったよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 4
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0046>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 25, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0048>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 26, 1)  ; 「どういうこと…？\nヘッドハンティング？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 32
PUSH INT 6
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0050>)  ; 木崎
PUSH INT 32
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 27, 1)  ; 「ないない。\n今のところあいつをそこまで評価してるのって\n風岡さんぐらいだし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 11
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0052>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 28, 1)  ; 「新人だもんねぇ…\n身内しか知らないよね、彼の仕事ぶりなんて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 5
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0054>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 29, 1)  ; 「ていうか………冗談でしょ？\nだって、北原だよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 32
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0056>)  ; 木崎
PUSH INT 32
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 30, 1)  ; 「松岡…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 6
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0058>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 31, 1)  ; 「あの責任感の塊だよ？\n規則の鬼だよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 4
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0060>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 32, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 10
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0062>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 33, 1)  ; 「なんだよ、それ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 30
PUSH INT 5
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2029
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0064>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0065>, 34, 1)  ; 「…理由は？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0066>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0067>, 35, 1)  ; 「急に辞めてしまうことになって申し訳ありません。\nただ、今抱えている仕事は全部終わらせてから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0068>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 36, 1)  ; 「そんなこと聞いてない。\n理由だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0070>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 37, 1)  ; 「………ですから、一身上の都合です」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 38, 1)  ; やっぱり…\nこちらが一番言いたくないことは、\n向こうが一番聞きたいことで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0073>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 39, 1)  ; 「家庭の事情とか？\nでもお前、独身だよな？\nもしかして、親御さんが何か？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0075>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 40, 1)  ; 「親は関係ありません。\n本当に、個人的な事情です」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 41, 1)  ; 少なくとも、自分の親は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0078>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 42, 1)  ; 「そんな勝手が許されるとでも思ってるのか？\nそれとも、いつもみたいに社則とか労基法とか\n盾にでも取るつもりか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0080>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 43, 1)  ; 「………すいません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0082>, 44, 1)  ; 一月以上前に告知すれば、\nこの会社は、社員の自主退職を却下することはできない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0083>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0084>, 45, 1)  ; 「お前、まだ一年目だろ？\nこれからにも程があるだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0085>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 46, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 47, 1)  ; けれどもちろん、\nそんな文章化された契約が全てじゃないって、\n俺にだってわかってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0088>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 48, 1)  ; 「お前らが会社を儲けさせるのに\n何年かかるか知ってるか？\nそれまでは会社の金使い込んでるってわかってるか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0090>, 49, 1)  ; 仕事を通じて積み上げてきた、沢山の価値あるもの。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 50, 1)  ; 先輩から後輩に脈々と受け継がれてゆくスキル、人脈、\nそして、絆。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0092>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 51, 1)  ; 「いくらお前でも、まだ会社的には全然赤字なんだぞ？\nなんの恩返しもできてないんだぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0094>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 52, 1)  ; 「わかって…ます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0096>, 53, 1)  ; それは、俺がこの場所に根を下ろすから…\n自分の、会社の、そして社会のためになるからこそ、\n先輩が、会社が無償で俺に与えてくれたもの。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 9
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0097>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 54, 1)  ; 「だったら、何で…\nお前、バイトから這い上がってきたじゃないか。\nずっと上向いて頑張ってきたじゃないか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0099>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 55, 1)  ; 「浜田、さん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 10
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0101>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 56, 1)  ; 「最初から、他の新人とは違っててさ…\nなんつ～か、いい意味で古くさい奴だって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 57, 1)  ; 最初は、三年近く前。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0104>, 58, 1)  ; コピーと使い走りと原稿取りの、\n単純作業と肉体労働と寝ずの仕事から始まって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 59, 1)  ; けれど、俺が逆指名した鬼のような女性上司は、\nすぐにその肉体労働よりもよほど体力を使う頭脳労働を\n大量に押しつけてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0106>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 60, 1)  ; 「真面目だけど、人とも合わせられるし、\n理屈っぽいけど、自分がサボったり得するための\n屁理屈は決して言わなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 61, 1)  ; 一年後…\n彼女は栄転で颯爽とアメリカに旅立つ際、\n人数の減った編集部に、新卒の俺を押し込んだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0109>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 62, 1)  ; 「たまに一人で突っ走ることもあるけど、\n決して個人主義ってんじゃなくて、\n何より、仕事と真剣に向き合ってた」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 63, 1)  ; そして、それから今まで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 64, 1)  ; 厳しくて適当な人たちに囲まれて、\n苦しくて、楽しくて、いつも忙しい毎日を過ごして。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0113>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 65, 1)  ; 「だから、風岡だってお前を特別に可愛がってた…\nそれに俺だって、皆だって…\nいや、デスクや編集長だって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0115>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 66, 1)  ; 「ありがとう…ございます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 67, 1)  ; 古くさい言い方だけど、\n『男子一生の仕事』と思えるくらい、\n面白さとやりがいを感じるようになれてきて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0118>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 68, 1)  ; 「なのに…\n直属の上司にすら事前に一言もなく辞めるって、\n一体どういうことなんだよ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0120>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 69, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 70, 1)  ; そして………これでおしまい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0123>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0124>, 71, 1)  ; 「ふざけんなよ！\nどうして俺に相談しない？\n俺はそんなに信頼できない上司だったか…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0125>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0126>, 72, 1)  ; 「すいません…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0127>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 73, 1)  ; 「すいませんじゃ済まないよ…\nなんでだよ、北原…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 74, 1)  ; 今まで積み重ねてきたスキル、人脈、絆…\nそんな、沢山の人生の価値が。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0130>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 75, 1)  ; 「でも、無理なんです。\n相談したからってどうにかなる事情じゃないんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 76, 1)  ; 表紙に“辞表”と書かれた手紙一通で、\n全て水泡に帰す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0133>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0134>, 77, 1)  ; 「それでも、上司に相談するもんだろう？\n仕方なくても、腹を割って話すもんだろう？\nお前は、そういうことができる奴じゃなかったのか…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0135>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 78, 1)  ; 「申し訳ありません。\n本当に…本当に、ごめんなさい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0137>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 79, 1)  ; 「どうなってんだよ！\nもう勝手にしやがれ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 80, 1)  ; 浜田さんは、完全にキれていた。\nそして、もう諦めかけていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 81, 1)  ; だって、この一年…\nいや、三年の付き合いで、もうわかってるから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0141>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 82, 1)  ; 「………仕事に戻ります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 10
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0143>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0144>, 83, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 84, 1)  ; 俺が…\n一度決めたことを上司に言われたくらいで覆すような、\nそんな素直な部下じゃないってことが。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 31
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 32
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 33
PUSH INT 4
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2028
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0146>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 85, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0148>)  ; 木崎
PUSH INT 32
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 86, 1)  ; 「北原…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0150>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 87, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 88, 1)  ; ある意味、予想はしてたことだけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 89, 1)  ; これでもう、\nここでの俺の居場所はなくなってしまったって、\nそう実感させられる、皆の表情だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0154>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0155>, 90, 1)  ; 「冗談…だよな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 91, 1)  ; 俺の冗談が壊滅的なことを知っていながら、\n松岡さんは、それでも問いかけてきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 92, 1)  ; その、今の俺を否定する言葉は、\n今までの俺を肯定してくれているってことで、\n本当はありがたい態度のはずだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 93, 1)  ; それでも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0159>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0160>, 94, 1)  ; 「お世話に…なりました。\n来月いっぱいで、俺…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 10
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0161>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 95, 1)  ; 「な………んだよそれ。\nなんでお前が先にいなくなるんだよ？\nどう考えても俺が飛ばされんのが先だろ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0163>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 96, 1)  ; 「松っちゃん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0165>)  ; 木崎
PUSH INT 32
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 97, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 98, 1)  ; もう、峰城グラフのチームに、\n元通りの空気が戻ることはない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 99, 1)  ; …少なくとも、俺がここにいる間は。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 100, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0170>  ; CATCH3
PUSH INT 100
CALL SCall
OPERATOR POP

PUSH INT 2013
PUSH INT 2
PUSH INT 19
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 42
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2073
PUSH INT 1
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0171>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 101, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0173>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0174>, 102, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 103, 1)  ; 夜も更けて、俺たち以外に人のいなくなった\nホテルのカフェは、いつも以上に静寂に包まれていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 16
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0176>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 104, 1)  ; 「ギター君…\nいいえ、北原君」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0178>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 105, 1)  ; 「はい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 106, 1)  ; 曜子さんがしばらく上を向いたまま\n黙り込んでしまっていたせいで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0181>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 107, 1)  ; 「あなた…本当にそれでいいの？\nあの子のために何もかも捨ててしまって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0183>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 108, 1)  ; 「今は俺の話じゃなくて、\n曜子さんのことです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0185>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 109, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0187>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0188>, 110, 1)  ; 「帰ってくれませんか？\n俺たちと…かずさと一緒に、ウィーンに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 111, 1)  ; 俺が、ここ数日のうちにしたことを、\n包み隠さず話してから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0190>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 112, 1)  ; 「とうとう…やっちゃったのね。\nあの子を…受け入れてしまったんだ。\n自分のブレーキ、壊してまで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0192>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 113, 1)  ; 「すいません…\nなんの相談もせずに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0194>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 114, 1)  ; 「すいませんはこっちの台詞…\nあなたが実は危険なコだって気づいた時に、\n無理にでも止めておくべきだった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 115, 1)  ; 「反対…なんですか？\n曜子さんは、その、俺とかずさが…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0198>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 116, 1)  ; 「反対なんてできない…できるわけない。\n娘が、生まれてから今までで一番の幸せに浸ってるのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0200>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 117, 1)  ; 「い、いや、それほどのことじゃ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 108
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0202>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 118, 1)  ; 「けれど…最悪ね。\nあの子の望んだ結果だけど、\nわたしの望んだ結末とは違う」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0204>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 119, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0206>, 120, 1)  ; 曜子さんは、すごく微妙な表情で、\nすごく極端な言葉で、\n俺のしでかした行為を批判する。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 121, 1)  ; …俺が裏切った他の人たちと同じように。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0208>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 122, 1)  ; 「あなたに大切な人がいなければ、\nこうなってくれればいいと思ってた」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0210>, 123, 1)  ; けれど、俺には心の底から大切な人がいて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0211>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0212>, 124, 1)  ; 「かずさが、あなたを卒業できれば、\nこんなことにはならなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 125, 1)  ; けれど、かずさの気持ちはあまりに純粋で、強くて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0214>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 126, 1)  ; 「何より、わたしが病に倒れなければ、\nあなたを巻き込まずにすんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0216>, 127, 1)  ; けれど、曜子さんは…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0217>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0218>, 128, 1)  ; 「…結論。\n全部わたしの病気のせい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 129, 1)  ; やっぱり曜子さんらしく、\n今のこの状況を総括した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0220>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 130, 1)  ; 「一つずつ、歯車が狂った。\nどんどん皆が望む方向からずれていって、\n何もかもが壊れていくのを止められなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0222>, 131, 1)  ; 自分も含め、悪い人間なんか誰もいない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 132, 1)  ; 状況が、巡り合わせが、最終的には社会が悪いって、\nそんなモラトリアム的な青臭い社会批判。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 133, 1)  ; …俺の考えとはまるで正反対の、\nどっちが年下なんだかわからない認識の齟齬。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0225>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 134, 1)  ; 「…結果的に、あなたの人生を。\nわたしの娘が、壊してしまった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 135, 1)  ; だって俺は…\nどう考えても、俺が悪いって信じてるから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0228>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0229>, 136, 1)  ; 「わたしが直接壊したなら、天罰も地獄行きも覚悟してる。\n…けれど、我が娘が地獄に落ちるのは見るに忍びない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 137, 1)  ; 何もかも、俺の決断で、俺の責任で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0231>, 138, 1)  ; その上で、今の俺にとって最善の決断をしたって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0232>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0233>, 139, 1)  ; 「だから、ごめんなさい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 140, 1)  ; だから、謝られる筋合いなんかないって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0235>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 141, 1)  ; 「結局、あなたもかずさも、\n日本にいられなくなってしまった…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0237>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 142, 1)  ; 「別に、逃げる訳じゃありません。\n二人で相談して、決めたことです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 102
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0239>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 143, 1)  ; 「二人で相談したから逃げてないってのは、\n全然説明になってないし…ついでに嘘よね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 144, 1)  ; そんなふうに全然認識が違うくせに、\nところどころ本質を言い当ててくるところが\n以前から少し苦手だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0242>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 145, 1)  ; 「曜子さん…\nかずさには、やっぱりあなたが必要なんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0244>, 146, 1)  ; だから、無理やり話を切り替える。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0245>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0246>, 147, 1)  ; 「あなたのケアについては、俺が絶対に何とかします。\n日本じゃなくても…ううん、日本以上に、\nあなたに不自由はさせません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 148, 1)  ; いや、最初に話を逸らしたのは曜子さんの方だ。\n俺は、会話を正しい方向に軌道修正しただけだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0248>, 149, 1)  ; 俺が今日彼女に会いに来たのは、\nただ、この申し出に首を振ってもらうためだけだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0249>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 150, 1)  ; 「だから…一緒に来てもらえませんか？\nかずさのこと…一緒に護ってもらえませんか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 107
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0251>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0252>, 151, 1)  ; 「北原君…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 152, 1)  ; もちろん、縦に。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0254>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 153, 1)  ; 「あいつが辛い思いをしないように、\nこれからも、あいつを導いて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0256>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 154, 1)  ; 「どこまでお人好しなのよ。\n…いいえ、どこまで人が悪いのよ、あなたは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0258>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 155, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0260>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 156, 1)  ; 「これから本当の意味で辛い目に遭うのは、\nかずさじゃなくて、あなたなのよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 157, 1)  ; でも、そうやって性急に結論を求める俺を、\n曜子さんは、そうやって何度も押し留める。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 158, 1)  ; 今の俺…\nそんなに危うく見えるんだろうか？
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 101
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0264>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 159, 1)  ; 「かずさは、周囲にどう思われるかはさておき、\n本人の中では、最高に幸せに生きていける。\nだって、最愛の男に護ってもらえるんだもの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0266>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0267>, 160, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0268>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 161, 1)  ; 「けれどあなたは…誰も護ってなんかくれない。\nだって、かずさにそんな普通の力なんてないもの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0270>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0271>, 162, 1)  ; 「曜子さん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0272>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0273>, 163, 1)  ; 「あの子はこれからも、\nあなたが一生懸命頑張ってる横で寄り添ってるか、\n気ままにピアノを弾いてるくらいしかできない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0274>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 164, 1)  ; 「そんなこと…最初からわかってます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 109
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0276>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 165, 1)  ; 「あなたには、\nこれから地獄が待ってるかもしれない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0278>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0279>, 166, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 167, 1)  ; 曜子さんは…\n今になって、今さらなことを言い出した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 168, 1)  ; …とびっきりの正論を。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0282>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 169, 1)  ; 「かずさを護るって使命を抱えたまま、\n言葉も通じない、何もかもが初めての場所で、\n一人で生きていくよりも過酷な人生を歩いていく…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 170, 1)  ; アリが冬に備えてせっせと働いているとき、\nキリギリスは優雅に歌い、遊び。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 171, 1)  ; だから冬を越せたのはアリだけ。\nそれが寓話の教えだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0286>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0287>, 172, 1)  ; 「しかも、絶対に立ち止まるわけにはいかない。\n何しろ、あなたが倒れるってことは、\n共倒れと同じ意味だから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 173, 1)  ; そして寓話じゃない現実世界でも、\nキリギリスが楽しそうにピアノを弾いているとき、\nアリは必死で働いて冬の蓄えをしないといけない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 174, 1)  ; これからは、キリギリスの分まで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 175, 1)  ; これからは、自分たちの巣を離れて。\n…他のアリたちと決別してまで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 106
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0291>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0292>, 176, 1)  ; 「何もかも違う環境で、\nそんな大きなプレッシャーを抱えて…\nいくらあなたでも、しっかり生きていけるかは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0293>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 177, 1)  ; 「俺は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 105
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0295>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 178, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0297>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 179, 1)  ; 「俺は…\nかずささえいれば、大丈夫ですよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0299>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0300>, 180, 1)  ; 「あなた…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0301>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 181, 1)  ; 「あいつに護ってもらおうなんて思ってません。\nこれからも、自分の人生は自分で切り開きます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0303>, 182, 1)  ; それは、曜子さんに対しての\n単なる意地なのかもしれなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0304>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0305>, 183, 1)  ; 「ちゃんと現地で仕事を探して、言葉も勉強して、\n二人…いや、三人だって抱えてみせます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0306>, 184, 1)  ; 今まで散々煽っておきながら、\n最後の最後に梯子を外されてしまったことに対して、\n意趣返しをしたかっただけかもしれなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0307>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0308>, 185, 1)  ; 「あいつが側にいれば、それができるんです。\nそれこそあいつは、\n隣で気ままにピアノを弾いていればいい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0309>, 186, 1)  ; けれど…\nその時の俺は、その気持ちが嘘だなんて、\nこれっぽっちも思えはしなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0310>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0311>, 187, 1)  ; 「そして俺は、かずさを護るためなら、\nあなたの力にだってなってみせます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 188, 1)  ; それは、俺の数十倍も数百倍も稼ぐ、\n俺より何十年も長く生きてきた人生の先輩に対して、\nあまりにも不遜な申し出に違いなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0313>, 189, 1)  ; それでも俺は、本気で彼女の人生も背負うつもりだった。\nそれが、かずさをもっと幸せにできる手段だったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0314>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0315>, 190, 1)  ; 「だから、一緒に来てください。\nあいつを世界一幸せなキリギリスにしてやってください」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0316>, 191, 1)  ; アリと一緒に笑って冬を越せる。\nそんな、幸せなキリギリスに…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 103
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0317>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0318>, 192, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0319>, 193, 1)  ; 曜子さんは、もう一度俺の顔をじっと見つめた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0320>, 194, 1)  ; 説得するのを諦めたのか、ただ呆れただけなのか、\nその顔には、脱力したような微笑が広がっていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0321>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0322>, 195, 1)  ; 「…北原君」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0323>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0324>, 196, 1)  ; 「は、はい…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0325>, 197, 1)  ; そして彼女は、\nそんな柔らかな表情のまま…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0326>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0327>, 198, 1)  ; 「………ごめんなさい。\nもう、決めたことなの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0328>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0329>, 199, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0330>, 200, 1)  ; 今まで、避けに避けてきた結論を、とうとう口にした。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0331>, 201, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3003
PUSH INT 60
PUSH INT 1
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1062
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0332>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0333>, 202, 1)  ; 「そっか…やっぱりか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0334>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 203, 1)  ; 「ごめん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 130
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0336>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0337>, 204, 1)  ; 「なんで春希が謝るんだよ？\n全部お前に任せたあたしが悪いに決まってるだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0338>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0339>, 205, 1)  ; 「けど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0340>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0341>, 206, 1)  ; 「あたしが犯した罪のことも、\n無茶なお願いのことも…\n本当は、娘が母親に直接話さないといけないことだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0342>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0343>, 207, 1)  ; 「かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0344>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0345>, 208, 1)  ; 「最初からわかってた。\n病気のことを聞いたときから覚悟はできてた。\nだから、そんな心配そうな顔すんなよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0346>, 209, 1)  ; かずさは、俺の絶望的な報告を聞いても、\nまるで俺を鼓舞するかのように、強く振舞った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0347>, 210, 1)  ; …けれど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0348>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0349>, 211, 1)  ; 「でも、そっか…\n母さん、もう日本を離れないのか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0350>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0351>, 212, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0352>, 213, 1)  ; その強がりは、結局ほんの数秒しか保たなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0353>, 214, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0354>, 215, 1)  ; 曜子さんは、自分の決意を頑なに守り通した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0355>, 216, 1)  ; “死ぬときは自分の生まれた国で”という彼女の決意は、\n何事にも優先されるべき崇高なものだって、\n同じ日本人の俺は、認めざるを得なかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0356>, 217, 1)  ; それでも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3105
PUSH INT 60
PUSH INT 1
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2061
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0357>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0358>, 218, 1)  ; 「まだ行かないって決まったわけじゃない。\nまた来週にでも、もう一度説得してみるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0359>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0360>, 219, 1)  ; 「春希…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0361>, 220, 1)  ; かずさは当然として、\n俺も、ショックを隠しきれていなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0362>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0363>, 221, 1)  ; 「曜子さん、今はちょっと気弱になってるだけだって。\nもっと元気になれば考え方も変わってくるって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0364>, 222, 1)  ; 曜子さんだけは、何があっても俺たちの味方だって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0365>, 223, 1)  ; なんだかんだ言って子煩悩なあのひとなら、\nかずさの側にいてくれると思ったのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0366>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0367>, 224, 1)  ; 「多分、もう無理なんじゃないかな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0368>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0369>, 225, 1)  ; 「そんなことないって。\n諦めたら駄目だって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0370>, 226, 1)  ; ここで、負の連鎖は一息ついてくれるに違いないって、\n結構、甘い期待をしてたのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0371>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0372>, 227, 1)  ; 「弱気になってる時こそ本音って出るものじゃないか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0373>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 140
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0374>, 228, 1)  ; 「そんなこと誰が言ったんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0375>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 141
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0376>, 229, 1)  ; 「あたしに決まってるだろ…\nつい最近、お前相手に見せたばかりじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0377>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 142
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0378>, 230, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0379>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 143
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0380>, 231, 1)  ; 「だから、わかるよ…\n母さんは、本当に日本に残りたいんだよ。\nそれが何よりも大きな願いなんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0381>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 144
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0382>, 232, 1)  ; 「けどお前…\n曜子さんだけ一人、日本に残ったら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0383>, 233, 1)  ; もしかしたらかずさは、\n彼女の最期に立ち会えないことも…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 320
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0384>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 145
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0385>, 234, 1)  ; 「心配すんなよ。\nヨーロッパの冬馬曜子オフィスが開店休業になっても、\nあたし一人の稼ぎ口くらい、なんとかなるって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0386>, 235, 1)  ; けれどかずさは、その最悪の想像を\n敢えて思いつかないかのように振舞う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0387>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 146
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0388>, 236, 1)  ; 「なんとかなるって…どうやって？\nお前が事務所回せるのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0389>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 147
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0390>, 237, 1)  ; 「もっと手っ取り早い仕事やるよ。\nそうだな、近所の子供にピアノを教えたりとか。\nそれなら、自分の腕だけで稼げるだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0391>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 148
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0392>, 238, 1)  ; 「お前が先生？\n…そりゃ、とんでもなく面白い冗談だな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0393>, 239, 1)  ; だから俺も、そんなかずさの会話に合わせる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 142
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0394>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 149
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0395>, 240, 1)  ; 「その突っ込みはとんでもなくつまらないけどな。\n…子供相手ならなんとかなる。馬鹿にするな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0396>, 241, 1)  ; だって、その可能性を思い悩んでいたら、\n俺たちは、一歩も進めなくなってしまうから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0397>, 242, 1)  ; 彼女が日本を…\n峰城大病院を戦場として選んでしまった以上、\n俺たちは、彼女の側にいることはできない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0398>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 150
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 243, 1)  ; 「それこそ子供を馬鹿にするなよ。\n大人以上にコミュニケーション能力が必要になるんだぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0400>, 244, 1)  ; 俺たちに、日本に残るという選択肢はない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 245, 1)  ; これ以上罪を犯せない…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0402>, 246, 1)  ; 雪菜のいる場所に、\n俺たち二人が根を下ろすことはできない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2143
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 100
OPERATOR NEGATE
PUSH INT 0
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
PUSH INT 0
PUSH INT 4000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0403>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 151
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0404>, 247, 1)  ; 「…なぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0405>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 152
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0406>, 248, 1)  ; 「ん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0407>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 153
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0408>, 249, 1)  ; 「今日も、そっちで寝ていいか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0409>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 154
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0410>, 250, 1)  ; 「かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0411>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 155
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0412>, 251, 1)  ; 「寝るだけだよ。\nちゃんと、お前との約束は守る」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0413>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 156
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0414>, 252, 1)  ; 「別に、お前の方を心配してる訳じゃ…\nむしろ自分の理性が保つかってのが」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0415>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 157
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0416>, 253, 1)  ; 「それこそ心配したって仕方ないだろ。\nお前の意志がそんなに弱いわけがないし、\nそもそも勝手に誓いを立ててるのはお前だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0417>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 158
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0418>, 254, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0419>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 159
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0420>, 255, 1)  ; 「…あたしの気持ちなんか、\nこれっぽっちも考えてくれずにさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0421>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 160
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0422>, 256, 1)  ; 「…ごめん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0423>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 161
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0424>, 257, 1)  ; 「いいよ、わかってる。\nお前がそういう奴だってことは、\nずっと前からわかってるんだ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0425>, 258, 1)  ; そうだ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0426>, 259, 1)  ; 雪菜のいる場所に、\n俺たち二人が根を下ろすことはできない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0427>, 260, 1)  ; 愛を育むことなんか、できるわけが…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8193
PUSH INT 0
PUSH INT 1
PUSH INT 100
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2061
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0428>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 162
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0429>, 261, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0430>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 163
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0431>, 262, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0432>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 164
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0433>, 263, 1)  ; 「悪い。マナーモードにするの忘れてた」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0434>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 165
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0435>, 264, 1)  ; 「別に、出てもよかったんだぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0436>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 166
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0437>, 265, 1)  ; 「いや、後で掛け直すから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 130
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0438>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 167
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0439>, 266, 1)  ; 「もしかして…雪菜？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0440>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 168
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0441>, 267, 1)  ; 「違う。仕事関係。\nそれも、多分急ぎの用じゃないから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0442>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 169
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0443>, 268, 1)  ; 「そう…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0444>, 269, 1)  ; かずさは、俺の答えを\nほんの少しだけ信じていないみたいだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0445>, 270, 1)  ; けれど俺の言ったことは本当だ。\nそれは、雪菜からの電話じゃなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0446>, 271, 1)  ; …けれど、俺の言ったことは嘘だ。\nそれは、仕事関係の電話じゃなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0447>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 170
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0448>, 272, 1)  ; 「………帰ろう。\n腹減ったろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 8000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0449>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 171
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0450>, 273, 1)  ; 「うん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0451>, 274, 1)  ; 本当なら、もう少し時間が欲しかった。\nあいつらになんて話すか、考えたかった…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0452>, 275, 1)  ; 着信画面に表示された『飯塚武也』の文字を、\n俺は、電源とともに消した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0453>  ; CATCH3
PUSH INT 100
CALL SCall
OPERATOR POP

ARRAY_S RES<0454>  ; 3106
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
