!RESOURCE "3106.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3106
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2013
PUSH INT 2
PUSH INT 22
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 10
PUSH INT 102
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 11
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 19
PUSH INT 6
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2091
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 5
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0004>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「え～と、それじゃ今日も一日お疲れ様でした。\nかんぱ～い！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 6
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0008>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0010>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0012>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「………かんぱ～い」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8408
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0014>, 5, 1)  ; 武也は、必死だった。\n必死で、この場を盛り上げようとしてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 6, 1)  ; …この四人が集まった理由を否定する勢いで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0016>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 7, 1)  ; 「さてと、それじゃ頼もうぜ。\nな、俺いきなりチゲ行きたいんだけど駄目？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 8, 1)  ; 「飯塚さん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 103
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0020>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 9, 1)  ; 「そっか…\nじゃ、最初は適当に色々頼むか。\nんじゃ、フライドポテトと、冷奴と…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0022>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 10, 1)  ; 「武也」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 11, 1)  ; 「わかってるって。だし巻きだろ。\nお前、どこの店行っても必ず…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 7
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0026>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 12, 1)  ; 「飯塚さん、もう黙って」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0028>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 13, 1)  ; 「ここから先はあたしたちがやるから。\nあんたは黙って飲んでなさい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 112
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0030>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 14, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0032>, 15, 1)  ; 武也は、必死だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 16, 1)  ; すぐにでも噛みつこうとする柳原朋と、\n何事かすごく言いたそうな依緒を\n必死で押し留めていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 17, 1)  ; 集合場所の駅前に俺が顔を見せた瞬間も。\n店のテーブルについた直後でも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 18, 1)  ; 居酒屋ってのも武也が強引に決めた場所だ。\nこいつにしては、信じられないくらい気を使ってる。\n…俺だけに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0036>, 19, 1)  ; けれど、乾杯まで済んでしまった以上、\nもう、二人を止めることはできなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 6
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0037>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0038>, 20, 1)  ; 「北原さん…\nあなた、雪菜に何をしたのよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0039>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 21, 1)  ; 「柳原…さん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 107
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0041>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0042>, 22, 1)  ; 「あ～、もうちょっと前から説明するね。\n実は今週からさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 103
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0043>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 23, 1)  ; 「いや、俺は誤解だって何度も言ったんだよ。\nなのに朋が妙な思い込みしちまってて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0045>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 24, 1)  ; 「雪菜が今、どんなことになってるか知ってる？\n…全部あなたのせいなんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 103
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0047>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 25, 1)  ; 「この子の言うことはさすがに大袈裟だと思うんだけどね。\nでも、雪菜と連絡が取れないってのは本当なの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0049>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0050>, 26, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 103
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0051>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0052>, 27, 1)  ; 「どうせ些細なことが原因なんだろ？\nそんな騒ぐほどのことでもないんだろ？\n朋はいっつも周囲をむやみに引っかき回すからなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 7
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0053>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0054>, 28, 1)  ; 「ちょっとぉ！　茶々入れないでよ二人とも！\nわたしが話があるから呼び出したんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 105
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0055>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 29, 1)  ; 「でも、実際に春希を呼び出したのは俺だろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0057>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 30, 1)  ; 「武也を説得したのあたしだし。\nあんたを勝手に走らせる訳にはいかないよ。\n…ま、武也ほど春希を庇うつもりもないけどね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 31, 1)  ; 三人は、矢継ぎ早に俺に問いかけてきたけれど、\nまるで統制が取れていなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 32, 1)  ; 情報も、認識も、熱さもバラバラ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 33, 1)  ; 特に、柳原朋と他の二人の間には、\n天と地ほどの思いの差があった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0062>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 34, 1)  ; 「雪菜と…連絡取れないのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0064>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0065>, 35, 1)  ; 「お母さんに聞いたら、会社には行ってるみたい。\nだからちょっと拗ねてるだけだと思うんだけどね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 6
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0066>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0067>, 36, 1)  ; 「だから、わたし日曜に会ったんだよ！\n雪菜、ボロボロに泣いてたんだってばぁ！\nこの人のマンションのすぐ前で！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0068>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 37, 1)  ; 「っ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0070>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 38, 1)  ; 「…今週に入ってから、ずっとこの調子なんだよ。\nだから、お前に声かけないわけにはいかなくてさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 16
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0072>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 39, 1)  ; 「あんな悲しそうな雪菜、わたし見たことない…\n二年前のあの頃だって、見たことないんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0074>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 40, 1)  ; 「雪菜、が…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 41, 1)  ; 日曜、俺のマンションの前…？
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 42, 1)  ; それって、あの日の、次の…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 14
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0078>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 43, 1)  ; 「雪菜に、何言ったの？\nううん、雪菜があんなに泣くことなんて一つしかない。\n…別れ話だよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 108
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0080>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 44, 1)  ; 「だからぁ、ちょっと待ちなって。\nどうしてすぐ短絡的な結論に持って行こうとするかなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0082>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 45, 1)  ; 「そりゃ、何かしらのきっかけで\nそういう話になったかもしれないけど、\nそんなの、二人とも本気な訳ないじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 6
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0084>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 46, 1)  ; 「違う！　あなたたち、\n今の雪菜を見てないからそんなこと言えるのよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0086>, 47, 1)  ; 朋が、どれだけ熱く俺のことを糾弾しても…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 48, 1)  ; いや、強く罵れば罵るほど、\n二人はどんどん俺を弁護する側に回ってしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 14
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0088>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 49, 1)  ; 「ねぇ、北原さん…\nあなた今、冬馬かずさと一緒にいるよね？\n雪菜に隠れて、彼女と会ってたよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0090>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 50, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 107
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0092>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 51, 1)  ; 「やめろって言っただろそれ言うの！\nその話をしないって言うから今日セットしたのに…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 107
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0094>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 52, 1)  ; 「あ～、ごめん春希。\nそれはさすがに信じちゃいないから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 17
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0096>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 53, 1)  ; 「だ、だけど、だけど…\nわたし、本当に見たんだからっ！\n北原さんの隣の部屋に、冬馬かずさが…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 54, 1)  ; それは、俺と過ごした時間の差だったり、\n柳原朋の、元々の性格に起因するものだったり、\nそんな様々な要因が絡んでのことだと思うけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 55, 1)  ; 皮肉なのは…\n俺を弁護しようとすればするほど、\n武也と依緒が、真実から離れていくこと。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 56, 1)  ; 俺と一番敵対している柳原朋こそが\n唯一正鵠を得ているという、\nあまりにも酷すぎる、喜劇じみた事実。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 103
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0101>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 57, 1)  ; 「たださ…朋の言うことにも\n一理あるんじゃないかって思ってるんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0103>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0104>, 58, 1)  ; 「依緒…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 105
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0105>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0106>, 59, 1)  ; 「これだけの喧嘩ってなると、\n冬馬が絡んでるってのは本当なのかなって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 105
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0107>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 60, 1)  ; 「例えばさ、冬馬さんが来日してきてから、\n春希が変に彼女のこと意識しすぎてたとか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 109
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0109>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 61, 1)  ; 「雪菜ちゃんに隠れて冬馬のコンサート行ったとかさ、\nお前、心当たりあるんじゃないのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0111>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 62, 1)  ; 「お前ら…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0113>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 63, 1)  ; 「なんで信じてくれないの…？\n二人とも、昨日まではわたしの言うこと\nマジメに聞いてくれてたじゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 64, 1)  ; 二人とも、俺を信じてる…だけじゃない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0116>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 65, 1)  ; 「どうして北原さんを目の前にすると、\nそんなふうにいきなり<R萎|しぼ>んじゃうのよ？\n雪菜のこと、心配じゃないの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 110
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0118>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 66, 1)  ; 「そりゃ、心配だよ。\n心配だけど…でも春希がさぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0120>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 67, 1)  ; 「今は、春希の話をちゃんと聞こうぜ？\nきちんと説明してもらえれば朋だって納得するだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 68, 1)  ; 武也も依緒も、俺を『信じたい』んだ。\n俺の口から『ありえない』って言葉が聞きたいんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 69, 1)  ; 雪菜と別れるなんてありえない。\n俺とかずさが未だに関係してるなんてありえない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0124>, 70, 1)  ; 俺たちの友情が壊れるなんて、\nそんなこと絶対にありえない、って…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0125>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0126>, 71, 1)  ; 「なぁ、春希…\nだから、正直に話してくれよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0127>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 72, 1)  ; 「依緒…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 73, 1)  ; 今、もし俺が口から出任せを言っても…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 74, 1)  ; 『悪い、ちょっとやっちゃってさ…』なんて、\n頭を掻きながら白々しく反省の表情を見せたとしても…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 75, 1)  ; 二人は、<Rあっち|とも>よりも、俺の言うことを信じるに違いない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 76, 1)  ; 『またか』みたいに呆れた笑いで、\n俺たち二人の仲直りのために\n協力を約束してくれるに違いない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 109
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0133>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0134>, 77, 1)  ; 「俺たちで力になれること、あるだろ？\n雪菜ちゃんのためにも、抱え込むなよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0135>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 78, 1)  ; 「武也…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0137>, 79, 1)  ; いつもなら、それで万事解決な…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 80, 1)  ; なぁなぁというか、\nちょっと出来レースっぽい俺たちの友情。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0139>, 81, 1)  ; だから今回も、そんなふうに平和な四人…\nいや、五人に戻れるかもしれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

@VCALL WN(RES<0140>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 82, 1)  ; 「俺…俺、は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 83, 1)  ; 何事もなかったかのように、\nほんの数日前の、俺たちに…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0143>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0144>, 84, 1)  ; 「………………かずさが、好きなんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 85, 1)  ; 馬鹿な…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 86, 1)  ; もう、戻れる訳なんか、ないだろ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0147>, 87, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 88, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 89, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 3006
PUSH INT 60
PUSH INT 1
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 19
PUSH INT 12
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 11
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 10
PUSH INT 110
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2091
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0150>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 90, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0152>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 91, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0154>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0155>, 92, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 93, 1)  ; 俺が、全てを…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 94, 1)  ; 『雪菜に告げたことの全て』を話し終わったとき、\n誰もが、絶句してた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 95, 1)  ; 俺の話す一つ一つの事柄が、\nあまりにも、柳原朋の指摘通りだったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 96, 1)  ; 武也と依緒が、すぐに思いつきながらも、\n必死で思い描こうとしなかった最悪の事実が、\n俺の口から語られてしまったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 107
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0160>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 97, 1)  ; 「は、はは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0162>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 98, 1)  ; 「依緒…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 99, 1)  ; 周囲の喧騒が痛いくらいに耳に響く。\nだって、このテーブルだけ静か過ぎたから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 100, 1)  ; 柳原朋は俺を睨みつけ、\n武也は依緒の横顔を見つめ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 101, 1)  ; そして依緒は、人ではなくテーブルを見つめ、\n細かく肩を震わせて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 300
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 2091
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 200
OPERATOR NEGATE
PUSH INT 60
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 0
PUSH INT 60
PUSH INT 3500
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 210
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 12
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0167>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 102, 1)  ; 「嘘だ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 103, 1)  ; 声まで、その肩の震えに合わせ、\n小さく振り絞った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0170>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 104, 1)  ; 「嘘って言え、春希…\nみんなをからかってたんだって…\n今すぐあたしを指差して笑ってくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0172>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 105, 1)  ; 「依緒…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0174>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 106, 1)  ; 「違う！\nあたしが聞きたいのはそんな声じゃない！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0176>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 107, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 108, 1)  ; 気遣うような俺の、依緒そっくりな調子の声は、\nあまりにも求めたものとは違うらしかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0179>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 109, 1)  ; 「そりゃ、あたしたちは知ってたよ…\n五年前、冬馬かずさが春希のこと好きだったって。\n雪菜に負けないくらいに本気だったって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 110, 1)  ; 俺の口から真実が零れた瞬間、\n依緒はとうとう、自分が疑うのをやめてしまった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0182>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0183>, 111, 1)  ; 「けれど、今の春希が受け入れたら駄目だろ？\nそんなの、彼女も最低だけど…\n春希、あんたはもっと最悪だよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 112, 1)  ; 今の俺が嘘をついていないって…\n今までの俺が嘘をついていたことを、やっと信じた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0185>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 113, 1)  ; 「何年雪菜と一緒にいたの…？\n何度裏切れば…\nどれだけ、あのコを傷つければ気が済むの…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 114, 1)  ; それは、ようやく上げた顔に貼りついた表情からも\nうかがえた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0188>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 115, 1)  ; 「何年、冬馬かずさと離れてたの…？\nなのに、どうして彼女なの？\nどれだけ拘れば気が済むの…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0190>, 116, 1)  ; 歯を食いしばり、頬を引きつらせ、\n瞳は潤み、今にも泣きそうで、\nけれどあまりに情けなくて泣くこともできなくて…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0191>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0192>, 117, 1)  ; 「あんたと雪菜の関係をぶち壊しておいて、\nさっさと逃げちゃった女なんだよ？\n一度捨てられたんだよ、春希？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 118, 1)  ; 悔しさと悲しさと、呆れと混乱と、\nおよそ負の感情を全てごちゃまぜにしたような…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0194>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 119, 1)  ; 「わかんない…\n春希の考えてること全然訳わかんないよっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 12
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 11
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 10
PUSH INT 110
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2091
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0196>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 120, 1)  ; 「………ごめん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0198>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 121, 1)  ; 「ごめんじゃないよ！\n春希が今するべきなのは、謝ることじゃないよ！\nどうしてそれがわからないんだっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0200>, 122, 1)  ; けれど、\nまだ友達だからこそ見せてくれる表情、だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 123, 1)  ; 依緒はまだ、諦めていなかった。\n必死で俺を引き戻そうとしてくれていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0202>, 124, 1)  ; 雪菜のために、俺が必要だって。\n俺と雪菜が一緒にいることが正しいって。\nそれが雪菜の、そして俺のためだって思ってくれていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 125, 1)  ; けれど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 14
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0204>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 126, 1)  ; 「雪菜を、どうするの…？\nあんなにボロボロにしといて、ポイって捨てちゃうの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0206>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 127, 1)  ; 「柳原…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0208>, 128, 1)  ; けれど彼女だけは、\nこの中でも明らかに雪菜寄りだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 6
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0209>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0210>, 129, 1)  ; 「ついこの間まで婚約だって言ってたんだよ？\nわざわざ天国から地獄に突き落として何がしたいの？\n雪菜が…何をしたって言うの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0211>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0212>, 130, 1)  ; 「それは…\nだから雪菜は、何も…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 8
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0213>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0214>, 131, 1)  ; 「そんなに雪菜のこと嫌いになっちゃったの？\nわざわざ深く傷つけるようなことばかりして…\nまるで親の敵みたいにさぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0215>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0216>, 132, 1)  ; 「違う…やめてくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 133, 1)  ; だから、武也も依緒も聞きたがらなかったことを、\n敢えて問うてくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0218>, 134, 1)  ; 一番確かめておかなくちゃならない、\nそして、一番俺が答えたくない問いを…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 17
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0219>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0220>, 135, 1)  ; 「今まで雪菜は、\n北原さんありきで進む道を決めてきたんだよ？\n北原さんのために、将来の可能性を狭めてきたんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 136, 1)  ; 柳原朋は、雪菜に求めることが俺とは違ってた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 137, 1)  ; 「進学も、就職も…\nそれに歌だって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0224>, 138, 1)  ; そう、たとえば歌。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 139, 1)  ; 彼女は、雪菜の歌の一番の理解者にして、\n熱狂的なファンにして、あくどいプロモーターだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0226>, 140, 1)  ; 雪菜が、小木曽雪菜であるよりも、\nＳＥＴＳＵＮＡである時間をもっと求めてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0227>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 141, 1)  ; 「あなたの側にいられること、\n二人で過ごす時間が取れること…\n必ずそれを条件の中に入れてきたんだよ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0229>, 142, 1)  ; けれど雪菜は、大学を卒業し、就職し、\nステージで歌う回数を、徐々に減らしていった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 143, 1)  ; 俺が一緒にステージに上がらないから。\n俺がライブを見に来ないから。\n俺と過ごす時間が減ってしまうから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0231>, 144, 1)  ; 本人の実力とかやる気とか、立ちはだかる現実とか、\n他にも原因は色々あったけど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 145, 1)  ; でも、そんな雪菜の決断に俺が絡んでいなかったなんて、\nそんなこと、誰も信じる訳がなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0233>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 146, 1)  ; 「だって、ずっと一緒に歩いていくつもりだったから。\nあなたと生きていくつもりだったからだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 147, 1)  ; それでも彼女は、雪菜の気持ちを考えて、\n雪菜の決める道を尊重してきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0236>, 148, 1)  ; ちょっと恨みがましい視線を俺に向けながらも、\nそれでも雪菜が俺に寄り添う姿を、\n苦笑交じりに見守っていてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 6
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0237>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 149, 1)  ; 「なのに、なんで今さら冬馬かずさ？\nどうして、雪菜じゃいけないの…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0239>, 150, 1)  ; けれど、そんな雪菜の決断が、\n今となっては、なんの意味もない行き止まりだったって、\nそんな酷い現実を知ってしまった…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 4
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0240>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 151, 1)  ; 「そんなに彼女は良かった？\n身体の相性、抜群だった？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0242>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 152, 1)  ; 「っ…違う」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0244>, 153, 1)  ; 俺には、彼女の怒りが十分に理解できる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 154, 1)  ; けれど、その怒りを鎮めることはできない。\nだから俺は、受け止めなければならない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0246>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 155, 1)  ; 「ちょっと昔の女が身体開いたからって、\nあっさりたらし込まれちゃってさ…\nそんなに気持ち良かった？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0248>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0249>, 156, 1)  ; 「そんなこと…言うな。\n俺のことはいいけど、かずさのことだけは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0250>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 157, 1)  ; 「実はすんごいテクニックだったとか？\nあ～、きっとピアノと同じで随分やり込んだんだろうね。\n…母親みたいにさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0252>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 158, 1)  ; 「やめろ、やめろ…っ！\n俺、かずさと寝てなんかない！\nあいつはそんな女じゃない！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 6
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0254>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 159, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0256>, 160, 1)  ; …それでも、かずさのことを言われるのだけは、\n受け止められなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0257>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0258>, 161, 1)  ; 「あいつだって辛くて、悩んで、苦しんで…\nだから…そんなふうに言わないでくれ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 162, 1)  ; かずさの気持ちだけは、\nかずさの名誉だけは尊重したかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0260>, 163, 1)  ; だって俺は、かずさを護るって決めたから。\n罰を受けるのは、俺だけで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 111
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0261>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 164, 1)  ; 「………なにそれ、最低」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0263>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0264>, 165, 1)  ; 「え…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 166, 1)  ; けれど反撃は、そして俺への断罪は、\n予想もしてなかった方向から、来た…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 110
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0266>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0267>, 167, 1)  ; 「寝てもいないのに、何もしてないのに、\n取り返しがつかなくなった訳でも、\n重いもの背負った訳でもないのに…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0268>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 168, 1)  ; 「ただ、彼女を愛してるからって理由だけで、\n雪菜を、切り捨てるの…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0270>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0271>, 169, 1)  ; 「依緒…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 170, 1)  ; 俺の意地は…\nかずさを護るための最後の砦は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0273>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 171, 1)  ; 「じゃあ、雪菜はなんだったの？\n心と身体の両方の繋がりを合わせても、\n彼女との心の絆に敵わないって言われたんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0275>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 172, 1)  ; 「………なに、を」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 173, 1)  ; でもそれは、彼女たちにとっては、\nまったくの逆効果だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 174, 1)  ; 依緒は…思いっきり退いていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0279>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 175, 1)  ; 「雪菜はなんだったの？\nそんなのが免罪符になるとでも思ってるの？\n春希…あんたどれだけ雪菜を見下してんのよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0281>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 176, 1)  ; 「え、いや、違…\nそんな…ま、待って…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 177, 1)  ; 顔色を失い、感情を失い、\n俺に対する熱さを、失っていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0284>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 178, 1)  ; 「これだけ周囲をボロボロに壊して、\n自分たちはプラトニックですって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 105
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0286>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0287>, 179, 1)  ; 「最低の純愛だね。吐き気がする」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0288>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 180, 1)  ; 「待ってくれよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 181, 1)  ; 今日で、友情は終わりだって覚悟してた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 182, 1)  ; 軽蔑されても、憎まれても、\n仕方ないって思ってた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0292>, 183, 1)  ; けれど…\n俺が想定していたよりもよっぽど、\n依緒のその言葉は…痛かった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0293>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0294>, 184, 1)  ; 「いいよ、もう…\n二人しかいない世界で、\n仲良くおままごとやってりゃいいじゃん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0295>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 185, 1)  ; 「ち、違う、違うって…\n聞いてくれ、依緒」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0297>, 186, 1)  ; こんなところに嫌悪感を示されるなんて…\n拒絶反応を起こされるなんて、想像もしてなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0298>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0299>, 187, 1)  ; 「どれだけ周囲を不幸にしてもさ…\n純粋な二人にはお互いのことしか見えないからいいよね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0300>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0301>, 188, 1)  ; 「かずさはさ…ずっと色々あって、\nこんなに有名になっても一人ぼっちで…\nだから俺が…俺しか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0302>, 189, 1)  ; 全てが終わるまではと、\n必死で我慢していたことが…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0303>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 190, 1)  ; 「雪菜は色々ないからいいんだ？\n一人ぼっちじゃないから捨ててもいいんだ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0305>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0306>, 191, 1)  ; 「そんなこと言ってないだろぉ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0307>, 192, 1)  ; これ以上雪菜を傷つけないためだからと、\n自らに厳しく課していた制約が。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0308>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0309>, 193, 1)  ; 「言ってるよ春希…\n雪菜は自分がいなくても一人じゃないから、\n可哀想じゃないから捨ててもいいって、言ってるよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 194, 1)  ; まったく意味がないどころか、\nかえって雪菜を貶めているって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0311>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 195, 1)  ; 「そ、んな…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0313>, 196, 1)  ; まだ、覚悟が全然足りてなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0314>, 197, 1)  ; 何もかも敵に回すって…\nここからはもう、誰も味方なんかいないって、\nそう言い聞かせていたはずだったのに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0315>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0316>, 198, 1)  ; 「依緒、俺は、俺はさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0317>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0318>, 199, 1)  ; 「痛いだろ？　春希」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0319>, 200, 1)  ; 痛い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0320>, 201, 1)  ; 本当の心が通じないのが痛い。\n相手を好きな気持ちがもう二度と伝わらないのが痛い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0321>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0322>, 202, 1)  ; 「でもな、春希…\n雪菜は…あんたに捨てられた雪菜はこんなもんじゃ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0323>, 203, 1)  ; そうか…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0324>, 204, 1)  ; これはあの時、雪菜が抱えていた絶望的な痛み。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0325>, 205, 1)  ; ただ、日を変え相手を変え、\n俺に返ってきた報い。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0326>, 206, 1)  ; 俺が受け止めなければならない、\n依緒からの、最後の…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 107
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0327>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0328>, 207, 1)  ; 「………帰れ、お前ら」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0329>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0330>, 208, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0331>, 209, 1)  ; けれど、心の中の何かが折れそうになった瞬間、\n静かなくせに迫力のある声が、俺を押し留めた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0332>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0333>, 210, 1)  ; 「春希を説得する気がないなら帰れ。\nただ言い負かしたいだけなら、もう二度と会うな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 19
PUSH INT 12
PUSH INT 30000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0334>)  ; 朋
PUSH INT 19
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 211, 1)  ; 「飯塚さん…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0336>, 212, 1)  ; 女性陣に『黙れ』と言われてから、\nずっと、その言葉を守り続けていた武也が。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0337>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0338>, 213, 1)  ; 「もう諦めろ。\nというか、お前らもう諦めてるじゃないか。\nいらねぇよこの場に」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 109
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0339>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0340>, 214, 1)  ; 「な…んだって？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0341>, 215, 1)  ; さっきから一人、ただ何も口にせず、\nじっと俺の横顔だけを眺めていた武也が、\n一瞬でこの場の空気を支配する。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 110
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0342>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0343>, 216, 1)  ; 「俺は諦めない。ちゃんと春希を説得する。\n…もう一度、雪菜ちゃんのことを考え直させる。必ず」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0344>, 217, 1)  ; あろうことか、女性陣の正義に牙を剥く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0345>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0346>, 218, 1)  ; 「だから、お前らみたいに春希を追い込む奴はいらない。\nとっととこの場からいなくなれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0347>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0348>, 219, 1)  ; 「武也…やめろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0349>, 220, 1)  ; 依緒を…否定する。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0350>, 221, 1)  ; ずっと、自分と同じ視線で俺と雪菜を見つめてきた、\n誰よりも気心の知れた相手を。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0351>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0352>, 222, 1)  ; 「なんだよ、それ…\n武也…春希を庇うのか？\nあたしの方が間違ってるって言うのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 107
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0353>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0354>, 223, 1)  ; 「知るかよそんなの。\nただ、今は春希と話すのにお前が邪魔なだけだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0355>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0356>, 224, 1)  ; 「っ…お、お前…\n春希とあたし…どっちの味方なんだよ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0357>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0358>, 225, 1)  ; 「決まってんだろそんなの…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0359>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0360>, 226, 1)  ; 「やめろっておい！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0361>, 227, 1)  ; 今この場面で、\nどう考えても武也が俺を庇う理由なんかなくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0362>, 228, 1)  ; そしてどう考えても、\n今この場面で正しいことを言ってたのは依緒と柳原で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0363>, 229, 1)  ; なのに俺は、\n武也が今から口にする名前が誰かわかってしまい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 107
PUSH INT 25000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0364>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0365>, 230, 1)  ; 「春希だよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0366>, 231, 1)  ; 鼻の奥が熱くなるのを止められなかった…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0367>, 232, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0368>, 233, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2911
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL SetMessageE(RES<0369>, 234, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 10
PUSH INT 106
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0370>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0371>, 235, 1)  ; 「ほら、酔いざまし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0372>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0373>, 236, 1)  ; 「…サンキュ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0374>, 237, 1)  ; あの後、女性陣二人はすぐに去っていった。\n…俺以上に、武也への非難の視線を強くして。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8061
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL SetMessageE(RES<0375>, 238, 1)  ; けれど、静かになったテーブルで、\nそのまま話を続ける気にもなれず、\n間もなく俺たちも、なんとなく店を出た。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0376>, 239, 1)  ; 武也は黙って街を歩き、\n俺は黙って武也の後についていき。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0377>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0378>, 240, 1)  ; 「お疲れ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0379>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0380>, 241, 1)  ; 「ああ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8202
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0381>, 242, 1)  ; 寒い夜空の下、やっと座れる場所を見つけ、\n男だけで缶コーヒーの乾杯をする。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0382>, 243, 1)  ; ほとんど酒を飲んでいなかった体に、\n温かいコーヒーの熱が徐々に染み込んでいく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0383>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0384>, 244, 1)  ; 「悪かったな。\nあんなことになっちまって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0385>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0386>, 245, 1)  ; 「あんなことになったのは俺のせいだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 108
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0387>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0388>, 246, 1)  ; 「…ま、そりゃそうだけどさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0389>, 247, 1)  ; 女性陣を追い出してから、\nいや、最初から、今日の武也は穏やかだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0390>, 248, 1)  ; 四人の中で、誰よりも皆に気を使い、\n愛想よく笑い、聞き役に徹し。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0391>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0392>, 249, 1)  ; 「後で、依緒とちゃんと仲直りしとけよ？\n俺、もう間に入れないんだからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 106
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0393>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0394>, 250, 1)  ; 「この期に及んで余計なお世話かよ。\n自分のしたことと立場をよく考えろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0395>, 251, 1)  ; まぁ、結局最後にはキれてしまったんだけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 108
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0396>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 140
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0397>, 252, 1)  ; 「あ～あ、なんで俺が\nこんな敗戦処理やらないといけないんだろうな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0398>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 141
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 253, 1)  ; 「敗戦処理って…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0400>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 142
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 254, 1)  ; 「間違ってようが正しかろうが、\n本気になった時のお前が意見を曲げないなんて、\n俺が一番よく知ってるってのに…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0402>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 143
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0403>, 255, 1)  ; 「武也…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0404>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 144
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0405>, 256, 1)  ; 「本当に、なんでこんなことになるんだか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0406>, 257, 1)  ; いや、最初から途中でキれるつもりだったのかも。\n最終的に自分で決着をつけるつもりで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0407>, 258, 1)  ; 俺を説得できなかったという事実を、\n全部、自分の責任として被るつもりで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0408>, 259, 1)  ; それはまるで、いつもは俺がやってたことを、\nこれからは自分の役目だと覚悟したかのようで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 3012
PUSH INT 120
PUSH INT 1
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0409>, 260, 1)  ; ほとんど飲んでなかったせいもあって、\n真冬の寒さがじわじわと染みてくる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0410>, 261, 1)  ; 手に持った缶コーヒーはあっという間に冷めてしまい、\nもう、手も体も温めるほどの熱量を持っていなくて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0411>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 145
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0412>, 262, 1)  ; 「…武也」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0413>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 146
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0414>, 263, 1)  ; 「ん～？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0415>, 264, 1)  ; そんな寒さが、俺の孤独感を呼び覚ましたのか、\nそれとも他の理由なのかはわからないけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0416>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 147
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0417>, 265, 1)  ; 「ちょっとだけ、話を聞いてくれるか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0418>, 266, 1)  ; ただ、目の前のただ一人にだけは、\n伝えておきたいと思った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0419>, 267, 1)  ; ほんの少し言い訳じみた、真実のうちの一つを。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0420>, 268, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 10
PUSH INT 111
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0421>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 148
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0422>, 269, 1)  ; 「峰城大病院って…なんつ～灯台の真下だよ。\nマスコミ全然気づいてないじゃん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0423>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 149
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0424>, 270, 1)  ; 「政治家や芸能人もよく入院してるらしいからな。\nそういう方面のケアは万全なんだろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0425>, 271, 1)  ; 冬馬曜子の病名と入院先を聞いたとき、\n武也は、ほんの少し言葉を失った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0426>, 272, 1)  ; まぁ、そういう反応をするのは当然だとわかってた。\nそれどころか、思った以上に冷静に対処してくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0427>, 273, 1)  ; 武也にとっては他人だったからなのか、\nそれとも、俺の態度に思い当たる節でもあったのか。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0428>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 150
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0429>, 274, 1)  ; 「もちろん他言無用で頼むな。\n日本だと、色々と騒がれるかもしれないし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 109
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0430>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 151
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0431>, 275, 1)  ; 「雪菜ちゃんにも？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0432>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 152
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0433>, 276, 1)  ; 「…雪菜にこそ、絶対に」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 111
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0434>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 153
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0435>, 277, 1)  ; 「なんで？\nどう考えても理由の一つだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0436>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 154
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0437>, 278, 1)  ; 「こんなの、ただの言い訳だ。\n俺が間違った選択をしてることに変わりない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 110
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0438>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 155
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0439>, 279, 1)  ; 「ああ、そうだな。\nお前は間違ってる。\n…雪菜ちゃんに正直に話すべきだった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0440>, 280, 1)  ; 武也の指摘する『間違い』は、\n俺の思い描く『間違い』と少しずれていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0441>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 156
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0442>, 281, 1)  ; 「お前がそれを正直に話したら、雪菜ちゃんは、\n一緒に背負ってくれようとするかもしれないじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0443>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 157
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0444>, 282, 1)  ; 「………かもな。\n雪菜だし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0445>, 283, 1)  ; けれど、俺も武也もわかってる。\n二人の論点が違うってことが。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 105
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0446>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 158
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0447>, 284, 1)  ; 「そしたらさ…\nもしかしたらその先に、\nもっといい答えがある可能性だって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0448>, 285, 1)  ; そして、俺はもう少し余計にわかってる。\n…武也が、わざと論点をずらしたってことも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 109
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0449>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 159
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0450>, 286, 1)  ; 「ないのか…そういう選択？\n今からでも、三人で話し合うことできないのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0451>, 287, 1)  ; みんなで少しずつ知恵を出しあって、\nみんなで少しずつ辛さを負担しあって、\nより良い解決法を探っていこうって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0452>, 288, 1)  ; いつもなら、俺が言い出すような三方一両損。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0453>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 160
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0454>, 289, 1)  ; 「もう、無理だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 107
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0455>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 161
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0456>, 290, 1)  ; 「なんで…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0457>, 291, 1)  ; けれどその選択肢は…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0458>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 162
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0459>, 292, 1)  ; 「俺は、かずさと生きることを選んだんだ。\n雪菜を、巻き込まないって誓ったんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0460>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 163
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0461>, 293, 1)  ; 「巻き込まれた方が幸せなことだってある！\n雪菜ちゃんなら、ぜったいにそう思ってくれる！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0462>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 164
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0463>, 294, 1)  ; 「それでも…もう駄目なんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0464>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 165
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0465>, 295, 1)  ; 「だから、なんでっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0466>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 166
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0467>, 296, 1)  ; 「………もし三人で背負ったら、\n俺はもう、二人のうちからかずさを選べなくなる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0468>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 167
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0469>, 297, 1)  ; 「っ！？\nお…お前…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0470>, 298, 1)  ; その選択肢を選べるのは、\n俺が、かずさを諦める決心をした時だ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0471>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 168
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0472>, 299, 1)  ; 「俺、やっぱりかずさが好きだった。\n俺だけのものにしたかったんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0473>, 300, 1)  ; もしかずさの境遇を三人で背負って、\nその結果、三人が幸せになれた時…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0474>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 169
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0475>, 301, 1)  ; 「二年前、吹っ切ったと思ってたけど違ってた。\nずっと昔から、何も変わってなかった。\n二年間、自分でも気づかないうちに嘘を重ねてたんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0476>, 302, 1)  ; かずさは、もう俺を奪うことはしない。\nいつしか一人、静かに消えていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0477>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 170
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0478>, 303, 1)  ; 「だから、雪菜には頼れない。\n…ただの、エゴだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0479>, 304, 1)  ; その先に、俺の側に寄り添うかずさはいない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0480>, 305, 1)  ; 幸せな三人と、幸せな二人と…\nそして、幸せになれなかった二人が、残る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0481>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 171
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0482>, 306, 1)  ; 「お前、最低だな。\nそして冬馬も…最低だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0483>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 172
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0484>, 307, 1)  ; 「かずさは関係ない。\n全部俺の…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0485>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 173
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0486>, 308, 1)  ; 「お前がどんなに庇っても、\n向こうにどんな事情があっても、\n冬馬が酷いことをしたって事実に変わりはないんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0487>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 174
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0488>, 309, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 110
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0489>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 175
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0490>, 310, 1)  ; 「本当に愛し合ってる…\n婚約までしてる恋人同士を引き裂いてまで、\n男を自分のものにしようとしてんだぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0491>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 176
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0492>, 311, 1)  ; 「今まで俺が見てきた中にも、\nそんな酷ぇ女いやしなかった。\n…最悪の地雷だよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0493>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 177
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0494>, 312, 1)  ; 「あ、あ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0495>, 313, 1)  ; 反論、できなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 150
PUSH INT 100
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 150
OPERATOR NEGATE
PUSH INT 100
PUSH INT 4000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0496>, 314, 1)  ; 『やめろ、やめろ…』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0497>, 315, 1)  ; 理論よりも、感情が追い越してしまったせいで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0498>, 316, 1)  ; 『かずさを…俺のかずさをいじめるな』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0499>, 317, 1)  ; そんな稚拙な言葉しか浮かんでこなかったせいで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0500>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 178
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0501>, 318, 1)  ; 「俺、お前のこと見損なってたよ。\nもっと分別のある奴だって…\n少なくとも俺よりはって、そう思ってたんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0502>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 179
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0503>, 319, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0504>, 320, 1)  ; 何も言い返せない俺を見て、\n武也が、呆れたような、納得したようなため息をつく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0505>, 321, 1)  ; ほんの少し前、依緒と柳原を必死で抑え込んで、\nまだこんな俺の味方だと言い切ってくれた武也が…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0506>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 180
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0507>, 322, 1)  ; 「今だって、本当は口もききたくないんだ。\nそのくらい、お前のことを軽蔑してんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0508>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 181
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0509>, 323, 1)  ; 「…ごめん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0510>, 324, 1)  ; とうとう、その武也までもが、\n俺の前から、去って…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

@VCALL WN(RES<0511>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 182
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0512>, 325, 1)  ; 「けど俺、お前の親友だから。\n望みがないってわかってるけど、\nそれでも、まだお前の親友だからさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0513>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 183
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0514>, 326, 1)  ; 「武也…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 10
PUSH INT 110
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 8
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0515>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 184
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0516>, 327, 1)  ; 「だから、これが最後の頼みだ…\n頼むよ春希…元のお前に、戻ってくれよっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0517>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 185
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0518>, 328, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0519>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 186
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0520>, 329, 1)  ; 「お前が一言、雪菜ちゃんの元に戻るって言ってくれれば、\n俺がなにもかも元通りに戻してやる！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0521>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 187
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0522>, 330, 1)  ; 「お前…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0523>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 188
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0524>, 331, 1)  ; 「依緒も、朋も…みんな説得する！\nお前の言ってしまったこと全部なかったことにしてやる。\nだから、だから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0525>, 332, 1)  ; あ、こいつ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0526>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 189
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0527>, 333, 1)  ; 「頼む…頼むから撤回してくれ！\n悪い冗談だったって、\n笑いながら謝ってくれればいいんだよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0528>, 334, 1)  ; 本物の親友、だったんだ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0529>, 335, 1)  ; 俺にとって、唯一の…\nもう、二度と出会えないかもしれない存在、だったんだ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0530>, 336, 1)  ; 雪菜とも、かずさとも違う、\nもう一人の、世界で一番大切な…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0531>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 190
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0532>, 337, 1)  ; 「武也…俺」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0533>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 191
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0534>, 338, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0535>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 192
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0536>, 339, 1)  ; 「無理だよ、もう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 112
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0537>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 193
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0538>, 340, 1)  ; 「っ…い、いぅぁぁぁぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0539>, 341, 1)  ; …大切、だった奴。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0540>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 194
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0541>, 342, 1)  ; 「最初から間違ってるってわかってるんだ。\nそれでも、最初から直すつもりがないんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0542>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 195
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0543>, 343, 1)  ; 「なんでだ、なんでだよ…\n信じらんねぇよ…どうしてだよ春希…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0544>, 344, 1)  ; なんだよ、馬鹿みたいだ。\n…失う今になって、その大切さがわかるなんて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0545>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 196
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0546>, 345, 1)  ; 「俺…いつもこんなだよ。\n基本的に、馬鹿なんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0547>, 346, 1)  ; 本当に、馬鹿みたいだ。\n今の俺は、こんなことばっかりだ…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0548>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 197
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0549>, 347, 1)  ; 「正しいことをしようと思うけど、間違える。\n何が正しいのかわかってるのに、\nそれでも間違ったことをしてしまうんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0550>, 348, 1)  ; 新しい発見は、嬉しさと、悔しさと、切なさと。\nそして、懐かしさを俺の心に運んでくれる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0551>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 198
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0552>, 349, 1)  ; 「だからって…間違えすぎだろよ…\n俺にだってできねぇぞ。\n雪菜ちゃんを…あんないいコを捨てるなんて…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0553>, 350, 1)  ; こんな絶望的な状況の中で、\n必死に泣くのを堪えてる表情が、\nほんの一瞬、緩んでしまうほどだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0554>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 199
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0555>, 351, 1)  ; 「撤回、してくれよ…\nでないと俺、今度こそ本当に、\nお前のこと軽蔑しなくちゃならなくなるんだぞ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0556>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 200
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0557>, 352, 1)  ; 「わかってる、よ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0558>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 201
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0559>, 353, 1)  ; 「お前を庇えなくなる…庇いたくなくなる。\n最低な奴だって、認めてしまうんだぞ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0560>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 202
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0561>, 354, 1)  ; 「もう、これ以上俺を庇うな。\nお前まで、友達なくすぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0562>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 203
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0563>, 355, 1)  ; 「春希ぃぃっ…\nお前、お前…マジ、かよっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0564>, 356, 1)  ; ありがとう、武也…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0565>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 204
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0566>, 357, 1)  ; 「嘘だ…嘘だろぉ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0567>, 358, 1)  ; けど、もう、泣くのはよしてくれ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0568>, 359, 1)  ; だって俺の方は、泣くことは許されないんだから。\n俺が悲しむことは、あってはならないんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0569>, 360, 1)  ; 全て自分でしでかしたことだから。\n仕方なかったことなんて、何一つなかったんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0570>, 361, 1)  ; 避けられた運命を、ただ自分の欲望のためだけに、\n選んでしまったんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0571>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 205
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0572>, 362, 1)  ; 「もう、行けよ。\nこれ以上話しても、平行線だ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0573>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 206
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0574>, 363, 1)  ; 「待てよ…待ってくれよ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0575>, 364, 1)  ; 本当に、本当に…\nありがとう、武也。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0576>, 365, 1)  ; お前のおかげで俺は、少しだけ救われた…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0577>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 207
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0578>, 366, 1)  ; 「お前が行かないなら、俺が先に行くわ。\nじゃあな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0579>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 208
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0580>, 367, 1)  ; 「許さねえ…\n一生、許さないからな、春希ぃ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0581>, 368, 1)  ; もう、壊れてしまったけれど…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0582>, 369, 1)  ; それでも、ほんの少し前までは、\n俺たちの間には真の友情があったって…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0583>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 209
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0584>, 370, 1)  ; 「さよなら…武也」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0585>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 210
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0586>, 371, 1)  ; 「ふざけんなぁぁぁぁ～っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0587>, 372, 1)  ; これからも、信じていける。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL SetMessageE(RES<0588>, 373, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0589>, 374, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0590>, 375, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3002
PUSH INT 30
PUSH INT 1
PUSH INT 60
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2061
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 42
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL SetMessageE(RES<0591>, 376, 1)  ; 電車は、まだ動いてるみたいだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2013
PUSH INT 2
PUSH INT 23
PUSH INT -1
PUSH INT 0
CALL Calender
OPERATOR POP

@VCALL SetMessageE(RES<0592>, 377, 1)  ; ただでさえ、ほとんど２４時間眠らないこの街の駅は、\n日付の変わったこの冬の深夜でも、\n改札口から出入りする人たちを大量に飲み込み、吐き出す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0593>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 211
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0594>, 378, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0595>, 379, 1)  ; そんな、駅前の人の群れにほっとしてしまったのか、\n今までこらえていたものが溢れそうになり、\n思わず空を見上げるしかなくなる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0596>, 380, 1)  ; この街の灯りに星をほとんど消されてしまい、\nただ、月だけがぼんやりと浮かんでる空を。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0597>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 212
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0598>, 381, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0599>, 382, 1)  ; 夢でも見ているような心地だった。\nもちろん、いい夢なんかじゃない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0600>, 383, 1)  ; 付属に入って、一番最初にできた友達だった。\nいつも、俺の人間関係の中心にいやがった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0601>, 384, 1)  ; 終わらない腐れ縁だと諦めつつ受け入れてるつもりの、\n勝手に続いていく友情だと思ってた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0602>, 385, 1)  ; 俺は、あいつらの将来が心配だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0603>, 386, 1)  ; 俺以上に腐れ縁で、俺たち以上に素直じゃなくて、\n十年近くも、何も進歩してない二人がもどかしかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0604>, 387, 1)  ; いつか、何とかしてやりたいと思ってた。\n二年前、あいつらが俺を救ってくれたように。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0605>, 388, 1)  ; でも、そんな俺たちを繋ぐ全てのものが、\nなにもかも水泡に帰した。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0606>, 389, 1)  ; ただ、俺一人の過ちのせいで。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 8193
PUSH INT 0
PUSH INT 1
PUSH INT 100
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0607>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 213
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0608>, 390, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0609>, 391, 1)  ; なのに、今の俺には、\nそれを嘆く時間も与えられていない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0610>, 392, 1)  ; 柳原に憎まれたこと、依緒に愛想を尽かされたこと、\nそして武也を…親友を失ったことを泣かせてもくれない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0611>, 393, 1)  ; 神様、俺、そんなに酷いことしましたか…？
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0612>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 214
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0613>, 394, 1)  ; 「はい…北原です」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

@VCALL WN(RES<0614>)  ; 雪菜の父
PUSH INT 13
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 215
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0615>, 395, 1)  ; 「小木曽です。\n…雪菜の、父です」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0616>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 216
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0617>, 396, 1)  ; 「………こんばんは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0618>, 397, 1)  ; いや………したんですよね。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0619>  ; CATCH3
PUSH INT 100
CALL SCall
OPERATOR POP

ARRAY_S RES<0620>  ; 3107
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
