!RESOURCE "3201.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3201
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2013
PUSH INT 2
PUSH INT 14
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2100
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 150
PUSH INT 60
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
OPERATOR NEGATE
PUSH INT 60
PUSH INT 5000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 9
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0004>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「さて本日２月１４日。\nバレンタインデーのニュースです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「まずはマイリースポーツさんの記事ですが…\n『冬馬かずさ追加公演中止？』」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0008>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「１月の来日初コンサートも好評で、\n今月末、追加公演が既に決定している\nピアニスト冬馬かずささんですが…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0010>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「実は現在、深刻な体調不良ということで\n次回公演の開催が危ぶまれていることが、\n関係者の話で明らかになりました」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0012>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「前回のコンサート以来、かずささんは、\nプロデューサーであり母親の冬馬曜子さんとともに、\n報道陣の前に一切姿を現さなくなりましたが…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0014>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 5, 1)  ; 「実は、前回のコンサートの後に体調不良を訴え、\n現在は都内の病院で療養していると言うんですね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0016>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 6, 1)  ; 「というのもですね、実は先週、\nかずささんの滞在先と思われるホテルに\n深夜救急車が出動する騒ぎがありまして…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 7, 1)  ; 「その時運び出された女性が\n彼女ではないかという目撃者の証言もあり、\nここに来て追加公演の開催が危ぶまれています」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 8, 1)  ; 「なお、この件に対して冬馬曜子オフィスは昨夜、\n『こちらではそのような報告を受けておりません。\n現在確認中です』とのコメントを発表しました」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0022>)  ; 男性アナウンサー
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 9, 1)  ; 「冬馬かずささんの日本公演に関しては、\n発売一時間でチケットが完売するほどの、\nクラシックとしては異例の大人気となっていまして…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8442
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL VS
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
PUSH INT 2100
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0024>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 10, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 5
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 8260
PUSH INT 60
PUSH INT 1
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 30
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2027
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0026>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 11, 1)  ; 「どういうことですかこの広告…\n確か２１００円って話でしたよね？\nなんで３１５０円になってるんです？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0028>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 12, 1)  ; 「いくら増刊号だからってこの価格は…\nえ？　俺が強く推したって？　なんですそれ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0030>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 13, 1)  ; 「………はぁ？\n聞いてませんよ、全然！\nなんでそんな話になってんです？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0032>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 14, 1)  ; 「ええ、ええ………何ですって？　そんな…\nそれ、初っ端に向こうにハねられた企画じゃないですか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0034>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 15, 1)  ; 「吉松さんが通したんですか？　それ。\nえ、だから俺じゃ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 10
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0036>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 16, 1)  ; 「………ってことは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0038>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 17, 1)  ; 「…どうやら二人とも、部下に騙されてたみたいですね。\nええ、ええ、わかりました。とにかく本人と話してみます。\nそれじゃ、失礼します」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 0
PUSH INT 8452
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0040>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 18, 1)  ; 「北原ぁ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0042>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 19, 1)  ; 「北原！\nどこ行きやがったこの野郎！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 9
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0044>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 20, 1)  ; 「う～るさいな～も～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 6
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0046>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 21, 1)  ; 「北原なら打ち合わせで直帰になってますよ。\n浜田さんが出社する前に顔出してましたけどね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0048>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 22, 1)  ; 「…もしかして逃げやがったか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0050>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 23, 1)  ; 「そろそろアンサンブル増刊号の\n締め切りも近づいてきたみたいだし、\nそっちで忙しいんじゃないですかね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0052>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 24, 1)  ; 「本職のグラフでは一番下っ端なのに、\n部員の中で一番仕事の範囲が広いもんねぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 4
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0054>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 25, 1)  ; 「風岡二世の名は伊達じゃない…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 10
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0056>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 26, 1)  ; 「呑気に言ってる場合じゃない。\nその増刊号がえらいことになってんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 6
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0058>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 27, 1)  ; 「えらいことって？\n冬馬かずさのヌードグラビアでも載るとか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 4
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0060>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 28, 1)  ; 「いやそれ社長賞ものだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0062>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 29, 1)  ; 「ある意味これも特ダネだけど…\nでも、どうやって企画通したんだ？\nいつの間にタイアップ先まで決めてきたんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0064>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0065>, 30, 1)  ; 「タイアップ？\nどんどん話おっきくなってきたねぇ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0066>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0067>, 31, 1)  ; 「忘れないでくださいね？\nあいつ、一年目のペーペーですよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0068>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 32, 1)  ; 「かと思えば追加公演中止なんて噂も流れてるし…\n訳わかんねえよ。\n一体どうなってんだよ北原！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0070>)  ; 携帯アナウンス
PUSH INT 98
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 33, 1)  ; 「留守番電話センターに接続します。\n合図の後、３０秒以内でメッセージをお願いします」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 3002
PUSH INT 60
PUSH INT 1
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 10
PUSH INT 109
PUSH INT 26000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2096
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0072>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 34, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 10
PUSH INT 109
PUSH INT 26000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 11
PUSH INT 101
PUSH INT 26000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2096
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0074>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 35, 1)  ; 「お待たせ。\nこっち済んだわよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0076>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 36, 1)  ; 「ああ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 11
PUSH INT 103
PUSH INT 26000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0078>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 37, 1)  ; 「なに？　まだ繋がらない？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0080>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 38, 1)  ; 「週明けてからずっと留守電ばかりだ。\nどうなってんだよ春希…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0082>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 39, 1)  ; 「締め切りが近くて連日徹夜とか？\n確か来月発売の本、メインで任されたんでしょ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0084>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 40, 1)  ; 「にしたって事前に一言あるだろあいつなら。\n何しろ今日は…本当に来るつもりあるのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 101
PUSH INT 26000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0086>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 41, 1)  ; 「信じるしかないよ。\n春希だって、今日がどんな日か忘れてる訳ないし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0088>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 42, 1)  ; 「けど、最近おかしかったろ？　あの二人」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 110
PUSH INT 26000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0090>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 43, 1)  ; 「それは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 105
PUSH INT 26000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0092>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 44, 1)  ; 「なんか会ってる気配なかったし、\n雪菜ちゃんに聞いても、どことなくぎこちなかったし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 103
PUSH INT 26000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0094>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 45, 1)  ; 「でもほら、『お互い忙しくて』って言ってたじゃん。\n今は仕方ないんじゃないのかな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0096>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 46, 1)  ; 「…まさかあいつ、\nまだ冬馬のこと引きずってるんじゃないだろうな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 107
PUSH INT 26000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0098>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 47, 1)  ; 「っ、や、やめてよそういうこと言うの！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0100>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 48, 1)  ; 「だってさ…公演キャンセルって噂が出てるんだぜ？\nあいつ、絶対気にしてるだろ？\nもしかして、冬馬のところに…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0102>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 49, 1)  ; 「だからやめろって～！\nあたしまで不安になってきちゃうじゃん！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 103
PUSH INT 26000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0104>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 50, 1)  ; 「まぁいくらなんでも、\n今の冬馬と春希とじゃあり得ないか…\nうん！　ないない！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 108
PUSH INT 26000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0106>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 51, 1)  ; 「…しかも人の不安煽っておいて\n自己解決しないでよね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 10
PUSH INT 101
PUSH INT 26000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0108>)  ; 武也
PUSH INT 10
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 52, 1)  ; 「ま、とにかく今日、\nそこんとこハッキリ確かめとこうぜ。\nそろそろ向かうか。雪菜ちゃんもう帰ってるって？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 11
PUSH INT 101
PUSH INT 26000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0110>)  ; 依緒
PUSH INT 11
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 53, 1)  ; 「そういえば…実はこっちも今朝からさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 54, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 16
PUSH INT 105
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2085
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 41
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0113>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 55, 1)  ; 「で、あの飛ばし記事、美代ちゃんが流したの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0115>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 56, 1)  ; 「一部マスコミの間で、\n社長の病気のことが取り沙汰されていたので、\n目先を変えておこうかと思いまして」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 16
PUSH INT 103
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0117>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 57, 1)  ; 「…なるほど、かずさの件がガセとわかったら、\n今度は冬馬曜子だと言っても誰も信用しない、か」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0119>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0120>, 58, 1)  ; 「『ピンチをチャンスに変える会話術』は\n社長に鍛えていただきましたから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0121>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 59, 1)  ; 「さすがは冬馬曜子オフィス随一の切れ者。\nやってくれるわね～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0123>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0124>, 60, 1)  ; 「そもそも日本オフィスには私一人しかいませんし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2072
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0125>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0126>, 61, 1)  ; 「…で、あの子はまだ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0127>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 62, 1)  ; 「ええ、客室から一歩も出てきません。\n…そろそろ一週間になるんですけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0129>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 63, 1)  ; 「そう…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0131>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 64, 1)  ; 「一応、毎日三回は伺ってるんですけど、\n未だにドアを開けてくれません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0133>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0134>, 65, 1)  ; 「ごめんね美代ちゃん。\nうちの娘が迷惑かけて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0135>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 66, 1)  ; 「いいんです。\n彼女の気持ち、痛いほどわかりますから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0137>)  ; 曜子
PUSH INT 16
PUSH INT 128
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 67, 1)  ; <F16「…本当はわかるわけないんだけどね」>
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0139>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 68, 1)  ; 「私だって泣きたいくらいショックなんですよ？\n社長が引退しちゃったら、\n冬馬曜子オフィスはどうなるんですか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0141>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 69, 1)  ; 「まぁ、その件は退院してから相談するとして、\nそれで、コンサートの準備の方は？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0143>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0144>, 70, 1)  ; 「そちらは準備万端です。\n開催についても…撤退についても。\n例の記事も半分はそれが狙いですから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0145>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 71, 1)  ; 「…やっぱり冬馬曜子オフィス随一の切れ者ね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0147>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 72, 1)  ; 「社長が決断した瞬間に、\nすぐに各方面が動けるように手配しています。\n損害も最小限に抑えられるように手を打ちました」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0149>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0150>, 73, 1)  ; 「ありがとう美代ちゃん。\n…でも大丈夫、追加公演は予定通り開催するわ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0151>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 74, 1)  ; 「…やるんですか？\n正直、今のかずささんを見ていると、\nとてもあと二週間で元通り弾けるようになるとは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0153>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 75, 1)  ; 「それでもやるわよ。\nついでにね、コンサート前にもう一仕事入れたわ。\n今夜、担当がそっちに行く手はずになってるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0155>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 76, 1)  ; 「はぁっ！？　何言ってるんですか社長！？\n今の状況わかってるんですか！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0157>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 77, 1)  ; 「冬馬親子は不治の病と恋の病に冒されて、\n二人揃ってピアニスト生命の危機…ってところかしら？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0159>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0160>, 78, 1)  ; 「わかってるなら考え直してください。\nコンサートのことだけでも慎重な対応が必要なのに、\nこの上まだ負担をかけるなんて！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0161>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 79, 1)  ; 「…まぁね、実はわたしもちょっとビビってる。\nあまりにもやりすぎなんじゃないかなって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0163>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 80, 1)  ; 「でしたら！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0165>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 81, 1)  ; 「でも…今はその劇薬にすがるしかないかなって。\n日本でなければできないことがあるかなって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0167>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 82, 1)  ; 「でも彼女、今は誰とも会おうとしないんですよ？\nわたしでさえ部屋に入れてくれないんですから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0169>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0170>, 83, 1)  ; 「…それは多分大丈夫。\nとにかく美代ちゃんは、担当の人が来たら、\n部屋の前まで案内するだけでいいから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0171>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 84, 1)  ; 「そこから先は本当に責任持てませんよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0173>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0174>, 85, 1)  ; 「ええ、それでいいわ。\n…だってあの子は、その人に対してだけは、\n逃げることは許されないから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0175>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 86, 1)  ; 「…よくわかりませんけどわかりました。\nやります。仕事ですから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0177>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 87, 1)  ; 「本当、いつもいつも面倒かけてゴメンね？\n退職金弾むから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0179>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 88, 1)  ; 「冗談でもそう言う縁起でもないこと\n言わないでください！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0181>)  ; 曜子
PUSH INT 16
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 89, 1)  ; 「それじゃね美代ちゃん。\nあとよろしく～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 2205
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0183>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 90, 1)  ; 「もうっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0185>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 91, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0187>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0188>, 92, 1)  ; 「…恋の病？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 93, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1901
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0190>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 94, 1)  ; 「すいません、開けてください」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 8
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2100
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1901
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0192>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 95, 1)  ; 「今、お客様をロビーに待たせてるんです。\n社長から、その方と会うようにという指示も来てるんです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1901
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0194>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 96, 1)  ; 「お願いします、そろそろ外に出てきてください！\nせめて食事だけでも！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1901
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0196>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 97, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0198>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 98, 1)  ; 「今日は…今日は簡単に引き下がりませんよ？\n返事をしてくれるまで、ずっとここで待ってますからね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 1901
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL WN(RES<0200>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 99, 1)  ; 「元気ですか？　起きてますか？\n…意識、ちゃんとしっかりしてるんですか？\nお願いですから、これ以上心配かけないで…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0202>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0203>, 100, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 2202
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 8453
PUSH INT 0
PUSH INT 1
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0204>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 101, 1)  ; 「あ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 0
CALL SES
OPERATOR POP

PUSH INT 0
PUSH INT 8194
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2137
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0206>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 102, 1)  ; 「ごめん、なさい…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0208>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 103, 1)  ; 「か、かずささん？\nかずささんなんですね！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0210>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 104, 1)  ; 「ごめんなさい美代子さん…\n本当に…ごめん…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0212>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 105, 1)  ; 「よ、良かったぁ…\nとにかく大丈夫なんですね？\nお腹、すいてません？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0214>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 106, 1)  ; 「いい…何も食べたくない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0216>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 107, 1)  ; 「かずささん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0218>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 108, 1)  ; 「…わかんないよ、もう。\nなにも、わかんない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0220>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 109, 1)  ; 「…とにかく、ここ開けてください。\n落ち着いて話をしましょう？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 110, 1)  ; 「駄目だよ…今は人に会えない。\nどんなこと言い出すか、どんなことしてしまうか、\n自分でもわからないんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0224>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 111, 1)  ; 「だからこそ人に会うべきなんですよ…\n自分一人で考え込んじゃったら、\n何もいい解決策なんか浮かんできませんよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0226>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 112, 1)  ; 「でも、でも…でもっ、\n駄目だよあたし…もうこの国にいるのは嫌だ…\nウィーンに帰る」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0228>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0229>, 113, 1)  ; 「社長は…お母さんのことはどうされるんです？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0230>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0231>, 114, 1)  ; 「っ…わからない、だから何もわからないんだって！\nどうしたらいいかわからないから逃げたいんじゃないかぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8401
PUSH INT 0
PUSH INT 0
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 0
PUSH INT 8402
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 131
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2100
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0232>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0233>, 115, 1)  ; 「なのに、どうしたらいいかわからないから逃げられない。\nもう、とっくに荷造りだって済ませたのに、\nここから外に出られない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0234>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 116, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0236>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0237>, 117, 1)  ; 「なにもできない。決められない。動けない。\n生きてる価値ないよ、もう…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0238>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0239>, 118, 1)  ; 「そんな、そんなこと………あ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0240>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 119, 1)  ; 「今日は…帰って。\n大丈夫、まだ生きてるよ。\n生き恥、さらしてるよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0242>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 120, 1)  ; 「え、ええ、ここなんですけど…\nでもその、やっぱりまだ体調が悪いみたいで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 130
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0244>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 121, 1)  ; 「………？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0246>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 122, 1)  ; 「はい、だから今日のところは…え？\nあ、でも、その…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0248>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0249>, 123, 1)  ; 「美代子さん…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0250>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 124, 1)  ; 「は、はい、確かに冬馬はそう申してましたが。\n………信じていいんですね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0252>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 125, 1)  ; 「じゃあ…切るよ、もう」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0254>)  ; 美代子
PUSH INT 35
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 126, 1)  ; 「あ、ちょっと待ってくださいかずささん。\n今、代わりますから！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 130
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0256>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 127, 1)  ; 「代わる、って、\n…誰に？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

@VCALL WN(RES<0258>)  ; ？？？
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 128, 1)  ; 「いつもお世話になっております。\nわたくし、ナイツレコードの…小木曽と申します」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0260>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 129, 1)  ; 「～～～っ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

@VCALL WN(RES<0262>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 128
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 130, 1)  ; 「久しぶりだね………かずさ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0264>, 131, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 132, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0266>, 133, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8219
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 0
PUSH INT 8240
PUSH INT 0
PUSH INT 0
PUSH INT 200
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0267>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 120
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0268>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 129
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 134, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 135, 1)  ; 朝までという願いも虚しく、\n雪は、一時間も経たずにやんでしまっていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0271>, 136, 1)  ; 始発が動き出すまでにはまだ時間があり、\nタクシーを使ってまで動こうという気力も湧かず。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 137, 1)  ; 俺は、この寒さの中、他に佇む人もいない公園のベンチで、\n徐々に雲が切れていく空を見上げていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0273>, 138, 1)  ; そう…\n俺は、動くことすらできなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 201
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0274>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 130
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 139, 1)  ; 「こんばんは」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0276>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 131
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 140, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 141, 1)  ; なのに雪菜は、こんなどうしようもない俺のために、\nこんな真夜中に、タクシーを飛ばしてここに来てくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 200
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0279>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 132
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 142, 1)  ; 「これ、使い捨てカイロ。\n懐に入れて温めておきました…なんてね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0281>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 133
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 143, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 144, 1)  ; カイロを握らせてくれる雪菜の手が、\nカイロよりも温かく、俺の全身に染みる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 201
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0284>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 134
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 145, 1)  ; 「お疲れさま…春希くん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0286>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 135
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0287>, 146, 1)  ; 「雪菜…雪菜ぁ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 147, 1)  ; 二週間ぶりに聞くその声は、\nやっぱり、いつまでも褪せない優しさに満ちていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0289>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 136
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 148, 1)  ; 「ごめんね、ずっと連絡しなくて。\n辛い思いさせてしまって、ごめんね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 149, 1)  ; でも、その空白の二週間を、\n雪菜は、本当は謝る必要なんかない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0292>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 137
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0293>, 150, 1)  ; 「ごめん、ごめん、雪菜…\n俺、やっぱり…あいつを支えきれなかった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 100
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0294>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 138
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0295>, 151, 1)  ; 「ん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0296>, 152, 1)  ; だって、約束だったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0297>, 153, 1)  ; かずさから逃げないって。\n今はかずさの側にいるって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0298>, 154, 1)  ; かずさを安心させるって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0299>, 155, 1)  ; それまでは、会わないって約束だったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0300>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 139
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0301>, 156, 1)  ; 「いや、俺が支えようとすることそのものが\n間違ってたのかも。\n…やっぱり俺じゃ、駄目だったんだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0302>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 140
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0303>, 157, 1)  ; 「駄目なこと、ないよ。\nそんなこと、ないって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0304>, 158, 1)  ; だから雪菜は、\n俺が何度も言い訳がましいメールを送っても、\n約束通り、返事もよこさなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0305>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 141
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0306>, 159, 1)  ; 「駄目だよ、やっぱり…\nだって、俺といると、かずさは余計に傷つく。\n俺があいつの針のムシロになっちまってる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0307>, 160, 1)  ; けれど、たった一言『助けて』って書いた途端、\n５分も経たないうちにコールバックしてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0308>, 161, 1)  ; 見ててくれてた…\nずっと返事をしなかったときも、\n届いたメール、すぐに見ててくれたんだ、雪菜は。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 31000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0309>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 142
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0310>, 162, 1)  ; 「話して、くれるかな…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0311>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 143
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0312>, 163, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0313>, 164, 1)  ; そして、来てくれた…\n雪菜が、俺のもとへと来てくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0314>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 144
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0315>, 165, 1)  ; 「この二週間のこと。\n春希くんがどう頑張って、どう挫折したのかを」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0316>, 166, 1)  ; かずさと同じように、辛い現実から逃げ出して、\n雪菜に救いを求めた俺を、受け入れてくれた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0317>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 145
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0318>, 167, 1)  ; 「春希くんは今…\n何を、求めているのかを」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0319>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 146
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0320>, 168, 1)  ; 「雪菜…雪菜…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0321>, 169, 1)  ; 雪菜は、慈しむような視線で俺を見つめてくれている。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0322>, 170, 1)  ; だから俺は、ゆっくりと手を伸ばし、\n雪菜を求めるように、立ち上がる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0323>, 171, 1)  ; その胸で、泣くために。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

ARRAY_S RES<0324>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

@VCALL SetMessageE(RES<0325>, 172, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2100
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0326>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 147
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0327>, 173, 1)  ; 「じゃあ、改めて。\n…ナイツレコード広報担当の小木曽と申します。\n今後ともよろしくお願いいたします」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 203
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0328>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 148
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0329>, 174, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0330>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 149
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0331>, 175, 1)  ; 「…って、とりあえず社会人の義務は果たしました、と。\nそれにしてもすっごい部屋だね～。\n一泊何万くらい取られるの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0332>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 150
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0333>, 176, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0334>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 151
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0335>, 177, 1)  ; 「わたしも他のインテグラル泊まったことあるけど、\nいっつも普通の客室だから…\nそれでも２万くらい取られるんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0336>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 152
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0337>, 178, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0338>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 153
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0339>, 179, 1)  ; 「あ、いきなり下世話だったかな。ごめん。\nウチ、お母さんがすぐお金のこと気にするから、\nついつい影響受けちゃうんだよね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0340>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 154
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0341>, 180, 1)  ; 「…なんで」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0342>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 155
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0343>, 181, 1)  ; 「ん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0344>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 156
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0345>, 182, 1)  ; 「なんで、来たんだ。\nあたしを見下したいのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0346>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 157
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0347>, 183, 1)  ; 「かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0348>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 158
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0349>, 184, 1)  ; 「笑いに来たのか？　罵りに来たのか？\nそれとも…哀れみに来てくれたとでも言うのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0350>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 159
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0351>, 185, 1)  ; 「話を、しに来たんだけど。\nただ、それだけなんだけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0352>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 160
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0353>, 186, 1)  ; 「怒ってんだろ？　あたしのこと。\n許す気なんか、ないんだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0354>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 161
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0355>, 187, 1)  ; 「そうだね…\nせっかく帰国してきたのに一度も連絡くれないこととか、\nちょっと根に持ってるかも」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0356>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 162
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0357>, 188, 1)  ; 「っ…あ、あたしがそんなことできるわけないって\n知ってるくせに…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0358>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 163
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0359>, 189, 1)  ; 「あ～あ、連絡欲しかったな。\nかずさ、昔の携帯番号繋がらないし。\n何より、わたしから連絡入れても嫌だろうし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0360>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 164
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0361>, 190, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0362>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 165
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0363>, 191, 1)  ; 「それは否定してくれないんだ。\nあ～あ、地味にショックかも、やっぱり」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 212
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0364>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 166
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0365>, 192, 1)  ; 「これが雪菜の復讐なのかよ？\nみじめなあたしの姿を見ることが…\n醜いあたしの未練を嘲笑うことが…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0366>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 167
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0367>, 193, 1)  ; 「なんでそんなネガティブに考えちゃうかなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0368>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 168
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0369>, 194, 1)  ; 「だって、だって…！\nお前にここ教えたの、春希だろ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0370>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 169
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0371>, 195, 1)  ; 「…そうだよ。\n少し考えればわかることだもんね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0372>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 170
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0373>, 196, 1)  ; 「つまり二人してあたしのこと笑ってたんだろ？\n昔のことずっと根に持ってる痛い女だって！\nまるでストーカーみたいだって！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0374>)  ; 雪菜
PUSH INT 2
PUSH INT 128
PUSH INT 0
PUSH INT 0
PUSH INT 171
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0375>, 197, 1)  ; <F16「…どっちかと言うと春希くんの方が\n><F16その傾向強いんだけどなぁ」>
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0376>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 172
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0377>, 198, 1)  ; 「ほら答えられないじゃないか！\nそうなんじゃないか！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0378>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 173
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0379>, 199, 1)  ; 「………それじゃあ、そろそろ本題行こうか。\nそういう話してても埒が明かないしね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0380>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 174
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0381>, 200, 1)  ; 「っ！　埒が明かないってどういうことだよ！\n雪菜、やっぱりお前あたしのこと馬鹿に…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0382>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 175
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0383>, 201, 1)  ; 「このたび弊社は、開桜社アンサンブル増刊号\n同梱ＣＤ『冬馬かずさミニアルバム』の\nプロデュースを手がけることになりました」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 115
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0384>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 176
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0385>, 202, 1)  ; 「………なんだって？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0386>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 177
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0387>, 203, 1)  ; 「それで、今日はご挨拶とスケジュールの確認に。\n収録内容はおいおい相談していくことにしましょう。\n何しろ同時期にコンサートもあるから日程がタイトで…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0388>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 178
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0389>, 204, 1)  ; 「開桜社…？\nアンサンブル…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0390>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 179
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0391>, 205, 1)  ; 「ちなみに、今回はウチの完全持ち出し。\nいずれ日本で冬馬かずさのＣＤが発売されるときのために、\n恩を売っておこうってのがぶっちゃけた狙いなの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0392>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 180
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0393>, 206, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0394>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 181
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0395>, 207, 1)  ; 「かずさとの契約ってすごくハードル高いんだよ？\nクラシックレーベル持ってる<Rレコード会社|ところ>は\nほとんど全社が狙ってるんじゃないかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 212
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0396>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 182
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0397>, 208, 1)  ; 「………だな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0398>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 183
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0399>, 209, 1)  ; 「ん？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0400>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 184
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0401>, 210, 1)  ; 「あいつが売ったんだな…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0402>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 185
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0403>, 211, 1)  ; 「売った…って」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0404>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 186
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0405>, 212, 1)  ; 「自分の仕事のために…雪菜の機嫌を取るために…\nあいつ、あたしのこと売ったんだな！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0406>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 187
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0407>, 213, 1)  ; 「………そう思う？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0408>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 188
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0409>, 214, 1)  ; 「だ、だって…だってそんな…\nそうじゃなきゃ、こんな出来過ぎた話あるかよ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0410>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 189
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0411>, 215, 1)  ; 「そう思うんなら思えばいいんじゃない？\n…かずさがその可能性を信じられるなら、だけどね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 307
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0412>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 190
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0413>, 216, 1)  ; 「…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0414>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 191
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0415>, 217, 1)  ; 「でも、最終的には冬馬曜子さんの…\nあなたの所属会社の社長が決めたの。\nだからこれは、正式な契約なんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 131
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0416>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 192
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0417>, 218, 1)  ; 「母さん…まで？\n母さんまで、あたしを見捨てたって言うのか…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0418>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 193
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0419>, 219, 1)  ; 「自分で本人に聞いてみたらどうかな？\n…心配してたよ、曜子さん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0420>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 194
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0421>, 220, 1)  ; 「雪菜…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 201
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0422>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 195
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0423>, 221, 1)  ; 「もちろん、コネはあったよ。\n春希くんが直接曜子さんに口利きしたから、\n理屈抜きでウチが仕事を取れた」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0424>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 196
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0425>, 222, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 200
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0426>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 197
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0427>, 223, 1)  ; 「開桜社、ナイツレコード、冬馬曜子オフィス…\n三社を巻き込んだ、ありえない友達仕事だよね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0428>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 198
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0429>, 224, 1)  ; 「友達…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0430>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 199
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0431>, 225, 1)  ; 「月曜に企画書を出して、\n今朝プロデューサーの決裁が下りた。\nいくら雑誌付属のミニアルバムでも普通ないよこんなの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0432>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 200
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0433>, 226, 1)  ; 「それが…なんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0434>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 201
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0435>, 227, 1)  ; 「あなたが絡むと、社会の常識なんて\n結構ねじ曲がっちゃうってこと。\n…これが、冬馬かずさって人間の力なんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0436>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 202
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0437>, 228, 1)  ; 「そんなの知らない…\nそんな力、欲しかった訳じゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0438>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 203
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0439>, 229, 1)  ; 「ただ、好きな人を振り向かせられたら良かった？\n…春希くんにさえ、届けば良かった？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 206
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0440>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 204
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0441>, 230, 1)  ; 「っ…雪菜！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0442>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 205
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0443>, 231, 1)  ; 「かずさって…本当に春希くんのことが大好きなんだね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0444>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 206
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0445>, 232, 1)  ; 「～～～っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0446>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 207
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0447>, 233, 1)  ; 「ふふ…図星？\n…なんて、聞くまでもないよね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 131
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0448>)  ; かずさ
PUSH INT 1
PUSH INT 128
PUSH INT 0
PUSH INT 0
PUSH INT 208
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0449>, 234, 1)  ; <F16「………………………悪いかよぅ」>
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0450>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 209
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0451>, 235, 1)  ; 「…やだなぁもう。その可愛さ反則だよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0452>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 210
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0453>, 236, 1)  ; 「からかうなよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 222
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0454>)  ; 雪菜
PUSH INT 2
PUSH INT 128
PUSH INT 0
PUSH INT 0
PUSH INT 211
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0455>, 237, 1)  ; <F16「そんな顔されたら、そりゃ春希くん参っちゃうよ。\n><F16かずさのこと、二度と離せなくなっちゃうよ…」>
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0456>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 212
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0457>, 238, 1)  ; 「………帰れよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0458>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 213
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0459>, 239, 1)  ; 「だいたい仕事の内容は理解してくれた？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 203
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0460>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 214
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0461>, 240, 1)  ; 「いいから帰ってくれよ！\nあたしはそんな仕事しない。\nするわけないだろ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0462>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 215
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0463>, 241, 1)  ; 「…わかった、とりあえず帰るね。\n今日のところは挨拶だけのつもりだったし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0464>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 216
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0465>, 242, 1)  ; 「二度と…来ないでくれ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0466>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 217
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0467>, 243, 1)  ; 「そんな訳にはいきません。\n締め切り迫ってるしね。\n追加公演より前に収録済ませちゃいたいし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0468>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 218
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0469>, 244, 1)  ; 「そんなの…物理的にだって無理だ。\nあと二週間しかない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0470>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 219
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0471>, 245, 1)  ; 「あと二週間かぁ…\n昔も、そんなやっつけ仕事があったね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0472>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 220
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0473>, 246, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0474>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 221
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0475>, 247, 1)  ; 「それじゃあ、おやすみなさい。\nあ、これ差し入れ。\nおなかが空いたら食べて」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 110
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0476>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 222
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0477>, 248, 1)  ; 「いらない。\n持って帰れ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0478>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 223
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0479>, 249, 1)  ; 「別に変なもの入ってないよ？\nそりゃ、わたしが作ったから味の保証はないけれど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0480>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 224
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0481>, 250, 1)  ; 「なんでもいいから、早くいなくなってくれ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0482>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 225
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0483>, 251, 1)  ; 「わかった…それじゃ、おやすみなさい。\n…また明日」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 212
PUSH INT 30000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0484>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 226
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0485>, 252, 1)  ; 「二度と来るなって言っただろ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 2
PUSH INT 0
PUSH INT 15
CALL CR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1000
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 125
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT -2
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0486>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 227
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0487>, 253, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0488>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 228
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0489>, 254, 1)  ; 「っ…ぅ、ぅぅ…っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0490>, 255, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1020
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3002
PUSH INT 60
PUSH INT 1
PUSH INT 40
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 311
PUSH INT 25000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2071
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0491>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 229
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0492>, 256, 1)  ; 「ふぅ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0493>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 230
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0494>, 257, 1)  ; 「先、長そ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0495>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 231
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0496>, 258, 1)  ; 「本当に、これでいいのかな？\nわたしで、大丈夫なのかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0497>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 232
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0498>, 259, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0499>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 233
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0500>, 260, 1)  ; 「…何言ってるの。\nたった一日で、いきなり弱音吐いてどうするの」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0501>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 234
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0502>, 261, 1)  ; 「くじけるな、わたし！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0503>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 235
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0504>, 262, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0505>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 236
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0506>, 263, 1)  ; 「依緒たち、怒ってるだろうなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 90
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0507>, 264, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2118
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0508>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 237
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0509>, 265, 1)  ; 「馬鹿野郎…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0510>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 238
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0511>, 266, 1)  ; 「誕生日だったんじゃないかよ、あいつ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0512>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 239
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0513>, 267, 1)  ; 「そんな大切な日に、\nなんでこんなとこ、来てるんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 300
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0514>  ; 3202
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
