!RESOURCE "3205.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3205
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
PUSH INT 2013
PUSH INT 2
PUSH INT 20
PUSH INT -1
PUSH INT 1
CALL Calender
OPERATOR POP

PUSH INT 3
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 1
PUSH INT 8260
PUSH INT 60
PUSH INT 1
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2027
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 0
PUSH INT 8
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 16
PUSH INT 30
PUSH INT 0
PUSH INT 16
CALL SetShake
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0004>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「どうなってんだよ北原！\nあれから一週間経つのに\nナイツから何の音沙汰もないじゃないか！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「一応、担当から毎日進捗報告は受けています。\n…まぁ、今のところ\n一曲も収録できてないみたいですけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 16
PUSH INT 30
PUSH INT 0
PUSH INT 16
CALL SetShake
OPERATOR POP

@VCALL WN(RES<0008>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「馬鹿野郎！　それは進捗とは言わん！\n締め切りは今月中なんだぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0010>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「あと１０日あります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0012>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「その１０日目にはコンサートがあるだろうが！\n本当に冬馬かずさはこの仕事やるんだろうな！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0014>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 5, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 6, 1)  ; 浜田さんの怒号に、少しの間言葉を失ってしまう。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 7, 1)  ; その迫力に押された訳じゃなくて、\nその主張の正しさにぐうの音も出なくなってしまったから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0018>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 8, 1)  ; 「だいたい、最初から無理だったんだよこんな企画！\nどうして当初の予定通りの台割で行かなかったんだよ。\nおかげでアンサンブルの編集部は大混乱だ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 9, 1)  ; 「そっちは…ちゃんと編プロとは協議を重ねてます。\n編集長もなんとか了解をいただけてますし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0022>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 10, 1)  ; 「そんなの、モノが上がらなきゃ何の意味もないんだよ！\nお前約束できるのか？\n今月末までに必ず音源用意できるのか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 11, 1)  ; 「やれることは全てやります。\n…あとは冬馬かずさ頼みです」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0026>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 12, 1)  ; 「勝手に企画捻じ込みやがって！\n勝手に告知しやがって！\nこれで勝手にこけたりしたらお前が責任取るんだぞ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0028>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 13, 1)  ; 「もちろん、覚悟はできてます。\nクビだって言われても受け入れます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 16
PUSH INT 30
PUSH INT 0
PUSH INT 16
CALL SetShake
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0030>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 14, 1)  ; 「馬鹿野郎！　お前は本当に大馬鹿野郎だ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0032>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 15, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0034>, 16, 1)  ; けれど、俺が自らの首を差し出したとき…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 17, 1)  ; 浜田さんの『馬鹿野郎』は、\n今までよりもさらに大きな怒号となって響いた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0036>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 18, 1)  ; 「前向きな失敗で首切るわけないだろ！\nそういうのは上司が全部被るもんだ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0038>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 19, 1)  ; 「浜田さん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0040>, 20, 1)  ; それは、俺がバイト時代にずっと背中を見てきた、\n“あの人”を思わせる力強さと、頼もしさで…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 9
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0041>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0042>, 21, 1)  ; 「………って、今朝風岡からまた国際電話で怒鳴られた。\nお前、あいつに援護射撃頼んだな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0043>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0044>, 22, 1)  ; 「あ、もう来ました？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 23, 1)  ; なんて、それも当然だ。\n何しろあの人の<R受け売り|おしつけ>なんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0046>, 24, 1)  ; 昨夜、覚悟を決めてかけた国際電話の先の声は懐かしく、\n久しぶりに嬉しい二時間を過ごした。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0047>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0048>, 25, 1)  ; 「あ、あのなぁ…\nもう風岡はウチの編集部の人間じゃないんだから、\nあいつに頼ったところでなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0049>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0050>, 26, 1)  ; 「ええ、関係ないです。\nですから俺は浜田さんの指示に従いますよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 10
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0051>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0052>, 27, 1)  ; 「………そんな前提、あの女が従うと思うか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0053>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0054>, 28, 1)  ; 「だって関係ないんですよね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0055>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 29, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0057>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 30, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 31, 1)  ; そして、浜田さんの内面から、\n力強さと頼もしさが徐々に失われていくにつれ、\n俺は自分の暫定勝利を悟った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 9
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0060>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 32, 1)  ; 「…その殊勝な態度は完全に見せかけだろお前。\n反省なんかちっともしてないだろ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0062>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 33, 1)  ; 「そんなことないですよ。\nこれからの努力と…\nできれば成果で取り返したいと思ってます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0064>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0065>, 34, 1)  ; 「っ…もういい。\nあとナイツへのフォロー忘れんな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0066>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0067>, 35, 1)  ; 「ありがとうござます。\nそれじゃ俺、打ち合わせがあるんで。\n失礼します」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 1001
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2028
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 36, 1)  ; 浜田さんの言う通り、\n何の進展もないまま一週間が過ぎた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 37, 1)  ; 雪菜からは毎日『進展なし』という、\n味も素っ気もないメールが届くだけ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 38, 1)  ; 一度だけ『かずさが返事してくれないの！』という、\n心の篭もったパニックコールがあったけど、\nあれは例外中の例外で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 39, 1)  ; けれど俺は、焦ったりしない。\nひたすらに、雪菜の成果を待ち続ける。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 40, 1)  ; それが、俺たちの約束だったから。\n『その時』が来るまで会わないって約束だから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 41, 1)  ; …たとえその時が、締め切りの前夜だとしても。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0074>, 42, 1)  ; だから、今の俺にできることは、\nかずさ以外の全ての準備を整えること。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 43, 1)  ; あいつの指から、再び力強い旋律が流れ出したとき、\nその音をすぐに、そして全て拾い上げるために。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 8260
PUSH INT 60
PUSH INT 1
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2027
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0076>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0077>, 44, 1)  ; 「あああああああ～っ、もうっ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 31
PUSH INT 5
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0078>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 45, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 11
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0080>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 46, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0082>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 47, 1)  ; 「なんだよ？\n何か言いたいことがあるなら言ってみろよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 3
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0084>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 48, 1)  ; 「いや別に。\n『せっかく浜田さんのこと見直しかけたのに』\nなんて思ってませんよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 12
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0086>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 49, 1)  ; 「『一年目の新人にいいようにあしらわれちゃって』\nなんて考えたこともないですから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 8
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0088>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 50, 1)  ; 「わざと負けてやってんだよ！\nこんなところで潰すには惜しい奴だろ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 2
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0090>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 51, 1)  ; 「わかってますって。\n『負け惜しみもイマイチ弱々しいですね』\nなんて台詞、頭に浮かんだりしてませんよ俺」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 1
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0092>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 52, 1)  ; 「にしても北原君って、\nホント麻理さんに愛されてるよね～。\nえこひいきにも程があるってくらいに…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 7
PUSH INT 2000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0094>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 53, 1)  ; 「そんなだからいつまで経っても独身なんだよ風岡は」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 31
PUSH INT 4
PUSH INT 2000
OPERATOR ADD
PUSH INT 3
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0096>)  ; 松岡
PUSH INT 31
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 54, 1)  ; 「それ訴訟モノ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 33
PUSH INT 12
PUSH INT 2000
OPERATOR ADD
PUSH INT 4
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

@VCALL WN(RES<0098>)  ; 鈴木
PUSH INT 33
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 55, 1)  ; 「ええと、アメリカの国番号は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 150
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2062
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 1020
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 314
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2062
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

@VCALL WN(RES<0100>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 56, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0102>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 57, 1)  ; 「お疲れさま～。\n今日も遅くまで頑張ってたね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0104>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0105>, 58, 1)  ; 「帰ればよかったのに。\nこんな遅くまで待ってなくても」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0106>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 59, 1)  ; 「今のところ、\nわたしの仕事はかずさへの張り付きだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0108>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 60, 1)  ; 「広報の仕事じゃないだろそれ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0110>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 61, 1)  ; 「今のお仕事は特命プロジェクトだからね。\n冬馬曜子に直々に指名されたとあれば、\n上司だって見て見ぬふりだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0112>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 62, 1)  ; 「…ちぇっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 108
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0114>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 63, 1)  ; 「それにしても寒いよね～。\n待ってる間に手がこんなに冷たく…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 203
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0116>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 64, 1)  ; 「って、冷たっ！\n勝手に人の頬に触れるな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0118>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 65, 1)  ; 「あはは…温か～い。\nそれじゃ行こうか、ホテルまで送るよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0120>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 66, 1)  ; 「本当に、もう…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 67, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3105
PUSH INT 60
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2061
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 101
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2061
PUSH INT 0
PUSH INT 15
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0123>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0124>, 68, 1)  ; 「食欲はある？\nちゃんと食べてる？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0125>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0126>, 69, 1)  ; 「まぁ、適当に。\n弾いてると、よく食べること忘れるから、\n一日に一度くらいだけど」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0127>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 70, 1)  ; 「う、う～ん…\n集中してることを喜ぶべきか、\n栄養不足を心配するべきか…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0129>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 71, 1)  ; 「別に心配はいらない。\n向こうにいるときだって、こんなもんだった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 101
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0131>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 72, 1)  ; 「あんまり誉められたものじゃないけど…\nでも、一日一回だとしたら、\nその食事は特に気を使わないとね」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 100
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0133>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0134>, 73, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0135>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 74, 1)  ; 「ねぇ、明日からお弁当作ってきていいかな？\n朝、出勤前にホテルに届けに行くから…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 104
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0137>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 75, 1)  ; 「なんでだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0139>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 76, 1)  ; 「？　スタジオの方がいい？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0141>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0142>, 77, 1)  ; 「どうして毎日会いに来るんだ？\nあたしはお前の仕事を引き受けないって言ったんだぞ？\nそれどころか、お前の顔に傷までつけたんだぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0143>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0144>, 78, 1)  ; 「あれは…おあいこじゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0145>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 79, 1)  ; 「どうして愛想を尽かさない？\nどうして、放っておこうとしないんだ？\n…まるで、あいつみたいに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0147>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 80, 1)  ; 「好きだから…だよ。\nそれこそ“あいつ”みたいに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0149>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0150>, 81, 1)  ; 「っ…でも憎いんだろ？\n引っぱたいてやりたいくらい、ムカつくんだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0151>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0152>, 82, 1)  ; 「その辺のところ突っ込まないで欲しいなぁ。\n全部が全部、割り切れてる訳じゃないんだから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 150
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0153>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0154>, 83, 1)  ; 「お前、この前言ってたよな？\nあたしを引っぱたきながら」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0155>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0156>, 84, 1)  ; 「後半は別に言わなくてもいいことだと思うけど…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0157>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0158>, 85, 1)  ; 「春希のこと…\n嘘だらけの汚くて卑怯な奴だって、言ってたよな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0159>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0160>, 86, 1)  ; 「ほんっと酷い人だよね春希くんって。\n五年間もずっとふたまたかけ続けてさぁ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0161>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0162>, 87, 1)  ; 「だったらどうしてお前こそ、\nあいつのことを好きなままなんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 314
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0163>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0164>, 88, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0165>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0166>, 89, 1)  ; 「お前があたしに構うのは、あいつがそうするからだろ？\nあたしを立ち直らせることが、\nあいつに尽くすことだって思ってるんだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0167>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0168>, 90, 1)  ; 「そんな…それだけである訳ないじゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0169>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0170>, 91, 1)  ; 「つまり、それもあるってことだろ？\n春希に尽くしてるつもりもあるんだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0171>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 92, 1)  ; 「そんな細かい揚げ足取らなくても…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0173>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0174>, 93, 1)  ; 「酷いはずの春希のこと、そこまで愛してるんだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0175>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0176>, 94, 1)  ; 「………だからなんなのよぅ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0177>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0178>, 95, 1)  ; 「ほら、雪菜こそ全然人のこと言えないじゃないか。\nあたしの気持ちを説明しろって言っておいて、\n自分の気持ちも説明できないじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 222
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0179>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0180>, 96, 1)  ; 「あ、あの時わたしが言いたかったのは、\n人を好きなことに理由なんかないって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 150
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0181>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 97, 1)  ; 「なんであいつのことそんなに好きなんだよ雪菜…\n何度も裏切られて、どうして諦められないんだよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0183>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 98, 1)  ; 「………そういうかずさはどうなの？\n五年も会えなかった人のこと、\nどうしてそこまで想い続けられるの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0185>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 99, 1)  ; 「今はあたしが質問してるんだろ？\nちゃんと答えろよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0187>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0188>, 100, 1)  ; 「け、けどかずさだって、\nこの前のわたしのその質問、答えてないよ？\nだからわたしの質問の方が先！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 104
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0189>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0190>, 101, 1)  ; 「………あたしはあいつのこと好きだなんて\nひとことも言ってない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 321
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0191>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0192>, 102, 1)  ; 「なにを今さら！\nわたしが『好きなんだよね？』って聞いたら、\n『悪いかよ』って答えたじゃない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 110
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0193>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0194>, 103, 1)  ; 「覚えてない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0195>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0196>, 104, 1)  ; 「嘘ばっかり」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0197>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0198>, 105, 1)  ; 「あたしがいつそんなこと言ったって言うんだ。\n何月何日何時何分何秒？\n言っとくけど一秒でもずれたら不正解だからな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0199>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0200>, 106, 1)  ; 「それってやっぱり正解があるってことじゃ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0201>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 90
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0202>, 107, 1)  ; 「ぶっぶ～、時間切れ。\nほら見ろ、あたしがそんなこと言ってないって\nこれで証明された」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 321
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0203>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 91
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0204>, 108, 1)  ; 「もう！　小学生じゃないんだから！\nどうしてかずさはそんなに素直じゃないかなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 109, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 1020
PUSH INT 0
PUSH INT 0
PUSH INT 200
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0206>)  ; フロント
PUSH INT 99
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 92
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 110, 1)  ; 「お帰りなさいませ冬馬様。\nごゆっくりどうぞ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2072
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 8245
PUSH INT 0
PUSH INT 1
PUSH INT 200
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0208>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 93
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0209>, 111, 1)  ; 「雪菜に何がわかるんだ。\nあたしの何がわかるってんだよ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0210>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 94
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 112, 1)  ; 「その台詞何度目？\nもう飽き飽き！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0212>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 95
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 113, 1)  ; 「お前が全然わかってないから、\n同じ事を繰り返すしかないんじゃないか」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 2072
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 150
PUSH INT 60
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
OPERATOR NEGATE
PUSH INT 60
PUSH INT 5000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0214>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 96
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 114, 1)  ; 「そんなことない、わかってる！\n…って、自信満々に言うことはできないけど、\n少なくとも、わかろうと頑張ってるよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0216>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 97
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 115, 1)  ; 「コンサートに努力は関係ない。\n観客は結果しか見ない」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0218>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 98
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 116, 1)  ; 「でもお客さんは集中して聴いてる。\n頑張って、ピアニストに近づこうとしてくれる」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0220>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 99
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 117, 1)  ; 「居眠りしてる客を目覚めさせてこそプロだろ？\n認めてくれないのは相手が悪いなんて、\n努力不足の言い訳でしかないな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 100
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 118, 1)  ; 「だったらもっと頑張るから！\nかずさのこと、必ずわかってみせるから！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 8401
PUSH INT 0
PUSH INT 0
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
PUSH INT 2072
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 8402
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0224>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 101
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 119, 1)  ; 「はい時間切れ。\n今日はここまでだな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0226>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 102
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 120, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0228>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 103
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0229>, 121, 1)  ; 「おやすみ、雪菜。\n毎日毎日、無駄な努力ご苦労様」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0230>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 104
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0231>, 122, 1)  ; 「………それでも、明日も来る」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0232>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 105
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0233>, 123, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0234>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 106
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 124, 1)  ; 「たとえ今日はわかってくれなくても…\n全然観客の心に響かないコンサートだったとしても、\nわたしにはまだ、チャンスがある」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 110
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0236>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 107
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0237>, 125, 1)  ; 「ふん」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0238>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 108
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0239>, 126, 1)  ; 「追加公演を見てなさい。\n今度こそかずさの…\n観客の心、掴んでみせるから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0240>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 109
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 127, 1)  ; 「ああ、そうかよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0242>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 110
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 128, 1)  ; 「そうよ！\n………じゃ、おやすみなさい」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

@VCALL WN(RES<0244>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 111
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 129, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0246>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 112
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0247>, 130, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 316
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0248>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 113
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0249>, 131, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0250>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 114
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 132, 1)  ; 「………行かないの？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 110
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 10
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0252>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 115
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 133, 1)  ; 「アンコールもなしかよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0254>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 116
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 134, 1)  ; 「え…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 205
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0256>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 117
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 135, 1)  ; 「ちょっとブーイングされただけですごすご帰るのか？\n結局、お前の覚悟なんて、その程度なんだ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 115
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0258>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 118
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 136, 1)  ; 「え？　え？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0260>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 119
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0261>, 137, 1)  ; 「言いたいことがあるなら、熱いうちに言えよ。\nなんでそんな簡単に諦めるんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0262>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 120
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0263>, 138, 1)  ; 「か、かずさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 218
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0264>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 121
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0265>, 139, 1)  ; 「あ～、明日仕事あるもんなぁ。\n会社員は大変だもんなぁ。\nごめんな、あたし自由業だからわからなかったよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 217
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0266>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 122
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0267>, 140, 1)  ; 「っ！\n…一度上がり込んだら朝まで帰らないに決まってるから、\nせっかく遠慮してたのになぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 134
PUSH INT 8000
OPERATOR ADD
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0268>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 123
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0269>, 141, 1)  ; 「無理しなくたっていいんだぞ？\n明日の仕事に差し支えるだろ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0270>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 124
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0271>, 142, 1)  ; 「夜通し怒鳴ってるかもしれないけど、\nそれでもいいんだね…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0272>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 125
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0273>, 143, 1)  ; 「たとえどれだけ大きな音でも、\n心に響かなかったら観客はグースカ寝るぞ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 321
PUSH INT 25000
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0274>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 126
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 144, 1)  ; 「寝かさない…あなたのこと」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 8402
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 178
PUSH INT 256
OPERATOR ADD
PUSH INT 0
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0276>)  ; かずさ
PUSH INT 1
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 127
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 145, 1)  ; 「やれるもんならやってみな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0278>, 146, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0279>, 147, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 148, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0281>  ; CATCH3
PUSH INT 100
CALL SCall
OPERATOR POP

ARRAY_S RES<0282>  ; 3206
PUSH INT 0
CALL SLoad
OPERATOR POP

STATEMENT HALT
