!RESOURCE "3909.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 3909
CALL VI
OPERATOR POP

PUSH INT 0
CALL MS
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

STATEMENT IF _ #LABEL_12
PUSH INT 0
STATEMENT JMP_IF
OPERATOR POP

#LABEL_12
ARRAY_G 4
PUSH INT 3
OPERATOR MOV
OPERATOR POP
PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 150
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.3
PUSH FLOAT 1.3
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 3000
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 300
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3002
PUSH INT 60
PUSH INT 1
PUSH INT 80
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1062
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 4002
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 9
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0004>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0005>, 0, 1)  ; 「ですからそれは明日対応しますって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0006>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 1, 1)  ; 「明日じゃマズいんだってば！\n週明けの朝イチで編集会議なんだから、\n今日中に俺のチェックまで済ませておかないと」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0008>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 2
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 2, 1)  ; 「あれ？　浜田さん明日は…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0010>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 3
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 3, 1)  ; 「たまには休ませろ。\n同期の月例会なんだよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL WN(RES<0012>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 4
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 4, 1)  ; 「その、俺も今夜は外せない用事が…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0014>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 5
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 5, 1)  ; 「なんだとぉ？\nお前、上司がこんなに困ってるのにいい度胸だなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0016>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 6
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 6, 1)  ; 「でも、今日だけは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0018>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 7
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0019>, 7, 1)  ; 「…あ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0020>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 8
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0021>, 8, 1)  ; 「………わかりました。\n今から編集部に戻ります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0022>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 9
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0023>, 9, 1)  ; 「い、いや…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0024>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 10
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0025>, 10, 1)  ; 「全部仕上げるとなると、\n２時くらいまでかかっちゃいますけど、大丈夫ですか？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0026>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 11
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0027>, 11, 1)  ; 「あ、あのな、北原…\nごめん、やっぱいいわ。\n今日のところは帰れ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0028>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 12
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0029>, 12, 1)  ; 「え？　だって編集会議………ぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0030>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 13
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0031>, 13, 1)  ; 「いや、まぁ…\n週明けに早出してチェックするから。\nお前は気にせず、今日は帰れ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0032>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 14
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0033>, 14, 1)  ; 「浜田さん。\n遠慮してくれるのはありがたいですけど、\nそうあからさまにされても俺…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0034>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 15
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0035>, 15, 1)  ; 「いや、つい調子乗っちまった。\nお前にはもう３人前くらい仕事振ってるのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0036>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 16
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0037>, 16, 1)  ; 「いつもならやります。\nただ今日は…すいません」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0038>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 17
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0039>, 17, 1)  ; 「わかってる。そこまで踏み込むのはやめるよ。\n…お前をアメリカに引っ張って行かれるのはご免だし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0040>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 18
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0041>, 18, 1)  ; 「大丈夫ですよ、俺、今はまだ海外に行く気ないですから。\nそれに…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0042>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 19
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0043>, 19, 1)  ; 「それに？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0044>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 20
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0045>, 20, 1)  ; 「多分あの人の下についた方がよほど死ねます」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0046>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 21
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0047>, 21, 1)  ; 「ははははっ、間違いないな。\nあいつ面倒見はいいかもしれないけど、\n持ってくる仕事量がそもそも尋常じゃないし」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0048>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 22
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0049>, 22, 1)  ; 「それじゃ、\nすいませんけど、そろそろ…\n明日までにはメール出しておきますから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0050>)  ; 浜田
PUSH INT 30
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 23
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0051>, 23, 1)  ; 「ああ、お疲れ。\nそれじゃ、よい週末を」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 2210
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0052>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 24
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0053>, 24, 1)  ; 「…ふぅ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0054>, 25, 1)  ; 自分のオフの時間を勝ち取ったとはいえ、\nほんの少しの寂寥感みたいなものが残った。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0055>, 26, 1)  ; 傷痕…というか、\n一年経っても、あの時のことは、\n俺の日常に、未だ少なからず影響を与えてる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0056>, 27, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2143
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 100
OPERATOR NEGATE
PUSH INT 0
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
PUSH INT 0
PUSH INT 5000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0057>, 28, 1)  ; 社会人二年目の、冬。\n病院に通わなくなって、やっと二か月目に入った頃。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0058>, 29, 1)  ; 一年前『身に余る仕事量とプレッシャーの大きさによる\nメンタルダメージ』と随分好意的に解釈された例の症状は、\nもう、薬に頼る必要もなくなるほどに落ち着いてきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0059>, 30, 1)  ; とはいえ半年間くらいは、何かきっかけがあると\nすぐに自律神経が言うことを聞かなくなり、\n随分と周囲に迷惑を掛けたものだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0060>, 31, 1)  ; 職場では、未だにその頃の名残があるせいで、\n浜田さんも皆も、以前のような無茶振りは影を潜め、\n新人レベルの身の丈に合った仕事をくれるようになった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0061>, 32, 1)  ; …少なからず物足りない気はするけれど、\nこれも全て俺が招いた事態だから仕方がない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0062>, 33, 1)  ; …出世の道からは外れたかもしれないけどな。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0063>, 34, 1)  ; 社会人二年目の、冬。\nつまり、あれから一年…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0064>, 35, 1)  ; 国内の冬馬かずさ熱は過去のものとなり、\n今や、新聞や一般週刊誌で見かけることは\nほとんどなくなった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0065>, 36, 1)  ; けれどそれは、冬馬かずさというピアニストが、\n活動を縮小したとか、世間の評価が芳しくないとか、\nそういうことでは全然なく、むしろその逆で…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0066>, 37, 1)  ; 一般誌での露出は減ってはいたけれど、\nアンサンブル始め音楽専門誌での扱いは、\nますます拡大していくばかり。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0067>, 38, 1)  ; 欧州に根を下ろしたかのように、\n現地で積極的な演奏活動を開始した彼女は、\n日本公演の後、見事に花開いていった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0068>, 39, 1)  ; 冬馬曜子の影響力も遠慮せず積極的に使い、\n単独のピアノコンサートだけでなく、\n有名オケとの協奏曲も次々とこなし…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0069>, 40, 1)  ; 完全に『ウィーンの若手ピアニスト』として、\n世界に認知されていった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0070>, 41, 1)  ; …そうやって『日本の芸能人』でなくなったから、\n国内の一般誌での扱いが低くなっていった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 3008
PUSH INT 60
PUSH INT 0
PUSH INT 60
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 8475
PUSH INT 60
PUSH INT 1
PUSH INT 60
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 210
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0071>, 42, 1)  ; あれから一年…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0072>, 43, 1)  ; あの、最後のコンサートから一年。\nかずさが俺の前から消えて一年。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0073>, 44, 1)  ; 雪菜に、別れを告げてから一年。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 3
PUSH INT 8189
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 20
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 50
PUSH INT 128
OPERATOR ADD
PUSH INT 9900
PUSH INT 0
PUSH INT 30
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 255
PUSH INT 60
CALL SEV
OPERATOR POP

PUSH INT 2
PUSH INT 8520
PUSH INT 60
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 255
PUSH INT 60
CALL SEV
OPERATOR POP

PUSH INT 3
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 2086
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1.3
PUSH FLOAT 1.3
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 3000
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 400
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 2
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2147
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 5
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0074>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 25
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0075>, 45, 1)  ; 「ええっと、それじゃ次が最後の曲になります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8521
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0076>, 46, 1)  ; 雪菜は、また歌い始めた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0077>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 26
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0078>, 47, 1)  ; 「あ～、いつもいつもお約束ありがとうございます～。\n大丈夫、アンコール２曲用意してますから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8522
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0079>, 48, 1)  ; 『ナイツの“あの”広報のコがボーカルやってるバンド』
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0080>, 49, 1)  ; そんな噂を、取引先の人から聞いたのは半月前…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0081>, 50, 1)  ; そのバンドが参加するライブのチケットは、\nそんな裏事情を知らない人たちにとってもかなりの人気で、\nいつも発売開始の午前中に売り切れてしまうらしかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0082>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 27
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0083>, 51, 1)  ; 「あ、それで最後の曲行く前に告知があります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0084>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 28
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0085>, 52, 1)  ; 「ありがたいことに、ここスタジオトロイでの、\n次回ライブの予定も決まりまして…\n来月の２１日、春分の日の１８時からになります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8523
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 8475
PUSH INT 30
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0086>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 29
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0087>, 53, 1)  ; 「一応次はね、ちょっと色々やってみたいなって、\nみんなで話し合ってまして…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0088>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 30
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0089>, 54, 1)  ; 「どこまで言っちゃっていいものかわからないけど…\n多分、新曲はやると思います」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 8524
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 8475
PUSH INT 60
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0090>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 31
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0091>, 55, 1)  ; 「今、一生懸命リーダーが曲作ってるんで、\nできればその声援は向こうに向けてお願いします～」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 0
PUSH INT 8252
PUSH INT 0
PUSH INT 0
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

PUSH INT 180
CALL MS
OPERATOR POP

PUSH INT 0
PUSH INT 180
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 180
CALL SES
OPERATOR POP

PUSH INT 2
PUSH INT 180
CALL SES
OPERATOR POP

@VCALL WN(RES<0092>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 32
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0093>, 56, 1)  ; 「それじゃ、“一応の”最後の曲行きますね…\n『あなたを想いたい』、聴いてください」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 100
PUSH INT 68
OPERATOR ADD
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

PUSH INT 0
PUSH INT 9671
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2086
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1.3
PUSH FLOAT 1.3
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 3000
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1260
PUSH INT 0
PUSH INT 0
PUSH INT 1
CALL Wait2
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0094>, 57, 1)  ; 客席から雪菜を見上げたのは、\n実はこれが初めてのことだった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0095>, 58, 1)  ; だって俺は、いつも歌う雪菜の後ろ姿を、\nギターを弾きながら見つめていたんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0096>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 33
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0097>, 59, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0098>, 60, 1)  ; 方々手を尽くして、\nたくさんのコネを使って手に入れたプラチナチケット。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0099>, 61, 1)  ; けれど、その努力は正しく報われたって痛感する。\nだってステージの上の雪菜は、やっぱり輝いていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0100>, 62, 1)  ; …あの時のかずさに引けを取らないくらいに。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0101>, 63, 1)  ; 客層も、ノリも、なによりその人数も、\nもちろん、あの時とは全然違っていたけれど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0102>, 64, 1)  ; それでも周りの聴衆は、\nちょっとスローテンポな雪菜の歌声に体を委ね、\n恍惚とした表情を浮かべ、聴き入っている。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0103>, 65, 1)  ; 心をガツンと殴るほど強くない。\nけれど、優しく包み込む。\nなのに、華がある。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0104>, 66, 1)  ; なにより…\nこれは絶対に個人的な見解だけじゃないと思うけど、\n笑顔が、眩しい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0105>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 34
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0106>, 67, 1)  ; 「っ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2147
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0107>, 68, 1)  ; そう、あれから一年…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0108>, 69, 1)  ; 雪菜はもう、あんなふうに笑えるようになったんだ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0109>, 70, 1)  ; 何の非もないのに裏切られ、\n一方的に傷つけられ、\n理不尽に別れを告げられて。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0110>, 71, 1)  ; 六年前、笑顔をなくしてしまったときと同じ…\nいや、それ以上の仕打ちを受けておきながら、\n決して、折れたりしなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0111>, 72, 1)  ; 綺麗なのに強くなった。\n可愛いのにたくましくなった。\nいい女に、なった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 180
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0112>, 73, 1)  ; …俺なんかいなくても、全然関係ないくらい。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0113>, 74, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 8525
PUSH INT 90
PUSH INT 1
PUSH INT 128
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
PUSH INT 8475
PUSH INT 90
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 1
PUSH INT 2086
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0114>, 75, 1)  ; ……
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 3
PUSH INT 8189
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 3
PUSH INT 0
CALL SEW
OPERATOR POP

PUSH INT 1
PUSH INT 60
CALL SES
OPERATOR POP

PUSH INT 4
PUSH INT 8527
PUSH INT 60
PUSH INT 1
PUSH INT 60
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 2
PUSH INT 60
PUSH INT 60
CALL SEV
OPERATOR POP

@VCALL SetMessageE(RES<0115>, 76, 1)  ; …
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0116>, 77, 1)  ; アンコールの歓声が鳴りやまない中、\n俺は、雪菜に見つからないように、\nひっそりとライブハウスを出た。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0117>, 78, 1)  ; …なんて、別に見つかったところで、\n何が変わるという訳じゃないのかもしれないけど。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4
PUSH INT 180
CALL SES
OPERATOR POP

PUSH INT 2
PUSH INT 180
CALL SES
OPERATOR POP

PUSH INT 0
PUSH INT 8477
PUSH INT 0
PUSH INT 1
PUSH INT 150
PUSH INT 0
CALL SEP
OPERATOR POP

@VCALL SetMessageE(RES<0118>, 79, 1)  ; 本来の終了予定時間はとっくに過ぎてるのに、\n俺以外には、まだ誰一人として出てくる気配がない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0119>, 80, 1)  ; つまり、そこまで人気のあるバンド…\nいや、ボーカルってこと、なんだろうな。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

PUSH INT 300
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 6
PUSH INT 3
PUSH INT 7
PUSH INT 64
PUSH INT 2
PUSH INT 1
PUSH INT 5
CALL SetWeather2
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 15
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0120>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 35
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0121>, 81, 1)  ; 「あ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0122>, 82, 1)  ; とうとう、降ってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0123>, 83, 1)  ; ライブハウスに着いたときから、\nいつ泣き出すかもしれなかった空は、\nちょっとだけ意地を張り、その涙を冷たい風で凍らせた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0124>, 84, 1)  ; まだ耳に残る雪菜の歌をかき消すように、\n空から降りてくる粉雪は、\nますますその数を増やしていく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0125>, 85, 1)  ; そんな白さの源となる雪雲を探しても、\n黒い夜空と白い粉雪に隠され、\n何も見つけることはできなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0126>, 86, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 3
PUSH INT 7
PUSH INT 180
PUSH INT -1000
PUSH INT 1
CALL ChangeWeather
OPERATOR POP

@VCALL SetMessageE(RES<0127>, 87, 1)  ; とうとう、降ってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0128>, 88, 1)  ; 二人、二度と離れないことを約束した日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0129>, 89, 1)  ; そんな約束が、\n砂上の楼閣だったということを露呈させた日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0130>, 90, 1)  ; そして今日…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0131>, 91, 1)  ; 初めて、ステージの上の彼女を見上げた日にも。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0132>, 92, 1)  ; いつも、俺たちの分岐点に現れて、\n辛かったこと、哀しかったことを思い出させようと、\n雪が、降り積もる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0133>, 93, 1)  ; ………
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 360
CALL MS
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 360
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8044
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
PUSH INT 30
PUSH INT 255
PUSH INT 255
PUSH INT 255
CALL F
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0134>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 36
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0135>, 94, 1)  ; 「いてっ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0136>, 95, 1)  ; と、空から降る雪をずっと眺めていたら、\nいきなり後頭部に硬く、そして軽い衝撃が襲ってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 3
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 5
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 90
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 43
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL WN(RES<0137>)  ; ？？？
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 37
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0138>, 96, 1)  ; 「なんで途中で帰っちゃうかな～。\nまだアンコールがあるって言ったのに」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0139>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 38
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0140>, 97, 1)  ; 「ぇ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0141>, 98, 1)  ; 頭を押さえて振り向くと、\nそこには、小さな拳を握り込み、\nぷくっと頬を膨らませた、ステージ衣装のままの…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 321
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 30
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0142>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 39
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0143>, 99, 1)  ; 「あと、ほんの１５分くらいなんだから、\nそのくらい待っててくれても、\n罰は当たらないんじゃないかなぁ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0144>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 40
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0145>, 100, 1)  ; 「雪菜…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0146>, 101, 1)  ; 噂のボーカリストが、息を切らせて立っていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 212
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0147>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 41
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0148>, 102, 1)  ; 「だいたい、来るなら一言言ってよ…\n今まで全然顔出さなかったくせに、\nどういう風の吹き回し？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0149>, 103, 1)  ; あれだけの観客の中から、\n一番後ろに佇んでいた俺を、あっという間に見つけ出し。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0150>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 42
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0151>, 104, 1)  ; 「それよりも雪菜…アンコールは？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 305
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0152>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 43
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0153>, 105, 1)  ; 「今頃お客さんたち大ブーイングだよ？\n…本当に、迷惑かけてくれちゃって」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0154>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 44
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0155>, 106, 1)  ; 「は、はは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 321
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0156>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 45
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0157>, 107, 1)  ; 「おかしくない！\nお客さんを裏切るなんてとんでもないことだよ？\n一応、人気商売なのに！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0158>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 46
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0159>, 108, 1)  ; 「雪菜は…本当に愚かだな」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 320
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0160>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 47
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0161>, 109, 1)  ; 「わたしのせいじゃないでしょ！\n春希くんが帰っちゃうから悪いんじゃない。\nもう、反省の色が見られないなぁ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0162>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 48
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0163>, 110, 1)  ; 「本当に、本当にさ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0164>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 49
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0165>, 111, 1)  ; 「春希くん…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0166>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 50
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0167>, 112, 1)  ; 「俺…\n雪菜みたいな馬鹿、他に知らないよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8246
PUSH INT 0
PUSH INT 0
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 70
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 10
CALL SES
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 21110
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1.05
PUSH FLOAT 1.05
PUSH INT 0
PUSH INT 0
CALL V2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 350
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 180
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

@VCALL WN(RES<0168>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 51
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0169>, 113, 1)  ; 「………ぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0170>, 114, 1)  ; 本当に、こんな女ありえない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0171>, 115, 1)  ; 可愛くて、強くて、優しくて…\nけれど最高に愚かな女。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0172>, 116, 1)  ; たった一人の観客のために、\n他の全ての観客の期待を裏切る見境のなさ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0173>, 117, 1)  ; それを自分の判断じゃなく、\n俺の行動のせいだと信じて疑わない思い込みの激しさ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0174>, 118, 1)  ; そして…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0175>, 119, 1)  ; あれだけ酷い目に遭わされた…\n二度も裏切られた相手を、\n一年間も支え続けた、ありえない程の意志の強さ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0176>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 52
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0177>, 120, 1)  ; 「春希、くん…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0178>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 53
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0179>, 121, 1)  ; 「なんだよ馬鹿」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0180>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 54
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0181>, 122, 1)  ; 「そんなに馬鹿、馬鹿って言われると、\nますます馬鹿になっちゃうよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0182>, 123, 1)  ; いつの間にか、\n雪菜の顔が、俺の胸に埋まってる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0183>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 55
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0184>, 124, 1)  ; 「あなたのこと、好きになりすぎて、\n何をされても嫌いになれなくなっちゃうよ？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0185>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 56
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0186>, 125, 1)  ; 「………馬鹿っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0187>, 126, 1)  ; なんて、当たり前だ。\n俺が、自分の意志で抱きしめたんだから。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0188>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 57
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0189>, 127, 1)  ; 「大丈夫？　寒くない？\nどこも痛くない？\n…辛く、ない？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0190>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 58
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0191>, 128, 1)  ; 「大丈夫、大丈夫だ…\nただ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0192>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 59
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0193>, 129, 1)  ; 「ただ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0194>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 60
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0195>, 130, 1)  ; 「済まないって思ってるだけ。\nまた雪菜のことを好きになってしまって…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0196>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 61
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0197>, 131, 1)  ; 「…かずさに？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0198>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 62
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0199>, 132, 1)  ; 「雪菜に」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0200>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 63
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0201>, 133, 1)  ; 「………」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0202>, 134, 1)  ; だって俺は、また雪菜に迷惑をかける。\n雪菜に、護ってもらうしかなくなる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 180
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0203>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0204>, 135, 1)  ; かずさの、最後のコンサートが終わり、\n雪菜が、俺のもとから去り。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0205>, 136, 1)  ; 俺はまだ、その現実を受け入れられずに、\n部屋の中で呆然と、昼も夜も関係のない生活を送り…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0206>, 137, 1)  ; そんな中…\n雪菜は、たった一週間で俺の部屋に戻ってきた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0207>, 138, 1)  ; 加害者の俺よりも早く、しかも自力で回復し、\nその後は加害者のリハビリに全力を尽くした。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0208>, 139, 1)  ; ………信じられないお節介で、世話焼きで、馬鹿だった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0209>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 3
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 5
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 90
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

@VCALL WN(RES<0210>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 64
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0211>, 140, 1)  ; 「なんで戻ってきたんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0212>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 65
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0213>, 141, 1)  ; 「春希くんを奪い返しに行ったんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0214>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 66
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0215>, 142, 1)  ; 「なんで俺なんかを…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 222
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0216>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 67
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0217>, 143, 1)  ; 「だってわたし、かずさのこと嫌いだから。\n不倶戴天の敵だから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0218>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 68
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0219>, 144, 1)  ; 「なんですぐ来てくれたんだよ…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0220>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 69
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0221>, 145, 1)  ; 「一週間で、必死になって一年分泣いたの。\nだから一年間は頑張れるって自信があった」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0222>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 70
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0223>, 146, 1)  ; 「………っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0224>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 71
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0225>, 147, 1)  ; 「わたしの判断、間違ってなかったでしょ…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

ARRAY_S RES<0226>  ; sepia.AMP
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 1
PUSH INT 2135
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0227>, 148, 1)  ; あの時、俺は完全に壊れてた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0228>, 149, 1)  ; 外に出て、人と会うのが苦痛だった。\n会話をするだけで、体調がガタガタに崩れ、\n仕事になんか出られる状況じゃなかった。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0229>, 150, 1)  ; あげくの果てには、\n雪菜が訪れてきた時にもその症状を来たし、\n酷いことを言ったり、強く拒絶したりした。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0230>, 151, 1)  ; その時雪菜の言った言葉は…\nもう、一生忘れることはできそうにない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2040
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL WN(RES<0231>)  ; 雪菜
PUSH INT 2
PUSH INT 9000
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0232>, 152, 1)  ; 『わたしを忘れて克服するか、\nわたしと一緒に克服するか、\n今の春希くんには、そのどっちかしかないんだよ？』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 30000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0233>)  ; 雪菜
PUSH INT 2
PUSH INT 9001
PUSH INT -1
PUSH INT 256
PUSH INT 0
PUSH INT 0
CALL VX
OPERATOR POP

@VCALL SetMessageE(RES<0234>, 153, 1)  ; 『わたしにとってどっちが幸せか、\n春希くんには、わかるかな？』
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0235>, 154, 1)  ; …あまりの愚かしさに、\n俺は、かずさとの別れの日みたいに大声で泣いた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

ARRAY_S RES<0236>
PUSH INT 0
CALL SetEffctMode
OPERATOR POP

PUSH INT 255
PUSH INT 0
CALL SetChromaMode
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 256
PUSH INT 128
CALL CW
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL BC
OPERATOR POP

PUSH INT 3
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 5
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 0
CALL SetWeather
OPERATOR POP

PUSH INT 90
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

@VCALL WN(RES<0237>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 72
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0238>, 155, 1)  ; 「あ、それで話の途中ですが告知があります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0239>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 73
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0240>, 156, 1)  ; 「え…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0241>, 157, 1)  ; それから半年…
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0242>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 74
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0243>, 158, 1)  ; 「ありがたいことに、\nわたしの次回誕生日の予定も決まりまして…\n今月の１４日、バレンタインデーの０時からになります」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0244>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 75
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0245>, 159, 1)  ; 「平日だから…\n俺の部屋で、夜の８時スタートでどうかな？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0246>, 160, 1)  ; 俺が、ゆっくりと心の傷を癒し、\n元通り、社会へと溶け込んでいく間…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 209
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0247>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 76
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0248>, 161, 1)  ; 「８時ぃ？\n春希くんとこの定時って６時だったよね？\nそりゃ、普段は忙しいのはわかるけどさぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0249>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 77
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0250>, 162, 1)  ; 「その代わりと言っちゃなんだけど…\n今から、俺の部屋に来ないか？\n明日、家まで送ってくから」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0251>, 163, 1)  ; その隣には、ずっとその愚かな女が寄り添ってくれていた。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 102
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0252>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 78
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0253>, 164, 1)  ; 「可愛い可愛い雪菜様。\n俺はあなたを世界で一番愛しています。\nどうか朝まで一緒に過ごしてください」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0254>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 79
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0255>, 165, 1)  ; 「え…っ！？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 303
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0256>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 80
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0257>, 166, 1)  ; 「…って、言ってくれたらね？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0258>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 81
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0259>, 167, 1)  ; 「雪菜…\nお前、結構したたかになったなぁ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0260>, 168, 1)  ; いつの間にか『お前』って呼び捨てられるくらい、\n愚かで、愛しい女が。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0261>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 82
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0262>, 169, 1)  ; 「だって、鍛えられましたから。\nわたしが世界で一番愛してる人に。\n…わたしを世界で二番目に愛してくれてる人に」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0263>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 83
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0264>, 170, 1)  ; 「…本当に、いい性格になったよ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 113
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0265>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 84
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0266>, 171, 1)  ; 「…で、答えは？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0267>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 85
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0268>, 172, 1)  ; 「俺はあなたを世界で一番愛しています」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 321
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0269>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 86
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0270>, 173, 1)  ; 「嘘つき…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL WN(RES<0271>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 87
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0272>, 174, 1)  ; 「嘘は…半分だけだ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 2
PUSH INT 106
PUSH INT 28000
OPERATOR ADD
PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH INT 256
PUSH INT 128
CALL C
OPERATOR POP

@VCALL WN(RES<0273>)  ; 雪菜
PUSH INT 2
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 88
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0274>, 175, 1)  ; 「………うんっ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0275>, 176, 1)  ; 多分俺は、今でもかずさを愛してる。\n多分、世界で一位タイなくらい愛してる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0276>, 177, 1)  ; けど今の俺は、雪菜なしでは生きていけない。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0277>, 178, 1)  ; 雪菜の側にいなければ、人生の方角が…\n自分がどこを向いてるのかわからなくなる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 360
CALL MS
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 360
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 120
CALL SetDemoMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 2078
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 150
PUSH INT 120
PUSH FLOAT 1.5
PUSH FLOAT 1.5
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 100
OPERATOR NEGATE
PUSH INT 120
PUSH INT 3500
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 3
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 5
PUSH INT 10
PUSH INT 128
PUSH INT 2
PUSH INT 1
CALL SetWeather
OPERATOR POP

PUSH INT 120
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 9672
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 420
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL WN(RES<0278>)  ; 春希
PUSH INT 0
PUSH INT 256
PUSH INT 0
PUSH INT 0
PUSH INT 89
CALL VV
OPERATOR POP

@VCALL SetMessageE(RES<0279>, 179, 1)  ; 「<W15>雪<W15>菜<W15>…<W15>っ」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

PUSH INT 1
OPERATOR NEGATE
CALL WN
OPERATOR POP

@VCALL SetMessageE(RES<0280>, 180, 1)  ; 雪<W10>菜<W10>の<W10>歌<W10>声<W10>が、<W10>\n雪<W10>で<W10>静<W10>め<W10>ら<W10>れ<W10>た<W10>街<W10>に、<W10>優<W10>し<W10>く<W10>広<W10>がっ<W10>て<W10>い<W10>く。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 7000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0281>, 181, 1)  ; ま<W10>る<W10>で、<W10>俺<W10>を<W10>護<W10>る<W10>た<W10>め<W10>の<W10>子<W10>守<W10>唄<W10>の<W10>よ<W10>う<W10>に。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5000
CALL WaitTimer
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
CALL SetTimeMode
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
CALL FB
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 2
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 6
PUSH INT 256
OPERATOR BIT_OR
PUSH INT 3
PUSH INT 7
PUSH INT 120
PUSH INT 2
PUSH INT 1
PUSH INT 5
CALL SetWeather2
OPERATOR POP

PUSH INT 120
PUSH INT 128
PUSH INT 128
PUSH INT 128
CALL FB
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0282>, 182, 1)  ; と<W10>う<W10>と<W10>う、<W10>降っ<W10>て<W10>き<W10>た。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4500
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0283>, 183, 1)  ; こ<W10>ん<W10>な、<W10>何<W10>気<W10>な<W10>い<W10>…<W10>\nけ<W10>れ<W10>ど、<W10>二<W10>人<W10>の<W10>絆<W10>が<W10>ま<W10>す<W10>ま<W10>す<W10>深<W10>まっ<W10>た、<W10>\nそ<W10>ん<W10>な<W10>穏<W10>や<W10>か<W10>な<W10>日<W10>に<W10>も。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 7000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0284>, 184, 1)  ; 何<W10>故<W10>だ<W10>か、<W10>俺<W10>の<W10>前<W10>に<W10>そ<W10>の<W10>白<W10>い<W10>姿<W10>を<W10>見<W10>せ<W10>て<W10>く<W10>れ<W10>た。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0285>, 185, 1)  ; 雪<W10>は、<W10>覆<W10>い<W10>隠<W10>し<W10>て<W10>し<W10>ま<W10>う。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0286>, 186, 1)  ; 過<W10>去<W10>の、<W10>辛<W10>く<W10>苦<W10>し<W10>い<W10>日<W10>々<W10>を。<W10>\n思<W10>い<W10>出<W10>し<W10>た<W10>く<W10>な<W10>い<W10>罪<W10>深<W10>い<W10>現<W10>実<W10>を。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 5000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0287>, 187, 1)  ; た<W10>だ<W10>白<W10>く、<W10>綺<W10>麗<W10>な<W10>だ<W10>け<W10>の<W10>世<W10>界<W10>を<W10>目<W10>の<W10>前<W10>に<W10>広<W10>げ、<W10>\n俺<W10>た<W10>ち<W10>を、<W10>そ<W10>こ<W10>に<W10>閉<W10>じ<W10>こ<W10>め<W10>よ<W10>う<W10>と<W10>す<W10>る。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 7000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0288>, 188, 1)  ; …<W10>…<W10>…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0289>, 189, 1)  ; け<W10>れ<W10>ど、<W10>所<W10>詮<W10>雪<W10>は<W10>雪<W10>で<W10>あ<W10>り。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 4000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0290>, 190, 1)  ; 一<W10>度<W10>解<W10>け<W10>た<W10>ら、<W10>の<W10>た<W10>う<W10>ち<W10>回っ<W10>て<W10>生<W10>き<W10>抜<W10>い<W10>た<W10>過<W10>去<W10>を、<W10>\n二<W10>度<W10>と<W10>忘<W10>れ<W10>た<W10>ら<W10>い<W10>け<W10>な<W10>い<W10>思<W10>い<W10>出<W10>を、<W10>\nも<W10>う<W10>一<W10>度、<W10>俺<W10>た<W10>ち<W10>の<W10>心<W10>に<W10>呼<W10>び<W10>戻<W10>す。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 8000
CALL WaitTimer
OPERATOR POP

CALL StartTimer
OPERATOR POP

@VCALL SetMessageE(RES<0291>, 191, 1)  ; 雪<W10>と<W10>大<W10>地<W10>を<W10>突<W10>き<W10>破<W10>り、<W10>天<W10>に<W10>向<W10>かっ<W10>て<W10>芽<W10>を<W10>伸<W10>ば<W10>す、<W10>\n名<W10>も<W10>な<W10>き<W10>草<W10>花<W10>の<W10>よ<W10>う<W10>に。
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 6000
CALL WaitTimer
OPERATOR POP

PUSH INT -1
PUSH INT 0
CALL WR
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT -1000
PUSH INT 0
CALL ChangeWeather
OPERATOR POP

PUSH INT 0
PUSH INT 360
CALL SES
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 360
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 0
PUSH INT 0
CALL SetDemoMode
OPERATOR POP

ARRAY_G 4
PUSH INT 0
OPERATOR MOV
OPERATOR POP
PUSH INT 4
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

PUSH INT 32
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

PUSH INT 240
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

CALL GoTitle
OPERATOR POP

STATEMENT HALT
