!RESOURCE "5104.csv"

#Z9999

#LABEL_3
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_1
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 1
OPERATOR GT
CALL GetSkip
OPERATOR OR
CALL GetClick
OPERATOR OR
STATEMENT JMP_IF
OPERATOR POP
STATEMENT GOTO #LABEL_2
OPERATOR POP

#LABEL_1
CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_3
OPERATOR POP

#LABEL_2
STATEMENT HALT
STATEMENT NOP

#Z9997
OPERATOR POP
PUSH INT 0
ARRAY_S RES<0001>  ; B990000.tga
PUSH INT 15
PUSH INT 2
ARRAY_S RES<0002>
PUSH INT 256
ARRAY_S RES<0003>  ; bak
PUSH INT 0
CALL LoadBmp
OPERATOR POP

PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9996
OPERATOR POP
PUSH INT 0
CALL ReleaseBmp
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z9995
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_7
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_4
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR MOV
OPERATOR POP

#LABEL_4
STATEMENT IF _ #LABEL_5
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 3
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 255
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_6
OPERATOR POP

#LABEL_5
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 3
OPERATOR DIV
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_7
OPERATOR POP

#LABEL_6
STATEMENT HALT
STATEMENT NOP

#Z9994
OPERATOR POP
CALL StartTimer
OPERATOR POP

#LABEL_11
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
CALL GetTimer
OPERATOR MOV
OPERATOR POP
STATEMENT IF _ #LABEL_8
CALL GetSkip
STATEMENT JMP_IF
OPERATOR POP
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR MOV
OPERATOR POP

#LABEL_8
STATEMENT IF _ #LABEL_9
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
ARRAY_G 2
OPERATOR GEQ
STATEMENT JMP_IF
OPERATOR POP
PUSH INT 0
PUSH INT 1
PUSH INT 0
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

STATEMENT GOTO #LABEL_10
OPERATOR POP

#LABEL_9
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 255
PUSH INT 255
ARRAY_L 8
PUSH INT 0
OPERATOR INDEX
OPERATOR MUL
ARRAY_G 2
OPERATOR DIV
OPERATOR SUB
OPERATOR MOV
OPERATOR POP
PUSH INT 0
PUSH INT 1
ARRAY_L 9
PUSH INT 0
OPERATOR INDEX
PUSH INT 0
CALL SetBmpParam
OPERATOR POP

CALL runEX
OPERATOR POP

STATEMENT GOTO #LABEL_11
OPERATOR POP

#LABEL_10
STATEMENT HALT
STATEMENT NOP

#Z9993
OPERATOR POP
PUSH INT 9995
CALL call
OPERATOR POP

PUSH INT 9994
CALL call
OPERATOR POP

STATEMENT HALT
STATEMENT NOP

#Z00
OPERATOR POP
CALL run
OPERATOR POP

PUSH INT 0
PUSH INT 5104
CALL VI
OPERATOR POP

ARRAY_G 4
PUSH INT 4
OPERATOR MOV
OPERATOR POP
PUSH INT 1
CALL NevelMode
OPERATOR POP

PUSH INT 0
PUSH INT 1
CALL NB
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessage(RES<0004>, 0, 1)  ; 終章　届かない声\k\n\n
PUSH INT 0
PUSH INT 1
CALL NB
OPERATOR POP

PUSH INT 0
PUSH INT 4301
PUSH INT 60
PUSH INT 1
PUSH INT 200
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessage(RES<0005>, 1, 0)  ; 　五月、連休明け初日。\k\n　つまり、翌日。\k\n
PUSH INT 0
PUSH INT 1
CALL NB
OPERATOR POP

PUSH INT 1
PUSH INT 2008
PUSH INT 0
PUSH INT 60
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 2
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

PUSH INT 0
PUSH INT 120
CALL SES
OPERATOR POP

@VCALL SetMessageE(RES<0006>, 2, 0)  ; 「あ、おはよう、依緒、武也くん」\k\n「………」\k\n「………」\k\n「…どしたの？」\k\n「いや、呆れてるんだけどね」\k\n「この時間におはようと挨拶するその時間感覚にな…」\k\n「あ、あはは…」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0007>, 3, 1)  ; 　…そして時間は十二時二十分。\k\n「今日は午前中だけだよ？」\k\n「つまり、もう帰る時間なわけだ」\k\n「あ、あはははは…」\k\n　その証拠に、雪菜が二人に出会ったのは校門の前。\k\n　出てくる二人と、入ってくる雪菜の鉢合わせだった。\k\n「何やってたのよ昨夜。いつ寝たの？」\k\n「ちょ、ちょっとした連休ボケだよね。完全に夜型になっちゃってて！」\k\n　言えるわけがない。\k\n　あまりにも激しいオナニー疲れで寝坊したなどと…\k\n「の割には、なんかスッキリした顔してんじゃん雪菜ちゃん」\k\n「ふぇっ！？　う、嘘、わかっちゃう…？」
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0008>, 4, 1)  ; 「なになに、どしたの？　実は連休中何かいいことでもあった？」\k\n「あ～連休中ね！　うんうん、寝てばっかりだったよ朝から晩まで！」\k\n「お願いだから大学のアイドルがそういうこと言うのやめてくれ…」\k\n「あたしたちだからいいけど、他の連中が聞いたらネットで拡散ものだよ？」\k\n「あはは、そうだね、あははははっ」\k\n　昨夜の所業については後ろ暗いところがありすぎる雪菜は、二人のありきたりな問いかけにさえ様々な意図を連想して妙にテンションの高い受け答えになってしまう。\k\n　けれど、そうやって自然とテンションを上げてしまえるということは…\k\n「…ま、いいか」\k\n「そだね、まいっかぁ」\k\n「…な～んか投げやり」\k\n　雪菜が、何か振り切れたということ。\k\n　歩幅は小さいかも知れないけれど、一歩前に踏み出したということ。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0009>, 5, 1)  ; 「それじゃ、今から三人でメシでも食いに行く？」\k\n「いいねそれ！　わたし朝からなにも食べてないよ」\k\n「そりゃ、起きたのがついさっきじゃねぇ」\k\n　三年前から親友を名乗っている二人には、そんなことを読み取るくらい朝飯前だった。\k\n「じゃあ、行こうぜ…もうモーニングサービスはやってないけど」\k\n「ね、ヨネダコーヒーにしようよ？　あそこなら遠慮なく長居できるし」\k\n「粒あん乗っけた奴頼むのやめてね…」\k\n　話がまとまると、いつものように歩幅の長い武也とピッチの速い依緒の先頭争いで、ゆっくりできない移動が始まる。\k\n　春希がいるときもいないときも自分のペースを守る雪菜は、彼らの後ろをゆっくり歩きつつ、今からのランチタイムの話題に思いを馳せる。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessage(RES<0010>, 6, 1)  ; 　昨夜の友近の話を、どのくらい編集して話そうかとか。\k\n　春希が相変わらず春希だったこととか。\k\n　けれど、ちょっとだけ予想の斜め上の行動を取ったとか。\k\n　だから、ちょっとだけ、のろけてしまおうかとか。\k\n　あるいは、春希が友近でなく、武也だけを親友だと認めたこととか。\k\n　もしその話を武也に告げたら、彼はどう反応するだろうかとか。\k\n　それはそれで楽しいランチになりそうだなとか。\k\n　もし自分よりものろけられたら嫌だな、とか…\k\n\n
PUSH INT 0
PUSH INT 1
CALL NB
OPERATOR POP

PUSH INT 120
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 120
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0011>, 7, 0)  ; 　――届かない恋、をしていても…\k\n\n「っ！」
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 1
CALL NB
OPERATOR POP

PUSH INT 120
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL SetTimeMode
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 150
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 210
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 27
PUSH INT -2
PUSH INT 1
PUSH INT 255
CALL M
OPERATOR POP

@VCALL SetMessageE(RES<0012>, 8, 1)  ; 　無意識のまま、ひとつの旋律が喉から漏れ出そうになり。\k\n　けれど口を出た瞬間に霧散していく。\k\n　だから結局、雪菜自身を含め、誰の耳にも届くことはなく…\k\n「今の…」\k\n　冬になるとキャンパス中に流れていた旋律。\k\n　けれど二年間、自分の口からはずっと漏れることすらなかった旋律。\k\n　歌わなかった。\k\n　歌いたくなかった。\k\n　そして多分、歌えなかった歌。\k\n　けれど今、ほんの少し楽しい気分に浸っただけで、滲み出てきてしまった歌…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 15
PUSH INT 1
CALL NB
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 1
PUSH INT 2008
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 0
PUSH INT 15
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 1
PUSH INT 1
PUSH INT 1800
PUSH INT 0
PUSH INT 640
PUSH INT 360
PUSH INT 0
CALL Z
OPERATOR POP

PUSH INT 0
PUSH INT 0
PUSH INT 1800
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 150
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0013>, 9, 1)  ; 　――ねぇ、春希くん。\k\n\n　だから雪菜は、ふと正門の方に振り返る。\k\n　正しくは、その門から北に行ったところにある三号館の方角を。\k\n\n　――ねぇ、春希くん。\k\n　　わたし、やっぱり歌が好きだよ。\k\n　　………が、すきだよ。\k\n\n　多分、そこにいるであろう想い人に向かって。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessage(RES<0014>, 10, 1)  ; 　――本当は、いつかまた歌いたい。\k\n　　そして本当は、報われたい。\k\n\n「お～い、雪菜ちゃ～ん！」\k\n「なにぼやぼやしてんのよ、さっさと行くよ～！」\k\n
PUSH INT 0
PUSH INT 1
CALL NB
OPERATOR POP

PUSH INT 1
PUSH INT 1060
PUSH INT 0
PUSH INT 90
PUSH INT 0
PUSH INT 80
OPERATOR NEGATE
PUSH INT 10
PUSH FLOAT 1.2
PUSH FLOAT 1.2
PUSH INT 0
PUSH INT 0
CALL B2
OPERATOR POP

PUSH INT 80
PUSH INT 10
PUSH INT 3000
PUSH INT 0
PUSH INT 0
CALL S
OPERATOR POP

PUSH INT 90
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
PUSH INT 8238
PUSH INT 0
PUSH INT 0
PUSH INT 200
PUSH INT 0
CALL SEP
OPERATOR POP

PUSH INT 30
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

@VCALL SetMessageE(RES<0015>, 11, 0)  ; 「あ、は～い、ちょっと待って～！」\k\n　雪菜は、駆け出していく。\k\n　ずっと足踏みをしていた二年間とは違う歩幅で。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0016>, 12, 1)  ; 　――だからあきらめるな、あきらめるな、わたし…\k\n　　想いは、必ず届く。\k\n　　たとえ一度は途切れてしまった絆でも。\k\n　　彼の本質が変わらないのなら。\k\n　　そして、わたしの想いが変わらないのなら…\k\n\n　雪菜は、駆け出していく。\k\n　はやる心を抑え、一歩ずつ確実に、前に進んでいく。
PUSH INT 1
CALL EndMessage
OPERATOR POP

@VCALL SetMessageE(RES<0017>, 13, 1)  ; 　――でも今は、まだ歌えない。\k\n　　そして多分、今すぐ報われることもない。\k\n　　けれど、いつかこの歌とともに、わたしの想いを解き放ちたい。\k\n　　だから、今度わたしが歌うときは、彼に聞かせるとき。\k\n　　彼が…求めたとき。\k\n　　それまでは。\k\n　　それ、までは…
PUSH INT 1
CALL EndMessage
OPERATOR POP

PUSH INT 30
PUSH INT 1
CALL NB
OPERATOR POP

PUSH INT 60
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 360
CALL MS
OPERATOR POP

PUSH INT 1
PUSH INT 0
PUSH INT 0
PUSH INT 360
PUSH INT 0
PUSH INT 0
PUSH INT 0
PUSH FLOAT 1280
PUSH FLOAT 720
CALL B
OPERATOR POP

PUSH INT 180
PUSH INT 0
PUSH INT 0
CALL Wait
OPERATOR POP

PUSH INT 0
CALL NevelMode
OPERATOR POP

PUSH INT 11
PUSH INT 1
CALL SetGameFlag
OPERATOR POP

CALL GoTitle
OPERATOR POP

STATEMENT HALT
